### ISSUE TITLE
Taskbar application title

### ISSUE THREAD

**Issue by indig0F10w** [vladimiry/ElectronMail#106]
Greetings,

On Windows version the app name in taskbar button is not shown correctly. It just states "Unofficial desktop..."

Just a suggestion for taskbar name - "EmailSecApp".

Thanks for this great app.

![capture](https://user-images.githubusercontent.com/17021548/52563074-abe06b80-2e00-11e9-955c-92915b7b2096.PNG)

**Comment by vladimiry** [comment]
This has been handled in along with project renaming. v3 release is coming soon.

**Comment by vladimiry** [comment]
New version with the respective fix included has just been published.
