### ISSUE TITLE
Mail export not working ?

### ISSUE THREAD

**Issue by ihubgit** [vladimiry/ElectronMail#112]
Hi downloaded latest version 2.3.2 on High Sierra.
I manage to view my mailboxes in protonmail, but when switching to database view, nothing happens. The database icon just keeps blinking and i never see anything displayed. Also unable to export any messages. Is this a bug or me being noob?

**Comment by vladimiry** [comment]
The app does bootstrap fetch on enabling `local store` feature for the account. It involves downloading all the messages. This process takes time depending on the how many emails you got in your account. Besides there is a [rate limiting](https://github.com/vladimiry/email-securely-app/issues/73) involved for protonmail accout types which slows down the process. So you need to wait until the database icon stopped blinking.

During the botstrap fetch the app saves a messages by portions, portion size is about 500 messages. You will only be able to export the emails that have already been downloaded, those you can see in the the database view mode.

You can enable the `info` or `verbose` logging in the app settings and observe some progress information in the log file. If you locate any errors in the log file consider sharing it here or sending to the email specified [here](https://github.com/vladimiry/email-securely-app/blob/master/package.json#L5) in the `author` section.

The bootstrap fetch is a one-off thing. After it got completed the app will only apply the database patches which doesn't take long.

**Comment by vladimiry** [comment]
> This process takes time depending on the how many emails you got in your account.

If you got a lot of emails, like 10k+, consider using [2.3.3 pre-release](https://www.dropbox.com/sh/633bahtwctjtzb9/AADh6jaEDa5SQMd-vB5X2fSPa?dl=0&lst=) with the disabled full-text search feature.

This v2.3.3 is going to be further improved until released, see details [here](https://github.com/vladimiry/email-securely-app/issues/110).

**Comment by ihubgit** [comment]
I don't have that many emails. Just a few hundreds. I did try the 2.3.3. pre-release, but after an hour not even one mail showing up in the database. So something must be wrong !

**Comment by vladimiry** [comment]
> You can enable the `info` or `verbose` logging in the app settings and observe some progress information in the log file. If you locate any errors in the log file consider sharing it here or sending to the email specified [here](https://github.com/vladimiry/email-securely-app/blob/master/package.json#L5) in the `author` section.

**Comment by vladimiry** [comment]
@ihubgit can you try this [build](https://www.dropbox.com/sh/633bahtwctjtzb9/AADh6jaEDa5SQMd-vB5X2fSPa?dl=0&lst=)? Steps to perform:
- Locate the setting folder (see [how](https://github.com/vladimiry/email-securely-app/blob/master/images/open-settings-folder.jpg)).
- Close the app.
- Set `logLevel` value in `config.json` file to `verbose` (by default it's set to `error`).
- Remove or rename the `database.bin` file.
- Start the app, sign-in into the account and enabe the `local store` feature and then wait for icon stopped blinking in green (so data syncing got completed).

If it keeps blinking for a long time or you get some errors shown by UI please send `log.log` file to the email specified [here](https://github.com/vladimiry/email-securely-app/blob/master/package.json#L5) in the `author` section (`log.log` located in the same settings folder).

**Comment by vladimiry** [comment]
> @ihubgit can you try this build? Steps to perform:

[2.3.3](https://github.com/vladimiry/email-securely-app/releases/tag/v2.3.3) is now recommended for use.

**Comment by ihubgit** [comment]
well, tried again, and now I'm getting 

> Maximum call stack size exceeded

sent the log to the email you specified earlier

**Comment by vladimiry** [comment]
It fails on parsing specific email, I sent you its subject in email response. Here is what I need you to do in order to further investigate the case:
- Disable the `local store` feature for now.
- Login into the account using Google Chrome or Chromium browser.
- Locate there email by subject I sent you in email response. I guess you can use Protonmail's search as it searches by subjects or just scroll through all the emails in [plain view mode](https://protonmail.com/support/knowledge-base/disable-conversation-view/) (disable grouping) as you wrote before that you got just a few hundreds of emails. Since error occurs at the https://github.com/ProtonMail/WebClient side then I guess it might not be working even if you work with that `problematic` email in browser.
- Open the found email/emails for viewing (just click it).
- Then perform `export`, `print` and `view source code` actions:
  ![items](https://user-images.githubusercontent.com/1560781/53818217-caa5ce00-3f78-11e9-8984-c0a8fc351499.png)
- If there is more than one email with the subject used for filtering please perform specified actions for all of them.
- Then if there is no secrecy in located by subject email forward the email to me and also sent me the source code you got by clicking the `view source code` menu item (see above image).

**Comment by vladimiry** [comment]
> Since error occurs at the https://github.com/ProtonMail/WebClient side

I meant that it fails on this line https://github.com/ProtonMail/WebClient/blob/800107889f25e48746bf2fae433dc3c949561560/src/app/message/helpers/transformEscape.js#L126:
```javascript
const breakHtml = input.replace(REGEXP_IS_BREAK, '$1proton-$2');
```

Stacktrace:
```
RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at transformEscape (webclient1://mail.protonmail.com/appLazy.module.a8c4f9e11d.chunk.js:6688:25)
    at Object.getBodyParser (webclient1://mail.protonmail.com/appLazy.module.a8c4f9e11d.chunk.js:6735:12)
    at Message.countEmbedded (webclient1://mail.protonmail.com/appLazy.module.a8c4f9e11d.chunk.js:32749:37)
    at Message._callee4$ (webclient1://mail.protonmail.com/appLazy.module.a8c4f9e11d.chunk.js:33205:43)
    at tryCatch (webclient1://mail.protonmail.com/vendors~index.8f1dbc4323.chunk.js:34358:40)
    at Generator.invoke [as _invoke] (webclient1://mail.protonmail.com/vendors~index.8f1dbc4323.chunk.js:34584:22)
    at Generator.prototype.(anonymous function) [as next] (webclient1://mail.protonmail.com/vendors~index.8f1dbc4323.chunk.js:34410:21)
    at asyncGeneratorStep (webclient1://mail.protonmail.com/vendors~index.8f1dbc4323.chunk.js:38436:24)
    at _next (webclient1://mail.protonmail.com/vendors~index.8f1dbc4323.chunk.js:38458:9)
```

So far it looks like a protonmail's bug, specifically inefficient regex is used. This is why I asked to open the problematic email in a browser and send me the email content if that's possible so I could reproduce it.

**Comment by vladimiry** [comment]
To recap, there are two issues here:
- `RangeError: Maximum call stack size exceeded` error which blocks finishing the initial database fetch (bootstrapping). The respective issue has been opened in upstream project https://github.com/ProtonMail/WebClient/issues/146.
- Slow large mails export. This has been improved, the build is uploaded [here](https://www.dropbox.com/sh/94emgcnux90oy57/AAA1yV5NWoXzayHseQId8QR7a?dl=0&lst=).

**Comment by vladimiry** [comment]
Closing due to the inactivity and because it's upstream issue https://github.com/ProtonMail/WebClient/issues/146 causes the data syncing error.
