### ISSUE TITLE
Problems Handling Multiple Accounts

### ISSUE THREAD

**Issue by BobsUncle** [vladimiry/ElectronMail#113]
Hey vlad, first of all great work thanks for sharing. 

I currently have your software deployed in following configuration: 

1. 4 x Protonmail accounts (separate identities) 
2. All are accessed via the onion site/tor gateway

Problem: Each account is constantly logging back out and logging back in automatically. It happens every 90 seconds. One account will login the other will log out. This is probably not good because unless it is a bug it means the Protonmail server is logging you out which means isolation between accounts is not good. 

Also I am wondering can you give option in future update to set specific proxy parameter for each account? That was a person managing multiple accounts can implement stream isolation via TOR so each account has a different circuit. Just requires ability set IP and PORT. 

FYI. I am using this app on Debian 9 (whonix workstation). 

Thanks

**Comment by vladimiry** [comment]
- Can you confirm the app works well with your setup if you use only one account?
- Does it work well if you map your browser to Tor and login into several accounts?

> It happens every 90 seconds. One account will login the other will log out. This is probably not good because unless it is a bug it means the Protonmail server is logging you out which means isolation between accounts is not good.

I know there are users who go with multiple accounts and so far there was no such kind of issue revealed you describe. But still, there is a way to enable better account isolation.

> set specific proxy parameter for each account

I think it's feasible.

**Comment by vladimiry** [comment]
- Build with improved accounts isolation is uploaded [here](https://www.dropbox.com/sh/exyi3z67pkknzcr/AABejNBU-pZID6gFCWUsfjQua?dl=0&lst=). Does it work better with your setup?

- The new build also supports configuring proxy per account. Can you confirm it works as expected?
![proxy](https://user-images.githubusercontent.com/1560781/54069102-17cdbc80-4265-11e9-8b83-f4eba5f352e0.png)

**Comment by BobsUncle** [comment]
Hi Vlad, 

I tried downloading from the dropbox link but the link is no longer valid. 

I look forward to testing out the changes.

Thanks

**Comment by BobsUncle** [comment]
>     * Can you confirm the app works well with your setup if you use only one account?

Yes, works fine with just one account

>     * Does it work well if you map your browser to Tor and login into several accounts?

You mean one tor browser instance but multiple tabs? No that does not work fine it also risk the accounts being suspended because it does not isolate (cookies, etc) each tab.

**Comment by vladimiry** [comment]
> I tried downloading from the dropbox link but the link is no longer valid.

I removed the dropbox links as recently published v3 release includes new changes.

I'd ask you to try the app:
- with one account first
- then with several accounts (the original case)
- and then using the proxy

**Comment by BobsUncle** [comment]
> I know there are users who go with multiple accounts and so far there was no such kind of issue revealed you describe. But still, there is a way to enable better account isolation

I think full and proper isolation is imperative. The app should come with a warning that it is not designed for identity or isolation if these features you speak of for isolation are not yet implemented  so any other users not might make same mistake i make.

**Comment by BobsUncle** [comment]
> > I tried downloading from the dropbox link but the link is no longer valid.
> 
> I removed the dropbox links as recently published v3 release includes new changes.
> 
> I'd ask you to try the app:
> 
>     * with one account first
> 
>     * then with several accounts (the original case)
> 
>     * and then using the proxy

OK I will test it out now and report back!

**Comment by BobsUncle** [comment]
When I enable proxy it is not working. I entered it as IP:Port (since no field specific for port). I entered it like "127.0.0.1:9052"

**Comment by BobsUncle** [comment]
Perhaps it does not work with Socks 5 proxy?

**Comment by BobsUncle** [comment]
OK it should be entered like this socks5://10.152.152.10:9180

**Comment by vladimiry** [comment]
> OK it should be entered like this socks5://10.152.152.10:9180

Yep, see the [documentation](https://electronjs.org/docs/api/session#sessetproxyconfig-callback) link near to the field. I think it's quite flexible.

**Comment by BobsUncle** [comment]
Everything seems to be working beautifully. I'll keep you updated. 

Vlad, can you explain a little how isolation is implemented in this new version between different accounts?

**Comment by BobsUncle** [comment]
FYI: (possibly unrelated) I just added six accounts total and hit a "ENOMEM, Cannot allocate memory" error.

**Comment by vladimiry** [comment]
- How much RAM do you have?
- Is [local store](https://user-images.githubusercontent.com/1560781/45978558-4f4d0180-c055-11e8-8158-54d57d90bf7b.gif) option enabled and initial syncing got finished?
  - If so, are there a lot of emails in your account?
  - If so, what is the `database.bin` file size?

See here how to save some memory https://github.com/vladimiry/ElectronMail/issues/108
See here how to enable extended logs if you are going to send them to me https://github.com/vladimiry/ElectronMail/issues/110

**Comment by BobsUncle** [comment]
- I am using a bare-bones debian 9 VM with 1536 RAM. 
- Local store is setup for everyone and yes sync was finished i think except for one account (the account i just added when the error popped up). The app continued just fine and loaded everything including from the new account. 
- No, not a lot of emails. 
- 10.6MB

Everything is working a lot smoother now the new v3 update. 

How do you disable the full text search option? That sounds like what I need to do.

**Comment by vladimiry** [comment]
Do like here and restart the app then:
![img](https://user-images.githubusercontent.com/1560781/54424679-7c38c200-4724-11e9-97ae-e2d4478c840c.png)

This will save you some RAM. I think something like up to 200MB in summary. But I have to admit that 1536 MB for 6 accounts does not look promising.

Please close the issue if it's resolved.

**Comment by nil0x42** [comment]
Hey, just for the record, i sounds like i have EXACTLY the same setup as @BobsUncle , and also exactly the same issues.
I'll try electronmail v3 now to see if it resolves

**Comment by vladimiry** [comment]
Closing as resolved.

**Comment by libBletchley** [comment]
I think a very simple way to get stream isolation is to use the protonmail onion server for one account and the surface web for the other account.  It only works for protonmail and only if you have two accounts, but for that case it's much simpler and easier to trust than multiple proxy ports.  I say trust because there is no concern for whether the isolation code works because the surface web must use an exit node, and the onion server needs no exit node.

I'm a bit fuzzy on why account-dependent ports are needed.  Is that a whonix particular need?  It seems `IsolateDestAddr` and `IsolateDestPort` tor options are applied to the proxy port, and then all traffic through that port gets stream isolation.  So all accounts can be configured to use the same SOCKS port, no?

**Comment by nil0x42** [comment]
> I think a very simple way to get stream isolation is to use the protonmail onion server for one account and the surface web for the other account. It only works for protonmail and only if you have two accounts, but for that case it's much simpler and easier to trust than multiple proxy ports. I say trust because there is no concern for whether the isolation code works because the surface web must use an exit node, and the onion server needs no exit node.
> 
> I'm a bit fuzzy on why account-dependent ports are needed. Is that a whonix particular need? It seems `IsolateDestAddr` and `IsolateDestPort` tor options are applied to the proxy port, and then all traffic through that port gets stream isolation. So all accounts can be configured to use the same SOCKS port, no?

No, because "IsosolateDestAddr" and "IsolateDestPort" will pick a different route for each different "IP:PORT" tuple.
So using the same proxy port for' let's say tutanota and protonmail will lead to different routes, but the same route will be used to 2 tcp streams to "protonmail.com:443".

Note that whonix has pre-defined alternative open ports that will lead to different routes.
Take a look at "/usr/share/tor/tor-service-defaults-torrc".

**Comment by vladimiry** [comment]
> That's why a randomized & delayed connection or something similar would be greatly appreciated as a future feature of Electronmail (@vladimiry)

This is being discussed [here](https://github.com/vladimiry/ElectronMail/issues/121) and planned for implementing.

**Comment by vladimiry** [comment]
Here is brief info of how to use https://protonirockerxow.onion/ entry point on Windows:
- Install Tor, ie https://www.torproject.org/dist/torbrowser/8.5.5/tor-win64-0.4.1.5.zip or https://www.torproject.org/dist/torbrowser/8.5.5/tor-win32-0.4.1.5.zip.
- Run `tor.exe` in the console and wait until bootstrapping completed (see the console output). The default on-the-fly config will be used as we didn't specify the custom one. If you need to you could look up on the internet how to use a custom Tor config, how to set up Tor as a hidden Windows service, etc.
- In the app select https://protonirockerxow.onion as an entry domain for the account.
- In the app specify socks5://localhost:9050 as a proxy address for the account (`Advanced` settings block).

![tor](https://user-images.githubusercontent.com/1560781/64478350-e13f1300-d1af-11e9-9a6b-c49ce375bd7a.png)

Referencing this info with #146.

**Comment by lucknaumann** [comment]
@vladimiry 

> * Run `tor.exe` in the console and wait until bootstrapping completed

OK - I believe I _finally_, actually, found the answer. Ha-ha! So, I began to have issues with logging in to the onion site _again_. After much searching, I found out what the issue with Tor and Windows is. Launching tor.exe in a console will, indeed, run tor.exe as a Windows background service but with no console output. Regardless of waiting a few minutes, onion log-in was refused, including repeated attempts. Why the onion site refused to connect after doing this, I don't know. But after killing the tor.exe service, I ran this command: `tor.exe | more` found on [Tor Stack Exchange here](https://tor.stackexchange.com/a/9145). After the console output had finished, I attempted to log in again, and **holy universe**! It worked! _Geez_! 🤯 

NB: Windows users have to pipe **any** `tor.exe` command to `more` for console output. Eg: `tor.exe -h | more`,  `tor.exe --version | more`.

I was going to put this under issue #395 but thought it would be better here.

**Comment by vladimiry** [comment]
> NB: Windows users have to pipe any tor.exe command to more for console output. Eg: tor.exe -h | more, tor.exe --version | more.

It was not like that when the original message was written since I performed the stuff before writing the message. Also I guess "piping" stuff is not supported by old windows console like cmd.exe but powershell only. Editing the original message.

**Comment by lucknaumann** [comment]
I can't say regarding Windows 7, but on Windows 10 I used those commands with cmd.exe. 🤷

**Comment by vladimiry** [comment]
> I can't say regarding Windows 7, but on Windows 10 I used those commands with cmd.exe. shrug

I've changed the original message accordingly, you certainly know better how cmd.exe works being windows user.

**Comment by lucknaumann** [comment]
I hope I'm not being an annoying gnat here. 😄 I wanted to let you know (and yeah, I should have tried this before), that I just tried the command in PowerShell and this works: `.\tor.exe` without any piping. I guess sometimes PowerShell _is_ superior to CMD.

**Comment by vladimiry** [comment]
@lucknaumann does it work with piping in powershell? There better be unified way.

**Comment by lucknaumann** [comment]
@vladimiry Yes, it does, but it is not unified because PS uses a dot slash to launch programs, which won't work in CMD. You could put CMD use: `tor.exe | more` and PS use: `.\tor.exe`. The rest is the same.

The reason for this lies in the **tor.stackexchange.com** thread I linked to above, which has a link to a Tor-CMD bug ([GitLab issue](https://gitlab.torproject.org/legacy/trac/-/issues/13819)). Basically, tor.exe originally launched without a hidden CMD window, so they made it hidden. But people wanted a way to see console output on demand, so they included the pipe command. It seems to be strictly CMD-related. This could be because PS works differently, or its default is to use CMD. Probably the latter.

**Comment by vladimiry** [comment]
Ok, added both options to the original message.

**Comment by lucknaumann** [comment]
@vladimiry 
> Ok, added both options to the original message.

I noticed a typo: Then **tun** [run] `tor.exe | more` in cmd.exe console... 😃
