### ISSUE TITLE
Support mailto: links

### ISSUE THREAD

**Issue by samuel-w** [vladimiry/ElectronMail#118]
Support the usage of mailto:<email address> to create a new message and fill the email address into the to field.

**Comment by vladimiry** [comment]
Is this the same feature request as https://github.com/vladimiry/ElectronMail/issues/62?

**Comment by samuel-w** [comment]
No, it refers to this: https://en.wikipedia.org/wiki/Mailto feature in many email clients

**Comment by vladimiry** [comment]
So you got a `<a href="mailto:someone@example.com">Send email</a>`-like link in email's body and you want when you click it the "new email / compose" screen is opened with sender form field prefilled?

**Comment by samuel-w** [comment]
The mailto link is on a website, <a href="mailto:someone@example.com">like this,</a> click it and it opens the client with the sender field prefiled, similar to how Thunderbird works.

**Comment by vladimiry** [comment]
Ok, then it's a duplication of https://github.com/vladimiry/ElectronMail/issues/62 ie default mail client / mailto links handler.
