### ISSUE TITLE
settings directory parameter needed (the --user-data-dir parameter does not work)

### ISSUE THREAD

**Issue by libBletchley** [vladimiry/ElectronMail#122]
The settings directory seems to be hard-coded to $HOME/.config/electron-mail/.  Supplying the Chromium option `--user-data-dir` does not work.  It's apparently ignored.

This creates a few problems.

* It's very cumbersome to manage multiple profiles.  I wouldn't want to guess all the reasons multiple profiles would be useful, but at the moment it would be useful to workaround #121.

* Users don't necessarily want to organize their files in the same standard way.  I find it a bit annoying that the XDG-* standard dir for configuration (`.config`) starts with a dot, which hides something that's commonly useful.  I've created a symbolic link to resolve that, but in principle it shouldn't be necessary.  And for a bit of trivia, the symbolic linking breaks firejail (https://github.com/netblue30/firejail/issues/2617).  So it would have been useful to try a custom settings folder to circumvent a firejail bug but that's not possible.

* Having the settings and the application data in the same directory is normal in Windows but unconventional in all other OSs.  The separation enables users to treat different kinds of data differently for backup purposes and from a security permissions viewpoint.  Someone might rather have `database.bin` stored with all their other email, in `~/Mail/`.

**Comment by vladimiry** [comment]
> The settings directory seems to be hard-coded to $HOME/.config/electron-mail/. Supplying the Chromium option --user-data-dir does not work. It's apparently ignored.

> So it would have been useful to try a custom settings folder to circumvent a firejail bug but that's not possible.

Can you try running the app this way?

```
ELECTRON_MAIL_USER_DATA_DIR=$HOME/Mail `(which email-securely-app)`
```

> Having the settings and the application data in the same directory is normal in Windows but unconventional in all other OSs. The separation enables users to treat different kinds of data differently for backup purposes and from a security permissions viewpoint. Someone might rather have database.bin stored with all their other email, in ~/Mail/.

I tend to keep all the stuff that app explicitly creates and uses in a single folder. Purpose of each file is described in the readme file.

**Comment by libBletchley** [comment]
Yes that works.  Thanks!

**Comment by vladimiry** [comment]
The app doesn't officially support Chromium args. Just because @electron devs can decide to change things out of the blue. They actually used to break working things quite often with new releases. So you can try using Chromium args, but I don't recommend doing that.

**Comment by libBletchley** [comment]
>The app doesn't officially support Chromium args

ah, makes sense.

For the record, the `ELECTRON_MAIL_USER_DATA_DIR` variable also helps workaround the firejail bug.  So this script works for firejail users:
```
dir_default=$HOME/.config/electron-mail
dir_nonsym=$(readlink ${dir_default%/*})${dir_default##*/}
firejail --name=electronmail\
             --env=ELECTRON_MAIL_USER_DATA_DIR="$dir_conf"\
             --noblacklist="$dir_nonsym" --whitelist="$dir_nonsym"\
             --debug --output="${fn_log"\
             /usr/local/bin/electron-mail
```

**Comment by vladimiry** [comment]
So does the ELECTRON_MAIL_USER_DATA_DIR env variable resolve the issue? Closing?

**Comment by libBletchley** [comment]
ELECTRON_MAIL_USER_DATA_DIR works.  I left the ticket open figuring you would want to document it under this ticket.

Also, the `--user-data-dir` is untested in terms of whether it could be used to customize Chromium settings (like `userContent.css`).  Although either way that doesn't hold up the ticket since that's unofficial.

**Comment by vladimiry** [comment]
By the way ELECTRON_MAIL_USER_DATA_DIR effects only the app data files listed in the readme but electrion's service stuff will still be saved in the `$HOME/.config` folder. I didn't find a way yet how to control the location electrion's service stuff is being saved to.

**Comment by vladimiry** [comment]
Closing as resolved.
