### ISSUE TITLE
SOCKS 4a doesn't work

### ISSUE THREAD

**Issue by libBletchley** [vladimiry/ElectronMail#123]
SOCKS 4a has an advantage over SOCKS 4 and 5: SOCKS 4a *forces* DNS resolution over tor.  With SOCKS 4 and 5, an app has flexibility and can leak a lookup without using the proxy.  And IIRC, Chromium in particular has this leak (or maybe it was Firefox).

Maybe ElectronMail behaves, but users still must trust that it does.  If the proxy rule could be:
```
socks4a://127.0.0.1:9050
```
the user could be confident that there are unlikely DNS leaks.  An app *could* still leak, but not as a programming accident (it would have to be deliberate).

**Comment by vladimiry** [comment]
See this article http://dev.chromium.org/developers/design-documents/network-stack/socks-proxy.

It looks like setting `host-resolver-rules` per account/session is not supported by @electron. So not sure, but you can try using socks5 proxy combined with `--host-resolver-rules="MAP * ~NOTFOUND , EXCLUDE myproxy"` (`--host-resolver-rules="MAP * ~NOTFOUND , EXCLUDE 127.0.0.1"`) chromium command line argument.

**Comment by libBletchley** [comment]
oh right, I forgot I'd been using that option for Chromium.  Supplying `--host-resolver-rules` doesn't break anything.  I'll try to test for leaks and report back.

**Comment by vladimiry** [comment]
Closing due to the inactivity and because supported proxy types is defined by the @electron and @chromium.
