### ISSUE TITLE
forced re-login after logout

### ISSUE THREAD

**Issue by libBletchley** [vladimiry/ElectronMail#127]
I currently have all accounts using the new feature "login at account selection" with no timers, to give complete manual control over logins.  When I "logout" within the Protonmail UI, ElectronMail sees that I'm logged out and forces an immediate login.  The tab was yellow the whole time, but I did not click on the tab to initiate login.

**Comment by vladimiry** [comment]
This is expected behavior as yellow color indicates that account is selected.

But I think deselecting the accounts that have `loginOnSelection` option enabled after the logout might be a good idea.

**Comment by libBletchley** [comment]
seems necessary.. I cannot deselect the account myself.  If I click the tab again, it remains yellow.  If I click "options" that does not change the selection either.

**Comment by vladimiry** [comment]
Does [pre 3.1.1 build](https://www.dropbox.com/sh/bscb7grmpnj8wxm/AADGEKARLavUnV9WInOX1Xmia?dl=0&lst=) solve the issue?

**Comment by libBletchley** [comment]
Yes, in one way.  The tab stays yellow and even if I click on it nothing changes.  But logout from the UI of the website works now.  So apparently it's internally deselected.

**Comment by vladimiry** [comment]
> So apparently it's internally deselected.

Yes, provided build includes added automatic deselection on logout but only if "delay login until selected" option is enabled for the account.

> the yellow is apparently indicating which account is displayed.

Correct, yellow indicates the selected/active account, the one being currently displayed.

The issue is considered fixed.
