### ISSUE TITLE
Change the color of the titlebar and tab bar to match that of the web app

### ISSUE THREAD

**Issue by Bodup** [vladimiry/ElectronMail#132]
See example here: [https://imgur.com/W99LC81](https://imgur.com/W99LC81) (excuse the heavy blur) and here: [https://imgur.com/a/Rpjrqkl](https://imgur.com/a/Rpjrqkl)
I'd be nice if the colors of the tab bar and titlebar changed according to the color used in protonmail or tutanota (note that the colors in protonmail can be customized)
Obviously it should also change when switching accounts since they'll likely have different colors (e.g tutanota)

**Comment by vladimiry** [comment]
This is technically feasible but not a priority.

**Comment by vladimiry** [comment]
See in the similar closed issue #240 :

> There is no goal to match Protonmail's color scheme.
