### ISSUE TITLE
[AUR repo] pacman package issue with 3.3.0

### ISSUE THREAD

**Issue by ajgraves** [vladimiry/ElectronMail#135]
Hello! I wanted to report an issue with the pacman package for 3.3.0 (also posted my comment to the aur page https://aur.archlinux.org/packages/electronmail-bin/#comment-692001)

I get this error when running:

[17738:0430/094522.380764:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/ElectronMail/chrome-sandbox is owned by root and has mode 4755. zsh: trace trap (core dumped) electron-mail

I got it to run by setting mode 4755 (setuid root) on chrome-sandbox, but the package should probably be fixed to either do that on install/update, or if there's a better way of resolving this.

Not sure if related to the update to Electron 5. Still on Electron 4 (5 is in the community-staging repos at this time)

**Comment by vladimiry** [comment]
I made sure before releasing that the app works with SUID Sandbox if you install the Pacman package from here https://github.com/vladimiry/ElectronMail/releases. There is a [script](https://github.com/vladimiry/ElectronMail/blob/97cd25e05938fc985699726e65a62032a9f23f5e/scripts/prepare-chrome-sandbox.sh) that tweaks the `chrome-sandbox` binary during preparing the package on CI server.

Running `stat --format "%a %G %U %n" /opt/ElectronMail/chrome-sandbox` gives me such output for the package intall from the [releasese page](https://github.com/vladimiry/ElectronMail/releases) as `pacman -U electron-mail-3.3.0-linux-x64.pacman`: `4755 root root /opt/ElectronMail/chrome-sandbox`.

But if I install from https://aur.archlinux.org/packages/electronmail-bin I see that 4755 permission got lost: `755 root root /opt/ElectronMail/chrome-sandbox`.

So 4755 permission is not being respected if the package gets installed from the repository.

@joshirio can you look into it? I guess there is a need to tweak the `PKGBUILD` file a little, like adding there `chmod 4755 ./chrome-sandbox` command execution.

**Comment by ajgraves** [comment]
@joshirio let me know if you'd like any help on the PKGBUILD. I'm sure you've got this just fine, but figured I'd offer to help just in case

**Comment by joshirio** [comment]
> if you install the Pacman package from here https://github.com/vladimiry/ElectronMail/releases. There is a script that tweaks the chrome-sandbox binary during preparing the package on CI server.

I did check the pacman package, maybe I missed something, let me check again.

>@joshirio let me know if you'd like any help on the PKGBUILD. I'm sure you've got this just fine, but figured I'd offer to help just in case
Thanks, I'll look into it, if I need help I'll let you know.

**Comment by joshirio** [comment]
AUR package has been updated, the `.install` script now includes the permission setting, see [diff](https://aur.archlinux.org/cgit/aur.git/diff/electronmail-bin.install?h=electronmail-bin&id=44e477bc38e874986c9c65cd0a5659b8bc924d01)

Unfortunately the installed package must be removed first and then reinstalled via the AUR (user data is not touched, so not really an issue), otherwise the permissions are not set, no idea why. Fresh installs work fine. I'll add a comment to the AUR page. Or is there a better way that works also for exiting installs?

**Comment by joshirio** [comment]
Sorry, I was too quick. There's actually a `post_upgrade` script section, so I'll add it also there. Should work.

**Comment by vladimiry** [comment]
I think `chown root:root /opt/ElectronMail/chrome-sandbox` is not required as it's already owned by root but it doesn't hurt. It was needed on CI server for running e2e tests. `electronmail-bin 3.3.0-3` works for me, just tested it.

**Comment by joshirio** [comment]
Your are right, at the next update it will be removed.
