### ISSUE TITLE
Unable to open embedded links

### ISSUE THREAD

**Issue by joshirio** [vladimiry/ElectronMail#136]
![confirm link](https://user-images.githubusercontent.com/12795018/57137897-7b7ded00-6db1-11e9-9e2f-7abc1b611b2b.png)

Recently this confirmation box started to appear, when clicking continue nothing happens, ie. no link is opened in browser.

Links inside the about dialog work fine, so it's just the embedded email links.

```
ElectronMail v3.3.0
Unofficial desktop app for ProtonMail and Tutanota E2EE email providers

Distributed under MIT license.

Electron: 4.1.5
Chrome: 69.0.3497.128
Node: 10.11.0
V8: 6.9.427.31-electron.0

Installed via snap on Ubuntu 18.04.
```

![client](https://user-images.githubusercontent.com/12795018/57138059-f0512700-6db1-11e9-9fd6-45d7ae48ff06.png)

**Comment by vladimiry** [comment]
I see that link confirmation dialog was added with [3.15.28](https://github.com/ProtonMail/WebClient/blob/public/CHANGELOG.md#31528---2019-04-26) protonmail's web client update. So it looks like there is a need to handle the link opening confirmation dialog case at the app side.

**Comment by vladimiry** [comment]
There is a need to somehow intercept and tweak this function https://github.com/ProtonMail/WebClient/blob/29b23c1fc754d32d0006647057899523c583b3a1/src/helpers/browser.js#L73. The thing is that it's not exposed as dependency injection thing and so overriding it would be harder than usual (static patching might be required, not just monkey one).

**Comment by vladimiry** [comment]
I see that it's still possible to copy the link using the right mouse click. So there is no high priority as the workaround exists.

**Comment by vladimiry** [comment]
Should be fixed with [pre-3.3.1](https://www.dropbox.com/sh/esf91pwb5xa7fb5/AAAQ8SmXZT_Y2YZJHsI_Zwjha?dl=0&lst=) build.

**Comment by joshirio** [comment]
Yes can confirm, thanks

**Comment by vladimiry** [comment]
Btw it's solved with [monkey/in-memory patching](https://github.com/vladimiry/ElectronMail/blob/a2311de35c1b81a89b9d75fe6e32f1d9d1380556/src/electron-preload/webview/protonmail/configure-provider-app.ts#L106-L135) (overriding `document.createElement`). So the web clients resources still remain completely original means there is no pre-processing applied.
