### ISSUE TITLE
Add support for ctemplar.com

### ISSUE THREAD

**Issue by fire-pig** [vladimiry/ElectronMail#139]
Thanks for creating ElectronMail!  I've found it very helpful for keeping up to date with my email accounts.  Any chance you could add support for ctemplar.com? They're similar to Protonmail and Tutanota with some nice features that neither of those currently support.  

For example, their checksum implementation, which allows you to check that the code you download matches the code in the repository: 

https://blog.ctemplar.com/ctemplar-checksum-implementation/

Their client is is open source:

https://github.com/CTemplar/webclient

**Comment by vladimiry** [comment]
Adding a new email provider support to the app is not something that can be done in an hour or so. The initial implementation would require a relatively huge amount of work, especially the local store feature. Then the polishing things stage would take place. Besides, there would be a need to maintain the integration, ie keeping the integration in sync with the web client updates. I do like though that the web client is built on TypeScript.

Anyway, I'm not going to start seriously considering enabling CTemplar support until:
- I know that demand to work effort ratio for the service is getting close to the same value of tutanota/protonmail. Right now based on github/reddit pages the community seems to be small.
- I get some indications that service is trustworthy. Again, bigger community would be one instance of such indication.
- Things like encrypted contacts/subjects/attachments/metadata and 2FA support are supported. Right now [it doesn't seem to be the case](https://blog.ctemplar.com/ctemplar-comparison-table/).

So at this time, I'm not ready to invest my time into enabling the integration and maintaining it then. Closing the issues for now. Feel free to reach out if the above-listed points get resolved and I will reopen.

> For example, their checksum implementation, which allows you to check that the code you download matches the code in the repository:

Data hashing is not something unique and it's not something that was invented by CTemplar. This is a known web standard https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity.

Protonmail actually enabled SRI on [Jan 2, 2019](https://github.com/ProtonMail/WebClient/commit/8d4fb531d7c2d47b232d48eb3d8142e0252a8e0c). CTemplar did on [Nov 8, 2018](https://github.com/CTemplar/webclient/commit/f996b6953a6772659826a1a2ced8fd57cab7cfc0). Tutanota [has not done yet](https://github.com/tutao/tutanota/issues/202).

**Comment by fire-pig** [comment]
Gotcha, thanks for taking the time to consider adding support for CTemplar in such detail!  Yeah, I totally understand that it's a lot of work to add a new provider, and that you don't want to spend the time to do so unless there's a proven demand for ctemplar's services.  Hopefully, they eventually will grow to the point that it makes sense to do so.

**Comment by vladimiry** [comment]
As far as I understand neither protonmail nor the tutanota allow anonymous service use. But ctemplar seems to be supporting such capability. If that's correct then that would be a positive point for adding ctemplar support.

**Comment by Godfry** [comment]
Hello I am a member of the CTemplar team.  Encrypted attachments and subjects will be released by the end of this month.  Encrypted contacts and metadata will be released by the end of September.  

SRI provides assurance that the JS libraries served from the website server match the code in Github.   This is not a new technology. However, we were the first to checksum the whole index.html with every build. This allows users to check that we have not altered any content, like loading hidden libraries or change existing ones with different code to the one signed in Github. To summarize, SRI provides protection against library manipulation but does not give users protection against the company itself.   We protect our users against our self with checksums. 
I want to be very careful that we don’t seem negative about Protonmail.  They have a more polished service than we do.  They maintain the OpenPGP.js, and welcome us using that code.  They led the way with elliptic curve encryption for email usage.  They defend the whole community against those that seek to make encryption illegal.   Protonmail and Tutanota are wonderful services and we would be honored to someday be viewed as well as they are.

**Comment by johnbrz** [comment]
Hey, almost a year later and ctemplar had a lot of improvements. Any chance of being added?

**Comment by vladimiry** [comment]
Tutanota support got deprecated in July last year and then got dropped in December. Then all the code abstractions for supporting multiple emails services also got dropped too. So no, new services are not going to be added here, regardless of how great they are. The primary reason is that my time/effort capacity is limited.

**Comment by johnbrz** [comment]
@Godfry maybe your team could help?

**Comment by Godfry** [comment]
@vladimiry I would be more than happy to pay for your time.  Please let me know.
