### ISSUE TITLE
Add a spellchecker

### ISSUE THREAD

**Issue by Ghost-Recon131** [vladimiry/ElectronMail#141]
Is it possible to integrate a spellcheck tool into the app? There's one in Protonmail webpage version.

**Comment by vladimiry** [comment]
There are ready-made modules supposed to handle the need. So there is a need to pick the right one, integrate it, verify that it works without the issue with the most recent electron version and `sandbox: true` / `nodeIntegration: false` flags, etc.

**Comment by Ghost-Recon131** [comment]
ok thanks

**Comment by vladimiry** [comment]
The issue could remain open if you prefer at least as a TODO point.

**Comment by KipThorne** [comment]
I'd like to see a spell checker as well !

**Comment by vladimiry** [comment]
Going to look into this issue soon, maybe next week.

**Comment by vladimiry** [comment]
Spellchecker is coming.

**Comment by vladimiry** [comment]
Can someone confirm that [this](https://www.dropbox.com/sh/kr4wneo19cbwqiz/AACOQ4xBGjJh3Xe_WF02ERkXa?dl=0&lst=) version resolves the issue (please specify which OS you were using, mac/win/linux)?

This is an opt-in feature so it needs to be explicitly enabled for now. After some time it's going to be enabled by default with new releases.

The `config.json` file gets a new `spellCheckLocale` option which is controlled by the dropdown menu of any editable form control and can have the following values:
  - `false` (`boolean` type) - the default value, indicates that the feature is disabled.
  - `true` (`boolean` type) - the app sets this value if feature got enabled. The default/system locale will be resolved automatically with preference to en_US locale.
  - A custom locale value (`string` type), like `en_US` or `ru_RU`. Such value will be set if you explicitly select a specific language from the dropdown menu.

![check-spleelling](https://user-images.githubusercontent.com/1560781/58744892-76b06580-8451-11e9-9ae6-09291db71682.gif)

**Comment by joshirio** [comment]
Ubuntu 18.04 (snap) doesn't work. Maybe the language is missing, see gif
![Peek 2019-06-01 09-36](https://user-images.githubusercontent.com/12795018/58745404-e07c3f80-8450-11e9-97f2-fe45aed3c3ae.gif)

**Comment by vladimiry** [comment]
In your case the app doesn't see dictionaries, there is no respective dropdown list on the shown menu, and it seems to be only the [Snap-related issue](https://forum.snapcraft.io/t/desktop-allow-access-to-host-hunspell-dictionaries/7346). There needs to be at least one dictionary for the feature to work. For Linux, it's `hunspell` dictionaries. So looks like for Snap build the dictionaries need to be pre-packaged with the app as there is no official interface provided for automatic `hunspell` dictionaries detection.

**Comment by Ghost-Recon131** [comment]
This version is working fine on Windows 10 1809
![image](https://user-images.githubusercontent.com/40227626/58745830-cadf3800-8499-11e9-9c1f-ac225924d39c.png)

**Comment by vladimiry** [comment]
@joshirio the build has been updated, second try (link is the [same](https://www.dropbox.com/sh/kr4wneo19cbwqiz/AACOQ4xBGjJh3Xe_WF02ERkXa?dl=0&lst=))? Snap package has got dictionaries embedded (about 60 of them) and it seems to be working well at least on clean Ubuntu 19.04 running under the virtual machine, hope it works for you too.

**Comment by joshirio** [comment]
Yes works fine, tested with multiple languages.

**Comment by vladimiry** [comment]
Resolved with [v3.4.0](https://github.com/vladimiry/ElectronMail/releases/tag/v3.4.0) release.

**Comment by itisafrickinhighlander** [comment]
I was playing with the spell-checking today. It very well, however I would like to suggest two possible additions:
- Adding an option to ElectronMail's settings where spell-checking can be enabled/disabled (e.g. until I found this issue, I didn't know it is in the context menu) + a field with locale selection where one can add/remove/choose which locales they would want to use (e.g. just en_US (now there is multiple English ones) or/and some foreign language/s), just like in browsers;
- Adding an option to automatically select the active locale (language recognition) - a similar way how it works in browsers (personally I have always found Chromium browsers being a bit better at it, so..maybe something like that has gotten into Electron as well??).

**Comment by vladimiry** [comment]
@itisafrickinhighlander 

> a field with locale selection where one can add/remove/choose which locales they would want to use (e.g. just en_US (now there is multiple English ones) or/and some foreign language/s), just like in browsers

Language selection is available through the context menu on any input control, see images posted in the above messages. For now, I'm not going to replicate the same menu in-app settings modal but going to add on/off toggle in the "general" settings block so the feature is better visible to a user.

Automatic language detection doesn't currently work well in @electron https://github.com/electron-userland/electron-spellchecker/issues/85 and I'm not going to implement it customer but maybe after #216 gets resolved something will be changed toward better automatic detection support in @electron.
