### ISSUE TITLE
System File Viewer Unusable Due to Broken Font

### ISSUE THREAD

**Issue by SaltyCybernaut** [vladimiry/ElectronMail#142]
# OS

- Ubuntu 18.04.2

# Software Versions

- ElectronMail v3.3.0
  - Electron: 4.1.5
  - Chrome: 69.0.3497.128
  - Node: 10.11.0
  - V8: 6.9.427.31-electron.0
- GNOME nautilus 3.26.4

# Discription
When ElectronMail spawns a child process like the file explorer (in my case Nautilus) or a system error message, all characters are rectangle as seen below.

![Screenshot from 2019-05-09 11-27-33](https://user-images.githubusercontent.com/7234219/57478494-e3b84d00-724f-11e9-8908-10be8901d171.png)

**Comment by vladimiry** [comment]
Snap / AppImage package?

Can you try DEB package from the [assets list](https://github.com/vladimiry/ElectronMail/releases/tag/v3.3.0)?

**Comment by vladimiry** [comment]
Closing due to the inactivity.

**Comment by SaltyCybernaut** [comment]
@vladimiry I was using the snap package. The .deb package you linked to does **not** have the same problem.

**Comment by vladimiry** [comment]
@SaltyCybernaut can you try the Snap package uploaded [here](https://www.dropbox.com/sh/xxngvxsykh1a4y5/AAC6cljCNDfdtM-cRXVV8d2Ha?dl=0&lst=)? There is no Snap related code change but electron-builder has significantly redesigned the Snap packaging with recent [v20.44.1](https://github.com/electron-userland/electron-builder/releases/tag/v20.44.1) version and so I guess maybe the issue got resolved upstream.

**Comment by vladimiry** [comment]
Closing inactive issue.

**Comment by Cyber-Talleyrand** [comment]
I have this problem, I was using electronmail on Parrot OS (debian) and it was working perfect, but once i change to fedora this problem had appear. Should I attach more info?

**Comment by vladimiry** [comment]
> Should I attach more info?

An issue like this won't be investigated by me as it's OS-specific and there is a workaround of using other Linux package types (deb/Flatpak/Snap).
