### ISSUE TITLE
Allow use of shortcut in MacOS

### ISSUE THREAD

**Issue by frorayz** [vladimiry/ElectronMail#143]
Hello, 

I am an extensive user of shortcut and would like a way to navigate around ElectronMail interface. Can you make it so that I can do that using MacOS's shortcut? For example using Command + Q to close it, Command + W to navigate between tabs?

Thanks!

**Comment by vladimiry** [comment]
That's technically feasible but I don't promise such improvement will be released soon partially because I don't have macOS device and developing with a virtual machine is a pain in my case.

**Comment by frorayz** [comment]
I am not sure if there is any solution to "share" my mac with you? I can always test it for you.

**Comment by wjhrdy** [comment]
My solution to this is to remap Cmd+W -> Cmd+H for this app specifically within bettertouchtool. I'm still missing Cmd+Q but it works alright.

**Comment by vladimiry** [comment]
Moved to #499.
