### ISSUE TITLE
Drop https://beta.protonmail.com entry point

### ISSUE THREAD

**Issue by vladimiry** [vladimiry/ElectronMail#164]
- https://beta.protonmail.com will be removed from the list. So only prepackaged/built-in/offline web clients will be available for selection.
- For those who were using https://beta.protonmail.com entry point, it will be automatically reset to https://mail.protonmail.com.

**Comment by vladimiry** [comment]
The [v3.5.0](https://github.com/vladimiry/ElectronMail/releases/tag/v3.5.0) release has just been published with the change included.

**Comment by HarpuaTheBrave** [comment]
Is it possible to add this back in since Protonmail 4.0 is a major overhaul that I'm sure many users would like to use. Thanks!

**Comment by vladimiry** [comment]
ElectronMail is tightly integrated with the Protonmail WebClient's code so enabling Protonmail 4.0 support will require a significant rework of the current integration which means just getting back the beta entry point in the way it was working before won't be enough. #210 is a related issue.
