### ISSUE TITLE
Can't have a ProtonMail and Tutanota account with the same name

### ISSUE THREAD

**Issue by steamp0rt** [vladimiry/ElectronMail#167]
**Version:** 3.5.0  
**OS:** Arch Linux  
**Installation Method:**  electronmail-bin from the AUR
[log.log](https://github.com/vladimiry/ElectronMail/files/3287351/log.log)

**Comment by vladimiry** [comment]
This is by design and has been discussed before. Simply put user name with domain incuded, like using `darth-vader@pm.me` and `darth-vader@tutanota.de` but not like just `darth-vader`.

**Comment by steamp0rt** [comment]
Oh, ok. Thank you!
