### ISSUE TITLE
Save master password on KDE Wallet

### ISSUE THREAD

**Issue by andretiagogr** [vladimiry/ElectronMail#171]
I can only save the master password with Gnome Keyring installed

* With GNOME Keyring installed:
![gnome-keyring](https://user-images.githubusercontent.com/22418131/59867410-a631fe00-937d-11e9-8a7a-d010565f580d.png)

* With KDE Wallet installed:
![kde-wallet](https://user-images.githubusercontent.com/22418131/59867414-a8945800-937d-11e9-8165-8d0a84c12288.png)

Log file in the settings folder:
`[2019-06-20 18:07:28.536] [error] [src/electron-main/api/index] "keytar" module is unsupported by the system Error: The name org.freedesktop.secrets was not provided by any .service files`

**Comment by andretiagogr** [comment]
Should I close this issue?

I decided to google it and it seems to be related with atom/node-keytar#74

**Comment by vladimiry** [comment]
Thanks for the thoughtful report.

https://github.com/atom/node-keytar/issues/74 is a known upstream issue I'm subscribed to which. The topic also has been discussed before in #57 and #104.

So closing as this is an upstream issue.
