### ISSUE TITLE
Where is the autologin script location?

### ISSUE THREAD

**Issue by ylluminate** [vladimiry/ElectronMail#174]
This is a very cool app and seems great for managing ProtonMail on its own, however I need to be able to manage multiple communication platforms at once and for that I use Rambox.

RamboxPro supports JavaScript injection and I was hoping to extract the JS methodology that you use here to facilitate autologin functionality. Could you please point me to the location of this within the ElectronMail project so that I can emulate this?

**Comment by vladimiry** [comment]
See here https://github.com/vladimiry/ElectronMail/blob/e4481e57c705acec76f5fd15e95a61933946ea24/src/electron-preload/webview/protonmail/api/index.ts#L138.

**Comment by vladimiry** [comment]
Closing as resolved.
