### ISSUE TITLE
How do I add a Tutanota account?

### ISSUE THREAD

**Issue by kevinmcfarlane** [vladimiry/ElectronMail#176]
I installed ElectronMail after getting ProtonMail. Then I got Tutanota. I can't see any way of adding my Tutanota to ElectronMail.

(I'm aware Tutanota has its own desktop application but it would still be convenient to add it to Electron.)

**Comment by vladimiry** [comment]
The similar way you do that with ProtonMail, see animation below.

![tutanota-add](https://user-images.githubusercontent.com/1560781/60272620-2e278300-98fd-11e9-9ff8-accbb8b0e7b1.gif)

**Comment by kevinmcfarlane** [comment]
Hi Vladimir, thanks for the quick response. 

Lol, I did look at Options but I was just clicking on the dropdown to the right, which just shows Toggle View Mode and Settings, etc. Doh!

All sorted now. Thanks.
