### ISSUE TITLE
Add an option to change the desktop notification sound

### ISSUE THREAD

**Issue by KipThorne** [vladimiry/ElectronMail#178]
I have many Windows notifications and this is always the same sound. It would be nice to have a custom sound to set and instantly make the difference between random notification and mail notification.

**Comment by vladimiry** [comment]
The app uses system notifications and so the sound is the same. Switching to custom notifications implementations is not planned.

**Comment by pangratt12345** [comment]
hey, sorry for digging up old topic, there has been added a feature to invoke shell commands after every new e-mail got received as written in this issue https://github.com/vladimiry/ElectronMail/issues/387

So for example a solution to play sounds in Linux could be like this 
- check checkbox in `Account setings->Local store`
- check checkbox in `Account setings->Desktop Notifications->Shell command execution`
And something like this into "Shell command execution" box
```javascript
formatNotificationShellExecArguments(({ login, alias, mails }) => {
	const shellCommand = `mplayer /home/username/sound_for_notification.mp3`
	// const powershellCommand = `Start-Process -FilePath "C:\Users\username\sound_for_notification.mp3" -Wait`
  return {
    command: shellCommand, // shell command to execute after receiving a new e-mail
  };
});
```
You can also send notifications alongside playing sounds in shell command like in issue https://github.com/vladimiry/ElectronMail/issues/387#issuecomment-3189435833
```bash
shellCommand = `mplayer /home/username/sound_for_notification.mp3 & notify-send -t 0 "Title" "Message"`
```
I didn't test this in Windows but maybe something like this could work in Powershell or in WSL
