### ISSUE TITLE
Check Realease Failed

### ISSUE THREAD

**Issue by nullxyz07** [vladimiry/ElectronMail#179]
Hello,

First of all I wanted to thank you for your fantastic work.
We finally have a secure application to connect to Protonmail & Tunatoa. 

On the other hand, I notice a very small bug.
When I launch ElectronMail I get the following error message: 

request to https://api.github.com/repos/vladimiry/ElectronMail/releases failed, reason: connect ECONNREFUSED 192.30.253.116:443

This error message comes from the fact that for the Check Release part, I cannot configure a socks5 proxy.

You can configure one proxy per account, but you can't specify a global value for the other requests, in this case the test to check the updates.

Regards

**Comment by vladimiry** [comment]
Thanks for the report. It has never been stated that proxy for an update check is supported, so not a bug but enhancement :)

Until it's supported I'd recommend to disable update check in the app and watch for releases here on GitHub so you don't observe annoying error messages in the app.
![proxy](https://user-images.githubusercontent.com/1560781/60411952-e001d080-9bd7-11e9-9517-a24335fe2953.png)
![watch](https://user-images.githubusercontent.com/1560781/60411953-e001d080-9bd7-11e9-816d-f263bb671120.gif)

**Comment by nullxyz07** [comment]
Indeed I misspoke it is not a bug but enhancement,)

Thank you for your fantastic work, because in the end you do the work that everyone expected so that we can finally trust in protonmail.

**Comment by vladimiry** [comment]
@nullxyz07 can you try [this](https://www.dropbox.com/sh/4io8j2to9l47k23/AADP5G6as2r4oxwQcGDz88axa?dl=0&lst=) build? When you first time start it the `config.json` file located in [settings folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg) will get updated. Then close the app, fill the `updateCheck.proxy` property of `config.json` file with your value, start the app.

**Comment by nullxyz07** [comment]
Hello,

What reactivity I am imbued with, thank you :)

I found the variable well and I filled it in as I do for my other software

    "proxy": "socks5://127.0.0.0.1:9150"

But I have the following error at startup:

Update check failed: {"url":"https://api.github.com/repos/vladimiry/ElectronMail/releases","status":501,"statusText":"Tor is not an HTTP Proxy"}
Is the error coming from github?

Regards

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by vladimiry** [comment]
The https://github.com/TooTallNate/node-https-proxy-agent is currently used as a proxy agent which only supports http proxies. Going to replace it with a more universal https://github.com/TooTallNate/node-proxy-agent module so socks5 will be supported.

**Comment by vladimiry** [comment]
@nullxyz07 second try? Updated build is [here](https://www.dropbox.com/sh/9vsbzrpoa8cr9mo/AADCa4oCJ7M8CSPz9wRL8Npoa?dl=0&lst=). This time socks5 proxy is going to be supported.

**Comment by nullxyz07** [comment]
Hello,

I think it's work now i dont see any error message when i launch ElectronMail :)

Big Thank You

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
