### ISSUE TITLE
Drop Tutanota support

### ISSUE THREAD

**Issue by vladimiry** [vladimiry/ElectronMail#180]
- From now on, the Tutanota support gets low priority.
- The Tutanota support is going to be dropped when the official desktop client gets offline emails access support or possibly earlier.

So if there are Tutanota users here, consider checking out their [desktop app](https://tutanota.com/blog/posts/desktop-clients).

**Comment by vladimiry** [comment]
Right now the integration works but if they change their internals significantly it's unlikely that I will be willing to keep supporting them. So I want users to know that Tutanota support is deprecated as of now and might get dropped at some point.

**Comment by ookangzheng** [comment]
Okay, Im already migrate to their desktop app

**Comment by matstage** [comment]
Oh no, I picked this package because I have both Proton and Tutanota...

**Comment by vladimiry** [comment]
If someone was still using Tutanota with the [local store](https://user-images.githubusercontent.com/1560781/51189497-382a6c00-18f1-11e9-9b9a-baa63f0c0ff4.gif) option enabled then there probably `body must be a string` errors quire frequently appearing in the app (especially in the case of working with external emails). [Here](https://www.dropbox.com/sh/1ieblp8kjr80lvu/AAD3S7dTHkIjVC57GrFRw9YTa?dl=0&lst=) is the link to the work-in-progress version that includes a fix for the named issue. It was assembled from the master branch just recently: [travis](https://travis-ci.org/vladimiry/ElectronMail/builds/608951487), [appveyor](https://ci.appveyor.com/project/vladimiry/electronmail/builds/28700470). But in general, I recommend stopping using Tutanota with ElectronMail since the support of this service to be dropped here.

The high frequency of errors explained by a "backup" syncing trigger which is set to 5 minutes (another "reactive" trigger is any action with email/folder/contact). The iteration of the locally saving synced data was failing since Tutanota changed the API but the app was not taking this change into the account. They introduced a use case when `compressedText` property should be taken as body content if the `text` property is not set. Such issues expected to happen since neither Tutanota nor Protonmail provides public API, besides the app is an unofficial client.

**Comment by vladimiry** [comment]
I was personally asked to keep the Tutanota supported and I now consider to:
- Keeping the Tutanota-only app version in `tutanota` branch with minimal to non-existing support from my side.
- Renaming the app located in `tutanota` branch to `tutanota-mail` so both `electron-mail` and `tutanota-mail` could be started at the same.

**Comment by vladimiry** [comment]
Tutanota support has been dropped with v4.0.0 release (will be published soon).

If someone wants to use working but unsupported `tutanota-mail` desktop app assembled from the `tutanota-mail` branch with dropped ProtonMail support:
- Installation packages uploaded [here](https://www.dropbox.com/sh/yfoh6pac91np67p/AABUb3-2zVo4oAg866ftNDvza?dl=0&lst) (`tutanota-mail-4.0.0-2019-12-20-911c8c0` build)
- SHA1 hashsums
```
fd4ca34d285eb07a333b3491e977627fc9591779  tutanota-mail-4.0.0-linux-amd64.deb
0392bdd04513bd773ca5710bb656bd426d0291c2  tutanota-mail-4.0.0-linux-amd64.snap
b41bb3f3045c23da5d77fc3fd852881a421c2c70  tutanota-mail-4.0.0-linux-x64.freebsd
a5d650c81d1d1e3fb0643b518390f816aca1cdf6  tutanota-mail-4.0.0-linux-x64.pacman
2c906e0b649611c20c3904dd29da2a82709fa099  tutanota-mail-4.0.0-linux-x86_64.AppImage
fc1f69d4defa20814e23290475b928e8e51a165a  tutanota-mail-4.0.0-linux-x86_64.rpm
3bd393fbdb033d6211effc25712390b4bdcb40db  tutanota-mail-4.0.0-mac.dmg
3bdd5f7a811f923d5c08221b5d062c6ee3f04570  tutanota-mail-4.0.0-windows-nsis-installer.exe
```
- CI build logs:
  - https://ci.appveyor.com/project/vladimiry/electronmail/builds/29676729 (Windows).
  - https://travis-ci.org/vladimiry/ElectronMail/builds/627670986 (Linux, macOS).

**Comment by DutchPete** [comment]
> Tutanota support has been dropped with v4.0.0 release (will be published soon).
You should change the GIF animation on your Github page because it still shows Tutanota too. I installed ElectronMail because of that since I have Proton and Tuta.

I am disappointed you dropped support for Tuta but you have your reasons.

**Comment by vladimiry** [comment]
> You should change the GIF animation on your Github page because it still shows Tutanota too.

The animated image placed in the readme/project-front-page has just been updated.

**Comment by DutchPete** [comment]
> The animated image placed in the readme/project-front-page has just been updated.
Thank you. But now there is a grey field saying "another account". Is it possible to add e.g. a Gmail account? If so how? When I tried to add another account the drop-down only gives 3 ProtonMail options.

**Comment by vladimiry** [comment]
The app only supports ProtonMail email service. Supporting other services is not planned.

**Comment by DutchPete** [comment]
OK, so in your GIF that grye field showing "other accounts" is misleading too.
Note: I am not trying to hassle you, I just want it to be clear because I was misled about Tuta, as I said.

**Comment by vladimiry** [comment]
> in your GIF that grye field showing "other accounts" is misleading too.

Not misleading at all. The app supports adding multiple ProtonMail accounts.

**Comment by DutchPete** [comment]
OK, got it ;-)
Over & out.

**Comment by vladimiry** [comment]
If someone needs it, v4.0.2 installation packages uploaded [here](https://mega.nz/folder/N0YjGIYY#W_ZhbVKF2nqw5pdX_0RbEw). Assembled from `tutanota-mail` branch. See changes list [here](https://github.com/vladimiry/ElectronMail/compare/cfa39179...378c12a6) (the key one is [update built-in tutanota web client (3.66.3 => 3.74.2)](https://github.com/vladimiry/ElectronMail/commit/ba8bb9c78efa50efd05efd676f3f2cfcf7220f65)). It's unsupported build.

**Comment by DutchPete** [comment]
@vladimiry Wow. So, does this mean that if I download the tutanota-mail.dmg and install it I will have control of both my Protonmail and Tutamail?

**Comment by vladimiry** [comment]
Nope, see https://github.com/vladimiry/ElectronMail/issues/180#issuecomment-567642263.

**Comment by DutchPete** [comment]
Having to install 2 apps is not acceptable for me. Thanks for your effort anyway.

**Comment by vladimiry** [comment]
New v4.0.3 build placed [here](https://mega.nz/folder/wp4g1JaT#UXnAfFkoGSAKelS-VwiV3g) (comes with tutanota web client 3.76.11+ 4395838).

**Comment by vladimiry** [comment]
New v4.0.3 build placed [here](https://mega.nz/folder/1xQG0DBZ#Kg5xO36Ifyd2Sp-Ntk8FsA) (comes with tutanota web client (3.76.11+ 64121d5).

**Comment by bingoxo** [comment]
I hope you consider bring back tutanota , as the official client has limited search (14 days) and we have to pay to search for longer periods . Or offline mode (still in roadmap) so the benefit of their official app is  very minimal .

I just downloaded the 4.0.4 build and downloaded my emails to local storage , is there a way to export the attachments that are in local storage ?

I am only getting the first 500 emails  , is there a way to see all of them ? 

and how does the refresh work ? i don't see a manual button for it

**Comment by vladimiry** [comment]
> I hope you consider bring back tutanota

There is no such intention at the moment. My capacity is limited and so I had to make a move toward supporting and enabling new features only for a single email provider.

> is there a way to export the attachments of emails that are in local storage ?

No. There is no such feature even for protonmail since the app doesn't store the attachments data but it's possible to perform batch export with attachments in live/online mode.

> I am only getting the first 500 emails , is there a way to see all of them ?

The initial/bootstrap fetch should get all the messages. If it doesn't then it might be that tutanota has set limit on the amount of data returned by API. Or they have changed the API in some other way.

> and how does the refresh work ? i don't see a manual button for it

Once the initial/bootstrap fetch completed the local store updating gets triggered reactively, no refresh button needed.

> the benefit of their official app is very minimal

Yep.

**Comment by bingoxo** [comment]
can you please show us how to build your app with latest tutanota maybe that can help someone make a fork

**Comment by vladimiry** [comment]
How to build the app is described in readme. It might be a better option to put effort into expanding the functionality of the official tuatnota desktop app since it's going to stay but still lacks some essential features.

**Comment by TNCS-git** [comment]
The day I discover a client that can use offline for both Tutanota and Protonmail is also the day I had to look again :'(

**Comment by vladimiry** [comment]
Tutanota is not something I'd be interested in: re-integrating in EM, using it, talking about here.

**Comment by t3dium** [comment]
> The day I discover a client that can use offline for both Tutanota and Protonmail is also the day I had to look again :'(

same

**Comment by allanonmage** [comment]
I don't use Proton, only Tuta, and was surprised that no one had developed stand alone clients for it. Something like 5 years later I come across your project on Alternative.to and it says it supports Tuta, so I was all excited. Now I am sad.
