### ISSUE TITLE
Deploy also as flatpak

### ISSUE THREAD

**Issue by mike2307** [vladimiry/ElectronMail#181]
From all the available distribution formats, flatpak is missing.

**Comment by vladimiry** [comment]
Flatpack [is not yet supported by electron-builder](https://github.com/electron-userland/electron-builder/issues/512). Custom build scripts implementation is not planned at the moment.

**Comment by vladimiry** [comment]
Will reopen when the referenced upstream issue gets resolved.

**Comment by blackva** [comment]
Hey! There is [a tool](https://github.com/endlessm/electron-installer-flatpak) that seems to make it much easier to build flatpak apps. Can you please check it out? 

I am using Fedora and snap is buggy here. I have to reinstall your app multiple times a month because it somehow unrecoverably loses its dependencies. Would be really nice to have flatpak as an option.

**Comment by vladimiry** [comment]
I think if `flathub` package gets supported here then it would be publishing to https://flathub.org/ without `electron-installer-flatpak` use. Related doc is here https://github.com/flathub/flathub/wiki/App-Submission.

**Comment by vladimiry** [comment]
I've already tried the v4.6.0-based flatpak build and it works well except for the master password saving using KeePassXC as a Secret Service implementation, see feature details in https://github.com/vladimiry/ElectronMail/wiki/FAQ. So unfortunately GNOME Keyring us required for now if you want to save the master password using flatpak package. See the upstream app publishing issue [here](https://github.com/flathub/flathub/pull/1656).

**Comment by vladimiry** [comment]
By the way it looks like the Snap and Flatpak packages will be able to get security boost when @electron releases https://github.com/electron/electron/pull/19159.

**Comment by vladimiry** [comment]
The app is now published at https://flathub.org/apps/details/com.github.vladimiry.ElectronMail. Here is the repository https://github.com/flathub/com.github.vladimiry.ElectronMail.
