### ISSUE TITLE
Use monochrome icons for tray

### ISSUE THREAD

**Issue by fbraz** [vladimiry/ElectronMail#184]
Could you please consider to change your tray icon? Please adopt a monochrome icon. That way it will have a great look for most configurations. 

Let's use Steam as an example: 

OLD 
![before](http://2.bp.blogspot.com/-aoj7Ovw9-uw/UQ_brIhS_kI/AAAAAAAANN0/w2NJ0GCpHzA/s1600/steam-appindicator-default.png)

NEW (dark background) 
![after](http://4.bp.blogspot.com/-Jet9AhvH_FM/UQ_bw98UCFI/AAAAAAAANN8/CocrDzEePNU/s1600/steam-appindicator-ubuntu-mono-dark.png)

NEW (light background) 
![after](http://2.bp.blogspot.com/-YaG7xXBrQic/UQ_cAsy0OuI/AAAAAAAANOE/bHcqE0cO3i4/s1600/steam-appindicator-ubuntu-mono-light.png)

**Comment by vladimiry** [comment]
Is it macOS?

Electron supports detecting dark mode on macOS and system colors on Windows:
- https://electronjs.org/docs/tutorial/mojave-dark-mode-guide
- https://electronjs.org/docs/api/system-preferences

So supporting dark/light icons set for at least macOS should be technically possible.

The thing is that I tend to keep the app work and look similar on all the systems partially because of the reduced maintenance burden. Which is why this issue gets low priority.

Besides that, the Electron documentation highlights that Apple's own guidelines saying:
> you shouldn't use the dark mode native interfaces if your app's own interfaces don't support dark mode themselves.

**Comment by fbraz** [comment]
It's a very old version of GNOME, a desktop manager for Linux. I picked that image after a quick search but the idea is the same for every Linux desktop.
Maybe it would be easier to let the user pick one from a few options (2 or 3) like this app does:
![Screenshot from 2019-07-10 04-49-56](https://user-images.githubusercontent.com/32760239/60950862-55ebf300-a2ce-11e9-8d68-37acf6899b3b.png)

**Comment by vladimiry** [comment]
I'd also consider an option to change the color programmatically, similar to how the app currently handles the unread badge coloring, so any color could be used.

**Comment by vladimiry** [comment]
@fbraz can you try [this](https://www.dropbox.com/sh/w0oo7hdgzauahls/AABrhvpVDagT2lBIYydOpoqVa?dl=0&lst=) build?

Here is how to customize the tray icon color:
![icon](https://user-images.githubusercontent.com/1560781/61171195-e3546f00-a57c-11e9-9efe-415b7bdcdc38.gif)

**Comment by fbraz** [comment]
I instaled the .deb package but I see the same tray icon as before and changing parammeters in Appearence does nothing. Should I try removing my snap app first?

**Comment by vladimiry** [comment]
I didn't try installing both deb and snap packages on the same system, but my guess is that these packages should not conflict with each other.

Works on clean Ubuntu 19.04 (as well as on macOS and Windows):
![peek](https://user-images.githubusercontent.com/1560781/61176530-0279ed80-a5cb-11e9-9697-d78560c3a380.gif)

**Comment by fbraz** [comment]
I uninstalled the snap package and installed the debian package and the icon didn't change.
Do I need to remove some folder by hand?

**Comment by fbraz** [comment]
I deleted the following folders and the same icon keeps poping up, extrange:
~/.config/electron-mail
~/snap/electron-mail

**Comment by vladimiry** [comment]
There is no need to remove your data folders as they don't contain the assets like a static icon. The implementation doesn't include the OS-dependent logic. My guess is that you go with the somehow special setup/environment since it worked well on all the systems I tried the feature (Arch + Xfce, Ubuntu 19.04, Windows 10, macOS Catalina 10.15).

**Comment by vladimiry** [comment]
When you change the color in settings modal can you see the same value got saved to the `customTrayIconColor` property of the `config.json` file (located in the [setting folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg))?

**Comment by fbraz** [comment]
Yes. 
This is my config.json
```
{
  "spellCheckLocale": false,
  "encryptionPreset": {
    "keyDerivation": {
      "type": "sodium.crypto_pwhash",
      "preset": "mode:moderate|algorithm:default"
    },
    "encryption": {
      "type": "sodium.crypto_secretbox_easy",
      "preset": "algorithm:default"
    }
  },
  "window": {
    "bounds": {
      "x": 448,
      "y": 171,
      "width": 1024,
      "height": 768
    },
    "maximized": false
  },
  "fetching": {
    "rateLimit": {
      "intervalMs": 60000,
      "maxInInterval": 275
    },
    "messagesStorePortionSize": 500
  },
  "timeouts": {
    "dbBootstrapping": 43200000,
    "dbSyncing": 1800000,
    "webViewApiPing": 15000,
    "domElementsResolving": 20000,
    "defaultApiCall": 25000,
    "databaseLoading": 300000,
    "indexingBootstrap": 30000
  },
  "updateCheck": {
    "releasesUrl": "https://api.github.com/repos/vladimiry/ElectronMail/releases",
    "proxy": ""
  },
  "indexingBootstrapBufferSize": 1000,
  "jsFlags": [
    "--max-old-space-size=3072"
  ],
  "checkUpdateAndNotify": true,
  "closeToTray": true,
  "compactLayout": true,
  "disableSpamNotifications": true,
  "findInPage": true,
  "fullTextSearch": true,
  "logLevel": "error",
  "startMinimized": true,
  "unreadNotifications": true,
  "_rev": 14,
  "customTrayIconColor": "#ffffff",
  "customUnreadBgColor": "",
  "customUnreadTextColor": ""
}
```
But I see the old icon. The default for electron trays:
![Screenshot from 2019-07-14 16-04-29](https://user-images.githubusercontent.com/32760239/61188129-27b13f00-a651-11e9-9b6b-2b6a5f25c542.png)

**Comment by vladimiry** [comment]
I thought you were seeing the custom app icon, the green one but it's worse as you get the electron icon displayed. This makes me think that it's @electron 's icon, ie the upstream one. I mean Electron itself doesn't support your system setup (`old version of GNOME`).

I could play around the issue, maybe making it work somehow on your setup but it would require me to have the same exact system setup as you have and I don't have the capacity for such activity.

The feature will be working well for the majority of the users and so it will be included in the next release.

**Comment by fbraz** [comment]
Sorry, I'm not a native english speaker so my comunnication skills aren't the best, but that image showcasing a very ```old version of gnome``` weren't mine, were picked randomly from the web just as an example. I'm running GNOME 3.32.1 wich is the version that is shipped with Ubuntu 19.04.

**Comment by vladimiry** [comment]
Ok. As you could see on the above picture it works well on Ubuntu 19.04 at least on the one I installed on virtual machine for testing purposes. So the issue remains unreproducible on my side and therefore unfixable.

Don't know if [this](https://github.com/ubuntu/gnome-shell-extension-appindicator) stuff is compatible with your system but it presumably might change/improve the systray behavior.

**Comment by fbraz** [comment]
It doesn't work for me right now but these things change all the time so I'll keep an eye for the appindicator extension. Thank you for your efforts Vladimir, much appreciated.
