### ISSUE TITLE
ElectronMail MacOS icon problem

### ISSUE THREAD

**Issue by Imparium** [vladimiry/ElectronMail#185]
The ElectronMail icon on notifications in MacOS is different from the main being used.
Here is a printscreen to this defective icon shown.
![Xwf8Kd](https://user-images.githubusercontent.com/26612284/60917266-f0b0e700-a266-11e9-8f6c-9dfd5bb316d9.png)

**Comment by vladimiry** [comment]
I confirm the issue. Thanks for the report.

**Comment by vladimiry** [comment]
Chrome [since v22](https://developer.mozilla.org/en-US/docs/Web/API/Notification/icon) supports the explicitly specified custom icon for notifications, so going to try this option first of all.

**Comment by vladimiry** [comment]
@Imparium can you try [this](https://www.dropbox.com/sh/w0oo7hdgzauahls/AABrhvpVDagT2lBIYydOpoqVa?dl=0&lst=) build?

**Comment by Imparium** [comment]
I am going to try it now

**Comment by Imparium** [comment]
No, the icon is still incorrect.

**Comment by vladimiry** [comment]
Worked well for me on macOS Catalina 10.15. At the moment I don't have another macOS system to test the stuff as well as don't have other ideas of the potential fix.

**Comment by andrewkdinh** [comment]
I have this issue when the app is in a folder. The icon will show normally when you click on the folder, but not when the folder is closed. 

ElectronMail v3.7.0
MacOS Mojave v10.14.5
MacBook Pro (13-inch)

[Video proof](https://imgur.com/a/YLZqkDO)

**Comment by vladimiry** [comment]
Can someone confirm that v3.7.1 is still affected? That version has got @eletctron 5 => 6 update and so maybe the issue got resolved upstream.

**Comment by andrewkdinh** [comment]
I still have the folder icon problem with v3.7.1

**Comment by BBaoVanC** [comment]
I'm running v3.7.1 on my MacBook Pro, macOS Mojave 10.14.6, I also have the issue.

**Comment by bit-for-byte** [comment]
@vladimiry I have the same issue. It looks like that in notifications when I get a new message.

**Comment by BBaoVanC** [comment]
This issue doesn't happen anymore for me on macOS Catalina 10.15.1, ElectronMail v3.8.0. Not sure which update fixed it.

**Comment by ylluminate** [comment]
Still having this on 10.14.6.

**Comment by vladimiry** [comment]
This is an upstream issue as the app doesn't explicitly render the icon but only specifies the PNG image. So the only possible solution is updating @electron version or macOS version. We got the message above that updating to Catalina helps. I work on upgrading to @electron version 8 but there are still blocking upstream issues.

**Comment by vladimiry** [comment]
Can someone who still experiences the issue test [this](https://www.dropbox.com/sh/vgsmco3sgtvzr3a/AAA9pNU_7xTPKRKj_38uKxPQa?dl=0&lst=) build?

Changes:
- Make icon color customization introduced with [v3.7.0](https://github.com/vladimiry/ElectronMail/releases/tag/v3.7.0) release affect desktop notification icon too (#222, 38629bcf324c3a73847a5da0ffd04b0f23bcbdbc)

So the build uses a dynamic/DataURL image instead of the static file, so maybe it will work around the original issue.

**Comment by vladimiry** [comment]
> PS don't use this build on a regular basis as it's a little buggy (at least don't edit/add the accounts to the app).

Updated the build link in previous message, it's now safe to use it on a daily basis.

**Comment by vladimiry** [comment]
I'm closing the issues since as I wrote before it's the upstream issue. I'd recommend trying the recent release. There are now 3 packages provided for specific macOS versions and it increases chances for better compatibility.

**Comment by macbugs** [comment]
The issue persists in 4.13.5 - also affects file browser ("Finder") and file properties ("get info") views

![Screen Shot 2022-03-18 at 14 34 56](https://user-images.githubusercontent.com/101867641/159063276-4cfc512f-2812-4c67-ab4c-610778491400.png)

![icon](https://user-images.githubusercontent.com/101867641/159062157-d4374645-a3fa-405a-994f-b46c239111a3.png)
