### ISSUE TITLE
Can't log in to ElectronMail

### ISSUE THREAD

**Issue by lowender62** [vladimiry/ElectronMail#191]
I am a Tutanota user and when I was setting up ElectronMail I accidentally put in yutamota dot com instead of tutanota dot com and I couldn't change it. I tried uninstalling and reinstalling it but it takes me straight to the password log in but then fails. I am sure it would because I have fixed the email address. Any idea's how I can just get a fresh start at installing it? I am no programmer but do ok if someone can help me out. 
Thanks

**Comment by pszabo75** [comment]
https://github.com/vladimiry/ElectronMail/releases/tag/v3.6.2
Tutanota support was removed.

**Comment by lowender62** [comment]
Well I guess that explains it. I thought it said it may be removed but I guess that really doesn't matter. I like the email but need to get notifications on my laptop not just my phone which works fine. 
I appreciate the help. I guess my search for a email provider goes on. 
Thanks !!!!

**Comment by vladimiry** [comment]
@lowender62, you can remove the wrong account via the settings modal:
![remove-account](https://user-images.githubusercontent.com/1560781/61175887-c7be8800-a5bf-11e9-8b33-9bfffaa5c946.gif)

Alternatively, you can remove the `settings.bin` file located in the [setting folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg) and restart the app then. This action removes all the accounts.

By the way the initial auto login attempt won't happen if you don't save the password in the app.

@pszabo75, Tutanota support [is deprecated](https://github.com/vladimiry/ElectronMail/issues/180) but not removed yet. Which means it still works but there will be no new related to Tutanota features added or fixes implemeted and at some point the account type support will be removed.

**Comment by lowender62** [comment]
When I log in this is the only screen I have come up. 
![2019-07-13 13_12_40-Window](https://user-images.githubusercontent.com/11477816/61176018-ddf82400-a57e-11e9-8fb0-d9a850bacb05.png)

**Comment by vladimiry** [comment]
Which means you are entering the incorrect master password. Removing the `settings.bin` file as written above will allow you to re-enter the master password.

**Comment by lowender62** [comment]
I am not able to get anywhere except this screen shot. No way I can find to get to the setting as in your above instructions. 
![2019-07-13 15_08_58-Window](https://user-images.githubusercontent.com/11477816/61176079-38de4b00-a580-11e9-97db-0f90f78a3615.png)

**Comment by lowender62** [comment]
I appreciate your help and your first response makes perfect sense to me but I just can't get there. Much of this is over my head but your instructions are straight forward if I could get to the settings.

**Comment by vladimiry** [comment]
There are 2 ways of how to reach the settings folder, repeating [the link to the image](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg). Obviously, in your situation, your way is through the context menu of the tray icon (the bottom picture on the referenced image).

**Comment by lowender62** [comment]
Thank you for working with me on this. I think I am there to start over and try again. 
![2019-07-13 15_20_36-Window](https://user-images.githubusercontent.com/11477816/61176185-e9008380-a581-11e9-9b57-5ea0f8edd1c7.png)

**Comment by lowender62** [comment]
Now I am getting this error. 
![2019-07-13 15_45_21-Window](https://user-images.githubusercontent.com/11477816/61176376-6083e200-a585-11e9-9c0d-b0f5c4cf17e4.png)

**Comment by vladimiry** [comment]
It looks like the same issue, the incorrect password has been entered and so the app can't decrypt the settings.

**Comment by lowender62** [comment]
Yeah. I was hoping I could just start over, create a new password as if I never installed it before but it doesn't seem like I can. I am using Windows 10 and installed the ver for windows. I do appreciate you walking me though and trying to get to work. Thanks again !!!

**Comment by vladimiry** [comment]
Unfortunately, there is nothing else I could guess given the provided information. So closing the issue as it has been addressed to some extent.

**Comment by vladimiry** [comment]
> Now I am getting this error.

@lowender62 if you are still interested in trying the app, try removing both `settings.bin` and `database.bin` files or just remove the entire folder and restart the app then. My new guess is that the latest error you pictured is related to the `database.bin` file decrypting which is logical since the previous encryption key is no the same as the newly generated with new `settings.bin` file creating.

**Comment by lowender62** [comment]
Absolutely interested and will try what you posted above and see if that get's it to work.

**Comment by lowender62** [comment]
Seems to be working fine. Notification badge is working and that is what I really wanted. I would imagine at some point they will get that figured out in their official app but this seems to be a great alternative. 
Thanks again for all your help !!!!

**Comment by vladimiry** [comment]
Thanks for the feedback. Aside from the notification badge feature, I think that, in general, features like offline access to the email messages and full-text search could also be considered as interested and somehow unique.

**Comment by lowender62** [comment]
Yes, I agree. I am new to Tutanota and have been trying out a few different providers. I liked what I read about Proton but wish it had a calendar as I do need that, but I can always get another calendar app. One other thing lacking in Tutanota desktop app is no spell check. Web based has it but not their app but they say it's coming.

**Comment by vladimiry** [comment]
Spell check is supported here. But if you are aiming using Tutanota service I'd recommend reviewing [this](https://github.com/vladimiry/ElectronMail/issues/180) issue.

**Comment by lowender62** [comment]
I did see that so I figured it would be temporary and completely understand why you would make that decision. Their app is nice just not quite ready with all the features I would like, but on a whole it seems like a good choice. I'm still exploring before I make a final decision.
