### ISSUE TITLE
[Question] How to remove master password from Windows 10?

### ISSUE THREAD

**Issue by DarylSun** [vladimiry/ElectronMail#198]
Hello, how can I securely remove my master password from the system keychain of Windows 10? I uninstalled the app, but forgot to log out. I looked it up online, and saw that I had to open Credential Manager to delete the password. Is this correct?

**Comment by vladimiry** [comment]
> I had to open Credential Manager to delete the password. Is this correct?

Correct. You can reach the Credential Manager via the Control Panel or simply run the command for direct access: `rundll32.exe keymgr.dll, KRShowKeyMgr`.

Also remove the data folder which on Win 10 is normally located in `C:\Users\<user name>\AppData\Roaming\electron-mail`.

**Comment by DarylSun** [comment]
Alright, I managed to delete both my master password from Credential Manager, and my settings folder. Thank you for the clarification.
