### ISSUE TITLE
Tray icon blurry in macOS

### ISSUE THREAD

**Issue by BBaoVanC** [vladimiry/ElectronMail#199]
I have noticed that the tray icon on macOS appears very low-res (about 16x16).
<img width="627" alt="image" src="https://user-images.githubusercontent.com/17971474/63657086-a0cca780-c762-11e9-903f-cc73a492a904.png">
Compare to the other tray icons to the right in the above screenshot.

MacBook Pro 13-inch (2560x1600 resolution) -- macOS 10.14.6 -- ElectronMail v3.7.1

**Comment by vladimiry** [comment]
The app scales the 128x128 icon down to 16x16 on macOS, related code is [here](https://github.com/vladimiry/ElectronMail/blob/5c8acecf5003b982891f13f18fd3e3661afe9fd5/src/electron-main/api/endpoints-builders/tray-icon/lib.ts#L25). There was no such scaling initially but macOS was unable to scale big icons automatically, see the respective issue [here](https://github.com/vladimiry/ElectronMail/issues/24).

Going to try disabling the downscaling when I get acces to macOS system, maybe there will be no described above issue anymore since the app now uses upgraded @electron version.

**Comment by andy-asana** [comment]
So what dimensions should our PNG be to avoid blurriness?

**Comment by macbugs** [comment]
should be maximum allowed by OS in vertical dimension (22 pixels)
"menu bar icon" - https://iconhandbook.co.uk/reference/chart/osx

**Comment by vladimiry** [comment]
Can someone test [this](https://mega.nz/folder/swAwzazS#whMkrHaQUZlh2EqbxO4znA) build (if you do, please specify macOS the version used)? The build comes with `16x16 => 22x22` increased size of the tray image.

**Comment by macbugs** [comment]
Tested on Mac OS 12.3
(image depicts "selected" mode with mouse button depressed)

![menubar4](https://user-images.githubusercontent.com/101867641/162550579-a8016b0b-0f10-4ccf-bd6b-8ac61f8ad05f.png)
**note:** this looks like 20 pixels to me, but at least the padding is balanced 👍
 (and looks much better than Mac OS system icons)
![menubar5](https://user-images.githubusercontent.com/101867641/162550639-fec43c22-ce0f-4119-86b4-7d4bd526e5af.png)
However, [this](https://github.com/vladimiry/ElectronMail/issues/185#issuecomment-1072695777) icon issue persists.

**Comment by vladimiry** [comment]
Thanks, so going to keep the updated/22x22 image size.

Btw, you can change the icon color to white so it doesn't stand out from the rest of your icons. See https://github.com/vladimiry/ElectronMail/issues/376#issuecomment-786484142 for details.

**Comment by vladimiry** [comment]
> However, [this](https://github.com/vladimiry/ElectronMail/issues/185#issuecomment-1072695777) icon issue persists.

Same [here](https://mega.nz/folder/F0QBAJDL#_f5vPIGwBHvWkc9FCpFQrA)?

**Comment by macbugs** [comment]
> Btw, you can change the icon color

I like that... (and wish other apps supported this feature.)
Also here is a browser-based [color chooser widget](https://duckduckgo.com/?q=color+picker).

> Same [here](https://mega.nz/folder/F0QBAJDL#_f5vPIGwBHvWkc9FCpFQrA)?

Same.  (Every icon below this size is corrupted)

![Screen Shot 2022-04-09 at 16 51 33](https://user-images.githubusercontent.com/101867641/162591256-ca818210-922a-4896-96f7-5706327fb83a.png)
![Screen Shot 2022-04-09 at 16 50 49](https://user-images.githubusercontent.com/101867641/162591233-02a17c3c-5b0f-49a3-85e8-1eec9b718aeb.png)

**Comment by vladimiry** [comment]
> Same.

I just got a regular image url back instead of used in the app release "data url" hoping maybe @electron has fixed the issue but it's still there. No more workaround ideas at the moment.

**Comment by macbugs** [comment]
Problem appears to be corrupted source image file, patch submitted https://github.com/vladimiry/ElectronMail/pull/503

**Comment by vladimiry** [comment]
> Same [here](https://mega.nz/folder/F0QBAJDL#_f5vPIGwBHvWkc9FCpFQrA)?

Can you retest this build for the notification icon case? As I guess a static icon actually made a trick according to https://github.com/vladimiry/ElectronMail/pull/503#issuecomment-1097880465.

**Comment by vladimiry** [comment]
Tray icon size customization is going to be available in the next release, see https://github.com/vladimiry/ElectronMail/issues/505#issuecomment-1105713447.
