### ISSUE TITLE
Crash on Print

### ISSUE THREAD

**Issue by joshirio** [vladimiry/ElectronMail#203]
Printing a mail from ProtonMail webclient causes the entire app to crash when clicking on printing after the print preview dialog. The saved PDF file is still saved entirely on disk, so it looks like it crashes after successful printing.

The log files shows no related entry to this. Tested on Ubuntu and macOS.

**Comment by joshirio** [comment]
Another issue: the built-in (protonmail) print preview dialog cannot be closed when clicking on close or the close button (nothing happens).

**Comment by vladimiry** [comment]
@electron is known to have severe issues with printing, some recent issues:
- https://github.com/electron/electron/issues/19946
- https://github.com/electron/electron/issues/19937
- https://github.com/electron/electron/issues/19768

I keep track of those upstream issues. Besides going to explore the issues one day in order to find a workaround.

**Comment by vladimiry** [comment]
The workaround, for now, is to export the email message to EML file, import it to an email client like Thunderbird and print it there.

**Comment by vladimiry** [comment]
Electron team is making some progress on the issue. Looks like they are going to completely resolve it soon.

**Comment by BBaoVanC** [comment]
Print to PDF works fine on my MacBook (Catalina, 10.15.2). (ProtonMail 4.0 beta Web UI) 
From about page:
ElectronMail v4.2.1
Electron: 7.1.10
Chromium: 78.0.3904.130
Node: 12.8.1
V8: 7.8.279.23-electron.0

**Comment by vladimiry** [comment]
@BBaoVanC does print work for you if you call it 2+ times one by one? There was an issue that printing worked only first time and then if you call it again nothing happened. They fixed it just recently in https://github.com/electron/electron/releases/tag/v7.1.11

**Comment by BBaoVanC** [comment]
Yes, it works. Tested 4 times in a row.

**Comment by vladimiry** [comment]
Thanks for testing the stuff. You were somewhat lucky getting it to work before it got officially fixed in https://github.com/electron/electron/releases/tag/v7.1.11 :smile: It's a good thing but I'm still going to keep the issue open until the app updates to Electron v7.1.11.

**Comment by vladimiry** [comment]
@joshirio, can you try [this](https://mega.nz/#F!ExpXSITa!6nGFWWgIrkSoH7DwAZMmnw) build? It comes with just released @electron version 8. I did a brief testing I didn't notice printing issues in this build.

**Comment by joshirio** [comment]
Printing actually works with v4.2.2, tested on windows and Ubuntu (snap)

> @joshirio, can you try this build? It comes with just released @electron version 8

Also works fine. Looks like it was fixed in some recent update :)

**Comment by vladimiry** [comment]
Closing the issue as Electron has finally sorted the problem out.
