### ISSUE TITLE
2-factor auth code produced is wrong

### ISSUE THREAD

**Issue by DonDino2** [vladimiry/ElectronMail#204]
Hello,

Thank you for this extremely useful program.

The 2FA code produced for Protonmail since I updated to 3.8.0 (half an hour ago) is incorrect.
It does not match the actual code that I get from other 2FA sources, and login is unsuccessful. I have re-entered the correct key in ElectronMail's settings, still no luck.
The time on my laptop is set correctly.
Any ideas are welcome.

**Comment by DonDino2** [comment]
There was something wrong with my laptop as another 2fa app was also producing wrong codes. Fixed itself after a restart.

**Comment by vladimiry** [comment]
> There was something wrong with my laptop as another 2fa app was also producing wrong codes. Fixed itself after a restart.

2fa tokens generating logic might produce invalid tokens if the time on your computer is incorrect.
