### ISSUE TITLE
Would you consider supporting  gmail?

### ISSUE THREAD

**Issue by kxxc** [vladimiry/ElectronMail#205]
Love your amazing work here, 
Like to know that, would you consider supporting  gmail?

thanks! 
Love

**Comment by vladimiry** [comment]
There was no feature-rich (with offline access to the emails and full-text search capabilities), reliable and open-source client for Protonmail and so I built one. But there are many client options for Gmail, so at this time there is no goal to build a new one.

**Comment by kxxc** [comment]
Just thought that will be nice to take only one tray to access mails,

thanks
