### ISSUE TITLE
Suggestion: Add Secure Swiss Data support?

### ISSUE THREAD

**Issue by trymeouteh** [vladimiry/ElectronMail#206]
Secure Swiss data is a new and not so common email provider similar to Proton Mail.

**Comment by vladimiry** [comment]
Closing the issue with wontfix status. You can see some points against adding new service providers support in #139. On top of that Tutanota support is going to be dropped soon (#180) so the app will be supporting Protonmail only and to be honest it will be hard to find a reason for adding support for new/immature service providers in the future.
