### ISSUE TITLE
Entered typo in email address

### ISSUE THREAD

**Issue by joeschmoe1869** [vladimiry/ElectronMail#207]
I cannot find a way to delete account (email address) due to a typo and start over. Electronmail only allows a log in prompt

**Comment by vladimiry** [comment]
![remove](https://user-images.githubusercontent.com/1560781/68068004-c8db1700-fd60-11e9-8a2b-4ed7b2473458.png)

**Comment by joeschmoe1869** [comment]
Thank you!
