### ISSUE TITLE
Where did the account switcher go?

### ISSUE THREAD

**Issue by ItsExtra** [vladimiry/ElectronMail#208]
Hello, I feel very very stupid but staring at it isn't going to help. 

I closed the account switcher options menu and I can't get it back.

It's not on the top of the window and it's not on the side. There's nothing in the top menu. 

Is there a keyboard shortcut or something?

The only thing I can find in here is #36 which shows what maybe ought to be happening. 

Thank you

**Comment by vladimiry** [comment]
Hi, see the second point of the changelog here https://github.com/vladimiry/ElectronMail/releases/tag/v3.6.0.

**Comment by ItsExtra** [comment]
F12 or the menubar. Got it. Thanks!
