### ISSUE TITLE
Setting to change Port

### ISSUE THREAD

**Issue by neubland** [vladimiry/ElectronMail#214]
Right now I have 2 programs on my windows desktop that both try to use the same Port 8989: Electronmail and Sonarr. This creates a conflict. I want to set Electronmail to use a different port. I could not find documentation or a setting to do so.

Feature Request: Implement an option in the Settings menu to change the port that is being used.
Alternative: Implement a setting in a human-readable text file that is documented somewhere.

**Comment by vladimiry** [comment]
ElectronMail doesn't have a built-in server so it doesn't listen to any port. If you still think ElectronMail causes 8989 port use conflicts please provide more information:
- Operation system
- ElectronMail version
- The output of the CLI command that shows 8989 port is used by ElectronMail.

By the way, I guess Sonarr thing is already supporting bind port configuration, you got a workaround if so.

**Comment by neubland** [comment]
Thanks, you are right that I am able to solve my problem, I'm just thinking it may be a useful feature. Sorry for not giving necessary details in the first place.

I use Windows 10 (1903), ElectronMail v3.8.0

I used this command in the PowerShell to get the information what program is using port 8989:
`Get-Process -Id (Get-NetTCPConnection -LocalPort 8989).OwningProcess`

In the Output it said under "ProcessName": ElectronMail. However I am not able to reproduce this output currently. I am not sure what caused this output to happen. I only noticed because Sonarr couldn't be started as the port it wanted to use was currently in use. Closing ElectronMail helped. Sorry for the inconvenience.

**Comment by vladimiry** [comment]
Thanks for proving details. I just have checked on Win 10 and there are ports listened by ElectronMail. Used the CLI command you listed, as well as a few more, and https://docs.microsoft.com/en-us/sysinternals/downloads/tcpview. So there is nothing can be done at the ElectronMail side. Closing the issue but would be interested in seeing new information on the issue if you investigated some.
