### ISSUE TITLE
Option to allow "title" of pageto be same as what a web browser would show.

### ISSUE THREAD

**Issue by mikejzx** [vladimiry/ElectronMail#215]
Greetings, I'd like to make a small suggestion for ElectronMail.
Simply, I think it'd be nice to see the "title" of the actual page change depending on the folder or tab being viewed within the application.  The web browser version does this automatically, but doesn't appear to show in ElectronMail.

For example, when I view ProtonMail in a web browser, the title tag of the page is set to "Inbox | [REDACTED]@protonmail.ch | ProtonMail" (Shown in the image below)
![electronmail-pm-browser](https://user-images.githubusercontent.com/42143005/69529524-8bb31f00-0fc4-11ea-863d-217131cd4a5d.png)

Whereas the application, ElectronMail, in it's current state simply shows, "ElectronMail" as the attached image below shows. (The title shown in the "taskbar" in Electron apps depends on the title tags set in the page from what I have seen in the past.)
![electronmail-title](https://user-images.githubusercontent.com/42143005/69528898-3de9e700-0fc3-11ea-86a3-392e824a7e5b.png)

Notably, the web browser also displays a "(1)", representing an unread message. This is beneficial to users like myself who have the titles of windows visible in their taskbars/panels/etc so that it is more clear when an e-mail has not yet been read.

This could possibly be an optional feature too, just in case some users prefer the current way the title is set.

I know this is a simple thing, but since I have never used TypeScript before I couldn't see a way for myself to implement it, so decided to post it here.

Thank you.

**Comment by vladimiry** [comment]
> I know this is a simple thing

I agree that it's manageable so let's make the feature to be planned :)

Since it's a privacy-concerning feature I think it should be an opt-in one, ie disabled by default, so the app doesn't show sensitive data in the taskbar.

By the way, early releases had the inner page title displayed in the account handle button (see [example](https://user-images.githubusercontent.com/12795018/40077344-ad756522-5881-11e8-9772-85d52b595d90.png)). So it was like tabs in the browser :)

**Comment by vladimiry** [comment]
WIP build with the feature included is uploaded [here](https://www.dropbox.com/sh/bntqrpqsomovujv/AACiAlGxS1ajk8fwR0wqJ9qDa?dl=0&lst=). @mikejzx can you confirm the feature works as expected? See on the below-animated image how to enable the feature:

![peek-min](https://user-images.githubusercontent.com/1560781/69566861-1d249000-0fc9-11ea-9a5f-36171c7f1d48.gif)

**Comment by mikejzx** [comment]
> WIP build with the feature included is uploaded [here](https://www.dropbox.com/sh/bntqrpqsomovujv/AACiAlGxS1ajk8fwR0wqJ9qDa?dl=0&lst=). @mikejzx can you confirm the feature works as expected? See on the below-animated image how to enable the feature:
> 
> ![peek-min](https://user-images.githubusercontent.com/1560781/69566861-1d249000-0fc9-11ea-9a5f-36171c7f1d48.gif)

Great! It works as expected, thank you.

**Comment by vladimiry** [comment]
Thanks for testing and confirming meeting the expectation, closing as resolved then.

**Comment by vladimiry** [comment]
This feature is going to be removed when the app moves to ProtonMail v4 Web Client. They have split the Web Client to 4 different HTML pages/SPAs which in my opinion not only hurts the UX but also increases the burden of having the original feature supported here.
