### ISSUE TITLE
[Request] Add Ability Give Nickname

### ISSUE THREAD

**Issue by fk3ma** [vladimiry/ElectronMail#220]
Can you add feature to give account nickname and/or short text field to add note what context or purpose of account is. Helps if you use to compartmentalize identities and keep track of context for each account. I suggest you give option to display nickname instead of email address in tab. We know its either protonmail or tutanota the icon indicates this no need waste screen real estate with full address name. I would like set custom display name perhaps instead? 

Thank you sir

**Comment by vladimiry** [comment]
Closing as duplicate.

> Can you add feature to give account nickname and/or short text field to add note what context or purpose of account is.

Already added, but not released yet, see https://github.com/vladimiry/ElectronMail/issues/175 (you will find there a dropbox link to the WIP 3.8.1 build).

> We know its either protonmail or tutanota the icon indicates this no need waste screen

#212 (account type icon going to be dropped in along with dropping Tutanota support).
