### ISSUE TITLE
Dark title bar on macOS + matching sidebar

### ISSUE THREAD

**Issue by ylluminate** [vladimiry/ElectronMail#221]
Other macOS Electron apps have had an issue with having a light app title bar like ElectronMail is having presently:
![image](https://p153.p0.n0.cdn.getcloudapp.com/items/E0uErekE/example-2.png)

Other apps such as Mattermost have now resolved this through Electron updates:
https://github.com/mattermost/desktop/issues/848

In addition to this, it would be nice to change the left bar's color scheme to match the dark/light mode of the OS.  Perhaps leaving it the way it is by default for when the OS is in light mode, but then when in dark mode, it would be nice to change the left side panel to a darker gray and black mode to match the OS.

**Comment by vladimiry** [comment]
@ylluminate, the first point should be easy to enable if @electron got the feature supported. The only issue is that I won't be able to test the feature in the near future so will ask you to do so.

The second point will cause adding custom macOS related code since at the moment detecting the dark/light mode toggling in @electron is only [supported for macOS](https://electronjs.org/docs/tutorial/mojave-dark-mode-guide). I would prefer to avoid adding such code but have not decided yet. Although I see that https://electronjs.org/docs/api/native-theme stuff got supported, it worth looking into it as it's supported for all systems since depends on chromium mechanisms.

**Comment by ylluminate** [comment]
Be happy to test. Also - honestly - even in light mode, making the left side bar dark by default wouldn't hurt aesthetics at all and would be better to default to dark for such a drawer / sidebar mechanism since it's mostly out of the way and does not need focus even in light mode.

**Comment by vladimiry** [comment]
Currently used left bar's color was chosen as a compromise between Protonmail's dark-ish colors and Tuatnota's light colors as the app supported both providers. But Tutanota support gt dropped with v4.0.0 and so I agree that it won't hurt to darken the color of the left bar.

**Comment by vladimiry** [comment]
https://electronjs.org/docs/api/native-theme support is added since @electron v7. The app currently uses v6 and the goal is to switch to v8 bypassing the v7. The switch is currently blocked by several upstream / @electron issues.

**Comment by ylluminate** [comment]
😢 So so sad. 😞

**Comment by vladimiry** [comment]
Besides we will probably need to switch to Protonmail v4 to enable dark mode support in the app (like at least left bar's color toggling) since v3 doesn't seem to be very darky.

**Comment by vladimiry** [comment]
Meanwhile, if you hate the left/top bar color so much and you use only one account you could try hiding that bar by hitting F12 or via the general app settings, see #128 (the feature enabled since [v3.6.0](https://github.com/vladimiry/ElectronMail/releases/tag/v3.6.0)).

**Comment by vladimiry** [comment]
@ylluminate can you try the dark title bar thing enabled with [pre-v4 release](https://www.dropbox.com/sh/pzcsm0que6sxw91/AABYdlIgd43H4786VzCoqNK7a?dl=0&lst=)?

FYI: this version also removes Tutanota accounts from the app settings:
- Drop [Tutanota](https://www.tutanota.com/) support (#180, 11033916a7397bb9dedeec4bab249fc0b0987c67, 2459f7078387c8a36336c4c9fe29e5b16287992a, fd3a74e3ae820cf84c7fbaf05c307d3e2b4ee5a9, 3676cb27fbe0fb55dbec66ba7e04d4681c86a26e, edac1584fceffa55218218084018f0e69511b24e, d29d45429006b80f5309af8bfc0cf9f5007a5197). The following action will be performed when the app starts:
  - Removing Tutanota accounts from the app settings.
  - Backing up the original `settings.bin` file (see file purpose in [FAQ](https://github.com/vladimiry/ElectronMail/wiki/FAQ) or in [Readme](https://github.com/vladimiry/ElectronMail/blob/master/README.md)).
  - Showing similar to the following notification:
  ![notify](https://user-images.githubusercontent.com/1560781/71218596-1b51a200-22d3-11ea-8bfa-827ed2ae7f71.png)

**Comment by ylluminate** [comment]
Excellent, dark titlebar is good and I'm detecting no problems @vladimiry.  IDEA: you could allow left sidebar / drawer customization by users like the notification colors. This way we could simply plug in our own colors to our pleasure and save yourself from implementation of mode switching logic.

**Comment by vladimiry** [comment]
@ylluminate please indicate if the issue got resolved in 4.2.0.

**Comment by ylluminate** [comment]
@vladimiry this is looking much better, thank you! 🚀

Dropdown still white on the gear down arrow, but you're doing great here. Ultimately ProtonMail itself needs to get full on dark themes working since it's still pretty clunky.
