### ISSUE TITLE
Fonts too small, and CTRL + or - doesn't work like it does in Chromium

### ISSUE THREAD

**Issue by oneEyedCharlie** [vladimiry/ElectronMail#233]
Fonts are too small for my screen in ElectronMail.  In Firefox or Chromium, accessing ProtonMail web page, I could simply do a CTRL + or - to fix it, but that doesn't work for ElectronMail.  Surely there must be an easy way to increase the general font size, but I was not able to find it when searching.

**Comment by vladimiry** [comment]
The feature comes with next release.

![zoom2](https://user-images.githubusercontent.com/1560781/72874308-c0143480-3d02-11ea-8e81-694ccbd37141.gif)

**Comment by oneEyedCharlie** [comment]
Thank you very much.  I appreciate your hard work on ElectronMail.

**Comment by vladimiry** [comment]
The feature has been shipped in https://github.com/vladimiry/ElectronMail/releases/tag/v4.2.0.
