### ISSUE TITLE
Database View is WHITE!

### ISSUE THREAD

**Issue by ylluminate** [vladimiry/ElectronMail#238]
I've really never used Database View before and just realized that not only it could be helpful, BUT it's BLINDING... Can you please also implement a dark mode for it?

**Comment by vladimiry** [comment]
Some users might like light stuff. So force-turn everything to dark would be a sort of discrimination :smile: But seriously, yes, consistency of UI color scheme still to be improved.

**Comment by vladimiry** [comment]
It's not really dark yet but I've already started making the adjustments:

![dbview](https://user-images.githubusercontent.com/1560781/73141704-10d7b480-4098-11ea-85ea-65587e801daa.png)

**Comment by ylluminarious** [comment]
@vladimiry You could always have a toggle button to allow users to switch between a light or dark theme, as they choose.

**Comment by vladimiry** [comment]
Sure, but that would mean more work to do and for now such switch is not planned.

**Comment by vladimiry** [comment]
Next iteration:
![dbview](https://user-images.githubusercontent.com/1560781/73164308-c2133480-4102-11ea-965f-f90bf9e8116b.png)

**Comment by vladimiry** [comment]
I think I prefer less standing out badges on the mail rows:
![dbview](https://user-images.githubusercontent.com/1560781/73175374-13c7b900-411b-11ea-998d-9c407d7e18d6.png)

**Comment by vladimiry** [comment]
Improved highlighting consistency: borders, font colors, etc (this will be it for now):

![dbview](https://user-images.githubusercontent.com/1560781/73182230-b424da00-4129-11ea-84b2-95439acd122e.png)

**Comment by vladimiry** [comment]
Here is the dark version but I'm going to keep lighter/on-previous-screenshot version for now:
![dbview](https://user-images.githubusercontent.com/1560781/73204215-a1bd9700-414f-11ea-8827-231a22ff0510.png)

**Comment by ylluminarious** [comment]
@vladimiry Why not use that darker version? Would at least be slightly easier on the eyes...

**Comment by vladimiry** [comment]
I've not finally decided which version becomes default until there is no mode toggle. But I tried both and the lighter version was somewhat more comfortable to read text. I didn't do much testing though.

**Comment by vladimiry** [comment]
> lighter version was somewhat more comfortable to read text

Maybe it's because the overall page contrast is high and so I should try turning the body part of the email background to dark mode too (right side on the screenshot).

**Comment by ylluminarious** [comment]
@vladimiry That sounds like a good idea which might make it easier to read, yes.

**Comment by vladimiry** [comment]
Closing the issue in favor of #242.

The following change has been included in just published [v4.2.1](https://github.com/vladimiry/ElectronMail/releases/tag/v4.2.1) release.

![](https://user-images.githubusercontent.com/1560781/73334113-d11df200-427c-11ea-83cc-f2eb9d7aa132.jpg)

**Comment by ylluminate** [comment]
Better, thanks @vladimiry 😅  The only thing I notice missing now is a command-q not quitting and command-, not giving preferences/settings on macOS.

**Comment by vladimiry** [comment]
> On the dark side, hopefully this will evolve at some point when you can consider a full mode switched as I believe you're pondering on.

It's supposed to evolve, one day, subscribe to #242.

**Comment by ylluminate** [comment]
Thank you so much.

**Comment by ylluminarious** [comment]
@vladimiry Thanks, it does look a little better now. Looking forward to the full dark release 😄
