### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Atrate** [vladimiry/ElectronMail#239]
Hello!

Are you open for translations? If so, can you point me to the files that need to be translated? I'll start working and make a PR soon after.

**Comment by vladimiry** [comment]
Hi, thanks for proposing the help with translations. The app was not originally designed to support translations, so some refactoring will have to take place. Such refactoring is not planned for the near future but it's ok if the issue remains open.

**Comment by KizunaH** [comment]
+1

**Comment by vladimiry** [comment]
Closing the issue with wontfix status to make it more clear that I have no interest in working enabling translations support for the app UI.
