### ISSUE TITLE
[UI/UX] Selected account highlight colour

### ISSUE THREAD

**Issue by Atrate** [vladimiry/ElectronMail#240]
Seen as both Protonmail and the app itself got a facelift recently, I've thought that it might be a good idea to make the selected account highlight in Electronmail be blue, like in Protonmail, to match it more nicely.

**Comment by vladimiry** [comment]
There is no goal to match Protonmail's color scheme. But some experiments are possible. So if I will be testing locally some highlighting color changes I think I could post the screenshots here for review.

**Comment by vladimiry** [comment]
> There is no goal to match Protonmail's color scheme.

Closing the issue with won't fix status.
