### ISSUE TITLE
option to revert back new beta design

### ISSUE THREAD

**Issue by ask2018** [vladimiry/ElectronMail#244]
I've noticed since version 4.2.0 there is only option to login using Protonmail 4 beta. I really hate the design change they did with this new beta and I don't see any way to switch back in the current beta version settings. Only option I see there is "default mode" and "dark mode" and then custom theme via CSS settings.
I'm not sure if Protonmail will give us option to switch to old design in final version. But at least for now would be nice to have option to use version 3 or maybe add version 3 theme via the custom theme option inside ElectronMail if that's somehow possible.

**Comment by vladimiry** [comment]
The original plan for adding proton-v4-ui support included keeping in the app both v3 and v4 proton-web-ui, see #210.

> The plan is to keep both v3 and v4 webclients available here in the app until v3 gets deprecated by the service provider.

But I reconsidered since my capacity is limited. So the app is not going to support proton-v3-web-ui anymore.

What I think I could do to tackle the issue is enabling support for embedding custom CSS into the proton pages. So then you will be able to tweak the styling the way you like.

PS I also like proton-v3-web-ui more than the new desing.

**Comment by ask2018** [comment]
I see and understand. Thanks for explanation. Yes enabling support for embedding custom CSS into the proton pages sounds like a good solution. I'm just not exactly sure if I can just extract the old CSS from Protonmail v3 and use it there or I need to write something from scratch  (I'm not CSS coder).
I don't see any critical security fix in the changelog since v4.0.0 , so I guess I can revert back to v4.0.0 for now, because the new design is something I really refuse to use.

**Comment by vladimiry** [comment]
> I'm just not exactly sure if I can just extract the old CSS from Protonmail v3

I have a guess that someone will do that at some point. As I think there many users who don't like the new design.

**Comment by ask2018** [comment]
We will see. But there seems to be more positive comments than negative here:
https://protonmail.com/blog/v4-beta-announcement/

**Comment by vladimiry** [comment]
Looks like ProtoMail Web UI already supports adding custom CSS code, see it in the admin area, `/settings/appearance`. So closing the issue as no action is supposed to be performed.

**Comment by vladimiry** [comment]
> We will see. But there seems to be more positive comments than negative here:
https://protonmail.com/blog/v4-beta-announcement/

See this too https://www.reddit.com/r/ProtonMail/comments/ea1o0p/am_i_the_only_one_who_doesnt_like_the_v4_beta/

**Comment by vladimiry** [comment]
> We will see. But there seems to be more positive comments than negative here:
https://protonmail.com/blog/v4-beta-announcement/

Another public feedback https://www.reddit.com/r/ProtonMail/comments/f2qoy2/protonmail_v40/
