### ISSUE TITLE
Delaying of auto-login process not functional after explicit logout since v4.2.0

### ISSUE THREAD

**Issue by TheDcoder** [vladimiry/ElectronMail#245]
Before v4.2.0, the logout option worked and the ProtonMail "client" used to be properly unloaded after the logout process is complete (I have my account set to login on selection).

Now with the new updated ProtonMail client, ElectronMail automatically logs me back in once ProtonMail reaches the login page.

This was a useful feature, please fix it as soon as possible. And thanks for the good work bringing ProtonMail to the desktop :smile:

**Comment by vladimiry** [comment]
>  (I have my account set to login on selection).

`login on selection` is one of the login triggers of "delayed login" feature.

The issue you described, ie no delayed login anymore after the explicit logout is a cost of RAM usage got optimized with 4.2.0 release :smile:  :

> - Improve the `delayed auto-login` feature (originally introduced in [v3.1.0](https://github.com/vladimiry/ElectronMail/releases/tag/v3.1.0) release). Before [v4.2.0](https://github.com/vladimiry/ElectronMail/releases/tag/v4.2.0) even if you specified either or both `timer`/`click`-based delays, the `web-view` process of the email account was still starting without delays. So the auto-login flow was delayed but the RAM was consumed greedily. Now the `web-view` process won't start while the delays are still in place.

It has never been promised that delayed login will be functional after it got finished once on app start. So that was a sort of an extra feature that now got dropped but might get back one day.

**Comment by vladimiry** [comment]
@TheDcoder, I just looked into the code and I think there is an easy way to get the behavior you liked back not affecting the existing functionality. Will ask you to test a new app build when it's ready.

**Comment by TheDcoder** [comment]
Thanks for the fast response, please build the pacman package if you'd like me to test a build, it will be easier for me to just upgrade/reinstall the package :)

**Comment by vladimiry** [comment]
The quick guess didn't work out, so I will need to take another look at some day later.

**Comment by vladimiry** [comment]
@TheDcoder, if you know how to build the pacman package you could already go ahead and try the fix pushed to https://github.com/vladimiry/ElectronMail/commits/issue-245 branch. Alternatively, I will upload the package when the CI service gets it prepared.

**Comment by vladimiry** [comment]
> Alternatively, I will upload the package when the CI service gets it prepared.

@TheDcoder, [here](https://mega.nz/#F!xlB20YKB!ve0BUiryuwCdamc06Cqfmg) it's. And the [build log](https://travis-ci.org/vladimiry/ElectronMail/jobs/644101138).

**Comment by TheDcoder** [comment]
The build works great! Now I can properly logout too. Thanks for spending the time to bring back this useful feature, I hope it will be included in the next release.

**Comment by vladimiry** [comment]
> I hope it will be included in the next release.

I just merged the change to master branch, so yes it's going to be included in the next release. Thanks for reporting the issue.

**Comment by vladimiry** [comment]
I'm reopening the issue since I've realized there is a need to apply a few more changes. @TheDcoder will ask you to try a new build soon.

**Comment by vladimiry** [comment]
@TheDcoder, the new build uploaded [here](https://mega.nz/#F!9p5ESYpC!IWpdpLnx-5hnldEAXn9iRw) (new changes: 5a5d20906e85b93618d3813715e533496c78a9ad + 53d4c78d6ab7c86a3b5b02ea52ba152f328045cc).

**Comment by TheDcoder** [comment]
@vladimiry The new build still works perfectly :smile:

**Comment by vladimiry** [comment]
Released in https://github.com/vladimiry/ElectronMail/releases/tag/v4.2.2.
