### ISSUE TITLE
cmd-x doesn't work on macOS

### ISSUE THREAD

**Issue by vladimiry** [vladimiry/ElectronMail#251]
The issue picked from #248. It's the bug in @electron, so `upstream` label assigned.

**Comment by ylluminate** [comment]
Any news on this?

**Comment by vladimiry** [comment]
Not from me since I don't use macOS. In general, I expect the issue to be fixed upstream.

**Comment by ylluminate** [comment]
Where is this noted in the upstream issue tracker?

**Comment by vladimiry** [comment]
I might be subscribed to presumably related upstream/@electron issues but I don't have a list of those issues. If I somehow get a macOS device or decent VM I cold play around the problem but it's unlikely to happen in the near future. I've tried some VMs before and that was a nightmare user experience.

**Comment by ylluminate** [comment]
Hmm, I'd be happy to track it down... but after some digging about in the Electron issues I'm not seeing anything that you're referring to in terms of it being related. I do use other Electron-based apps that are doing okay with cmd-x, so I'm very curious about this issue. I have seen cmd-z have trouble in another app (Ferdi), but it's only in one webapp so it doesn't appear to be an Electron issue.

**Comment by vladimiry** [comment]
> I do use other Electron-based apps that are doing okay with cmd-x, so I'm very curious about this issue. I have seen cmd-z have trouble in another app (Ferdi), but it's only in one webapp so it doesn't appear to be an Electron issue.

There are some specifics. If those working apps don't use `webview` thing then it most likely will be working out form the box. But in the case of `webview` use the keyboard events need to be explicitly processed since @electron quite a long time ago broke these events to be automatically translated and it's still unresolved. There are workarounds, like replacing webview with iframe and translating the event to the upper window or explicitly passing the events to the main process and then calling event on `webContents` instance. I use the second workaround which I originally found (applied for cut/copy actions) but when last time we were trying cmd-x with this workaround the app was just severely crashing. Maybe we should try it again with your help, I could prepare a build one day.

**Comment by vladimiry** [comment]
Moved to #499.
