### ISSUE TITLE
Linux 5.5.x: IPC/file-system operations seems to get sporadically freezed

### ISSUE THREAD

**Issue by vladimiry** [vladimiry/ElectronMail#253]
The work-in-progress v4.2.3 build verified in #250+#252 as working without the issues on Arch-based systems is uploaded [here](https://mega.nz/#F!h0IzhKRT!alKQxnPFdw_krZcin4pFmg) (based on Electron version 8).

---

I just tried to toggle the `Start minimized to tray` option on the "General" app settings block and got the `Invocation timeout of calling "patchBaseConfig" method on "electron-mail:ipcMain-api" channel with 25000ms timeout` error message which I expected to see since I visually saw that the form remains blocked which means the flag toggling process is still in progress.

The issue occurred after the computer got out from the suspend mode.

Toggling the `Start minimized to tray` flag simply sends the signal to the main process, then the main process updates the `config.json` and sends the updated version back.

So far the issue has been noticed only on Arch Linux based systems (see also #250 and #252). The app instability issues started to happen a few days ago (on Feb 8-12), so seems to be caused by recent system update since the app is a static thing (was not updated).

Toggling the `Start minimized to tray` flag is just one case I noticed but it looks like the inter-process communication is affected as a whole thing (see #250 and #252). The wild guess is that the file system access involvement is a required but not limited condition for an issue occurring (access to FS gets freezed and so IPC request doesn't respond within the timeout).

CC @lachlantula, @gourdcaptain, @srappan. Not sure if this issue is similar to issue you reported just recently, since I use @electron v8 based build but you were using released build which is @electron v7 based.

**Comment by vladimiry** [comment]
I also noticed that after the recent system updates if the `nm-applet` gets segfaulted with error message:
```
systemd-coredump[26719]: Process 22518 (nm-applet) of user 1000 dumped core.
                                                 #14 0x0000563bf888d1d6 n/a (nm-applet)
                                                 #16 0x0000563bf888d2fe n/a (nm-applet)
kernel: nm-applet[22518]: segfault at 20 ip 00007fcc90d51ca0 sp 00007ffca0d56530 error 6 in libglib-2.0.so.0.6200.4[7fcc90cdd000+81000]
```

The `5.5.2-1` kernel was used. Maybe it's worth to revert to the LTS/5.4 kernel.

**Comment by vladimiry** [comment]
In all the 4 reported cases of weird app behavior on Arch-based systems the 5.5.x Linux kernel was used (5.5.2 and 5.5.3).

**Comment by vladimiry** [comment]
I was able to find in the syslog mentioning libraries like `libpthread.so.0` and `libc.so.6` related to the `node/elecron/nm-applet` processes segfaults stacktraces. So I guess the following issues might be similar to what some Linux/Arch users face using ElectronMail with kernel 5.5 (especially the app based on @electron v7, like v4.2.2 release):
- https://github.com/dart-lang/sdk/issues/40589 ([log](https://github.com/dart-lang/sdk/issues/40589#issuecomment-585419730), [analysis](https://github.com/dart-lang/sdk/issues/40589#issuecomment-585979005))
- https://github.com/flutter/flutter/issues/49185
- https://github.com/flutter/flutter/issues/22229

**Comment by vladimiry** [comment]
I would be interested to see if someone who recently reported EM v4.2.2 use issues/freezes/timeouts on Arch + 5.5.x kernel could run `journalctl -p 3 -r --since "2020-02-12 00:00:00" --until "2020-02-12 23:59:59"`-like command and located there some `electron / electron-mail / node`-like processes segfaults (set the date range you faced the issue within).

**Comment by lachlantula** [comment]
I found the following:

> Feb 13 22:43:37 okcomputer systemd-coredump[82098]: Process 82000 (electron-mail) of user 1000 dumped core.

There were several instances of crashes like that.

**Comment by vladimiry** [comment]
Might be related kernel issue https://bugzilla.kernel.org/show_bug.cgi?id=205933 (picked from flutter issues tracker).

**Comment by vladimiry** [comment]
Also possibly related task https://github.com/electron/electron/issues/22291. The lib https://www.archlinux.org/packages/core/x86_64/glibc/ landed to repo on Feb 11 which is within above-mentioned time slot:

> The app instability issues started to happen a few days ago (on Feb 8-12), so seems to be caused by recent system update since the app is a static thing (was not updated).

**Comment by vladimiry** [comment]
Electron v8 based release https://github.com/vladimiry/ElectronMail/releases/tag/v4.3.0 got published. So closing the issue for now as there has been no freezing issues reported if Electron v8 based build was used.

**Comment by vladimiry** [comment]
Referencing relevant messages:
- https://github.com/laurent22/joplin/issues/2518#issuecomment-594499627
- https://github.com/electron/electron/issues/21415#issuecomment-594537478

Thanks @bedwardly-down for such a thorough investigation.

**Comment by bedwardly-down** [comment]
You're quite welcome. The little info you gave me went a long way and to be fair, that investigation was a bit frustrating but fun and i think I'd like to contribute more in that regard. I also use Protonmail as my main email service, so I'll try your client out and see what i can do here. ☺️

**Comment by vladimiry** [comment]
Looks like 5.7 kernel doesn't experience the issue. So using either 5.4 LTS or 5.7 is a solution.

**Comment by bedwardly-down** [comment]
5.6.13 up seems to have fixed the issue for Joplin (the other Electron app that had this issue). There were two epoll related commits submitted by the maintainers that created the original problem commit. Hopefully, no one will mess with this further in the kernel.
