### ISSUE TITLE
No tray icon on Linux since v4.2.3 (Electron v8 based build)

### ISSUE THREAD

**Issue by vladimiry** [vladimiry/ElectronMail#254]
To make the story short, if the tray icon is visible and functional then if needed just re-enable the `Start minimized to tray` and/or `Close to tray` toggles on the `General` app settings block:

  ![toggles](https://user-images.githubusercontent.com/1560781/74937622-756b0280-53fd-11ea-8007-babde13c665d.png)

If you don't see the tray icon or its menu acting flaky then keep reading the issue.

---

The v4.2.3+ app release will is based on Electron version 8. Electron since v8 switched to use SatusNotifier tray icons which some Linux systems don't have good support for. This is why new app release resets the `Start minimized to tray` and `Close to try` flags for Linux users. In along with the flags reset Linux users get the respective notification with a link to this issue:

![reset](https://user-images.githubusercontent.com/1560781/74605961-90780280-50dd-11ea-8998-df31ce4844c4.png)

Besides, since v4.2.3 new app Linux users get the `Start minimized to tray` and/or `Close to try` flags set to `false` by default.

Related upstream @electron issues:
- https://github.com/electron/electron/issues/21445
- https://github.com/electron/electron/issues/21576

SatusNotifier tray icons support status:
- `KDE`: supported out-from-the-box.
- `Xfce`: supported (`xfce4-statusnotifier-plugin` needs to be installed and then respective widget added to the panel). There is also https://gitlab.com/vala-panel-project/xfce4-sntray-plugin working plugin, alternative to `xfce4-statusnotifier-plugin`.
- `Gnome Shell`: supported with the help of preinstalled [gnome-shell-extension-appindicator](https://github.com/ubuntu/gnome-shell-extension-appindicator) extension but the tray/menu clicks might act flaky ([respective issue](https://github.com/electron/electron/issues/21576) placed).
- `Cinnamon / Mint`: `"System Settings" -> "General" -> "Enable support for indicators"` flag needs to be enabled. Some issues still possible, see https://github.com/linuxmint/cinnamon/issues/9176.
- `polybar`: not supported ([respective issue](https://github.com/polybar/polybar/issues/2010) placed).

**Comment by vladimiry** [comment]
@joshirio can you list `xfce4-statusnotifier-plugin` package as optional in AUR repo for v4.3.0+ releases?

**Comment by joshirio** [comment]
sure, I will!
The update will be made as soon as possible.

**Comment by vladimiry** [comment]
Closing the issue but keep it pinned for a while.

**Comment by TheDcoder** [comment]
Thanks for posting the status of the tray icon update in a dedicated issue with all the resource, working fine with `xfce4-statusnotifier-plugin` on XFCE panel!

**Comment by somospocos** [comment]
I am using dwm with patched systray support and I tried to enable the start minimized to tray setting to see if it works with 4.2.3. It didn't. Now I'm locked out of app because its window never appears and the config file seems to be a binary with encrypted content. How do I undo toggling that setting?

**Comment by vladimiry** [comment]
@somospocos, `Start minimized to tray` and `Close to tray` toggles were intentionally disabled for Linux users in v4.3.0+ so they could verify that the tray icon is visible and functional and only then enabled the toggles back.

To reset the flags again you could set the `startHidden` and `hideOnClose` flags to false in `/home/<user>/.config/electron-mail/config.json` file.

Besides if the app is already running and you run it again then the app window will be activated. So there is a way to show the hidden window without the tray icon involved which allows you to disable those toggles via the UI if you don't want to deal with manual `config.json` file editing.

**Comment by somospocos** [comment]
@vladimiry thank you, I have no idea how I overlooked that file. I was looking at settings.bin and saw it has encrypted content.

Since ElectronMail without a systray icon is pretty much unusable to me, does it mean I need to choose between using the last old version (4.2.2 I think) which has systray support or give up on using ElectronMail?

By any means, I'm not blaming you for an upstream problem. It's just that broken backwards compatibility systray support in Electron totally ruined my user experience. The reality ended being even worse than those countless Electron memes floating around online.

**Comment by vladimiry** [comment]
There was a choice to sticking to Electron v7 or upgrading to v8. For a lot of reasons, the choice was made toward upgrading the Electron version. From my side, I believe I did at least something by resetting the toggles and showing notification with a link to this issue. Many much more popular/starred Electron-based apps silently updated to Electron v8 leaving Linux users in the dark why tray icons support got broken.

> Since ElectronMail without a systray icon is pretty much unusable to me, does it mean I need to choose between using the last old version (4.2.2 I think) which has systray support or give up on using ElectronMail?

No idea, the choice is yours. Addition option is to enhance the `dwm with patched systray support` toward supporting Status Notifier tray icons standard or using another Linux/DE.

> By any means, I'm not blaming you for an upstream problem. It's just that broken backwards compatibility systray support in Electron totally ruined my user experience. The reality ended being even worse than those countless Electron memes floating around online.

The issue actually comes from @chromium which is used by @electron.

**Comment by vladimiry** [comment]
Cinnamon has just resolved https://github.com/linuxmint/cinnamon/issues/9176.

**Comment by vladimiry** [comment]
Some Linux users who still experience the tray icon issue with Electron-based apps might want to try https://git.sr.ht/~steef/snixembed thing.

**Comment by vladimiry** [comment]
It turned out Electron is getting rid of DBus related tray icon implementation rolled out with @chromium update in Electron v8 if favor of previously used / `GTK/appindicator` approach, see https://github.com/electron/electron/pull/23674. So will I then happily remove the behavior described in the first message and the related code too.

**Comment by vladimiry** [comment]
`GTK/appindicator`-based tray icon is now back on Linux. Next release coming soon.

**Comment by vladimiry** [comment]
@joshirio `xfce4-statusnotifier-plugin` is merged into the default xfce panel tray plugin (for a while), so can be removed from the optional deps of https://aur.archlinux.org/packages/electronmail-bin.

Since the next/5.1.3 app version, the tray icon on Linux requires support for [StatusNotifierItem](https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/)
  by user's desktop environment (https://github.com/vladimiry/ElectronMail/issues/514#issuecomment-1332700126).
