### ISSUE TITLE
Option to import emails as EML/MBOX

### ISSUE THREAD

**Issue by ManuelFte** [vladimiry/ElectronMail#256]
Although ProtonMail already has an import/export tool, it's still buggy and tends to crash, and it only has Windows and Mac versions, with no news about a Linux version as of yet. Tutanota announced plans to add an import feature to its desktop apps since 2018, but this still hasn't happened.

Since ElectronMail already has the ability to export emails to EML, I hope the inverse option isn't too difficult to implement.

**Comment by vladimiry** [comment]
Thanks for placing the issue but it's out of the ElectronMail scope, See some explanations below.

- Import feature requires some work to be done at the backbend side which is controlled by ProtonMail.
- There is no goal to re-implement already existing solutions. Existing import/export tool might be buggy but it's up to them to fix it.
- My time/capacity is limited.

> ElectronMail already has the ability to export emails to EML

By the way, the export capability is not complete. Attachments are not being handled.
