### ISSUE TITLE
Building the app from source

### ISSUE THREAD

**Issue by vladimiry** [vladimiry/ElectronMail#259]
Building the app from source is current blocked by upstream issue, see https://github.com/ProtonMail/proton-calendar/issues/2.

I can still build the app since I have `proton-calendar` in my cache same as appveyor/travis systems since it has been built there before.

CC @ShuminKong

**Comment by ShuminKong** [comment]
Thank you so much for letting me know XD. I was trying to fix it myself and gave up.

**Comment by vladimiry** [comment]
If you really want to build the app from sources right now, there is a way.

- Pick some package from https://github.com/vladimiry/ElectronMail/releases
- Install it of just unpack (if you know how).
- Then run `npx asar e /opt/ElectronMail/resources/app.asar /home/user/ElectronMail-app-unpacked`. This command unpacks `app.asar` archive to local directory. In your case path to `app.asar` can be different.
- Then copy `/home/user/ElectronMail-app-unpacked/app/webclient/<domain>/calendar/` to respective location in sources folders, ie `./app/webclient/<domain>/calendar/`. This action puts `proton-calendar` to your cache so it won't be build and therefore there will be no `[proton-pack] Module not found` error.
- Sync with master. I recently pushed 5494933871bac7b7aea48fd999447007c100cdb0.

But better wait for https://github.com/ProtonMail/proton-calendar/issues/2 resoling.

**Comment by ShuminKong** [comment]
I see that the issue is closed. How about now?

**Comment by vladimiry** [comment]
I will put update here after verifying building from sources is working.

**Comment by vladimiry** [comment]
I reset the cache on CI systems and triggered the new build, so we will see soon if the issue got resolved.

**Comment by vladimiry** [comment]
The project is buildable now. The build process got slowed down since `package-lock.json` file of `proton-mail-settings` is invalid and so I had to temporarily switch to running `npm install` vs `npm ci`. In general, the macos-high-sierra jobs are very flaky on travis-ci, so if you run travis-ci there might be a need to restart those jobs several times. Complete move out from travis-ci is in my todo list but only as a backlog task so far.
