### ISSUE TITLE
Why was the v3 UI support dropped and we have to use a beta product?

### ISSUE THREAD

**Issue by itisafrickinhighlander** [vladimiry/ElectronMail#262]

**Comment by vladimiry** [comment]
> we have to use a beta product?

You don't have to.

See the answer in https://github.com/vladimiry/ElectronMail/issues/244#issuecomment-580210419:

> The plan is to keep both v3 and v4 webclients available here in the app until v3 gets deprecated by the service provider.

> But I reconsidered since my capacity is limited. So the app is not going to support proton-v3-web-ui anymore.
