### ISSUE TITLE
ElectronMail icon stretched vertically in notifications on macOS Catalina

### ISSUE THREAD

**Issue by BBaoVanC** [vladimiry/ElectronMail#263]
I just upgraded from ElectronMail v4.2.2 to v4.4.0. The unread messages notifications has a second icon that's stretched and to the right in the notification center. The popup notification just has a very blurry icon. 

![Notification Center](https://i.imgur.com/CqZPYVX.png)
![Popup](https://i.imgur.com/hIQpi4o.png)

**Comment by vladimiry** [comment]
Icon being rendered by @chromium => @electron projects, so upstream issue.

**Comment by vladimiry** [comment]
I'm closing the issue since:
- Nothing is supposed to be changed in the app code.
- Even if I change something I won't be able to try the change in action since I don't use macOS.

So if the fixe comes here then only with @electron version upgrade, same way like it got broken.
