### ISSUE TITLE
electron-mail v4.4.1 unavailable on snap

### ISSUE THREAD

**Issue by KaKi87** [vladimiry/ElectronMail#265]
```
$ snap find electron-mail
Name           Version  Publisher  Notes  Summary
electron-mail  4.4.0    joshirio   -      Unofficial ProtonMail Desktop App
```
```
$ snap refresh electron-mail
snap "electron-mail" has no updates available
```

**Comment by vladimiry** [comment]
Snap repository is maintained by @joshirio, same as AUR repo, see the [readme](https://github.com/vladimiry/ElectronMail/blob/master/README.md) file. There is no issue here, just give the maintainers some time.

**Comment by joshirio** [comment]
Yeah, sorry guys but please understand sometimes it can take up to 24h for me to publish an update. On it right now... ;)
