### ISSUE TITLE
Links are sometimes long enough that they cover the button when hovering

### ISSUE THREAD

**Issue by BBaoVanC** [vladimiry/ElectronMail#269]
Some marketing emails will have very long URLs for links in them. The tooltip for those links can cover the "Continue" button of the ProtonMail link confirmation. This makes it impossible to go to those links (unless you right click and press "Copy link address").

Ideas:

- Option to change the size of the URL tooltip
- Automatically scale tooltip based on length of URL (or abbreviate)
- Option to disable tooltip

**Comment by vladimiry** [comment]
@BBaoVanC can you try [this](https://mega.nz/#F!cgoj2a7K!QIPZCAHoIo_zBVVrqDnVLQ) build?

**Comment by BBaoVanC** [comment]
Works on both macOS Catalina 10.15.3 and Windows 10 x64 1909 build 18363.657.
![macOS](https://i.imgur.com/ICcWmG4.png)

**Comment by vladimiry** [comment]
Thanks for confirming issue resolving, fixes come to the next release then.

**Comment by vladimiry** [comment]
[v4.4.2](https://github.com/vladimiry/ElectronMail/releases/tag/v4.4.2) release with the fix included has been published. Thanks for reporting the issue.
