### ISSUE TITLE
Exporting Emails With Long Name Halts Export

### ISSUE THREAD

**Issue by sol8712** [vladimiry/ElectronMail#272]
When I export emails in mass and there is a single email that has a long name it gives an error and halts the entire export.

`ENAMETOOLONG: name too long, stat '/home/user/Proton Mail/this-is-a-long-name-this-is-a-long-name-this-is-a-long-name-this-is-a-long-name-this-is-a-long-name-this-is-a-long-name-this-is-a-long-name-this-is-a-long-name-this-is-a-long-name-this-is-a-long-name-this-is-a-long-name-this-is-a-long-name-this-is-a-long-name-this-is-a-long-name-this-is-a-long-name-.eml'`

I dont know if its possible but i imagine it should show an error and continue to upload the rest if the file name is at some sort of hard limit.

**Comment by vladimiry** [comment]
Good finding. The app cuts the file name at 256 chars, but should cut at 255.

https://github.com/vladimiry/ElectronMail/blob/9fe24e2d25cf6cdd16a18024ffdc872196d272b3/src/electron-main/api/endpoints-builders/database/export.ts#L26

**Comment by vladimiry** [comment]
Fix implemented and will be include in the next release which is planned for the next day.

**Comment by vladimiry** [comment]
If you want to try fixed version before it's released, [here](https://mega.nz/#F!4tgX0QqZ!Df4RvLntf-hTRi5abGAV8Q) is the download link.

**Comment by vladimiry** [comment]
[v4.4.2](https://github.com/vladimiry/ElectronMail/releases/tag/v4.4.2) release with the fix included has been published. Thanks for reporting the issue.

**Comment by sol8712** [comment]
No thank you for the great mail app and the insanely fast fix! Im almost to my space limit on protonmail. Very smooth experience in the app.

**Comment by vladimiry** [comment]
Keep in mind that the app doesn't handle/import/index/export the attachments data.
