### ISSUE TITLE
Rotating User Agent

### ISSUE THREAD

**Issue by arch-btw** [vladimiry/ElectronMail#273]
I would like to propose a rotating user agent in ElectronMail to (partially) mitigate potential accounts association in worst case scenarios.

**Comment by vladimiry** [comment]
Referencing [related](https://github.com/vladimiry/ElectronMail/issues/88) issue. So currently the app strips out the electron/app specifics from the user agent to make it look like a regular Chrome browser.

**Comment by arch-btw** [comment]
Thank you @vladimiry 

How about something like this?

![Screenshot_20200329_071435 (1)](https://user-images.githubusercontent.com/57669023/77851499-5dba3300-718e-11ea-9953-a4a91ae709ed.png)

We could have them rotate through a list of random user agents on every logon.

A list of user agents can be found here: https://developers.whatismybrowser.com/useragents/explore/

**Comment by vladimiry** [comment]
Here is how to enable to option for the specific email account:
![rotate-user-agent-option](https://user-images.githubusercontent.com/1560781/79041244-e907df80-7bf6-11ea-9849-3881f3a285ea.png)

Here is the default user agents list:
https://github.com/vladimiry/ElectronMail/blob/34f3ee9919cd4438352ba40be3053463a51b7553/src/shared/util.ts#L63-L74

The list is saved in the `config.json` file which is located in the [setting folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg), so the list can be manually modified if needed.

**Comment by vladimiry** [comment]
The work-in-progress build with enabled feature is uploaded [here](https://mega.nz/folder/ExoGWQTZ#NWEPZrrrCfDW_P1wwGXjiQ).

**Comment by arch-btw** [comment]
@vladimiry you are so great !!!!!!! Thank you!

**Comment by User486375** [comment]
@arch-btw How exactly do you see this feature benefiting the avoidance of account association in its default state? As opposed to just blending in with the latest Chrome version for example.

**Comment by vladimiry** [comment]
Since v4.15.0 the user agent rotation feature gets replaced with an optional per account "user agent" string value.
