### ISSUE TITLE
ElectronMail can't handle NVIDIA Image Sharpening

### ISSUE THREAD

**Issue by Snaacky** [vladimiry/ElectronMail#274]
When using NVIDIA's Image Sharpening feature on an NVIDIA GPU, ElectronMail will slowly deep fry itself over time the longer it is idled or more immediately when switching through email tabs.

Image sharpening is available under:
NVIDIA Control Panel > Manage 3D Settings > Image Sharpness

My settings are:
Sharpen: 0.76
Ignore film grain: 0.67
GPU scaling: off

Showing some signs of excessive sharpness:
https://i.imgur.com/cxbOJ5E.png

Overtime it deep fries itself:
https://i.imgur.com/B6QI5sB.png 

I haven't experienced this on any other applications, including other Electron apps.

**Comment by vladimiry** [comment]
I remember I saw a screenshot with similar artifacts in Electron's issues tracker but could not find the issue yet, there might be a workaround or solution. It's clearly an upstream/Electron/Chromium issue. I don't have an NVIDIA card nor desktop computer at all so I won't be able to reproduce the issue and test the workarounds.

**Comment by vladimiry** [comment]
@Snaacky can you try https://github.com/vladimiry/ElectronMail/releases/tag/v4.4.0? This version is based on Electron version 8 and I guess the rendering might act differently than actual v4.4.2 release which is based on Electron 9.

**Comment by vladimiry** [comment]
Another thing to try is starting the app with `--disable-gpu` command line argument.

**Comment by Snaacky** [comment]
The issue is fixed on `v4.4.2` in conjunction with the argument but persists on `v4.4.0` with the argument.

Thank you!

**Comment by vladimiry** [comment]
Thanks for confirming that `--disable-gpu command line argument` workaround is helpful. Apparently recent Chromium version embedded in Electron v9 has changed/improved something related to the pages rendering.
