### ISSUE TITLE
Issue with Plank icon

### ISSUE THREAD

**Issue by Dev727** [vladimiry/ElectronMail#275]
I noticed an issue with the Plank icon when running this application (using the current AUR version).
There was a duplicate, blurry icon (a rather common issue that Plank occasionally has).

Changing the .desktop file entry to
`StartupWMClass=electron-mail`
solved the issue for me.

Not sure if I should post this here or the AUR forum, but I figured it might be helpful to know.

**Comment by vladimiry** [comment]
I think `electron-builder` supports configuring `StartupWMClass` desktop file property. So I'm going to try setting `StartupWMClass=electron-mail` for `pacman` package in the app code.

**Comment by vladimiry** [comment]
I think we better apply the change for all Linux package, no only the `pacman` one.

**Comment by vladimiry** [comment]
The change has been pushed to the mater branch, so it's planned for next release. The work-in-progress build is uploaded [here](https://mega.nz/folder/8lBhjKbB#E-TUIPUbAyd03tX6iQI0qw) if you want to try it right now.

**Comment by Dev727** [comment]
Just tested the new .deb binary on Ubuntu 18.04. It works just fine now, @vladimiry.

**Comment by vladimiry** [comment]
Ok, thanks for reporting the issue, listing the solution and verifying the fix.
