### ISSUE TITLE
Electronmail wont open on Windows

### ISSUE THREAD

**Issue by Mech0z** [vladimiry/ElectronMail#277]
After a crash the app wont open, when I open it I see it in the taskbar (Windows 10) and then it disappears again within a few seconds

There is nothing added to logfiles

If I look in Windows Event viewer I see 2 events

"Error":
Faulting application name: ElectronMail.exe, version: 4.4.2.375, time stamp: 0x5e37f738
Faulting module name: ntdll.dll, version: 10.0.17763.1131, time stamp: 0x4dc06dfc
Exception code: 0xc0000005
Fault offset: 0x0000000000066a1e
Faulting process id: 0x9bc
Faulting application start time: 0x01d60e71ac46849c
Faulting application path: C:\Users\user\AppData\Local\Programs\ElectronMail\ElectronMail.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 94da2653-7c00-4102-bcfd-1a0e00c13ce3
Faulting package full name: 
Faulting package-relative application ID: 

And "Information"
Fault bucket 2167022470594115463, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: ElectronMail.exe
P2: 4.4.2.375
P3: 5e37f738
P4: ntdll.dll
P5: 10.0.17763.1131
P6: 4dc06dfc
P7: c0000005
P8: 0000000000066a1e
P9: 
P10:

**Comment by vladimiry** [comment]
- Anything useful in the app log file (normally located in `C:\Users\user\AppData\Roaming\electron-mail/log.log`) (post here or send to email specified in [package.json](https://github.com/vladimiry/ElectronMail/blob/master/package.json))?
- Previous releases also crashing?

**Comment by Mech0z** [comment]
the --js-flags="--max-old-space-size=5120 worked it printed 
C:\Users\user\AppData\Local\Programs\ElectronMail>
(node:3500) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:3500) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:3500) DeprecationWarning: file property is deprecated and will be removed in v5.
(node:3500) DeprecationWarning: file property is deprecated and will be removed in v5.
(node:3500) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:3500) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:3500) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:3500) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:3500) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:3500) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:3500) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:3500) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:3500) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:3500) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:3500) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:3500) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:3500) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:3500) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.

**Comment by vladimiry** [comment]
If adding `--js-flags="--max-old-space-size=5120` CLI arg solved the issue then the app was crashing because the default memory limit was too low (5120 value here is memory limit in MB we set explicitly). This could happen if you have enabled the "local store" option for at least one mail account and you got a lot of email message there, like 10k+ messages.

There was a similar issue placed before #110 and listed there improvement of adjusting the default memory limit of the main node process has not been implemented yet:
> I will think how to make the max mem of the main process configurable without a need to pass the argument but taking the config params from config.json (it's currently only possible for the renderer process). Maybe using something like simple preloader or hardcoding the argument to the shortcut.

**Comment by vladimiry** [comment]
Closing as resolved with a workaround. The quoted in previous message point is in my TODO list but not planned for implementing in the near future.
