### ISSUE TITLE
Tray icon disappears after session lock

### ISSUE THREAD

**Issue by Dvlnst** [vladimiry/ElectronMail#279]
Hi, 

I'm having an issue with tray icon lately. After I lock my user session or it's locked due to inactivity, tray icon disappears. App keeps working fine in background.

OS: Debian 10 (buster).
GNOME Shell 3.30.2.

I hope it helps.

Kind regards.

**Comment by Dvlnst** [comment]
Sorry, I didn't notice it's an electron issue and you are already aware of it.

**Comment by vladimiry** [comment]
It's a known upstream issue, see #254 and https://github.com/electron/electron/issues/22443.

> The tray icon sporadically disappears, usually on unlocking the system from sleep/standby mode (respective issue placed).

> Sorry, I didn't notice it's an electron issue and you are already aware of it.

:+1:

**Comment by vladimiry** [comment]
There seem to be [a workaround](https://github.com/zulip/zulip-desktop/issues/910#issuecomment-608056150) but I'm not going to enable it in the app as it looks too raw/system-specific/hacky.
