### ISSUE TITLE
Glibc version dependency not recognized?

### ISSUE THREAD

**Issue by Kyther** [vladimiry/ElectronMail#281]
I run Linux Mint 18.1, which is a LTS release based on Ubuntu 16.04.  I was able to download and install the deb successfully - it reported all dependencies satisfied - only to have it give me this error dialog as soon as I tried to run it:

```
A JavaScript error occurred in the main process

Uncaught Exception: Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /opt/ElectronMail/resources/app.asar.unpacked/node_modules/sodium-native/build/Release/libsodium.so.23)
 at process.func (electron/js2c/asar.js:140:31)
 at process.func [as dlopen] (electron/js2c/asar.js:140:31)
 at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
 at Object.func (electron/js2c/asar.js:140:31)
 at Object.func [as .node] (electron/js2c/asar.js:149:18)
 at Module.load (internal/modules/cjs/loader.js:815:32)
 at Module._load (internal/modules/cjs/loader.js:727:14)
 at Module._load (electron/js2c/asar.js:738:28)
 at Function.Module._load (electron/js2c/asar.js:738:28)
 at Module.require (internal/modules/cjs/loader.js:852:19)
```

I double-checked, and the latest version of glibc available for my OS is 2.23 (fortunately, I was able to get it running fine using the snap - and I love it!).  It looks like it didn't recognize before installing that it needed glibc with a greater version, and I'm thinking it should have blocked the installation due to the mismatch between glibc versions.

**Comment by vladimiry** [comment]
Currently, all the Linux packages attached to the releases get assembled with help of Travis CI on Ubuntu 18.04.4 LTS (Bionic Beaver) and so it's the system the e2e tests get performed (e2e tests were disabled for the last few months, but I recently git it back by e205fe1667e08fea33b1594674cae03b48c9a750). During the assembling process, all the native dependencies get compiled from sources (prebuilds shipped with npm packages don't get used).

I don't have the capacity to enable running e2e tests on different systems nor adding any type of system verification to specific package types. So this will be won't fix for now. If after a while running a Snap package won't be an option for you anymore, you will have to compile your own package from sources on the system you want to run the app (so `sodium-native` and other native dependence will be compiled too on your system).

Maybe one day flatpack package format will get supported here, so it will come with all the libs prepackaged, including the glibc one.
