### ISSUE TITLE
Building Electron windows/mac & linux app folder results in error

### ISSUE THREAD

**Issue by dhammel** [vladimiry/ElectronMail#284]
I am new to node & yarn, therefore I am not sure exactly whats causing this but hours of research online just to determine the cause yield no useful results.

I have nodejs set (using nvm) as v12.16.2, yarn installed as well as all basic utilities like make & gcc.

The first 2 build commands in the README, were sucessful. The commands to build package for windows/mac (yarn run electron-builder:dist) & linux app folder (yarn run electron-builder:dir) fails with an error: 

[hook: afterPack] Processing ["snap","appImage"] targets
  ⨯ [hook: afterPack] Only one target is allowed at a time for Linux platform  stackTrace=
                                                                                 Error: [hook: afterPack] Only one target is allowed at a time for Linux platform
error command failed with exit code 1

Building a pacman package, results in error:

building        target=pacman arch=x64 file=dist/electron-mail-4.5.0-linux-x64.pacman
  ⨯ cannot execute  cause=exit status 1
                    out={:timestamp=>"2020-04-24T06:21:30.070940-0400", :message=>"Process failed: /bin/bash failed (exit code 127). Full command was:[\"/bin/bash\", \"-c\", \"LANG=C bsdtar -czf .MTREE --format=mtree --options='!all,use-set,type,uid,gid,mode,time,size,md5,sha256,link' .PKGINFO .INSTALL opt usr\"]", :level=>:error}

npx exited with non-zero code: 1

Everything else (appimage, deb, freebsd, rpm & snap) were all successfully built. I can't seem to resolve those errors above, regardless of what I may try & don't exactly understand the error output.

**Comment by vladimiry** [comment]
> The commands to build package for windows/mac (yarn run electron-builder:dist) & linux app folder (yarn run electron-builder:dir) fails

Windows package need to be build on Windows and macOS packages on macOS. The project prepares the installation packages for rereleasing using Travis CI + Appveyor CI.

It's technically possible to build the Windows on Linux using docker+wine, but I prefer not to do that.

**Comment by dhammel** [comment]
Thank you, i didn't realize that. If I have a need to build the Windows/Mac packages I suppose I could use a VM for that. The error for the building of the windows package that I get, is the same as what I get when trying to build a folder to execute the app from (for linux), using 'yarn run electron-builder:dir'

Since pacman though is linux, should that be able to be built on my Kubuntu os? I don't know if it just needs extra dependencies not listed in the readme (similar to rpm & snapcraft for those corresponding packages)?

**Comment by vladimiry** [comment]
Yes extra package type related deps might might needed on Linux (like snapcraft you mentioned) or you could use docker image with preinstalled deps (for example the images provided by electron-builder project, see https://www.electron.build/multi-platform-build#docker).

**Comment by dhammel** [comment]
Well I managed to get the pacman package built, easier than I had figured. I tried the command: sudo apt-get install --no-install-recommends -y bsdtar according to docker guide you linked to, apt informed me that it was not available, has been replaced by libarchive-tools. Once libarchive-tools was installed, the build command completed without errors. The linux app folder build command is still failing though. I will hop on a Windows vm to try building it the Windows package.

Thank you :)

**Comment by vladimiry** [comment]
You get there `Only one target is allowed at a time for Linux platform` error which is expected, see [here](https://github.com/vladimiry/ElectronMail/blob/baecd85b1c43c75e5c4628c8dc5b9d347e99a2ef/scripts/electron-builder/hooks/afterPack/index.ts) if interested. I don't normally prepare the folder executing `yarn run electron-builder:dir` but a package and so I missed supporting `yarn run electron-builder:dir` doing some scripts adjustments over a time.

I just have removed the `yarn run electron-builder:dir` command from the readme. It's still possible to prepare the folder if needed, but no support provided.

**Comment by vladimiry** [comment]
> I will hop on a Windows vm to try building the Windows package.

On Windows you will have to adjust the system in order to be able to build the proton projects located in https://github.com/ProtonMail. Like at least adding there bash support. They unfortunately heavily rely on bash scripting. You can see details in the readme of their projects if needed.

**Comment by dhammel** [comment]
I tried the Windows method, after successfully installing things like git for windows, node & yarn, installing and configuring WSL Ubuntu according to Protonmails guide linked in the readme the first error I received during the yarn --pure-lockfile command was network error, timeout. Adding --network-timeout 500000, I was able to resolve this error. When running yarn run app:dist, after 20 minutes received an error something like "Cannot fetch https;//www.yarnpkg.com/ Network timeout (over 30000ms) which the network timeout of 500000ms didn't resolve the error in this command. So, now its just stuck at a network error issue in the build. I did confirm it was not actually a network issue, got speeds in my vm of 250mbps download roughly, windows firewall or defender is confirmed to not be blocking it. No other software is interfering with it either.

As this all seems to be something that isn't actually an issue with ElectronMail, I can close this issue anytime, I can figure this error out over time, i usually do if I put in enough effort.

Thank you again for you help

**Comment by vladimiry** [comment]
By the way, you can reuse the proton-web-clients if you have built them before on Linux. Simply put `./app/webclient/` folder from Linux to the app dir on Windows system and the when you run `yarn app:dist` the proton-web-clients building step will be skipped. I do something like that on CI systems preparing the releases, means I have never built the proto-web-client on Windows system.

**Comment by dhammel** [comment]
Ok, I will do that during my next attempt of building on windows, any chance of saving time while trying to resolve the issue will help. I don't use Windows like at all anymore, I literally only have a windows vm, isolated with no network connection just for use of tax software so I don't need a build on Windows but did want to understand what was the cause of concern which I now know. So, i'll close the issue
