### ISSUE TITLE
Windows installer detected as malware

### ISSUE THREAD

**Issue by edwardjohnson11** [vladimiry/ElectronMail#288]
Avast and AVG seem to flag the compiled 4.4.2 windows installer as malware.

https://www.virustotal.com/gui/file/3056ae05921e125083ad0d6df7ef4b2bc748a3901c124323f680ae1c7b4a570b/detection

**Comment by vladimiry** [comment]
There is no malware code in the project, so nothing I could get fixed. If you believe the report is valid and the program actually includes the malware stuff then please don't use the program.

**Comment by vladimiry** [comment]
https://github.com/electron-userland/electron-builder/releases/tag/v22.8.1 release have some av-software related fixes included (see last point in the changelog). The next release will be built using v22.8.1+ `electron-userland` version.
