### ISSUE TITLE
failed to decrypt the settings storage

### ISSUE THREAD

**Issue by saintjay34** [vladimiry/ElectronMail#290]
Brand new MacBook 16... on April 24 my desktop app stopped working since then all I get is an error code.

failed to decrypt the settings storage

Today I loaded the mail app on my 1 year old machine works perfect.

I have tried to remove the app to start fresh and when I do it never fully removes the app because on reload its not taking me back in to set up original master password.

Help?
<img width="1115" alt="Screen Shot 2020-05-07 at 9 11 55 AM" src="https://user-images.githubusercontent.com/64967315/81299105-b6110a00-9043-11ea-945e-b54f78011ae1.png">

**Comment by vladimiry** [comment]
Normally this error message means that a wrong master password was entered, either manually or automatically if you enabled the respective checkbox before.

I'd ask you to provide the `log.log` file located in the [settings folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg) if you need more specific response. You can either attach the log file here or send it privately to the email specific in https://github.com/vladimiry/ElectronMail/blob/master/package.json (`author` field). Also would be intereted to know what app version was giving the error.

**Comment by saintjay34** [comment]
A tech friend of mine helped me to fully remove the cache files and i was able to reload it. Love love love this app. Thank you for your response so fast.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by vladimiry** [comment]
Closing as resolved then. I wish everyone to have a tech friend :)
