### ISSUE TITLE
Can not install it!

### ISSUE THREAD

**Issue by sapphirecap** [vladimiry/ElectronMail#292]
![electronmailissue](https://user-images.githubusercontent.com/60485595/81474336-c3a8ca00-91d2-11ea-931b-3c8ee4394c5a.png)

Hi, I get this issue after running the command:
yarn run app:dist

Don't know what to do.

**Comment by vladimiry** [comment]
It says `No package "xscrnsaver" found`. This package seems to be required for the `desktop-idle` native module compilation. So try installing `xscrnsaver` package.

**Comment by vladimiry** [comment]
I got it like you were building it from source code. If you did not but simply was running the app taken from the releases page then `xscrnsaver` required in runtime, not for compilation only. But there is no difference for you since `xscrnsaver` is required anyway.

**Comment by sapphirecap** [comment]
I did install xscrnsaver but it returns the same dialogue again so I installed it from snap but it has some bugs.

**Comment by vladimiry** [comment]
There is no enough information provided to guess a possible cause.

**Comment by sapphirecap** [comment]
I mean I was building it from source code but since I got  the xscrnsaver package request I quit from doing it. After I installed xscrnsaver, I tried to build it from source code again but got the same message from the screenshot above. That's why I installed it using snap but it doesn't run smoothly, I think I need more ram and also had some troubles when logging in. No worries bro, still looking forward to try it in the future.

**Comment by vladimiry** [comment]
You didn't specify the OS you run. Also you use nodejs v14, but readme advices to use nodejs v12.

Not sure if it helps, see [here](https://github.com/vladimiry/ElectronMail/blob/baecd85b1c43c75e5c4628c8dc5b9d347e99a2ef/.travis.yml#L60-L72) the addition packages get installed on Travis CI which runs Ubuntu Bionic image (`python3-secretstorage` package is not needed).

**Comment by vladimiry** [comment]
Closing since there i nothing I could do not having more info provided.
