### ISSUE TITLE
Electronmail not starting, javascript error, uncaught exception

### ISSUE THREAD

**Issue by thecursedfly** [vladimiry/ElectronMail#295]
A couple days ago I installed ElectronMail on a Windows 10 machine.
Installer used: electron-mail-4.5.0-windows-nsis-installer.exe

Upon launching it, I get the attached error: "The specified module could not be found". Pressing OK the application does not start, so I cannot use ElectronMail at all.

The file: C:\Users\username\AppData\Local\Programs\ElectronMail\resources\app.asar.unpacked\node_modules\sodium-native\build\Release\sodium.node
is present.

![Capture](https://user-images.githubusercontent.com/35839025/82992647-b7f53a00-9fff-11ea-826e-0d42b6ea640d.PNG)

**Comment by vladimiry** [comment]
See the last the point in [FAQ](https://github.com/vladimiry/ElectronMail/wiki/FAQ).

**Comment by thecursedfly** [comment]
Thanks, installing the "Visual C Redistributable for Visual Studio 2015" did it. Sorry for the duplicate.

**Comment by thecursedfly** [comment]
Perhaps a check could be made on whether this is installed and if not, prompt/suggest to install it?

**Comment by vladimiry** [comment]
Of course enabling such check would be a good thing. But due to the cross-platform nature it's not so trivial task. Maybe one day I will explore the capabilities of NSIS installer and electron-builder tools (this task is placed in the todo list).

**Comment by vladimiry** [comment]
Looks like electron-builder supports custom NSIS scripts. So I'm going to try embedding the `Visual C Redistributable for Visual Studio 2015` into the windows installer or making the installer to download it. Let's keep the issue open.

**Comment by vladimiry** [comment]
Since the next release windows installer will check if the 2015 redistributable installed and download+install it if needed.
