### ISSUE TITLE
Blank Screen in OSX

### ISSUE THREAD

**Issue by shirshak55** [vladimiry/ElectronMail#298]
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/8097377/84520158-d8f1a680-acf2-11ea-91c6-570b776da682.png">

I see like white screen only. Unfortunately i cannot open devtool as cmd +  option + I is not working.

**Comment by vladimiry** [comment]
Anything useful in the log file (`log.log` file located in the [settings folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg))?

**Comment by shirshak55** [comment]
hmm now i cannot even reproduce the issue may be after upgrade there were some issue but after restarting the pc it solves :( hisenbug :(
