### ISSUE TITLE
"Failed to clear session in 3000 ms" 

### ISSUE THREAD

**Issue by JamesJackson123** [vladimiry/ElectronMail#299]
I keep getting "Failed to clear session in 3000 ms" with some of my protonmail accounts on Electronmail, how do I fix this or allow it to try and clear the session in over three seconds.

**Comment by vladimiry** [comment]
The value of this timeout is currently [hardcoded](https://github.com/vladimiry/ElectronMail/blob/f1912ac0a09b537cbb8639aeb2a635cc8a75c200/src/electron-main/api/endpoints-builders/proton-session.ts#L130). But I think 3 seconds should be more than enough to reset the session. So it's likely the @electron's issue (I think I've seen before related issue somewhere in their issues tracker). The thing is that to place the issue in @electron's tracker it needs to be isolated and well reproducible which I'm not ready to jump into at the moment. But I'm going to make the timeout value customizable so you could try the larger value.

> with some of my protonmail accounts

Just some, not all of them? How many accounts added to the app? OS and app version used?

What I could recommend you to do right now is to (just a wild guess):
- Open the [app settings](https://github.com/vladimiry/ElectronMail/blob/612487406339357b3be607c97ceef72ab4360661/images/open-settings-folder.jpg) folded.
- Close the app.
- Remove all the stuff from the folded except for the files listed in [Data/config files created and used by the app](https://github.com/vladimiry/ElectronMail#dataconfig-files-created-and-used-by-the-app) readme section.
- Start the app.

Besides that, you could try to set up the auto-login delay in seconds for some accounts or/and enabling the "Login on account selection" toggle. See "extended options" collapsible section on the account setting form. I just have a guess that there might be timing issue in Electron when many sessions start processing the reset action at the same time.

**Comment by vladimiry** [comment]
[v4.6.0](https://github.com/vladimiry/ElectronMail/releases/tag/v4.6.0) allows configuring the discussed timeout value. See `timeouts.clearSessionStorageData` value in `config.json` file located in the [app settings](https://github.com/vladimiry/ElectronMail/blob/612487406339357b3be607c97ceef72ab4360661/images/open-settings-folder.jpg) folder.

**Comment by vladimiry** [comment]
Closing as inactive issue.
