### ISSUE TITLE
The app window isn't visible on MacOS after one of the latest updates

### ISSUE THREAD

**Issue by victor-yunenko** [vladimiry/ElectronMail#302]
The issue first appeared 2 or 3 updates ago, not sure which version of ElectronMail or MacOS I was running back then.

The app looks as if it's running, but the main window doesn't open. I can press `Toggle Window` item and it *does* trigger the OS focus, thus allowing me to see the `ElectronMail` menu in the top left corner, but that's the only effect that I can observe.

![image](https://user-images.githubusercontent.com/36416236/85223727-9bb1a680-b3cd-11ea-839b-736b8213575a.png)

It's also possible to see the app in the OS dock, but it isn't possible to open the app using it either.

Although I can still open the `About ElectronMail` window, here's its version info:
- v4.6.0
- Electron: 10.0.0-beta.3
- Chromium: 85.0.4161.2
- Node: 12.16.3
- V8: 8.5.73-electron.0

I'm on MacOS 15.15.5

Below I'm attaching the log file content, although it doesn't seem to be logging the attempts to open the window that I've been doing during the last hour.

<details>

```
[2020-05-19 19:55:52.480] [error] [web-contents] {
  constructor: 'Error',
  stack: 'Error: Opening a new window is forbidden, url: "https://effectivealtruism.us8.list-manage.com/track/click?u=52b028e7f799cca137ef74763&id=629166c16b&e=80571f0ff2"\n' +
    '    at notifyLogAndThrow (/Applications/ElectronMail.app/Contents/Resources/app.asar/app/electron-main.js:6466:19)\n' +
    '    at WebContents.<anonymous> (/Applications/ElectronMail.app/Contents/Resources/app.asar/app/electron-main.js:6479:13)\n' +
    '    at WebContents.emit (events.js:228:7)'
}
[2020-05-19 19:55:52.485] [error] {
  constructor: 'Error',
  stack: 'Error: Opening a new window is forbidden, url: "https://effectivealtruism.us8.list-manage.com/track/click?u=52b028e7f799cca137ef74763&id=629166c16b&e=80571f0ff2"\n' +
    '    at notifyLogAndThrow (/Applications/ElectronMail.app/Contents/Resources/app.asar/app/electron-main.js:6466:19)\n' +
    '    at WebContents.<anonymous> (/Applications/ElectronMail.app/Contents/Resources/app.asar/app/electron-main.js:6479:13)\n' +
    '    at WebContents.emit (events.js:228:7)'
}
[2020-05-21 22:49:50.662] [error] {
  constructor: 'Error',
  code: 'ELOCKED',
  file: '/Users/sin/Library/Application Support/electron-mail/config.json',
  stack: 'Error: Lock file is already being hold\n' +
    '    at Object.<anonymous> (/Applications/ElectronMail.app/Contents/Resources/app.asar/node_modules/proper-lockfile/lib/lockfile.js:54:47)\n' +
    '    at cb (util.js:196:39)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:81:21)'
}
```

</details>

**Comment by vladimiry** [comment]
Is the issue persistent or sporadical (you get it every time you start the app and click the tray's toggle window menu)?

> it doesn't seem to be logging the attempts to open the window that I've been doing during the last hour

You might want to set the `logLevel` property to `verbose` level in `config.json` file if you want more actions to get logged.

What I could recommend you to do right now is to (just a wild guess):
- Open the [app settings](https://github.com/vladimiry/ElectronMail/blob/612487406339357b3be607c97ceef72ab4360661/images/open-settings-folder.jpg) folded.
- Close the app.
- Remove all the stuff from the folded including the hidden files if any, except for the files listed in [Data/config files created and used by the app](https://github.com/vladimiry/ElectronMail#dataconfig-files-created-and-used-by-the-app) readme section.
- Start the app.

**Comment by vladimiry** [comment]
Also make sure that the `window` object in `config.json` looks valid (window size/width/height is not set to zero, no negative window placement x/y coordinates, etc).

**Comment by vladimiry** [comment]
Closing inactive issue.

**Comment by victor-yunenko** [comment]
Thank you! I ran into the same issue few months later and resettings `window.height` from `config.json` helped 🙏

**Comment by vladimiry** [comment]
Thanks for report. I just have enforced [100px as a minium app window width/height](https://github.com/vladimiry/ElectronMail/commit/1e34f2b2f20452883c6a750ecaa0cb3d344844ec#diff-daac5713296a0cc82be20b10c1e16a5950ba61fbde56613114e5a645d8c7f2b7R40-R47).
