### ISSUE TITLE
AV blocking

### ISSUE THREAD

**Issue by roberttilewick** [vladimiry/ElectronMail#304]
Any idea why my AV program (Bitdefender) blocks the .exe Windows download. I tried turning it off, but some residual AV still blocked it. 

Thx

**Comment by vladimiry** [comment]
If you face the issue during the installation process then I guess the AV program is scanning the activity of the installation package or/and the static resources/js-scripts/binaries app comes with. If the issue occurs in runtime then heuristic algorithms could cause false-positive case. So there are a lot of suspects, like NSIS installation package itself with its built-in scripts/scenarios, the fat @electron / @chromium bundle, and finally the app code part. The app code is open and unfortunately, at the moment there is nothing more I could do about making the project more trustworthy.

**Comment by roberttilewick** [comment]
Vladimir, thanks for the quick response. Maybe a future release won’t trigger the AV reaction. Could you be so kind to give me the URL to your project so I can check from time to time?

Thanks

**Comment by vladimiry** [comment]
> Maybe a future release won’t trigger the AV reaction. Could you be so kind to give me the URL to your project so I can check from time to time?

You could subscribe to new release notifications if you like. See the respective `watch` drop-down button in the top-right corner of the GitHub screen on the https://github.com/vladimiry/ElectronMail/ page.

![watch releases](https://user-images.githubusercontent.com/1560781/86902860-3375fb00-c117-11ea-9355-bcf5e27376e1.gif)

**Comment by vladimiry** [comment]
https://github.com/electron-userland/electron-builder/releases/tag/v22.8.1 release might fix/improve things. The next release will be built using v22.8.1+ `electron-userland` version.
