### ISSUE TITLE
ubuntu ppa

### ISSUE THREAD

**Issue by soredake** [vladimiry/ElectronMail#305]
Would be nice to have one.

**Comment by vladimiry** [comment]
I'm not going to support PPA package. Consider using Snap version.

**Comment by trymeouteh** [comment]
Would like to see a PPA version since Snaps and Flatpaks are large in size and take up lots of memory, and the DEB version needs to be installed manually every time there is an update.

**Comment by vladimiry** [comment]
See #489 for a possible option.
