### ISSUE TITLE
Auto discard failed decryption notice on successful decryption

### ISSUE THREAD

**Issue by schaafjs** [vladimiry/ElectronMail#306]
ElectronMail presents the user with a popup when they enter a wrong decryption password. I think while not necessary, it would make sense to discard that notification once the user is able to enter the correct credentials. This is of course a minor detail but something that bugs me especially because I cannot close the notification while the initial decryption is happening.

**Comment by vladimiry** [comment]
The wrong master password message is closeable (I mean [this](https://github.com/vladimiry/ElectronMail/blob/master/images/keep-me-signed-in.png) one). If that's about a password to an email account then it would be upstream issue to be resolved by protonmail.

**Comment by schaafjs** [comment]
I was refering to this one actually:
![grafik](https://user-images.githubusercontent.com/44237133/87966381-7e035a00-cabd-11ea-832b-a4c1807a3208.png)
I get it when I enter an incorrect password which is used for the local encryption. It is not about a password to an email account.

**Comment by vladimiry** [comment]
It's closeable. Notice X symbol at the right side of the message block (your screenshot is truncated).

**Comment by schaafjs** [comment]
Yes, the X symbol is indeed on the right but I get inconsistent behaviour from it. It does not always work for me on first click/try. The `Esc` key seems to always work consistently.

**Comment by vladimiry** [comment]
Request for making the failed decryption message to auto discard gets won't fix status. X symbol clicking processing inconsistency is not reproducible on my side and I'm not ready to jump into the debugging at the moment especially given the minor severity of the issue. Thanks for placing the issue though.
