### ISSUE TITLE
EACCES: permission denied, open '/home/tiana/snap/electron-mail/25/.config/electron-mail/config.json

### ISSUE THREAD

**Issue by KaKi87** [vladimiry/ElectronMail#307]
When ElectronMail starts and fails to fetch updates due to network not being connected, the app will auto-reload when network connected but will not be closable afterwards.

```
Unhandled Promise Rejection
Error: EACCES: permission denied, open '/home/tiana/snap/electron-mail/25/.config/electron-mail/config.json'
```

This error will popup once after clicking on window close button and once again after clicking `OK`.

Thanks

**Comment by vladimiry** [comment]
I don't use Snap stuff so can't advice on my own experience nor do I have a strong guess as to why the issue occurs. Maybe try manually tweaking the config.json permission flags like for example setting the same flags as set for settings.bin or other files listed in https://github.com/vladimiry/ElectronMail#dataconfig-files-created-and-used-by-the-app.

**Comment by vladimiry** [comment]
Is v4.9.1 affected?

**Comment by vladimiry** [comment]
Closing as inactive. Try a new release and the `flatpak repair --user` command.
