### ISSUE TITLE
Full text search times out

### ISSUE THREAD

**Issue by nayr1991** [vladimiry/ElectronMail#313]
I have a ProtonMail mailbox with ~33000 items, totalling about 1.9GB in my local database. Any full text search on the Archive or All Mail folders results in the following error:
`Invocation timeout of calling "dbFullTextSearch" method on "electron-mail:ipcMain-api" channel with 5000ms timeout`

I have looked through ~/.config/electron-mail/config.json and there doesn't appear to be anything configurable that relates to this error:
```
  "timeouts": {
    "dbBootstrapping": 43200000,
    "dbSyncing": 1800000,
    "webViewApiPing": 15000,
    "webViewBlankDOMLoaded": 15000,
    "domElementsResolving": 20000,
    "defaultApiCall": 25000,
    "databaseLoading": 300000,
    "indexingBootstrap": 30000,
    "clearSessionStorageData": 3000
  },
```

Is this something that is configurable?

**Comment by nayr1991** [comment]
Ahhh, I just updated to v4.8.0 and note that there's now a configurable timeout for `fullTextSearch`

**Comment by vladimiry** [comment]
> Ahhh, I just updated to v4.8.0 and note that there's now a configurable timeout for fullTextSearch

Yep, this timeout added in https://github.com/vladimiry/ElectronMail/commit/2040322ed3ca5408a9fe3c14491cabaace098fb2 just recently.

**Comment by vladimiry** [comment]
> I have a ProtonMail mailbox with ~33000 items, totalling about 1.9GB in my local database.

Sounds like quite a challenge for the app. The previous publicly named record was ~18k mails if I'm not wrong.

**Comment by nayr1991** [comment]
> > Ahhh, I just updated to v4.8.0 and note that there's now a configurable timeout for fullTextSearch
> 
> Yep, this timeout added in [2040322](https://github.com/vladimiry/ElectronMail/commit/2040322ed3ca5408a9fe3c14491cabaace098fb2) just recently and released in v4.8.0.

So I went through and re-tested this and this timeout doesn’t appear to apply to the search that I’m doing. It still times out after 5000ms, regardless of what I set this value to. I am updating the config while the app is closed then loading and testing.
Any ideas?

**Comment by vladimiry** [comment]
The API client timeout is involved too and unfortunately I missed tweaking it too (it's still hardcoded):

https://github.com/vladimiry/ElectronMail/blob/6a7d92f43fb6f34901b904c0107a038ce9bf704b/src/web/browser-window/app/_db-view/db-view.effects.ts#L155

What OS/package-type being used? I could do the fix and upload the package somewhere. Or you could build it yourself from the updated code.

**Comment by vladimiry** [comment]
The fix has been implemented. You can already built your own package form the sources or wait until the installation packages get prepared by CI systems.

**Comment by nayr1991** [comment]
Ok perfect, I've built and tested this successfully.

Many thanks!
