### ISSUE TITLE
Could not connect to .onion webclient

### ISSUE THREAD

**Issue by orbs163** [vladimiry/ElectronMail#315]
I keep getting "Could not connect to server" error messages when trying to connect through the .onion webclient.
I tried to manually connect through the webclient after credentials were autofilled, and I still get the same connection error.

Connecting through the Tor browser works, so this is not an issue on my end.

**Comment by vladimiry** [comment]
The Tor itself is not built-in in the app. So if you select https://protonirockerxow.onion/ API entry point you will need to specify `socks5://localhost:9050`-like proxy for the email account in the `Extended Options` block located on the account edit form. See more details in https://github.com/vladimiry/ElectronMail/issues/113#issuecomment-529130116.
