### ISSUE TITLE
Allow option to manually enable and load email accounts

### ISSUE THREAD

**Issue by KizunaH** [vladimiry/ElectronMail#316]
Current way atleast primary mailbox automatically load and login when open electronmail and it seems rest of them get loaded as well. Logout from certain mailboxes also not possible. Can you enhance settings page for,

- Logout (manually logout certain mailbox and notify confirmation dialog to login again)
(This feature for already logon accounts after launched the app and it doesn't remember that for next launch)
- Disable (this's a permanent option for disable certain mailbox until enable again also disappear from main window)
(When user click disable then the account should logout first then disable it in UI)

Example: https://github.com/ramboxapp/community-edition
![Screenshot from 2020-08-12 15-00-39](https://user-images.githubusercontent.com/63988538/89990493-aa6d5900-dcac-11ea-8ce0-27e453068fdc.png)

It has option(area) in right side for enable or disable services but i'm not prefer electronmail implement the same and separate page because i dont like people abuse the protonmail and use accounts for bad purposes or bother, harm people.

**Comment by vladimiry** [comment]
The requested feature is already there, enabled since [v3.1.0](https://github.com/vladimiry/ElectronMail/releases/tag/v3.1.0). Also, I guess you might want to explore the [persistent session](https://github.com/vladimiry/ElectronMail/issues/227) feature too.

![123](https://user-images.githubusercontent.com/1560781/90113633-50c36800-dd5a-11ea-82d9-409537d75e90.png)

**Comment by KizunaH** [comment]
No. I mean these options.

![Screenshot from 2020-08-26 01-56-00](https://user-images.githubusercontent.com/63988538/91216764-adeaf080-e740-11ea-9de8-7fb820dabe7b.png)

1. Color - account status
2. Logout - temporally logout account (until reboot or relaunch app)
3. Enable or Disable - Permanently enable and disable accounts.

**Comment by vladimiry** [comment]
> No. I mean these options.

Won't fix then.

**Comment by KizunaH** [comment]
> Won't fix then.

But what's the reason for consider to ignore it?

**Comment by vladimiry** [comment]
A balance of demand / increased complexity of code&maintainability&UX / my capacity / etc.

**Comment by KizunaH** [comment]
> A balance of demand / increased complexity of code&maintainability&UX / my capacity / etc.

However i think this might be a useful feature also essential for multiple accounts own users. Someone may able to help if this keep opened or you can implement when less issues in repository.

**Comment by vladimiry** [comment]
> Someone may able to help if this keep opened or you can implement when less issues in repository.

It's not only about implementing some new feature but also about supporting it in the future since in general the maintenance burden gets increased with code base growing. So even if someone will be willing to implement the requested feature I won't be accepting it in this protect at this time which means that should be maintained as a fork.

**Comment by azrea** [comment]
> > Someone may able to help if this keep opened or you can implement when less issues in repository.
> 
> It's not only about implementing some new feature but also about supporting it in the future since in general the maintenance burden gets increased with code base growing. So even if someone will be willing to implement the requested feature I won't be accepting it in this protect at this time which means that should be maintained as a fork by the feature author.

Late visit :)
I'm also multiple protonmail accounts user so i especially concern about that.

Can't you just add only a enable/disable option?, discarding everything else mentioned by @KizunaH (it seems new facilities and UI enhancements she suggested for electronmail) so It'll not expand the codebase as you make sounds.

(The simple goal is to ensure and prevent particular mailboxes get network access. that's what we expect as multiple account users. When enable then it can follow the normal login procedure to load the mailbox or it can be either persistent session according configuration made when add mailbox. Anyway as easy for you with minimum code lines)

Both are electron based apps and you can minimize what've done to implement that option in rambox
https://github.com/ramboxapp/community-edition

![Screenshot from 2020-09-05 02-18-16](https://user-images.githubusercontent.com/69689603/92278549-a802c580-ef1f-11ea-86d5-467e2684d2f2.png)

**Comment by vladimiry** [comment]
Adding only the disabling toggle near to the account is not a big change indeed.

**Comment by vladimiry** [comment]
The feature is on the way:

![issue-316](https://user-images.githubusercontent.com/1560781/92308941-f0ff5c00-efa9-11ea-9139-c1dc0fa964cc.gif)

**Comment by vladimiry** [comment]
The feature by the way works nicely with the [persistent session](https://github.com/vladimiry/ElectronMail/issues/227) feature. Means you can deactivate and activate the account back having the login form skipped. The app doesn't drop the saved session if any but only disables the account loading/rendering.

**Comment by azrea** [comment]
@vladimiry  :1st_place_medal:

**Comment by vladimiry** [comment]
If someone wants to try the WIP build with the enabled feature, it's uploaded [here](https://mega.nz/folder/glxmQYQI#ZRgA5JcDofRQXNpCBLGK-g).

**Comment by KizunaH** [comment]
Nice to see this feature quick. :)

**Comment by vladimiry** [comment]
Updated WIP build uploaded [here](https://mega.nz/folder/x4oRjZrY#OnnzG6B9vK5iOPjWjvrX8g) (fixed "Failed to resolve account" error occuring).
