### ISSUE TITLE
Unread count reports all unread messages across all folders

### ISSUE THREAD

**Issue by keawade** [vladimiry/ElectronMail#322]
I have lots of unread emails in folders and my archive as my default preference is to archive items rather than delete them. As a consequence, the unread count in the ElectronMail notification badge is useless.

Would you be willing to consider an option to restrict the unread count for the notification badge to the Inbox?

In the mean time, is there a way to disable the notification badge? Otherwise I'm stuck with a permanent red circle with a `+` in my tray. I've looked through all the settings I can find and while I can change the colors, I don't see an option to disable the badge.

**Comment by vladimiry** [comment]
> all the settings I can find and while I can change the colors

Right now the only option to blank the unread value rendered on the tray icon is to set the same color for the badge's font as used for the background. So you get just a single-color circle rendered on the tray.

**Comment by vladimiry** [comment]
The feature request gets closed with won't-fix status at this time.

**Comment by Atrate** [comment]
I know I'm kind of necrobumping here, but I have the opposite problem - I only get the unread badge for the inbox and not the folders, is there a setting I'm missing?

**Comment by vladimiry** [comment]
Taken from https://github.com/vladimiry/ElectronMail/issues/656#issuecomment-1820343107

> Also, currently if the [local store](https://github.com/vladimiry/ElectronMail/wiki/FAQ) is not enabled for the account, the app shows unread notification for the `Inbox` folder only. I'm changing it to "all folders" by 8378e3b967f3bc7a9e67f4cc8a19e497e87920a4, so it works similar to [local store](https://github.com/vladimiry/ElectronMail/wiki/FAQ) mode.
