### ISSUE TITLE
Mobile app?

### ISSUE THREAD

**Issue by Atrate** [vladimiry/ElectronMail#329]
Since PM only allows multiple accounts for paid plans, would there be a possibility of making EM into a mobile app as well?

**Comment by vladimiry** [comment]
The app is built on @electron which doesn't support regular mobile systems, like iOS/Android. But technically @electron based apps should work on Linux-based phones, like [PinePhone](https://www.pine64.org/pinephone/). The project doesn't ship the installation packages for ARM-based devices so if you want to start the app on a PinePhone-like device, you will have to assembly the package from sources with proper flags.

**Comment by chookity-pokk** [comment]
@vladimiry Can you by chance update the README with the instructions on building for the Pinephone? I don't know electron very well so I am not sure which flags are the proper flags.

**Comment by vladimiry** [comment]
> Can you by chance update the README with the instructions on building for the Pinephone?

@chookity-pokk, that should be done by someone who went through the process, and this is not me.

**Comment by chookity-pokk** [comment]
Okay. I am willing to do it but can you point me in the direction of which flags would need to be added?

**Comment by vladimiry** [comment]
@chookity-pokk, I didn't run these steps in full, but you could start from here and adjust if needed.

First, take the recent stable release and replace @electron with arm64 version:
- `wget https://github.com/vladimiry/ElectronMail/releases/download/v5.2.2/electron-mail-5.2.2-linux-x86_64.rpm`
- `ar x electron-mail-5.2.2-linux-amd64.deb`
- `mkdir app`
- `tar xf data.tar.xz -C ./app --strip-components=2 ./opt ./usr`
- Then replace everything in `./app/ElectronMail` except `resources` folder with unpacked `https://github.com/electron/electron/releases/download/v27.1.0/electron-v27.1.0-linux-arm64.zip`
- You will be running `./app/ElectronMail/electron-mail` when you complete the next step.

Now you need to replace the native modules located in `./app/ElectronMail/resources/app.asar.unpacked/node_modules` with arm64 version, so you need to compile the native modules first:
    - `git clone https://github.com/vladimiry/ElectronMail.git --branch v5.2.2 --single-branch && cd ElectronMail`
    - `pnpm install --frozen-lockfile`
    - `ELECTRON_DEST_MAIL_ARCH=arm64 npx pnpm prepare-native-deps`
    - Now replace the native binaries in `./app/ElectronMail/resources/app.asar.unpacked/node_modules` with ones you got compiled (located in `./node_modules/keytar/bin/linux-arm64-118`,	`./node_modules/msgpackr-extract/bin/linux-arm64-118` and `node_modules/sodium-native/bin/linux-arm64-118`).

Now you can try to run the app on `arm64`-based device.
