### ISSUE TITLE
About read mails offline 

### ISSUE THREAD

**Issue by ps-a** [vladimiry/ElectronMail#335]
I use electronmail but this is not especially belong to it. you may aware about various type of tools that available for linux related e-mails. i also aware electronmail has offline mode but it doesn't cover my requirement.

 Free accounts, protonmail has feature to export mails then it export as .eml format (basically i want to export some mails and delete from mailbox then keep for offline reading)

I open that files using text editor, atom etc but unable to see the body as huaman-readable mode except rest of contents. i asked protonmail support and they said there're lot of tools available for linux and you can find then hint me about thunderbird but it's not what i wanted

do you know any tools available for linux or workround to accomplish my requirement? 
(i dont want to add mailbox(login) to particular tool and only expect a way to read exported mails)

**Comment by vladimiry** [comment]
> they said there're lot of tools available for linux

This is correct. You can decode the base64 encoded EML content on Linux using built-in tools.

Few options:
- Using https://addons.thunderbird.net/en-US/thunderbird/addon/importexporttools-ng/ extension to import the EML files into a "local" folder in Thunderbird. The local folder in Thunderbird not necessary should be linked to any account. This is a user friendly option.
- The "Linux way" is to use the `base64` command + if needed sh script for automation (like locating and decrypting the content of all `Content-Type: text/html` + `Content-Transfer-Encoding: base64` sections in EML). See details in `man base64` command output.

**Comment by ps-a** [comment]
thanks ^^
