### ISSUE TITLE
программная ошибка

### ISSUE THREAD

**Issue by KizunaH** [vladimiry/ElectronMail#336]
Below error appear when close app with multiple accounts opened

Unhandled Promise Rejection
Error: Lock file is already being hold
    at Object.<anonymous> (/opt/ElectronMail/resources/app.asar/node_modules/proper-lockfile/lib/lockfile.js:54:47)

v4.9.0 | Ubuntu 20.04.01

**Comment by vladimiry** [comment]
This a know but not yet handled issue. Going to remove the stale lock files on the app start and maybe enable custom error processing (such files normally get created on abnormal program exit or on power loss).

The workaround is removing the lock-like files/directories located in the [settings folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg).

**Comment by vladimiry** [comment]
Implemented fix: 42b1847.

**Comment by vladimiry** [comment]
Same fix + custom error message: c9a6924.
