### ISSUE TITLE
Decryption issue

### ISSUE THREAD

**Issue by uberneko** [vladimiry/ElectronMail#340]
I stumbled across an interesting bug.
I wanted to give a try to the export feature with attachements - so I went to local database mode and selected a folder with quite old emails. I discovered than 25-30% of them were tagged with that little (!) in red : "Failed to decrypt the email body content:"
When re-downloading the email, it would not work.
It seems to affect old emails (at least 1.5 year possibly).
In the online mode, same issue : the emails appear like : "Decryption error: Decryption of this message's encryption content failed.
Try again" - and when trying again, it does not work.

The strange thing is that... using PM on the web, via firefox, emails are totally readable - no issue. Same on the PM app in Android.
So I would assume it happens on this app -

I use 4.8.0 Appimage on *buntu 20.04, started using PM for quite a long time now (maybe 2 years, or more).

When I saw the issue - I deleted the database and database-session file and let it reload my almost 7000 emails. Same emails were flagged as unreadable after - I am not really sure about what happens...

**Comment by vladimiry** [comment]
Can you click "re-download" on some email using [this](https://mega.nz/folder/QtwCQIZZ#sfAOA3Tobhj2n7QjuWLgUw) build (most recent 4.9.0 build)? I highly recommend enabling the `Block non "API entry point"-based network requests` option for all accounts if you run this build (see how to enable it on the screenhot in https://github.com/vladimiry/ElectronMail/issues/312#issuecomment-709650619).

**Comment by vladimiry** [comment]
The app decrypts the message body content using protons methods. It might be that in some cases the app doesn't call those methods having provided all the necessary arguments.

In general, having non-decryptable emails would be a valid case in the case if there is no more linked to those emails encrypting keys in your proton account.

**Comment by uberneko** [comment]
I tried on three emails at random and it worked !
But I assume I need to reload the database - I won't click hundreds of time -
Txs a lot !

**Comment by vladimiry** [comment]
Closing as resolved.
