### ISSUE TITLE
Calendar Desktop Notifications

### ISSUE THREAD

**Issue by IberratioActus** [vladimiry/ElectronMail#341]
Hey there,

I can't seem to make desktop notifications to work. It is enabled in the calendar settings, but I get none when I hit the "test" button neither when an appoinment hits

Any idea why? 

Win10,  v4.8.0

**Comment by vladimiry** [comment]
Closing as duplication of #328.

So the issue fixed in the code but v4.9.0 release is at the moment blocked by unresolved proton's issue, see https://github.com/vladimiry/ElectronMail/issues/332#issuecomment-713119346.

**Comment by vladimiry** [comment]
The work-in-progress v4.9.0 version with the included fix is uploaded [here](https://mega.nz/folder/YpIigT7R#eGH5QExiGLi1lHstiFallQ). For everyone running this build I highly recommend enabling the opt-in `Block non "API entry point"-based network requests` option for all accounts (see how to enable it on the screenshot in https://github.com/vladimiry/ElectronMail/issues/312#issuecomment-709650619)
