### ISSUE TITLE
Feature Request:  Add option to disable hardware acceleration

### ISSUE THREAD

**Issue by jleonar** [vladimiry/ElectronMail#343]
Chrome and electron based apps still have issues on AMD GPUs when running on Linux.  It causes all sorts of artifacts.  The only solution is to disable hardware acceleration.  

I have done that for Chrome and Slack Desktop App.  It does resolve the issue.  However, electronmail doesn't have that preference option.

Electronjs supports disabling this, so it would just be a matter of adding that as a preference in the application.

**Comment by vladimiry** [comment]
The respective option was originally enabled in https://github.com/vladimiry/ElectronMail/releases/tag/v2.3.3 but then got removed since unfortunately @electron doesn't guarantee its reliable work (from version to version it demonstrates issues related to this option).

What you can try to do independently is starting the app with the `--disable-gpu` command line argument.

**Comment by vladimiry** [comment]
> What you can try to do independently is starting the app with the --disable-gpu command line argument.

The next app release enables support for `commandLineSwitches` array in `config.json` (located in the [settings folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg)). So the `disable-gpu` and alike switches can be put there to avoid explicit args passing to app binary starting command.

**Comment by Milor123** [comment]
How should I add it to `config.json`?

`"commandLineSwitches": ["--disable-gpu"],` is okay ? or what should I write?

**Comment by Milor123** [comment]
> > What you can try to do independently is starting the app with the --disable-gpu command line argument.
> 
> The next app release enables support for `commandLineSwitches` array in `config.json` (located in the [settings folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg)). So the `disable-gpu` and alike switches can be put there to avoid explicit args passing to app binary starting command.

How should I add it to `config.json`?

`"commandLineSwitches": ["--disable-gpu"],` is okay ? or what should I write?

**Comment by vladimiry** [comment]
> `"commandLineSwitches": ["--disable-gpu"],`

looks valid
