### ISSUE TITLE
Cannot open outside links

### ISSUE THREAD

**Issue by indig0F10w** [vladimiry/ElectronMail#344]
Hi, the elements in confirmation window for opening outside links are not working properly.

User can click the [X] close button, "Do not ask again", select/copy link, select any text in the window.

User cannot click Cancel or Continue.

Thank you.

![EMb](https://user-images.githubusercontent.com/17021548/97859931-93fdf900-1d01-11eb-8837-7d3b43875f1b.png)

**Comment by vladimiry** [comment]
Thanks for the report. The fix has been implemented and scheduled for the next release.
