### ISSUE TITLE
Split the core engine from the GUI

### ISSUE THREAD

**Issue by redgryphon** [vladimiry/ElectronMail#347]
The proposal is pretty trivial _per se_. Having the project split in two parts would definitely help to maintain the code and to allow further work.
The idea behind this is that with a core engine on its own it would be possible to expose a IMAP server mimicking the official bridge, only available to paid users.

I'm open to every kind of question or discussion regarding this proposal.

**Comment by vladimiry** [comment]
In your terms, the core engine of ElectronMail is https://github.com/ProtonMail/proton-mail project, so it's already separated.

**Comment by vladimiry** [comment]
All the encrypting/decrypting/loading/etc operations done via https://github.com/ProtonMail/proton-mail (set of used functions listed [here](https://github.com/vladimiry/ElectronMail/blob/69b6d65c4b58b4993dedeb82fa6ed339836dd992/src/electron-preload/webview/primary/provider-api/model.ts#L128-L198)), so there is no such thing as engine.
