### ISSUE TITLE
Notification doesn't work if the mail is moved to a folder using the filter

### ISSUE THREAD

**Issue by pratik705** [vladimiry/ElectronMail#348]
# Issue:
Notification doesn't work if the mail is moved to a folder using the filter

**Comment by vladimiry** [comment]
Currently, the app displays the desktop notifications for the "inbox" folder only. If you want the desktop notifications to be displayed for all folders, consider enabling the [local store](https://github.com/vladimiry/ElectronMail/wiki/FAQ) option for the email account.

Here is how the feature can be improved:
- Adding a hint near to the "Desktop notifications for unread email messages" toggle which says what I've put above (notifications get displayed for the "inbox" folder only by default).
- Showing the desktop notification according to the folder's "notification" toggle (the toggle value setting happens in the [proton-mail-settings](https://github.com/ProtonMail/proton-mail-settings) @ProtonMail web client deployed in the app on `/settings` location).

**Comment by vladimiry** [comment]
> If you want the desktop notifications to be displayed for all folders, consider enabling the [local store](https://github.com/vladimiry/ElectronMail/wiki/FAQ) option for the email account.

In new release the desktop notifications in [local store](https://github.com/vladimiry/ElectronMail/wiki/FAQ) will be displayed depending not on all folders but on the folder "notification" state. No more related to this issue changes going to happen, so closing with won't fix status.
