### ISSUE TITLE
Failed to load webclient in 15000ms | Flatpak Version

### ISSUE THREAD

**Issue by kb8cb40j1av39c02** [vladimiry/ElectronMail#349]
Hi

First of all, thank you for Electronmail. I used it daily on Windows - however I have switched to PopOS 20.04 LTS recently, and I've been using the Flatpak version of your app on PopOS.

Since installing the flatpak version I get following error almost every time when I open the app:
Failed to load "webclient1://mail.protonmail.com" page in 15000ms

I have deleted part of the URL. I know where the logfile is located. But I'm not sure if it's safe to post the entire logfile? Does it contain sensitive information?

The issue is I think related to #311 .

Kindest regards!

**Comment by vladimiry** [comment]
This is a Flatpak-specific issue and unfortunately there is not a lot I can do about it. I will just ping @mike2307 and @pizzadude, maybe they have some information for sharing. The workaround is to use other package type.

> But I'm not sure if it's safe to post the entire logfile? Does it contain sensitive information?

The log file won't help much (I was reviewing it in #311). In general, the app tends not to put sensitive information into the log file. For sharing potentially sensitive information there is an email address specified in the `author` field of the [package.json](https://github.com/vladimiry/ElectronMail/blob/master/package.json) file.

**Comment by pizzadude** [comment]
I use Fedora 33. I used to have this issue but after some OS updates I no longer have this issue. Maybe Pop OS has outdated flatpak / some other libraries? You can try the snap version as a workaround, it should work. https://snapcraft.io/electron-mail

**Comment by pizzadude** [comment]
You can try updating flatpak via the official PPA to see if it helps.

sudo add-apt-repository ppa:alexlarsson/flatpak
sudo apt-get update
sudo apt dist-upgrade

**Comment by kb8cb40j1av39c02** [comment]
@vladimiry does the .deb version have a way of automatically updating or does it contain update notifications like windows? @pizzadude I suppose so in that case. Maybe if I upgraded to Pop OS 20.10 it would fix itself. If I do so and something changes I will update this.

**Comment by vladimiry** [comment]
The wild guess is that the issue might be kernel version dependent, see https://github.com/vladimiry/ElectronMail/issues/253.

**Comment by pizzadude** [comment]
I'm using kernel 5.9.9. What kernel does PopOS 20.04 use? You can check with " uname -r " in the terminal.

**Comment by kb8cb40j1av39c02** [comment]
5.8.0 in 20.04

**Comment by pizzadude** [comment]
Did you try the snap version of electronmail?

**Comment by vladimiry** [comment]
> does the .deb version have a way of automatically updating or does it contain update notifications like windows?

The code and app behavior is the same for all packages is the same except for that for snap+flatpak the `Check for update and notify` toggle disabled by default (but can be manually enabled if needed). That toggle simply enables the https://api.github.com/repos/vladimiry/ElectronMail/releases response checking on app start and showing the desktop notification of new version is available.

![123](https://user-images.githubusercontent.com/1560781/100093215-44c26880-2e68-11eb-922e-4ec712f5bd09.png)

**Comment by kb8cb40j1av39c02** [comment]
UPDATE @vladimiry @pizzadude: The issue is now fixed!
PopOS is still on 20.04 - Kernel still on 5.8.0 - but what HAS changed is the flatpak version installed - i noticed it got upgraded to 1.8.4 - I sadly don't quite remember what version was installed before. Since that upgrade though - I've never had the issue anymore.

**Comment by vladimiry** [comment]
Thanks for the update. Lets close the issue then.
