### ISSUE TITLE
Bind ctrl+q to application close

### ISSUE THREAD

**Issue by soredake** [vladimiry/ElectronMail#350]
Most applications have this binding.

**Comment by kb8cb40j1av39c02** [comment]
I don't know what you mean? For me using ctrl+q always closes all applications, Electronmail included. Are you perhaps using Gnome with the 'Dash-to-dock' extension?

**Comment by soredake** [comment]
> I don't know what you mean? For me using ctrl+q always closes all applications, Electronmail included. Are you perhaps using Gnome with the 'Dash-to-dock' extension?

I'm using KDE.

**Comment by kb8cb40j1av39c02** [comment]
The problem for me was that Dash-to-dock had a 'ctrl+q' binding registered and it interfered with the gnome 'ctrl+q' shortcut - so I disabled it in the dash-to-dock extension. Maybe you have a programm installed that uses 'ctrl+q'? They could interfere with each other.

**Comment by soredake** [comment]
I don't think KDE has global ctrl+q shortcut for closing any application, that's why i'm asking to add such binding to electronmail.

**Comment by kb8cb40j1av39c02** [comment]
https://docs.kde.org/trunk5/en/applications/fundamentals/kbd.html
according to this it has

**Comment by bersy** [comment]
It's CTRL + W in Windows to my knowledge, so your proposal isn't quite right.
