### ISSUE TITLE
Master Password 

### ISSUE THREAD

**Issue by crandersson** [vladimiry/ElectronMail#351]
Hello vladimiry this is not an issue i just want you to help me to recover my master password, i installed ElectronMail for Linux/Ubuntu , i tried uninstalling it but when i reinstall ElectronMail and open up the app it stills show me the login panel

Thanks for your help and congrats for this amazing app that you made !

**Comment by vladimiry** [comment]
If I got it right you want to completely reset the app settings. See how to do so:
- Open the [app settings folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg) in the file manager/explorer.
- Close the app.
- Empty/remove/rename/move the opened before "app settings folder".

**Comment by crandersson** [comment]
Yes! that is want to do but i cant open the app settings folder, i only can see the login option
There is no way to reset the settings from the terminal?

![1](https://user-images.githubusercontent.com/75137942/100481208-04a5f480-30b9-11eb-806b-f643e8b394dd.png)

**Comment by vladimiry** [comment]
On the [original screenshot](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg) presented two options to open the app settings folder (you can do that via tray menu having the app locked). Normally, on Linux the app settings folder location is `/home/<user name>/.config/electron-mail/`.

**Comment by crandersson** [comment]
Ok i found the folder, there is some config file to edit or some script that i can run for restore the settings? because from the desktop app is impossible i cant see more options than the login

**Comment by vladimiry** [comment]
You can't restore the settings not knowing the master password. You can only start from scratch in this case (how to start from scratch listed in https://github.com/vladimiry/ElectronMail/issues/351#issuecomment-734941065).

**Comment by crandersson** [comment]
Thats the problem man i cant see any app settings folder or some menu when i launch the app, i only see the login panel, no more options or menus

**Comment by vladimiry** [comment]
You have to enter the master password to get the app into the state of working with sensitive data. If you don't know the master password the only way to use the app is to completely drop/reset the app settings as described above. The you will be able to setup a new the master password, add accounts, etc.

**Comment by crandersson** [comment]
Yes man i dont remember my master password but i cant see the menus tha you mentioned in the other comments, that is the reason because i cant start from scratch.
i cant see this menus:
![1](https://user-images.githubusercontent.com/75137942/100492073-9aa84200-30ee-11eb-914c-5e9d2a4e514c.png)

**Comment by vladimiry** [comment]
> i cant start from scratch

You can. Just read the messages posted in the topic one more time.

**Comment by crandersson** [comment]
I couldnt man but i just deleted the config file and then re install the app for set from scratch and everyting is good
Thanks for your help!
