### ISSUE TITLE
Option to close green notifications

### ISSUE THREAD

**Issue by IberratioActus** [vladimiry/ElectronMail#353]
Is it possible to add an option to close the green notifications, like those when you delete a message or move it to a folder? 

If you do 2 actions, it does block the top bar and you have to wait a few seconds until it disappears. 

https://i.imgur.com/of9De6r.png

Just a very minor issue, but I'd be glad to see that in

Thanks in advance! :)

**Comment by vladimiry** [comment]
It's done on the @ProtonMail's side, so should be sorted out by them (upstream issue).

**Comment by vladimiry** [comment]
Technically you can apply the custom CSS rules to hide the green notification. The custom CSS support gets enabled in the next app release, see #355 for details.
