### ISSUE TITLE
Add custom CSS option

### ISSUE THREAD

**Issue by ShinyMountain** [vladimiry/ElectronMail#355]
ProtonMail recently deprecated the setting where you could add a custom CSS. It would be great if such an option could exist on top of Proton builds in ElectronMail

**Comment by vladimiry** [comment]
This is technically possible to enable in the app but as far as I know they will be getting it back. There os no clear information when it happens though, you know `Soon™`.

**Comment by ShinyMountain** [comment]
Thanks for your super fast answer!

Indeed, I'm not a big fan of downgrading as I will lose the new calendar integration in mail for eg. I had some chats with the CS and a product manager about that and they told me that they do not plan to add it back in the form it was before (where you could change anything basically) but rather a limited version where you could edit the spacing and some colors :(

**Comment by vladimiry** [comment]
The next app release with the custom css support enabled is planned for this week.

See how to apply the custom styling for the specific email account:
![custom-css-2](https://user-images.githubusercontent.com/1560781/101663498-d41c6e00-3a5b-11eb-8488-e61b83f9bf40.gif)

**Comment by ShinyMountain** [comment]
That's awesome, thanks a lot! You were super fast! # #

**Comment by vladimiry** [comment]
v4.10.0 has just been released

**Comment by romeoacevedo** [comment]
How can you change the body of the email to black using this feature?
