### ISSUE TITLE
Move binary symlink for archlinux package

### ISSUE THREAD

**Issue by StevenDoesStuffs** [vladimiry/ElectronMail#358]
Currently, in the Archlinux package, a symlink is installed to `/usr/local/bin` in order to put the binary in the path. 
I'm almost certain that that symlink should be going into `/usr/bin` instead.

According to the [Arch package guidelines](https://wiki.archlinux.org/index.php/Arch_package_guidelines#Directories), "Packages should never be installed to `/usr/local/`", and instead, any binaries (and I assume this includes symlinks to binaries) should go in `/usr/bin`.

**Comment by vladimiry** [comment]
This will be wontfix for now since the installation package assembling is the responsibility of [electron-builder](https://github.com/electron-userland/electron-builder/) project and it doesn't seem to support for custom binaries location configuration.
