### ISSUE TITLE
Unsupported browser

### ISSUE THREAD

**Issue by iwex** [vladimiry/ElectronMail#359]
For some accounts I'm getting such kind of error: 
![image](https://user-images.githubusercontent.com/4510068/104110015-31664200-52dc-11eb-9dca-6bbf46c2678d.png)

**Comment by vladimiry** [comment]
The CI/github-actions/travis-ci packages building pipeline includes basic tests for starting the app and loading the prepackaged @ProtonMail web clients and those tests got passed. So this is likely a system/environment dependent issue. When [I was adding support for v4 clients stack](https://github.com/vladimiry/ElectronMail/issues/332) I noticed that the "Unsupported browser"-like error was displayed on unrecoverable JS errors occurring on the page which makes me think there might be some information saved in the `log.log` file located in the [settings folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg). So consider the possibility to attach the relevant log lines here or send privately to the email specified in the "author" field of the [package.json](https://github.com/vladimiry/ElectronMail/blob/master/package.json). Besides, having the following info might help: OS type, app package type, API entry point specified for the mail account.

**Comment by vladimiry** [comment]
Closing as inactive.
