### ISSUE TITLE
Client doesn't connect - same password works fine on browser

### ISSUE THREAD

**Issue by andythedude** [vladimiry/ElectronMail#362]
Hello!

I believe i've detected an issue with the client, it will not connect to my account and spits out the message:
`Failed to decrypt the settings storage`
If i log into a browser (firefox) and try to connect via the website it connects just fine with the same password.

When i initially downloaded the flatpak client app i was able to log in.

running from terminal yields the following error messages on launch:
`(node:3) DeprecationWarning: file property is deprecated and will be removed in v5.
Gtk-Message: 23:19:23.678: Failed to load module "canberra-gtk-module"
Gtk-Message: 23:19:23.678: Failed to load module "canberra-gtk-module"
`

**Comment by vladimiry** [comment]
I think you are mixing different things here.

>  If i log into a browser (firefox) and try to connect via the website it connects just fine with the same password.

The app has nothing to do with the browsers.

>  Failed to decrypt the settings storage

This normally means that you enter a wrong master password when you start the app.

> running from terminal yields the following error messages on launch:

Not error but warning likely triggered by flatpak container.

**Comment by andythedude** [comment]
ahh yes... that would do it!

i had forgotten when i set it up that it had its own password >.<

user error! my apologies!

On Mon, 2021-01-18 at 00:46 -0800, Vladimir Yakovlev wrote:

I think you are mixing different things here.

If i log into a browser (firefox) and try to connect via the website it connects just fine with the same password.

The app has nothing to do with the browsers.

Failed to decrypt the settings storage

This normally means that you enter a wrong master password when you start the app.

running from terminal yields the following error messages on launch:

Not error but warning likely triggered by flatpak container.
