### ISSUE TITLE
How to migrate data?

### ISSUE THREAD

**Issue by refouna** [vladimiry/ElectronMail#366]
Hi,

I installed electronmail .deb package (for test early build) and has several accounts logon (with two passwords and two factor)
Then now i installed snap package so how i migrate all data from .deb to snap?

Thanks

**Comment by refouna** [comment]
eg: tell me which files, folders etc need to copy and to which locations etc

**Comment by vladimiry** [comment]
- Open the [settings folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg) for both deb/snap apps.
- Located in those folders files listed in https://github.com/vladimiry/ElectronMail/wiki/FAQ (`What are the data/config files the app produces?` section).
