### ISSUE TITLE
Dark mode for settings, drop down and about windows

### ISSUE THREAD

**Issue by Aikatsui** [vladimiry/ElectronMail#367]
I saw you have added some advanced features in settings about color customization for tray, notification badge, text and custom css for each accounts but small thing missing. 
I didnt noticed any way to apply dark mode for settings, drop down(next) and about window in app. may be you can set them dark by default, no one will feel unhappy about it. it's quite painful to eye while nowdays everything has dark mode then accidentally appear white window.

This is a simple app however if feels interest then you may able to add localization support. i'll also help for translations.
eg: cloud platform option instead PR to repo directly https://crowdin.com/pricing (it has enough free plan)
https://crowdin.com/page/open-source-project-setup-request (optional)

**Comment by vladimiry** [comment]
Thanks for thoughtful/detailed issue description. Dark mode thing linked to #242 (not planned for resolving in the near future), so closing this issue as duplicate. Translations thing got closed with wontfix status, #239.
