### ISSUE TITLE
Protonmail Keyboard Shortcuts

### ISSUE THREAD

**Issue by cwmke** [vladimiry/ElectronMail#368]
Not sure if I'm missing something but the default ProtonMail keyboard shortcuts don't seem to work. I'm using the Flatpak version on Fedora 33 using the wayland session. I'm unsure if this is related to ElectronMail or the flatpak package.

**Comment by vladimiry** [comment]
Originally there was no keyboard shortcuts feature enabled in https://github.com/ProtonMail/proton-mail. They enabled it in version `[4.0.0 - Beta 35] - 2021-01-21` but the released app version comes with `[4.0.0 - Beta 33] - 2020-12-16` / https://github.com/ProtonMail/proton-mail/commit/8245ffee429d35b52e9fca4debe79cec883c258d.

So you have the following options of getting the keyboard shortcuts feature:
- Build the app package from source code. The code repository has already adopted the newest https://github.com/ProtonMail/proton-mail version.
- Wait for new app release.
- Use https://beta.protonmail.com which comes with live/actual https://github.com/ProtonMail/proton-mail version deployed.

**Comment by vladimiry** [comment]
Addition option is trying the [nightly v4.10.1 build](https://mega.nz/folder/glBgTTSa#p-gyn1zgUaXMogNMo_GpWg).
