### ISSUE TITLE
4.10.1-linux-amd64.deb package shows as already installed in "Ubuntu Software" (LTS 20.04)

### ISSUE THREAD

**Issue by badger62** [vladimiry/ElectronMail#373]
Double clicking on the package brings up the Ubuntu Software install dialog. However the only option is "uninstall"  as 4.10.1 was already installed. Currently running ElectronMail 4.10.0 .

**Comment by vladimiry** [comment]
Unfortunately I'm not familiar with the options of installing the packages on Ubuntu using some GUI tools. To install v4.10.1 try to execute the following console command: `sudo dpkg -i electron-mail-4.10.1-linux-amd64.deb`.

**Comment by vladimiry** [comment]
Besides that, since you run Ubuntu, I think you might want to try Snap, see https://snapcraft.io/electron-mail. In general, if I would be running Ubuntu, I'd prefer Snap to DEB package since Snap provides some sandboxing/isolation capabilities.
