### ISSUE TITLE
Please destyle unread indicator on spam and "all mail" folders

### ISSUE THREAD

**Issue by KaKi87** [vladimiry/ElectronMail#374]
Hello,

The badge style for the inbox folder unread indicator is really great.

However, the spam (therefore, the "all mail" too) folder doesn't deserve as much attention.

Would you please destyle it so it gets less visible again ?

Thanks

**Comment by vladimiry** [comment]
Will some level of notification badge opacity work? Can you provide screenshot of desired destyling for better understanding?

**Comment by KaKi87** [comment]
By *destyling* I meant removing the custom style and let the unread indicator get its official appearance back :

![](https://user-images.githubusercontent.com/21284089/108897508-789f5c80-7616-11eb-87c1-dc29d1192343.png)

Thanks

**Comment by vladimiry** [comment]
The comes with the packaged as a static resource beta.protonmail.com / https://github.com/ProtonMail/proton-mail official web mail client. The official stable mail client version, ie https://github.com/ProtonMail/WebClient, is no longer used in this project since https://github.com/vladimiry/ElectronMail/releases/tag/v4.9.0.

**Comment by KaKi87** [comment]
I understand, in that case I agree about lowering the indicator's opacity. I really think ProtonMail devs did a bad move on this one

**Comment by vladimiry** [comment]
> I agree about lowering the indicator's opacity. I really think ProtonMail devs did a bad move on this one.

The custom CSS injection feature is available in the app since https://github.com/vladimiry/ElectronMail/releases/tag/v4.10.0.

**Comment by KaKi87** [comment]
So you wouldn't agree about making it default ?

**Comment by vladimiry** [comment]
I'm not the one who should change the default styling of the https://github.com/ProtonMail/proton-mail project. The styling is a subjective/individual thing.
