### ISSUE TITLE
Issues setting a custom tray icon

### ISSUE THREAD

**Issue by sometimes-retro** [vladimiry/ElectronMail#376]
I have several icon themes that have icons for ElectronMail, but they don't end up being applied when I change the icon theme. I have other applications running in the tray that work with these icon themes, so I know that the themes are working for other apps. 

The listed icon name is: `com.github.vladimiry.ElectronMail.svg`

Is that the correct name for custom icons for the ElectronMail app? Is there another way of changing the icon?

The theme that I'm using makes the teal color hard to see, and I'd prefer to choose a more visible color/style.

**OS**: Ubuntu Linux 20.04.2 LTS
**Desktop**: XFCE 4.14
**ElectronMail**: 4.10.1
**Installation Source**: Ubuntu repositories

**Comment by vladimiry** [comment]
The app renders the tray icon programmatically so there is no easy way to override it but it general possible. The https://github.com/vladimiry/ElectronMail/blob/master/src/assets/dist/icons/icon.png icon gets packaged into the app package during the build process.

You can customize the icon color though via the "color customization" collapsible block located in the "general" settings section.

![icon](https://user-images.githubusercontent.com/1560781/109273122-d3a59f00-7822-11eb-8189-147bcf060601.png)

**Comment by sometimes-retro** [comment]
Thank you very much, @vladimiry :)
