### ISSUE TITLE
inline image resize

### ISSUE THREAD

**Issue by edmundlaugasson** [vladimiry/ElectronMail#378]
Currently impossible to resize inline image in email. Would be appreciated...

**Comment by vladimiry** [comment]
Is it not up to @protonmail?

**Comment by edmundlaugasson** [comment]
When using Thunderbird, I can resize, because Thunderbird allows it. Still I can send email via ProtonMail Bridge over Thunderbird. So, even ProtonMail web interface doesn't allow, your program still could.

**Comment by vladimiry** [comment]
I believe the feature like this should be implemented in https://github.com/ProtonMail/proton-mail.
