### ISSUE TITLE
Composer window bug (after startup of app) - missing cursor incorrect input recognition

### ISSUE THREAD

**Issue by itisafrickinhighlander** [vladimiry/ElectronMail#383]
When I start EM and go to reply/compose an email, there is no visible cursor in the text field. When I start typing it is fine until I hit Enter, it doesn't create a new line, instead it moves the text one line down. Delete would work just fine, backspace would be deleting those new lines, formatting wouldn't work either.

My fix is to click on DB view or just the account tile in the EM sidebar, after that cursor will visually appear again and it will work as it should. Also, I think it goes away eventually, but I have no idea why or how.

Here is a short showcase of this
https://user-images.githubusercontent.com/54138438/110292602-c7250180-7fed-11eb-8e96-1a41ad106130.mp4

**Comment by vladimiry** [comment]
Does the same scenario work well in a regular browser (chrome / chromium)?

**Comment by itisafrickinhighlander** [comment]
A good thought. 
I have just tried a Chromium and this bug doesn't manifest there at all, editor works just fine. Same applies to FF, of course.
It seems like yet another Electron's specialty. Just as a note, I am using the current release v4.10.2.

**Comment by vladimiry** [comment]
Kind of OS and app package used?

**Comment by itisafrickinhighlander** [comment]
OS: Win10 and also Debian 10.
EM versions: I tried all starting from the latest down to 4.9.2, all of these showed up this bug.

It will show up right after the startup of app until you, e.g. go to PM settings and back, click on the DB view in EM or just click the tile of the account in EM's control bar.

**Comment by vladimiry** [comment]
Can confirm that it's reproducible on my side too which should help with the fixing process.

**Comment by vladimiry** [comment]
Fix has been implemented in df58f0c365614e3935e2cd52a78765a7d0796f40.

**Comment by vladimiry** [comment]
@itisafrickinhighlander can you verify issue resolving in [this](https://mega.nz/folder/hhBz3IQK#TNCm87xRIt3eWyPt1r5ZPA) build?

**Comment by itisafrickinhighlander** [comment]
Done, it is fixed in the provided build.

**Comment by vladimiry** [comment]
One originally enabled change, related to improving focusing @protonmail UI, [has been lost](https://github.com/vladimiry/ElectronMail/commit/964023ab3323bef460168ec36da5f8d22b45e6e7) in v4.12.0 release. The change is not critical but recommended for better UX. For concerned users, the fixed build uploaded [here](https://mega.nz/folder/t5w0SZ4Q#6F__sf31mrSvk4tOOTHm1A).
