### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by goldeneye66** [vladimiry/ElectronMail#388]
I am consistently getting this error message under Linux Mint 20.1.
Once in a great while, maybe once a day, the connection will work.
![Screenshot from 2021-04-01 09-20-43](https://user-images.githubusercontent.com/81758936/113300121-9cb42480-92cb-11eb-9ce0-8932cb502555.png)

**Comment by vladimiry** [comment]
Package type?

**Comment by goldeneye66** [comment]
Is this what you are looking for?
![Screenshot from 2021-04-01 09-27-07](https://user-images.githubusercontent.com/81758936/113301123-aa1dde80-92cc-11eb-927e-5a80c2f416d2.png)

**Comment by vladimiry** [comment]
No. The Linux package type you are running: snap, flatpak, deb, appimage, etc.

**Comment by goldeneye66** [comment]
Sorry, I'm a Windows convert and still learning.  If this is not what you want, what command do I run to find it?
![Screenshot from 2021-04-01 09-46-53](https://user-images.githubusercontent.com/81758936/113303697-56f95b00-92cf-11eb-93f4-290e3037c576.png)

**Comment by vladimiry** [comment]
How exactly did you install the app?

**Comment by goldeneye66** [comment]
Linux Mint has a Software Manager application. I chose it from the list and hit install.

**Comment by vladimiry** [comment]
> Linux Mint has a Software Manager application

I'm not familiar with Linux Mint but the guess is that the Software Manager scans https://flathub.org/apps/ and that's how you got the app listed for you. There were similar issues occurring when running the app in Flatpak container, #349 and #311. The resolution was in updating the Flatpak itself (upstream issue type).

Can you run `flatpak --version` console command and post the version here?

**Comment by goldeneye66** [comment]
flatpack 1.6.5

**Comment by vladimiry** [comment]
The most recent / actual `flatpak` version is 1.10.2 and I'd recommend you to find a way to update the `flatpak` package on your system (ideally to 1.10.2 or at least 1.8.4+).

@kb8cb40j1av39c02 noted before in https://github.com/vladimiry/ElectronMail/issues/349#issuecomment-764459980 that updating to 1.8.4 helped with resolving the issue.

**Comment by goldeneye66** [comment]
I ran the commands to update flatpak and it now works.  From a 35 year Windows person, I appreciate your help navigating my attempt to transition away from BigTech's hold on everyone.
Not sure the average Joe person could deal with issues like this.

**Comment by vladimiry** [comment]
Linux gives you so much freedom that sometimes things don't work well with each other. This is a price you have to pay when you get into the Linux jungle. There is a joke, you know, from the old days though: you can configure everything on Linux ... and you will have to configure everything.
