### ISSUE TITLE
Firejail sandboxing broke (`GLIBC_2.25' not found)

### ISSUE THREAD

**Issue by bruceleerabbit** [vladimiry/ElectronMail#389]
After an upgrade from 3.8 to 4.11, firejail no longer works.  This is the terminal output:
```
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /opt/ElectronMail/resources/app.asar.unpacked/node_modules/sodium-native/build/Release/libsodium.so.23)                                                                                             
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at load (/opt/ElectronMail/resources/app.asar/node_modules/node-gyp-build/index.js:21:10)
    at Object.<anonymous> (/opt/ElectronMail/resources/app.asar/node_modules/sodium-native/index.js:1:39)
```
The command I'm running is:
```
    firejail --name=electronmail\
             --env=ELECTRON_MAIL_USER_DATA_DIR="$dir_conf"\
             --env=ELECTRON_ENABLE_STACK_DUMPING=true --env=ELECTRON_ENABLE_LOGGING=true\
             --noblacklist="$dir_conf" --whitelist="$dir_conf"\
             --output="${logfile}"\
             /opt/ElectronMail/electron-mail --no-sandbox --host-resolver-rules='MAP * ~NOTFOUND , EXCLUDE 127.0.0.1'
```
I've verified that the `/lib/x86_64-linux-gnu/libc.so.6` file is present, and firejail grants read-only access to `/lib/` by default.

I also tried version 4.5 to get an idea of when this started.  Version 4.5 gives the same error, except the error output is in a GUI window instead of the terminal.  Same for 4.4.1 & 4.4.2.  The versions that work: 4.2.0, 4.3.0 & 4.4.0.

Note that firejail broke before but apparently that was a different issue:
https://github.com/vladimiry/ElectronMail/issues/168

**Comment by vladimiry** [comment]
The released Linux packages gets assembled on Ubuntu 20.04.2 LTS with help of GitHub Actions CI. The package assembling process includes native dependencies compiling stage (the `sodium-native` is one of them, it depends on [libsodium](https://github.com/jedisct1/libsodium)).

What I guess might help:
- Assembling own installation package from the source code.
- Making sure you have the glibc package 2.25+ version installed on your system. Run something like `lsof -p $$ | grep libc | awk ' { print $NF" --version"; } ' | sh` to see the current version.
- Downgrading the system/glibc version on GitHub Actions CI system which prepares the released installation packages. This is not planned to happen.

**Comment by vladimiry** [comment]
> Downgrading the system/glibc version on GitHub Actions CI system which prepares the released installation packages. This is not planned to happen.

If you are ready to test it, I'm ok downgrading ubuntu-20.04 on GitHub Actions CI system down to ubuntu-16.04 or ubuntu-18.04 and we see what happens.

**Comment by bruceleerabbit** [comment]
Thanks for the quick response.
```
$ lsof -p $$ | grep libc | awk ' { print $NF" --version"; } ' | sh
GNU C Library (Debian GLIBC 2.24-11+deb9u4) stable release version 2.24, by Roland McGrath et al.
```
I will be forced to upgrade to debian stable this year, so perhaps I should stick with 4.4.0 until then if this is just a matter of me being out of date.

BTW, have you considered getting the app into the official Debian repos?  That not only would have prevented this, but Debian official packages all conform to a quality standard that earns the project some extra recognition.  "aptitude search electronmail" would show your app, and thus Electronmail would appear on the radar for the users who are only willing to trust official packages.

**Comment by vladimiry** [comment]
> BTW, have you considered getting the app into the official Debian repos?

The related issue was placed before and closed with won't fix status since I'm not ready to maintain such kind of package repository.

> and thus Electronmail would appear on the radar for the users who are only willing to trust official packages.

In terms of this project, trusting official packages means only trusting packages published on https://github.com/vladimiry/ElectronMail/releases plus some repos listed in readme. As far as I know, some Linux distros tend to cut of the Electron part/bundle from the Electron-based apps and make them/the-asar-files use a single Electron package installed on the system. I think you understand that you can't expect the original level of stability from that kind of "patched" apps.

> I will be forced to upgrade to debian stable this year, so perhaps I should stick with 4.4.0 until then if this is just a matter of me being out of date.

You can also compile from sources (including the option of building on github actions ci instead of local build but then you will need to downgrade ubuntu-20.04 specified in https://github.com/vladimiry/ElectronMail/blob/master/.github/workflows/main.yml). Another option is the flatpak package if its sanboxing is sufficient for you needs.

**Comment by vladimiry** [comment]
> but then you will need to downgrade ubuntu-20.04 specified in .github/workflows/main.yml

Downgrading to `ubuntu-16.04` should happen which will also involve a need to tweak some other things, like adjusting a list of installed system packages, replacing `secret-tool` use with `python-gnomekeyring`, etc.

GitHub Actions CI `ubuntu-16.04` image:
> GNU C Library (Ubuntu GLIBC 2.23-0ubuntu11.2) stable release version 2.23, by Roland McGrath et al.

GitHub Actions CI `ubuntu-18.04` image:
> GNU C Library (Ubuntu GLIBC 2.27-3ubuntu1.4) stable release version 2.27.

**Comment by vladimiry** [comment]
> Downgrading to ubuntu-16.04 image should happen ...

Going to give it a try.

**Comment by vladimiry** [comment]
@bruceleerabbit can you test the build uploaded here https://mega.nz/folder/chJhBQhQ#Q0K6ZdbFN-3CsenX9rG4qA?

<details><summary>There is no more 2.25 glibc version in the list for this build so I hope things get better.</summary>

![diff](https://user-images.githubusercontent.com/1560781/113365129-f9f8b600-935d-11eb-9570-37ade1f291f2.png)

Used command: `for i in $( find /opt/ElectronMail/resources/app.asar.unpacked/node_modules -type f \( -name "*.so*" -o -name "*.node" \) ) ; do echo "$i"; objdump -T "$i" | grep GLIBC_ | sed 's/.*GLIBC_\([.0-9]*\).*/\1/g' | sort -u ; done`

</details>

**Comment by bruceleerabbit** [comment]
> @bruceleerabbit can you test the build uploaded here https://mega.nz/folder/chJhBQhQ#Q0K6ZdbFN-3CsenX9rG4qA?

that works.  Thanks!

**Comment by vladimiry** [comment]
Thanks for verifying the fix. I will include the 3d56369d53c634bd0380c26b15be084083807696 change to the next release then.
