### ISSUE TITLE
Cant Login - Error

### ISSUE THREAD

**Issue by Goneque** [vladimiry/ElectronMail#390]
Ive used the app a few times then these error messages at log-in attempt.
Can this be repaired by someone with limited experience and/or what are the specific details to a safe uninstall?

EACCES: permission denied, open '/home/dogagentc/snap/electron-mail/34/.config/electron-mail/config.json'
and...
Unhandled Error
RuntimeError: abort(Error: EACCES: permission denied, open '/home/dogagentc/snap/electron-mail/34/.config/electron-mail/config.json'). Build with -s ASSERTIONS=1 for more info.
    at process.C (/snap/electron-mail/34/resources/app.asar/node_modules/quickjs-emscripten/dist/quickjs-emscripten-module.js:159:55)
    at processEmit [as emit] (/snap/electron-mail/34/resources/app.asar/node_modules/signal-exit/index.js:161:32)

**Comment by vladimiry** [comment]
I don't use Snap stuff so can't advice on my own experience nor do I have a strong guess as to why the issue occurs.

Some things I would try if I were you (starting from the top, stop executing the steps if just performed bullet helped):
- Make sure you run the latest app version.
- Execute the following commands in console (applying the permission attributes from settings.bin to config.json):
  - `chown --reference=/home/dogagentc/snap/electron-mail/34/.config/electron-mail/settings.bin /home/dogagentc/snap/electron-mail/34/.config/electron-mail/config.json`
  - `chmod --reference=/home/dogagentc/snap/electron-mail/34/.config/electron-mail/settings.bin /home/dogagentc/snap/electron-mail/34/.config/electron-mail/config.json`
- Execute the following commands in console:
  - `chown $(whoami) /home/dogagentc/snap/electron-mail/34/.config/electron-mail/config.json`
  - `chmod 644 /home/dogagentc/snap/electron-mail/34/.config/electron-mail/config.json`
- Remove the `/home/dogagentc/snap/electron-mail/34/.config/electron-mail/config.json` file in file manager or just run `rm /home/dogagentc/snap/electron-mail/34/.config/electron-mail/config.json` console command (this file is not very important for the app and will be re-created by the app on start).
- Backup the `/home/dogagentc/snap/electron-mail/34/.config/electron-mail/` folder. Then remove the app and make sure that the `/home/dogagentc/snap/electron-mail/34/.config/electron-mail/` folder also removed. Then install the app again. Keep in mind that all the locally saved app data will be lost (you made a backup though). So fresh/cold start happens, you will have to add mail accounts to the app, etc.

**Comment by Goneque** [comment]
Thank you for the quick response.
Your instructions sound very thorough.
Will try and let you know results.

Farren

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Goneque** [comment]
Hi thanks for the quick response
Looks very thorough
I'll try it today

Farren

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Goneque** [comment]
Sadly nothing happened
The commands have no reaction
I seem to miss some instructions

Regards,
Farren

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by vladimiry** [comment]
Closing the issue as a stale one. The suggested workaround is to use another package type, like https://flathub.org/apps/details/com.github.vladimiry.ElectronMail, AppImage, etc.
