### ISSUE TITLE
Only able to use protonmail in electronmail client, no option for tutanota

### ISSUE THREAD

**Issue by y23bv0** [vladimiry/ElectronMail#392]
When I try to add a new account, there's not option for tutanota

Screenshots:

![e1](https://user-images.githubusercontent.com/45113008/114428902-c5210600-9b8a-11eb-8c4f-d7e42d4eeae0.PNG)
![e2](https://user-images.githubusercontent.com/45113008/114428906-c6523300-9b8a-11eb-8326-0385179cbfb0.PNG)

**Comment by vladimiry** [comment]
Tutanota support dropped since https://github.com/vladimiry/ElectronMail/releases/tag/v4.0.0.
