### ISSUE TITLE
Cannot Login

### ISSUE THREAD

**Issue by RiBXX** [vladimiry/ElectronMail#393]
Just updated the client and every time I try to get past the lock screen it gives me this error:

"Cannot convert undefined or null to object"

Please advise, thank you.

**Comment by vladimiry** [comment]
- Can you post here or send privately to the email specified in the [package.json](https://github.com/vladimiry/ElectronMail/blob/master/package.json#L5) the log lines related to this error? The `log.log` file located in the app [settings fodler](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg).
- What is the way you installed the app (which package type/repository used)?
- Is reverting to previous app version helpful?

**Comment by vladimiry** [comment]
Closing the issue as inactive.
