### ISSUE TITLE
Can no longer connect to TOR

### ISSUE THREAD

**Issue by lucknaumann** [vladimiry/ElectronMail#395]
Hi, I hope you are well.
I just updated to EM v4.12.1 and can no longer connect to ProtonMail via TOR. Granted, I haven't updated the EM app since v4.10.2, as I haven't used it again until now. It worked before updating the app, and I can log in through the TOR browser. Is there something new I need to do?
I have two accounts I use with PM, the other one I log in with the regular website, and that works fine in EM. I'm on Windows 10, 20H2.

**Comment by vladimiry** [comment]
Nothing has changed regarding TOR use. See https://github.com/vladimiry/ElectronMail/issues/113#issuecomment-529130116.

**Comment by lucknaumann** [comment]
Thanks for your response. I have seen that comment, which is how I set it up before. Since I haven't changed anything, I don't know why it isn't working now. Is there a debugging log I could post for you?

**Comment by vladimiry** [comment]
There were no TOR related changes in the app aside from the @electron / @chromium update. I've just tried TOR use on Linux and it works for me with the app recent release. It's unlikely but maybe @electron has broken proxy rules applying on Windows.

> can no longer connect to ProtonMail via TOR

What does the problem look like? You submit the password login form and get network connection error message?

**Comment by lucknaumann** [comment]
Yeah. At first, I had the persistent log-in enabled and got a message saying it couldn't connect to the network and reload the page. When I clicked on reload, it just gave me the same error message. I thought maybe it was some sort of cache error, so I disabled the persistent log-in, and now it won't log in.

**Comment by vladimiry** [comment]
I still tend to think it's the network/TOR setup issue. Maybe even at the @protonmail's side since I remember there were cases when @protonmail didn't allow to login via TOR saying that there are too many login attempts or something like that.

If you want to try downgrading, I'd first backup the [settings folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg) just in case (whole folder or just files listed in https://github.com/vladimiry/ElectronMail/blob/master/README.md#dataconfig-files-created-and-used-by-the-app).

**Comment by vladimiry** [comment]
> I still tend to think it's the network/TOR setup issue at your side.

To test the TOR setup you can  map a regular browser like chrome/firefox to socks5://localhost:9050 and see if the https://protonirockerxow.onion/ page gets loaded.

**Comment by lucknaumann** [comment]
> > I still tend to think it's the network/TOR setup issue at your side.
> 
> To test the TOR setup you can map a regular browser like chrome/firefox to socks5://localhost:9050 and see if the https://protonirockerxow.onion/ page gets loaded.

OK. I'll try that and report back. 

Otherwise, I'm not sure what the network setup on my side would be different from what it was before, since nothing changed between updating EM versions. PM is allowing me to log in via the TOR browser through their onion site, so I don't think they're blocking my log-in attempts. 

I will try the mapping now.

**Comment by lucknaumann** [comment]
I don't know if I did the mapping correctly or not, but it didn't work. I used Firefox since it allows using a proxy only for that browser. I looked into it a bit but am still unsure if I needed to do something else to get the proxy working with Firefox. I also don't know what network settings could have changed since Feb. to block another app from using Tor.

**Comment by vladimiry** [comment]
To be honest I don't know all the ways you can expose Tor to socks5://localhost:9050 on Windows since I run Linux only. If you look into https://github.com/vladimiry/ElectronMail/issues/113#issuecomment-529130116 I didn't write that you need to start Tor Browser but `tor.exe` which by default exposes the Tor to socks5://localhost:9050 (at least at the time the comment was written the `tor.exe` acted this way).

**Comment by lucknaumann** [comment]
Thanks for your response. I figured you might not know some things about Windows and its network (and Tor), which is fine. I use it and don't know many things about it. 😆 Thanks for the info about running the `chrome.exe` command. That's interesting. 

Yeah, I noticed that your post mentions `tor.exe`. However, running it in the console results in no output, and running it with `start tor.exe` just opens another console window with `tor.exe` as the title. Unless I did something wrong (likely). What I had read elsewhere said to have the actual browser running. That's because it launches a background process, probably the `tor.exe`, that helps other apps connect to the onion network. That might be old information, though, and may no longer work that way. It seems there's something more complex that needs to happen. Regardless, I solved the problem.

I remembered something about programs and Windows installs: sometimes the previous version needs to be removed before installing an upgrade, and sometimes an install doesn't go well. I think that's what happened. That something didn't go right with the upgrade process for whatever reason (it happens), and this affected the connection to Tor. I uninstalled EM but didn't downgrade. Instead, I reinstalled the current version, copied over the files you pointed me to in your previous comment and viola! It works fine now. _If only I had done that, to begin with!_

**Comment by lucknaumann** [comment]
I don't recall if the EM installer removes the previous version of the program first, but if not, it would be a good idea for it to remove any files having to do with the program itself while leaving all the settings files. Many Windows installers do this, with a message informing the user about it. Usually, something along the lines of: "This will uninstall the previous version of the program but leave all your settings in place. Proceed? (Yes/Cancel buttons)." Or you could tell Windows users to manually backup the settings files and uninstall the prior version before installing the new one. Just a suggestion to avoid any future such issues.

Anyway, thanks again for your help and quick responses! 😄

**Comment by vladimiry** [comment]
I'm glad you didn't give up fighting the issue 😄 Regarding tweaking the windows installer, this is not planned fro the near future.

**Comment by lucknaumann** [comment]
> I'm glad you didn't give up fighting the issue. Regarding tweaking the windows installer, this is not planned fro the near future.

I understand. If you decide to do that later on and need an example, the [installer](https://www.qbittorrent.org/download.php) for [qBittorrent](https://github.com/qbittorrent/qBittorrent) does that. Thanks.

**Comment by vladimiry** [comment]
The thing is that aside from other reasons, at least on linux and probably on macos too removing user's data on app uninstalling is not practiced. I normally prefer the app demonstrates similar behavior on all the platforms. But tweaking the win/nsis installer is technically possible (there is already [one necessarily tweak enabled](https://github.com/vladimiry/ElectronMail/search?l=nsis)).

**Comment by lucknaumann** [comment]
I applaud and appreciate your versatile option, even though I'm not a dev and don't understand the `--js-flags="--max-old-space-size=6144"` part, but I likely don't need to. 😄 

I understand not wanting to tweak the Windows installer, and I'm glad you support multiple platforms. That's why I also suggested letting Windows users know that they should back up the settings files, then uninstall before installing the newer version. Or add it to the FAQ or README as a Windows troubleshooting step or something similar.

My main objective is to let other Windows users know that as a step to prevent potential issues, or if they are having an issue, this should be a first step in solving it. Some Windows users do this because... Windows OS, but as I had forgotten about doing this, it could save both you and them time. And speaking of Windows OS, it is sadly not as well programed as Linux and probably Mac, since both of those have Unix as a base. And we all know that Unix is far superior. (Well, Linux is a derivative, but why split hairs?) 😀

**Comment by vladimiry** [comment]
> add it to the FAQ

The point has been listed in the https://github.com/vladimiry/ElectronMail/wiki/FAQ.

> don't understand the --js-flags="--max-old-space-size=6144" part, but I likely don't need to. 

It just lets the main process of the app use more than 2GB of RAM. It's useful if the "local store" option is enabled and you got a lot of mails in the account, like 20k+. The argument helps since local database gets loaded to the memory in full.
