### ISSUE TITLE
Custom CSS Themes No Longer Work

### ISSUE THREAD

**Issue by Skaalgard** [vladimiry/ElectronMail#396]
I just noticed today that my custom CSS theme I had been using no longer works. It doesn't seem like the custom CSS field does anything anymore. Is there a workaround for this?

ElectronMail: v4.12.1
Electron: 13.0.0-beta.17
Chromium: 91.0.4448.0
Node: 14.16.0
V8: 9.1.127-electron.0

**Comment by vladimiry** [comment]
> It doesn't seem like the custom CSS field does anything anymore.

It does.

Apparently @protonmail has changes styling/CSS-selectors of their apps in some of the recent updates. So you likely need to update your theme.

**Comment by vladimiry** [comment]
Closing as invalid.
