### ISSUE TITLE
Feature : Import backed up emails

### ISSUE THREAD

**Issue by fusionneur** [vladimiry/ElectronMail#398]
This is a question and/or a feature request

1. Assuming that I have a protonmail account which I added in electronmail as offline account (local store).
2. If I switch to database view, I am able to export the emails as eml/json. Opening the eml/json, i find the emails to have the content encrypted.
3. Suppose i close my protonmail account so I loose access to my emails online, but i want to preserve a copy of all emails downloaded in eml/json formats as backup that I could view later.

How can I import and view these emails, since they are encrypted? Which key exactly is used to encrypt them, the one from electronmail app or the protonmail account one (this no?) ? Am I missing something? (new here..just installed the app)

Thank you and great job!

**Comment by vladimiry** [comment]
> i find the emails to have the content encrypted
> How can I import and view these emails, since they are encrypted?

- In EML format some data, like body and attachments (if respective toggle selected during export), is not encrypted but encoded to base64 format. This is not encryption but encoding. So it's easy to decode without any key/password (there are lot of tools/scripts for this purpose). For example, if you use Thunderbird mail client, you can use [ImportExportTools NG](https://github.com/thundernest/import-export-tools-ng) extension to import the EML files to the "local" folder or to any IMAP mail account.
- In JSON format the body content is a plain text. It has both `Body` and `EncryptedBody` fields.

**Comment by fusionneur** [comment]
Excelent! Thanks a lot for the clarifications ! My bad, they are indeed encoded in base64 in EML :)

 I gave ImportExportTools NG a try in thunderbird and works as expected using import EML files inside a newly created folder in "Local Folders".

One question though.. how can the json be used afterwards? Is it supposed to be used in other custom 3rd party apps? Which is the point of having both decrypted and encrypted data in same json file?

**Comment by fusionneur** [comment]
I like the ability to import these eml files in thunderbird, but wouldn't it be great to have the same functionality inside ElectronMail itself (similar to "local folders" in thunderbird) ? 

This way, there wouldn't be any need for extra app such as thunderbird to be able to import these eml files and have them stored locally/offline. Do you think this feature is a good idea?

**Comment by vladimiry** [comment]
JSON stuff is needed mostly for the further automatic processing by own/custom scripts or programs. Keeping both encrypted and decrypted body fields allow to preserve original response served by @protonmail API. You can see that JSON contains more data than you get in EML.

> Do you think this feature would be a good idea?

The app is not built as a general-purpose mail program so importing generic EML files (from other mail service providers) won't make much sense. It might be useful though to allow storing the @protonmail emails deleted from the server/account. The thing is that the app at the moment doesn't have the ability to store attachments (you could notice that executing export, that toggle enables "live" attachments loading) which is necessary for storing email data in full.

Closing as resolved.

**Comment by fusionneur** [comment]
Is this ability to store attachments offline added to the roadmap? If yes, which is the expected date for the release? Thanks!

**Comment by vladimiry** [comment]
> Is this ability to store attachments offline added to the roadmap?

It's not, only kept in my hidden list.
