### ISSUE TITLE
EACCES Issue does continue

### ISSUE THREAD

**Issue by cs007lj** [vladimiry/ElectronMail#400]
My snap in Ubuntu still has this issue except it happens every time that new email gets pushed to my account.

It doesn't affect the ability of the app to display the messages and the web interface still works normally but the messages get extremely annoying and fills the screen every time I come home from work, very annoying.

The version I'm using is 4.12.0 from snap.
The problem I have is that there is no repair option on the snap command.
Do I need to install the flatpak command or is there a different way to fix this issue using the snap command?
![Electron Error Issue](https://user-images.githubusercontent.com/84001676/117763884-90d84e00-b1f9-11eb-85b1-e6bc0c2982ba.jpg)

**Comment by vladimiry** [comment]
Closing as duplicated of #390 (remains unresolved).
