### ISSUE TITLE
bug: search field cannot be activated repeatedly

### ISSUE THREAD

**Issue by edmundlaugasson** [vladimiry/ElectronMail#401]
When using CTRL+F to search, the search field cannot be activated, when trying to search again by pressing CTRL+F again. Only via mouse is currently possible to activate search field again.
Using Linux version:
ElectronMail v4.12.1f4d596c
Electron: 13.0.0-beta.17
Chromium: 91.0.4448.0
Node: 14.16.0
V8: 9.1.127-electron.0

**Comment by vladimiry** [comment]
Resolved by https://github.com/vladimiry/ElectronMail/commit/34ef2f5b14b42afcb555c56128623f1cf900c1c1#diff-9d0a6259fa754f2cd2e182f7ac3e589c1c82ac98c9bd0278ff5ccb1b8f48eab1R85. Comes in next release.
