### ISSUE TITLE
How start the app maximized on Mobile/Small screens

### ISSUE THREAD

**Issue by gjyoung1974** [vladimiry/ElectronMail#402]
**How start the app maximized ?**

- I am porting the packing flow to build artifacts for ARM (Pine Phone specifically)
- The app runs fine the first time! No problems with initial account set up flow. I can log in, check email, calendar, etc.
- The second time the app launches, it launches "minimized" which is expected behavior for Desktop environments
- On mobile  would like the app  to start "Maximized" the "Toggle Window" action isn't available on my mobile environment "Phosh"

the request here is how to start the app with the window "Toggled" or Maximized if running on mobile/smaller screens.

**Comment by vladimiry** [comment]
> I am porting the packing flow to build artifacts for ARM (Pine Phone specifically)

I guess @Atrate might be interested in exploring your changes (ref: #329).

> The second time the app launches, it launches "minimized" which is expected behavior for Desktop environments

To be precise, the app starts hidden not just the second time you start it, but if the `settings.bin` file exists in the [app settings folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg). The `settings.bin` file gets created when you submit the master password setup form.

> On mobile would like the app to start "Maximized" the "Toggle Window" action isn't available on my mobile environment "Phosh"

To disable "hidden" app start, you can manually turn the `startHidden` flag to `false` in `config.json` file located in the [app settings folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg). There is a respective toggle in the app's "general" settings block.

Btw, starting the app when it's already started should activate/show the hidden app window.

You might also be interested in exploring the `hideOnClose` and `window.maximized` flags.

Besides that, in 638580813208314bc48f38712fd3e57dd38da6de I've added support for the following built-time environment variables (remove the `config.json` file before starting new app build on the device so the file gets created with new defaults):
- `BUILD_DISABLE_START_HIDDEN_FEATURE` - sets `startHidden: false` by default in `config.json` and disables the respective toggle on the app's "general" settings block.
- `BUILD_DISABLE_CLOSE_TO_TRAY_FEATURE` - sets `hideOnClose: false` by default in `config.json` and disables the respective toggle on the app's "general" settings block.
- `BUILD_START_MAXIMIZED_BY_DEFAULT` - sets `window.maximized: true` by default in `config.json` and disables the respective toggle on the app's "general" settings block.

**Comment by gjyoung1974** [comment]
Excellent info @vladimiry  Thank you kindly.
I will commit my changes for Linux > Arm > Mobile soon!

**Comment by gjyoung1974** [comment]
![electronmail4](https://user-images.githubusercontent.com/3084087/118076034-20027480-b366-11eb-8ea4-198f665fa4be.png)

**Comment by gjyoung1974** [comment]
The above guidance works perfectly as evidenced by this screenshot

**Comment by vladimiry** [comment]
@gjyoung1974 do I get it right that the issue can be closed as resolved?

**Comment by vladimiry** [comment]
Closing as resolved.
