### ISSUE TITLE
mailto links/command line interface

### ISSUE THREAD

**Issue by Jan18101997** [vladimiry/ElectronMail#404]
After installing ElectronMail and setting it as my default mail app I've noticed, that runtime arguments are not supported. Would id be possible to implement these?
Sadly I don't know anything about electron or typescript in general.
This missing feature stops me from using your app.

**Comment by vladimiry** [comment]
> mailto links
> default mail app

Related issue is #62.

> runtime arguments are not supported

What kind of runtime arguments? Noticed that #62 is unresolved so if arguments you need are mailto links related then this will be a duplicate.
