### ISSUE TITLE
Changing font

### ISSUE THREAD

**Issue by rulet** [vladimiry/ElectronMail#405]
Hello. Is it possible to change font in ElectronMail?

**Comment by rulet** [comment]
What file should I change for this? Because I have no idea.

**Comment by vladimiry** [comment]
See animated screenshot on the https://github.com/vladimiry/ElectronMail/releases/tag/v4.10.0 page.

**Comment by rulet** [comment]
Ok, thanks, what this injection will look like if to change all fonts in app(menu e.t.)?

**Comment by vladimiry** [comment]
The app enables you to be able to inject the custom CSS code on the per account basis. Providing the CSS code itself is out of its scope.

**Comment by vladimiry** [comment]
I understood well what you meant. The previous answer is correct.
