### ISSUE TITLE
Alert for a planned change in protonmail web interface.

### ISSUE THREAD

**Issue by dominix** [vladimiry/ElectronMail#410]
Hi everyone, just received today an alert saying that protonmail plan a new web interface.

"In the coming week, we will be releasing a new version of ProtonMail for web to all users."

and in case of trouble the previous interface will still be reachable at old.protonmail.com

"If you encounter issues with the new version of ProtonMail, you will still be able to access the old version at old.protonmail.com. "

**Comment by vladimiry** [comment]
> "In the coming week, we will be releasing a new version of ProtonMail for web to all users."

The named new version of ProtonMail is the web clients apps stack currently deployed on https://beta.protonmail.com/ which means you get it in the app since [v4.9.0](https://github.com/vladimiry/ElectronMail/releases/tag/v4.9.0) (released on Nov 5, 2020).

**Comment by dominix** [comment]
Thanks @vladimiry  for the precision and for the good job. Sorry for the noise.

**Comment by vladimiry** [comment]
No worries. It doesn't hurt to extra check that everything is in order.
