### ISSUE TITLE
Make 'github-og-image-readme.png' background transparent

### ISSUE THREAD

**Issue by hwittenborn** [vladimiry/ElectronMail#411]
The current logo image in the README has a white background, which makes the image not blend well when GitHub is on dark mode:

![image](https://user-images.githubusercontent.com/74838472/120868932-c9e6b280-c55a-11eb-81bf-3d855dc41660.png)

**Comment by vladimiry** [comment]
The look got worse on white theme but better on dark one. Unfortunately theme-dependent images not yet supported by github, https://github.community/t/support-theme-context-for-images-in-light-vs-dark-mode/147981/58.

**Comment by Rudxain** [comment]
Why don't we use an SVG? Maybe using the CSS `prefers-color-scheme` media query would work. Also the logo looks worse in dark theme (from an accessibility POV), the black text is barely noticeable, because there's not enough contrast
