### ISSUE TITLE
ElectronMail 4.12.2 Will not start on Windows (using latest gen Intel / Ryzen CPU)

### ISSUE THREAD

**Issue by KevC117** [vladimiry/ElectronMail#412]
Having an issue with ElectronMail v4.12.2 on Windows 10 build 19043.1052 where the application will not start.
Clicking the shortcut created by the installer or the main executable itself will result in the program running for about 2 seconds then immediately crashing. Sometimes it will come up with the master password setup screen for a second, but most of the time it comes up as a black window and force closes. This also creates a ghost icon in the taskbar that closes when moused over. Program worked fine before I upgraded my processor from a 2600x to a 5900x.

Windows Event viewer shows this:

```
Faulting application name: ElectronMail.exe, version: 4.12.2.0, time stamp: 0x605030b6
Faulting module name: ElectronMail.exe, version: 4.12.2.0, time stamp: 0x605030b6
Exception code: 0xc0000409
Fault offset: 0x0000000003b99fff
Faulting process id: 0x2760
Faulting application start time: 0x01d75d74194d8a5f
Faulting application path: C:\Users\Kev\AppData\Local\Programs\ElectronMail\ElectronMail.exe
Faulting module path: C:\Users\Kev\AppData\Local\Programs\ElectronMail\ElectronMail.exe
Report Id: 3097a123-2d00-4094-bab3-d30fe0d49261
Faulting package full name: 
Faulting package-relative application ID: 
```

Here is what I have tried to remedy the problem to no avail:

- Reinstalling the program (For single user, for all users, as admin, etc.)
- Installing an older version of the program (Previous versions of the application will not open at all and show no window.)
- Launching the program with --disable-gpu
- Increasing the memory value in the --js-flags="--max-old-space-size=12288" parameter
- Changing Windows compatibility options/dpi options (Compatibility mode, scaling, as administrator)
- Closing all running applications to check for software interference
- Clean Windows install

Launching via command prompt with --enable-logging only shows this:

```
(node:15244) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `electronmail --trace-deprecation ...` to show where the warning was created)
```

Attached is the logfile created when verbose is set in the config.json
[log.log](https://github.com/vladimiry/ElectronMail/files/6627052/log.log)

**Comment by vladimiry** [comment]
Thanks for the detailed report.

The recent https://github.com/electron/electron/releases/tag/v13.1.1 release fixed crashing on latest gen Intel and Ryzen processors. This is likely your case. The v4.12.2 app comes with @electron 13.0.1 (older/lower than v13.1.1).

I think I have saved somewhere the app packages assembled on @electron 13.1.1+. Will share if so for you to test it.

**Comment by vladimiry** [comment]
The most recent v4.12.3 WIP build assembled from the master branch is uploaded [here](https://mega.nz/folder/coxEVDRJ#Ym_15bI-Rxnh7dEbARf4Pg). This is a WIP/unreleased build, so I don't recommend using it on daily basis but I think it's going to work well. Changes:
- Update @ProtonMail web clients stack (update to [v4 stable](https://protonmail.com/blog/new-protonmail-announcement/) @protonmail clients)
- Update @electron, 13.0.1 => 13.1.1 (so it should come with that ryzen fix).

**Comment by KevC117** [comment]
Thank you for the test build. I can confirm that this build runs properly!

**Comment by vladimiry** [comment]
Closing the issues as resolved. No code change required since @electron update is already in the `master` branch. So it's a matter of publishing a new release. Thanks for the thorough report.
