### ISSUE TITLE
TOR?

### ISSUE THREAD

**Issue by Stetsed** [vladimiry/ElectronMail#414]
Hey, so how do you use TOR on linux with electronmail I can't see to find out how to do it? And are you planning to add the v3 adress as I currently only see v2.

**Comment by Stetsed** [comment]
Edit: I found the v3 onion adress I just had to update

**Comment by Stetsed** [comment]
Edit 2: So I can switch to it, but it doesn't let me log in it just doesn't do anything.

**Comment by Stetsed** [comment]
Hello, you say "setting up Tor on this adress is on your" could you be so kind to explain how as I simply do not have a clue on how to do this.

**Comment by vladimiry** [comment]
Look up things on internet using "how to install Tor on Linux".

**Comment by Stetsed** [comment]
Yep sorry i'm an idiot. All I did was go to arch wiki(like I should have gone first) and bloody first thing is that. Sorry for bothering you mate.
