### ISSUE TITLE
macOS Menubar icon is fuzzy

### ISSUE THREAD

**Issue by t-anon** [vladimiry/ElectronMail#415]
<img width="307" alt="Screen Shot 2021-06-22 at 11 09 47 PM" src="https://user-images.githubusercontent.com/82717986/123029424-192c4000-d3af-11eb-9ec9-33fbb5f1dde8.png">

Every other program on my Mac has a nice, crisp menubar icon, but Electron Mail looks small and fuzzy in comparison.

**Comment by vladimiry** [comment]
Duplicated of #199.
