### ISSUE TITLE
Unhandled error when starting up

### ISSUE THREAD

**Issue by myangelaku** [vladimiry/ElectronMail#418]
![ElectronMail_IaObYK7GhZ](https://user-images.githubusercontent.com/28674643/125169451-7d6e4280-e1aa-11eb-84b0-1846731672d8.png)

```
Unhandled Error
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ReadStream.<anonymous> (C:/Program Files/ElectronMail/resources/app.asar/app/electron-main.js:79025:31)
```

**Comment by vladimiry** [comment]
Looks like some data files got corrupted. Normally data files corruption could happen in the case of abnormal program exit (power outage, forced program exit, etc). But we have the atomic write in a place that should work around the abnormal program exit cases so things look fishy.

If you run the recent/v4.12.4 release, then the error you posted says to me that this particular case is linked to the `database.bin` or `database-session.bin` file corruption. Atomic write for these files enabled with help of the `fs-write-stream-atomic` module so this module is the main suspect at the moment.

Steps to work around the issue:
- Open the [app data/settings folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg).
- Close the app.
- Remove/rename/backup the `database-session.bin` file and start the app. If no error occurs then you are good to go. In this case, the app will only re-download the emails data of your last app starting session (part of the [local store](https://github.com/vladimiry/ElectronMail/wiki/FAQ) feature).
- If error is still there, remove/rename/backup both `database-session.bin` and `database.bin` files. So the app will start full bootstrap fetch (part of the [local store](https://github.com/vladimiry/ElectronMail/wiki/FAQ) feature).

**Comment by myangelaku** [comment]
>     * Remove/rename/backup the `database-session.bin` file and start the app. If no error occurs then you are good to go. In this case, the app will only re-download the emails data of your last app starting session (part of the [local store](https://github.com/vladimiry/ElectronMail/wiki/FAQ) feature).
This made it work. Thanks!
