### ISSUE TITLE
cmd-q for Quit no longer active

### ISSUE THREAD

**Issue by ylluminate** [vladimiry/ElectronMail#430]
On macOS builds it appears we can no longer use command-q to quit the application.

**Comment by vladimiry** [comment]
I won't be able to look into the issue anytime soon as I don't get along with the macOS system.

The related code has not been changed for a long time, so the issue appears to be caused by update of the macOS system or @electron / @chromium.

**Comment by ELLIOTTCABLE** [comment]
I'm also observing this behaviour; other Electron apps still ⌘Q just fine.

For comparison:

<img width="276" alt="Screen Shot 2021-09-07 at 18 05 36" src="https://user-images.githubusercontent.com/200/132421318-20efcf04-2d7e-4725-bfb8-8b237542ad4a.png"><img width="228" alt="Screen Shot 2021-09-07 at 18 05 55" src="https://user-images.githubusercontent.com/200/132421321-fa5ff594-871b-40c2-a3af-43d233b70efa.png">

(I opted not to report it separately at the moment, as it'll need a dedicated macOS-contributor to keep stuff like this operating — but `⌘,` should open the settings-window, like it does for every other application on macOS! It's not super-crucial, though.)

**Comment by vladimiry** [comment]
Moved to #499.
