### ISSUE TITLE
Program crashes when sending email with attachment

### ISSUE THREAD

**Issue by Carlocarpintieri** [vladimiry/ElectronMail#434]
Hello Vladimir,
First of all thank you for the amazing software. i Just downloaded version 4.12.6 and when i try adding an attachment to a draft email the whole program closes without any warning or popup.

**Comment by vladimiry** [comment]
Thanks for the report. The issue has been confirmed now. Looking for the workaround (like downgrading @electron / [proton web client](https://github.com/ProtonMail/WebClients)).

**Comment by vladimiry** [comment]
> Looking for the workaround (like downgrading @electron / proton web client).

Downgrading @electron resolves the issue, so going to trigger new build/release.

**Comment by Carlocarpintieri** [comment]
Perfect thank you vladimir!

**Comment by vladimiry** [comment]
@Carlocarpintierim can you verify the build uploaded [here](https://mega.nz/folder/5khyABpA#I94gLa_J-Tg3jvQTvidicg)?

**Comment by vladimiry** [comment]
The build shared in the previous message has been tested at my side as not causing crashes when the attachment gets added. So I think it's ok to release it.

**Comment by vladimiry** [comment]
@Carlocarpintieri can you name the system you were using (Win/Linux/macOS and version/kernel)? This might be useful for hunting down the issue cause in @electron project.
