### ISSUE TITLE
electronmail started asking a master password?

### ISSUE THREAD

**Issue by tugrulpa** [vladimiry/ElectronMail#441]
I have not used electronmail app for maybe 3-4 months. suddenly it is asking for a master password. I dont know the master password and I dont remember ever setting one. Please help?
I am using current version. 
Thanks for the great app . 
![Capture](https://user-images.githubusercontent.com/71870788/133586028-cb63ed49-1353-43ed-a18b-bd926e3c04fe.JPG)

**Comment by vladimiry** [comment]
If the app was not asking a master password but then started doing that then the saved in your system's keychain password got removed. There is no way to recover the master password.

**Comment by tugrulpa** [comment]
ok, I tried my all regular passwords and one worked. Thanks. I must have forgotten I set up a password... 
    On Thursday, September 16, 2021, 12:23:46 PM GMT+3, Vladimir Yakovlev ***@***.***> wrote:  
 
 


If the app was not asking a master password but then started doing that then the saved in your system's keychain password got removed. There is no way to recover the master password.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by trulyegg** [comment]
Hi Vladimir,

I lost my master password so do you mind explaining some of the ways around it?

> If the app was not asking a master password but then started doing that then the saved in your system's keychain password got removed (there are many ways to remove it). There is no way to recover the master password.

**Comment by vladimiry** [comment]
> I lost my master password so do you mind explaining some of the ways around it?

The master password is not recoverable.

**Comment by MasterGroosha** [comment]
How can I force again Electronmail to ask for master password? 
For now I see "enter master password" window, but then it says "loading local store" and I get to my mail online view. So basically this layer of defence is skipped.
