### ISSUE TITLE
Feature: Option to open links in built-in browser or system default browser

### ISSUE THREAD

**Issue by mizzunet** [vladimiry/ElectronMail#450]
Opening links feels sluggish, buggy. That is, once link is clicked, it takes few moments to open on browser. Sometimes they do not just open so I would feel clicking more times which may open multiple tabs of single link.

So I would love to see built-in browser in ElectronMail, as it is electron and chromium, that would not be that difficult, right? And ask whether to open the link from there or system default browser.

What do you think?

Also I would like to know keyboard shortcut to show the Top Bar,  having yellow background and the Options button and all

 Thank you :)

**Comment by vladimiry** [comment]
This request gets the won't fix status here.

This is an open-source project which allows you to fork it and add the stuff you like. Like you said that would not be that difficult, so I guess it's technically possible to implement for someone besides me.

> Also I would like to know keyboard shortcut to show the Top Bar, having yellow background and the Options button and all

The hotkey is F12. If you accidentally hid it/controls-bar and want to get it back not remembering the hotkey (the hotkey option can be disabled by the way in the "General" options section) here is the way: open the settings via tray menu and disable the "Hide controls bar" toggle in the "General" options section.
