### ISSUE TITLE
Add option to close a mail without logging out

### ISSUE THREAD

**Issue by TheDcoder** [vladimiry/ElectronMail#456]
Hi, It would be nice to have a "close tab" button or option which would unload the mail. It can be done by logging out but this defeats the purpose of a persistent session :sweat_smile:

**Comment by vladimiry** [comment]
The requested feature is enabled since [v4.9.0](https://github.com/vladimiry/ElectronMail/releases/tag/v4.9.0)/Nov-2020. See the animated demo here https://github.com/vladimiry/ElectronMail/issues/316#issuecomment-687629253.

**Comment by TheDcoder** [comment]
@vladimiry My bad, I should've phrased my request correctly.

While the feature you mentioned does technically do what I want, this is not what I had in mind. Disabling an account will close the mail and the tab as well.

But what I want to do is just close the mail, i.e make it return to the original state where it waits for me to click on it before loading it. I have the "Login on account selection" option selected.

So would it be possible to "logout" without actually logging out from the ProtonMail session? (The tab would still be there, but unselected).

**Comment by vladimiry** [comment]
> I have the "Login on account selection" option selected.

This feature is put into the advanced block, so for advanced users, which I think is not a majority of the users.

The requested feature respectively would also be the feature for advanced users. Yes, this is possible to do. I imagine there would be an additional opt-in button added into the account's handle button, next to the [local store](https://github.com/vladimiry/ElectronMail/wiki/FAQ) toggle. It should be an opt-in feature/button as it's certainly not for everyone and if we enabled it by default for everyone then it would likely be annoying.

No estimation here. The workaround exists, see https://github.com/vladimiry/ElectronMail/issues/456#issuecomment-961635245.

> So would it be possible to "logout" without actually logging out from the ProtonMail session? (The tab would still be there, but unselected).

To be precise, this would not be the logout action, but more like unloading the page with a @protonmail web client (more exactly dropping the page-relative container/webview).

**Comment by TheDcoder** [comment]
I wasn't aware that it was in the advanced block, thought it would be pretty common among those who have multiple emails :smile:

> To be precise, this would not be the logout action, but more like unloading the page

Yes, exactly! That is why I tried to described it as "closing the tab" even though it's very misleading to think of it that way. Unload sounds much better.

Thanks for considering the request, maybe it can be implemented via a context menu that would open when the user right-clicks on the tab? Sounds like a feature that an advanced user would use :wink:

**Comment by vladimiry** [comment]
>  I imagine there would be an additional opt-in button added into the account's handle button, next to the local store toggle.

The alternative option is assigning the action to the `pressed Ctrl + mouse click` combination (or something similar). This would require less effort for implementation as no significant UI tweaking gets involved (no need to add buttons, deal with CSS/styling to please the 3 views mode: tabs, left column, narrow left column, etc).

**Comment by vladimiry** [comment]
> Yes, exactly! That is why I tried to described it as "closing the tab" even though it's very misleading to think of it that way. Unload sounds much better.

Btw, the alternative option to freeze the account activity is to completely disable the network connection for this account. I mean instead of unloading the page. The page would still be loaded in this case and so no related memory releasing happens. I see this option as easier in implementation but I guess there might be potential negative implications if the account gets into the offline mode (should not really be and I believe can be handled if any).

> Thanks for considering the request, maybe it can be implemented via a context menu that would open when the user right-clicks on the tab?

Sounds good as in this case we could extend the menu with new items/actions in the future if needed.

**Comment by TheDcoder** [comment]
> Btw, the alternative option to freeze the account activity is to completely disable the network connection for this account, so like "go offline" mode.

That sounds useful, but it's a different feature IMO. I was specifically looking to unload and release the memory resources.

> Sounds good as in this case we could extend the menu

Glad to hear that, that was part of my rationale too.

**Comment by vladimiry** [comment]
I seem to find a not very time-consuming implementation option - doing it via toggling the "on the fly" account's disabling state (without saving the toggle). So the feature is likely to come in the next release.

**Comment by vladimiry** [comment]
Here is how it's going to look/work:
![custom actions context menu](https://user-images.githubusercontent.com/1560781/141067739-dbf9c32f-d09d-4e54-bdbc-981fb48f25d3.gif)

**Comment by TheDcoder** [comment]
@vladimiry That looks great!

By the way, what's the "plug" icon inside the tab?

**Comment by vladimiry** [comment]
> By the way, what's the "plug" icon inside the tab?

The button for toggling between the @protonmail / live and the [local store](https://github.com/vladimiry/ElectronMail/wiki/FAQ) view mode. The blinking in the green icon indicates that the background mails syncing is in progress (downloading mails to local store, etc).

**Comment by vladimiry** [comment]
Available in v4.13.0 release.

**Comment by TheDcoder** [comment]
Thanks for adding this feature.

There is a minor bug I have noticed with the implementation though, when the custom actions are disabled, you get a "Copy email address" option inside a context menu, but with it enable this is overridden by the newer context menu, thus rendering the original menu inaccessible.

This "copy email" function could be merged into this new menu. I don't use this feature but had to report it after I noticed it during testing.

**Comment by vladimiry** [comment]
@TheDcoder I've noticed that too of course but left it that way for now. Not really a bug. The link copying feature was a generic one enabled by a global "context-menu" handler and now the menu replaces the global "context-menu". So yet if the mail link copy feature is in demand then the menu needs to be extended.

**Comment by TheDcoder** [comment]
I found a bug with the context menu, new accounts which are added in the current session don't get assigned the new menu, I see the generic global context menu for it:
![image](https://user-images.githubusercontent.com/6347576/163129368-b32e5ebc-e090-4fb5-ab7e-893c12429d6c.png)

**Comment by vladimiry** [comment]
> I found a bug with the context menu, new accounts which are added in the current session don't get assigned the new menu, I see the generic global context menu for it:

Not reproducible. Make sure you have enabled the `Enable the "custom actions" context menu on the account handle button
#456` toggle for this account. Currently, this is an opt-in per-account feature, so needs to be enabled for each account individually.

**Comment by TheDcoder** [comment]
Oops... I forgot that it is an opt-in feature. Why not make it the default though? I don't think we need the "Copy Email Address" feature now as ProtonMail natively supports it via the account details in the upper right corner. Or we could just merge it with the new custom actions menu and remove this configurability option entirely :smile:

**Comment by vladimiry** [comment]
> Why not make it the default though?
 
This is a goal but I normally prefer to test the stuff in action first. So one day it's going to become a default behavior. Before making it default, I think I will add the "edit" action there, so the menu doesn't look weird with just a single action in it.

**Comment by TheDcoder** [comment]
That sounds good to me! I use the "unload" feature regularly and I've never had any issues with it.
