### ISSUE TITLE
Problem Connection to my protonmail account

### ISSUE THREAD

**Issue by DaveWeb35** [vladimiry/ElectronMail#458]
Hello,
When I open Electronmail and that I am inquiring the password of my Protonmail account, a small window appears on ElectronMail and tells me "verification of the existence of the user. To combat unwanted messages and abuses, Please prove that you are human. " And there I have no proposed action to continue. (see screenshot).
What to do ? Thank's
![Capture 2021-11-10 à 18 18 15](https://user-images.githubusercontent.com/85820476/141161385-b7aa8838-a785-4574-89fb-f60ad2d2e617.jpg)

**Comment by vladimiry** [comment]
It looks like a duplicated of #419. To recap, this is the issue at the @protonmail side as they have not implemented the captcha backend for the API entry points other than https://mail.protonmail.com/.
