### ISSUE TITLE
v4.13.0 cannot start on Windows 7 system

### ISSUE THREAD

**Issue by ask2018** [vladimiry/ElectronMail#460]
There seems to be some compatibility regression in  version v4.13.0 for Windows
I cannot run the program at all with error:
"The procedure entry point GetHostNameW could not be located in the dynamic link library WS2_32.dll."
v4.12.9 works just fine.
OS is Win 7 SP1 x64 Enterprise with all updates, included current 11/2021 ESU updates

**Comment by ask2018** [comment]
This seems to be related to Electron 16. Look here - https://github.com/electron/electron/issues/31795

**Comment by vladimiry** [comment]
This will be a sort of won't fix at this time.

- The native modules get compiled at the GitHub Actions CI. The environment is Windows 10 10.0.17763 (Windows 2019).
- I don't test the release on Win7 before releasing and not planning to do so in the future.

> This seems to be related to Electron 16. Look here - electron/electron#31795

Thanks. I've just subscribed to the issue. The @electron downgrade, to something lower than 16.7.0, is planned at this time.

**Comment by vladimiry** [comment]
Will be sharing a build from the https://github.com/vladimiry/ElectronMail/tree/wip-issue-460 branch with downgraded @electron (not releasing but sharing for download).

**Comment by vladimiry** [comment]
If someone needs it, [here](https://mega.nz/folder/995U3YAD#8e4SVD8gVvq7_iAwoATogw) is the v14.13.0 build but with downgraded @electron 16.0.0-beta.8 => 15.3.1. The build log is [here](https://github.com/vladimiry/ElectronMail/actions/runs/1449187535).

**Comment by ask2018** [comment]
Thank you. This build with electron 15.3.1 works again fine.

**Comment by vladimiry** [comment]
@ask2018 can you test a new build uploaded [here](https://mega.nz/folder/9pIk0bba#D2yQT1g05uY79IdW06iIyg)?

**Comment by ask2018** [comment]
This one seems to be working fine.

**Comment by vladimiry** [comment]
Thanks. That build apparently includes the https://github.com/electron/electron/issues/31795 related fix (@electron v16.0.0 based build).

**Comment by ask2018** [comment]
No problem and thanks for the build. I'm always glad, when people still care about fixing stuff on Win7 :)

**Comment by ask2018** [comment]
This build seems to be working fine as well for me. And that high cpu usage issue I didn't have on my system.

**Comment by vladimiry** [comment]
v4.13.1 has just been released.
