### ISSUE TITLE
High CPU usage as of v4.13.0

### ISSUE THREAD

**Issue by TheDcoder** [vladimiry/ElectronMail#461]
Hi, I upgraded to `v4.13.0` recently and noticed that my fans were spinning even though I wasn't doing any CPU intensive tasks. Upon inspections it looks like one of the threads belonging to ElectronMail were the cause:
![image](https://user-images.githubusercontent.com/6347576/141311429-9e741ab2-92f1-4db5-bb90-0460aaa319aa.png)

Maybe it's due to some kind of continuous event loop?

OS: Arch Linux

**Comment by vladimiry** [comment]
It's a renderer/web/@chromium process but hard to say just by the screenshot which part of the functionality it's related to (@protonmail web clients or app's UI). I'm not seeing any intensive CPU load at my side (Linux).

**Comment by TheDcoder** [comment]
I think the issue started after I enabled the "custom actions" menu, but that is blind speculation on my part as it could've been a coincidence.

I can help by debugging the code on my computer. I cloned the code and installed the dependencies, but I can't find a way to run the app without building it so that I can use debugger tools to profile the code.
```
$ npm run start:electron:dev

> electron-mail@4.13.0 start:electron:dev
> electron ./app-dev/electron-main.js

Error launching app
Unable to find Electron app at ./app-dev/electron-main.js
```

Can you guide me through the debug process? I have experience with JavaScript and NodeJS, but I am not really familiar with other tools, especially TypeScript.

**Comment by vladimiry** [comment]
I thought maybe I missed properly disconnection the `MutationObserver` thing which might potentially cause the issue. But I just debugged it and can confirm it gets well disconnected ([here](https://github.com/vladimiry/ElectronMail/blob/0133434c1950832e76c7487df6ec31f09bd1a0c4/src/web/browser-window/app/_accounts/accounts.component.ts#L158) is the code line). The minor optimization I just pushed is 9af8f4c665d6eae57a4b0a2df7ef7ae73dd454b0.

> Unable to find Electron app at ./app-dev/electron-main.js

It's the same build steps as listed in readme (excluding the packaging step), but at the end run `yarn assets:dev && yarn build:dev`. Then you start it by `yarn start:electron:dev`. There is at the moment no hot reload thing for the web stuff (dropped it long time ago and didn't get back yet).

**Comment by vladimiry** [comment]
> Unable to find Electron app at ./app-dev/electron-main.js

Build command: `yarn && yarn assets:dev && yarn build:dev && yarn clean:prebuilds && npm exec --package=electron-builder -- electron-builder install-app-deps --arch=x64`

**Comment by TheDcoder** [comment]
Thanks for the instructions, but for some reason yarn is giving me errors, I ran the command from your post as well as the one from README: https://bpa.st/2QUA (output is too long so I pasted on an external site)

**Comment by vladimiry** [comment]
I missed the fact that you will need to build @protonmail clients by running `yarn assets:dev`. Better download those clients by https://github.com/vladimiry/ElectronMail/suites/4322244752/artifacts/113105326 (taken from https://github.com/vladimiry/ElectronMail/actions/runs/1447632905, ie v4.13.0 release build jobs). Then unpack the archive to some place, rename the `app => app-dev` folder, and then copy to the project folder.

**Comment by TheDcoder** [comment]
I did what you asked, and ran `yarn build:dev`, but it's still not working...

```
TheDcoder@arch /m/d/P/J/ElectronMail (master)> yarn start:electron:dev
yarn run v1.22.17
$ electron ./app-dev/electron-main.js
Error launching app
Unable to find Electron app at /mnt/data_partition/Projects/JavaScript/ElectronMail/app-dev/electron-main.js

Cannot find module '/mnt/data_partition/Projects/JavaScript/ElectronMail/app-dev/electron-main.js'
Require stack:
- /mnt/data_partition/Projects/JavaScript/ElectronMail/node_modules/electron/dist/resources/default_app.asar/main.js
- 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

TheDcoder@arch /m/d/P/J/ElectronMail (master)> ls app-dev
assets  electron-main  electron-preload  web
```

I think we can debug this more efficiently if we can communicate in real-time, do you use IRC or [Matrix](https://app.element.io/#/user/@thedcoder:matrix.org)?

**Comment by vladimiry** [comment]
My bad, I didn't update the `start:electron / start:electron:dev` npm scripts after recent `./app/electron-main.js => ./app/electron-main/index.cjs` rename. So use direct run, like `npx electron ./app-dev/electron-main/index.cjs`. Done now in 92a8834b7f5491a5bc639e96acb873eb5a09e086.

**Comment by vladimiry** [comment]
> I think we can debug this more efficiently if we can communicate in real-time, do you use IRC or Matrix?

Sorry, but I'm ready to provide live support at this time.

**Comment by TheDcoder** [comment]
Direct run worked... but unfortunately the native build artifacts were compiled with an older version of node, so I can't use them:

```
Error: The module '/mnt/data_partition/Projects/JavaScript/ElectronMail/node_modules/spellchecker/build/Release/spellchecker.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 99. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1800)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1800)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/mnt/data_partition/Projects/JavaScript/ElectronMail/node_modules/spellchecker/lib/spellchecker.js:3:16)
    at Module._compile (node:internal/modules/cjs/loader:1116:14) {
  code: 'ERR_DLOPEN_FAILED'
}
```
I will try building ProtonMail myself.

**Comment by vladimiry** [comment]
> the native build artifacts were compiled with an older version of node, so I can't use them:

A native dependencies. You need to run `yarn clean:prebuilds && npm exec --package=electron-builder -- electron-builder install-app-deps --arch=x64` (listed above).

**Comment by TheDcoder** [comment]
Oops, my bad, I missed that command. I ran it again and the app is running :+1:

I have encountered another issue though, I am getting this error while logging in;
```
Failed to resolve the "web-client" bundle location by "https://app.protonmail.ch" API entry point value
```

My fan is not spinning at full speed yet, so the resource-consuming loop isn't triggered at this point.

**Comment by vladimiry** [comment]
> Failed to resolve the "web-client" bundle location by "https://app.protonmail.ch" API entry point value

Make sure you properly unpacked the @protonmail web clients (see https://github.com/vladimiry/ElectronMail/issues/461#issuecomment-966869676). After doing that unpacking/renaming you need to run `yarn assets:dev` again so the script takes client from the ./output/git/backup and puts it into ./app-dev/webclient.

> My fan is not spinning at full speed yet, so the resource-consuming loop isn't triggered at this point.

At this point it's only the app stuff is loaded, no @protonmail involving yet.

**Comment by TheDcoder** [comment]
Awesome, thanks for assistance, I am able to run the app now.

But I couldn't reproduce the 100% CPU usage... so I tested with the pre-built release version and it still is eating up 100% of the CPU. It only happens once I load an email, so I guess it has to do something with the specific version/build of the ProtonMail stack?

@vladimiry Did you test the release build? Perhaps you might be able to reproduce it too.

**Comment by vladimiry** [comment]
> @vladimiry Did you test the release build? Perhaps you might be able to reproduce it too.

See https://github.com/vladimiry/ElectronMail/issues/461#issuecomment-966350172

> I'm not seeing any intensive CPU load at my side (Linux).

**Comment by TheDcoder** [comment]
Sorry for not explaining properly, I mean the exact binaries, I think a very specific version of ProtonMail stack might be responsible...

**Comment by prestr** [comment]
I too have high CPU usage since the update.
I'm on Windows 10 with a i7700k and ElectonMail is is using 13-17% CPU, even when its closed to the tray.

**Comment by vladimiry** [comment]
Can you test the build shared in https://github.com/vladimiry/ElectronMail/issues/460#issuecomment-966514321 (it's v4.13.0 but with downgraded @electron).

**Comment by TheDcoder** [comment]
@vladimiry This build is working without performance issues! Hardly any CPU is being used during idle now :)

**Comment by vladimiry** [comment]
Great, so you have got a workaround for now. It means that the issue lies somewhere in @electron since 16.0.0-beta.8 => 15.3.1 downgrade did the trick.

**Comment by prestr** [comment]
Just confirming that the build is working for me too on Windows 10.

**Comment by vladimiry** [comment]
So it's not system-specific as the issue reported to be happening in Linux and Windows 10.

I will consider publishing a new release with downgraded @electron if more reports get posted here. But would prefer to first make a new build based on a stable @electron v16 (it's going to be released next week).

**Comment by fusionneur** [comment]
I am experiencing high cpu usage on Windows 11 as well since last update

**Comment by vladimiry** [comment]
@fusionneur does https://github.com/vladimiry/ElectronMail/issues/461#issuecomment-967795055 help?

**Comment by fusionneur** [comment]
yes, that fix it (no more cpu usage)

![image](https://user-images.githubusercontent.com/7840350/141800293-5ad93c01-59ee-410f-8a23-35e732210bb3.png)

**Comment by vladimiry** [comment]
Ok, I wait then for @electron v16 stable release which gets published this week. Then I ask to test the new build and then I release the v15 or v16 @electron-based version depending on the testing outcome.

**Comment by vladimiry** [comment]
I'm asking everyone affected by abnormal CPU load of v4.13.0 to test the build shared in https://github.com/vladimiry/ElectronMail/issues/460#issuecomment-970189672.

**Comment by Tigrich** [comment]
WIP version 4.13.1 from mega link still causing 10% (high) cpu usage all the time on Windows 10.

**Comment by vladimiry** [comment]
Thanks. So a stable/today's @electron v16 reelase is also affected. It's at the moment unclear what exactly causes the abnormally high CPU usage between different @electron versions and I was not able to locate related open issues in https://github.com/electron/electron/issues but since a renderer process is affected the cause is likely somewhere in @chromium integrant. So it looks like we had to stick to @electron v15 for now.

**Comment by vladimiry** [comment]
Hopefully, a final testing build is uploaded [here](https://mega.nz/folder/wtJ2kDYa#K3RYZCLsR7tzbWMejukuTA). Going to publish it as v4.13.1 release when someone confirms that it doesn't cause an abnormally high CPU usage.

**Comment by Tigrich** [comment]
v4.13.1-wip-2 no more abnormal cpu usage for me on Windows 10.

**Comment by TheDcoder** [comment]
@vladimiry I tested the 2nd wip and I see constant 2-3% usage by two of the processes, maybe this is an unrelated issue but it is there. It was not present in `v4.13.0` with downgraded electron, it had 0% usage during idle.

**Comment by vladimiry** [comment]
@TheDcoder the recent build I shared (v4.13.1-wip-2) is built on @electron 15.3.2. The previously shared was 15.3.1-based and verified as not causing the issue. I'm ok to wait for one/two days before publishing the recently shared build as a release so we could get additional feedback from you or someone else.

**Comment by fusionneur** [comment]
For me v4.13.1-wip-2 (built on @electron 15.3.2) works fine - i see no idle cpu usage

**Comment by brandon-doornbos** [comment]
Can confirm that v4.13.1-wip-2 also fixes the high CPU usage for me (Arch Linux).

**Comment by vladimiry** [comment]
The v4.13.1 RC build assembled from the `master` branch is uploaded [here](https://mega.nz/folder/t84CnSSY#bl60XnwyBvSVtDT6CKTwzw). Hope someone confirms that there is no issue. It should be fine as it's based on the same @electron v15.3.2 but comes with updated @protonmail web clients.

**Comment by brandon-doornbos** [comment]
Can confirm, still fine (Arch Linux).

**Comment by vladimiry** [comment]
Any more feedbacks? I'm about to publish the recently shared build as a new release.

**Comment by vladimiry** [comment]
v4.13.1 has just been released.

**Comment by vladimiry** [comment]
Can someone who had CPU usage problem before to test [this](https://mega.nz/folder/FsRgEJjY#VTt0FZBcu08LDlzZ35lt8A) v4.13.2 release candidate build?

Changelog draft:
- Bundle [proton-vpn-settings](https://github.com/ProtonMail/WebClients/tree/main/applications/vpn-settings) web client into the app (#470).
- Update @ProtonMail web clients stack. The `session.bin` file produced or modified by the v4.13.2+ app version won't be compatible with the previous app versions.
- Upgrade @electron.

**Comment by brandon-doornbos** [comment]
Just tried the RC, and the issue has returned on my Arch Linux machine. One of the processes is again maxing out one thread. (Even after a restart)

**Comment by vladimiry** [comment]
@brandon-doornbos, thanks. That RC build is based on recently released @electron 16.0.6 which includes @chromium bump so I thought maybe the issue got fixed somewhere upstream in @chromium. So will be releasing a new version built on old/v15 @electron.

> Edit: Also happens on my Arch laptop.

Doesn't happen to me on Linux for some reason.

**Comment by vladimiry** [comment]
It's Manjaro (Arch based). I would not ask someone to test the build if I could reproduce the issue at my side.

To face the issue, do I need to perform a specific action in the app or just start it and login into the proton account?

> there are like 3 different issues about cpu usage on the electron GitHub, one on Windows 7 and 2 on MacOS from a quick glance.

Please list them here. I don't believe though that @electron contributors will start actively looking into it until the minimal repro project gets provided (which normally hard to do for such kind of issues).

Btw. Notice the below note. So if you use persistent session feature you will have to keep using that RC build or login again if you prefer downgrading to a stable release (new release is coming soon). The reason is that @protomail changed the session credentials storage format in a web clients.

> Update @ProtonMail web clients stack. The session.bin file produced or modified by the v4.13.2+ app version won't be compatible with the previous app versions.

**Comment by brandon-doornbos** [comment]
> To face the issue, do I need to perform a specific action in the app or just start it and login into the proton account?
I tried it fresh on my laptop today, and the only thing I did was install the RC pacman file and then login. This did not do anything so then I closed the app and opened it again and upon logging in, one full thread utilized. On my PC, where I already had the previous version, I just installed the RC and it immediately did it upon logging in.
> Please list them here.
https://github.com/electron/electron/issues/31916, which lists https://github.com/siyuan-note/siyuan/issues/3507, which I can't read. The other one I found was for a different version, sorry.

I just can't fathom what would cause this, as it is consistently happening to both my Arch machines but not your Arch based machine.
Is there something else that I could do to help with finding the cause? Are there debugging tools or something?

**Comment by vladimiry** [comment]
> Are there debugging tools or something?

The app's code need to be compiled in "dev" mode in order to be able to open dev tools (I think it's a web/renderer process i a problematic one). There is no documentation on this matter. It's not a complex process but time-consuming, similar to what described in https://github.com/vladimiry/ElectronMail#building-locally. Debugging of the main process can be achieved as listed in https://www.electronjs.org/docs/latest/tutorial/debugging-main-process but I tend to think that it's not the main process causes the problem.

**Comment by vladimiry** [comment]
> I think it's a web/renderer process is a problematic one

Yes it's clear that it's a renderer process since we got screenshot provided in https://github.com/vladimiry/ElectronMail/issues/461#issue-1051014796.

**Comment by vladimiry** [comment]
What about [this](https://mega.nz/folder/5g4UHDQC#TdiqCwZBfG6AXiEEFpNSZQ) build? if it runs well I will be publishing it as a new release then.

**Comment by brandon-doornbos** [comment]
Yep, no problems.

BTW, i built the thing and a dev build, so I'll see if I can find something.

**Comment by brandon-doornbos** [comment]
Hello again, well I could not find anything with just the normal debugging tools, and if I would want to debug electron itself, well, debug symbols. The whole electron repository doesn't even fit on my drive so that's a no.

Let's hope that this gets fixed accidentally someday.

**Comment by vladimiry** [comment]
What about [this](https://mega.nz/folder/MhgBEIzZ#im2Y5dbsqlFVRARY--C6wQ) build (built on recently released @electron v18.0.0-alpha.1 from [wip-electron-18](https://github.com/vladimiry/ElectronMail/tree/wip-electron-18) branch)? Still causing issue?

**Comment by brandon-doornbos** [comment]
Yep, this one has the high usage again :(.

**Comment by vladimiry** [comment]
Thanks for the test. So it's confirmed that newest @electron v18 alpha is unfortunately also affected.

**Comment by vladimiry** [comment]
@brandon-doornbos can you test [this](https://mega.nz/folder/8oBF2J6Q#3cEiFSa08X_zJE1Zcx3d5w) build? I has been assembled on recently published @electron [v19.0.0-alpha.1](https://github.com/electron/electron/releases/tag/v19.0.0-alpha.1). Anyone else is also welcome to test the build.

**Comment by brandon-doornbos** [comment]
The high usage does not seem to affect me with this build, so it may actually be fixed. We probably need other people from this thread to confirm it though. (I'm still on the same platform)

**Comment by vladimiry** [comment]
> The high usage does not seem to affect me with this build, so it may actually be fixed.

Thanks. So hopefully the next app release will be utilizing @electron v19 runtime. If possible please keep using this build (same as v4.13.6 but with bumped @electron).

**Comment by brandon-doornbos** [comment]
> If possible please keep using this build

Good call, after using the build for a while longer, the problem seems to have returned. A renderer process is again fully stressing out a single core :(.

**Comment by vladimiry** [comment]
Asking to share the CPU and GPU type used (including integrated graphics) as it might potentially help to narrow down the scope.

Also maybe someone who can reproduce the issue could try running the app with disable-like GPU/rendering-related command-line switches from the https://peter.sh/experiments/chromium-command-line-switches/ list (you would run the in-page search by the `gpu / renrerer` keywords to locate those switches).

**Comment by brandon-doornbos** [comment]
I've got an R5 1600 and an RX480, so no integrated graphics.

It consistently hits one core when I start the app, then if I switch to another account and close the app, it often fixes itself. So maybe it is related to residual processes.

The behavior is the same in X11 and Wayland.

List of command line arguments I've tried:
- `--disable-mojo-renderer`
- `--disable-gpu`
- `--disable-new-content-rendering-timeout`
- `--disable-partial-raster`
- `--disable-renderer-accessibility`
- `--disable-renderer-backgrounding`
- `--enable-nacl`
- `--enable-oop-rasterization`
- `--extension-process`
- `--font-cache-shared-handle`
- `--font-render-hinting`
- `--instant-process`
- `--renderer-cmd-prefix="valgrind --tool=callgrind"`
- `--disable-accelerated-2d-canvas`
- `--disable-frame-rate-limit`
- `--disable-gpu-compositing`
- `--disable-gpu-driver-bug-workarounds`
- `--disable-gpu-early-init`
- `--disable-gpu-memory-buffer-compositor-resources`
- `--disable-gpu-memory-buffer-video-frames`
- `--disable-gpu-process-crash-limit`
- `--disable-gpu-program-cache`
- `--disable-gpu-rasterization`
- `--disable-gpu-sandbox`
- `--disable-gpu-shader-disk-cache`
- `--disable-gpu-vsync`
- `--disable-gpu-watchdog`
- `--disable-threaded-compositing`
- `--disable-zero-copy`
- `--enable-gpu-debugging`
- `--enable-native-gpu-memory-buffers`
- `--gpu-launcher="valgrind --tool=callgrind"`
- `--ignore-gpu-blocklist`
- `--in-process-gpu`
- `--use-fake-mjpeg-decode-accelerator`

**Comment by vladimiry** [comment]
Can someone test the [electron v19 based build](https://mega.nz/folder/kpxx2baS#IRwQwqd_Ox0DMJaxfeBkOg) ([build log](https://github.com/vladimiry/ElectronMail/actions/runs/2433067562) / [changes](https://github.com/vladimiry/ElectronMail/compare/wip-electron-v19))? There is a hope that the following changes will make some effect: updated proton clients, updated electron, dropped MutationObserver use in the project.

**Comment by brandon-doornbos** [comment]
Well this may finally be it :).
It has not yet shown any signs of excessive resource usage, even after a restart and some usage.

**Comment by vladimiry** [comment]
Thanks for the feedback. If possible, please keep using this build for a while. Hopefully, the next app release switches to the recent @electron version.

**Comment by brandon-doornbos** [comment]
Still haven't found any issues, after multiple days, many restarts and actual usage.
We probably need a second person from this thread to confirm, but as far as I can see it's fixed.

Also, thank you for continually thinking of us :).

**Comment by vladimiry** [comment]
Going to publish [this](https://mega.nz/folder/4pIihRiB#T_hHGCtmDEq9mKj5AsLHFw) build later today as a release. Can someone do a final test?
