### ISSUE TITLE
Default electron tray icon on GNOME

### ISSUE THREAD

**Issue by Vallasc** [vladimiry/ElectronMail#464]
I'm on GNOME and it show the default electron tray icon instead of showing the app logo.
![Screenshot-20211118191444-456x23](https://user-images.githubusercontent.com/17199708/142473074-9593f1d9-3473-44f1-a206-7c019b0742dd.png)

**Comment by vladimiry** [comment]
The issue is not reproducible on Ubuntu 21.04 with Gnome 3.38.5.

Did you install it form https://snapcraft.io/electron-mail ?

**Comment by Vallasc** [comment]
I installed it via flathub 
Pop!_OS 21.04
GNOME 3.38.4

**Comment by vladimiry** [comment]
Can you also test the DEB package and/or https://snapcraft.io/electron-mail?

**Comment by Vallasc** [comment]
I tried the AppImage and DEB version but the issue persists

**Comment by vladimiry** [comment]
Thanks. It appears to be the Pop!_OS specific then.

**Comment by vladimiry** [comment]
Does setting the `XDG_CURRENT_DESKTOP=Unity` env variable make any difference?

**Comment by Vallasc** [comment]
No difference
![bug](https://user-images.githubusercontent.com/17199708/142693544-786b258e-c587-4375-8d4a-f5ca5ef6167a.png)

**Comment by vladimiry** [comment]
Thanks. So for now it would be up to someone who uses Pop!_OS to find the workaround.

**Comment by Vallasc** [comment]
I think the error is on tray.ts

On line 13
`const tray = new Tray(nativeImage.createEmpty());`

You should pass the image path to the Try constructor.
I tried to edit the file but I can't find the path of the icon.

**Comment by vladimiry** [comment]
@Vallasc, it's a lot more complex than you have explored so far. See https://github.com/vladimiry/ElectronMail/blob/master/src/electron-main/api/endpoints-builders/tray-icon/index.ts. The tray icon is dynamically/programmatically rendered. 
![icon](https://user-images.githubusercontent.com/1560781/61171195-e3546f00-a57c-11e9-9efe-415b7bdcdc38.gif)

**Comment by vladimiry** [comment]
flathub install.

![123](https://user-images.githubusercontent.com/1560781/142724461-fbd22444-64d1-44b0-b58a-517410c0868a.png)

**Comment by Vallasc** [comment]
I found the problem. Disabling Papirus icon pack the icon is shown in the right way.

**Comment by vladimiry** [comment]
Thanks for sharing the issue cause.

**Comment by vladimiry** [comment]
It appear that `papirus-icon-theme` does something with the app icons for some reason https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/search?q=electronmail&type=commits

**Comment by Vallasc** [comment]
I have removed all electron icons from the icon the directory and now it works as it should. Thanks.

**Comment by varlesh** [comment]
> It appears that `papirus-icon-theme` does something with the tray icons for some reason https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/search?q=electronmail&type=commits

We not doing something with the tray icons. Application use `electron` icon name instead of `electron-mail`. 
It's not our bug.
![image](https://user-images.githubusercontent.com/8083855/142748917-2fc8cc4e-1c94-4fe3-bfb7-94585f5a75f1.png)

**Comment by varlesh** [comment]
@vladimiry Вообще Papirus ничего не ломает и hardcode-tray тоже.
Ваш значок (раскрашенный в `#dfdfdf`):
![image](https://user-images.githubusercontent.com/8083855/142749337-152413ae-ad95-443b-aefb-0a84d63ad0ff.png)
Наш значок, с hardcode-tray (с дефолтным цветом `#1ba489`):
![image](https://user-images.githubusercontent.com/8083855/142749421-d1f65214-6b48-441c-84a0-bda9454ff659.png)
Проверенно в KDE. Для правильной логики программы могу просто перекрасить значок для трея в цвет `#1ba489` и всё будет работать как и задумано.

**Comment by varlesh** [comment]
Пофиксил, наш значок не ломает логику разукрашивания значка и все работает как и положено. 
По факту, наши костыли ненужны и ваше решение очень крутое. Но hardcode-tray и Papirus подгоняет размер значка и он не будет больше или меньше других в трее, ну и плюс выравнивание по пикселям, т.к. GNOME использует 16px, KDE 22px, а XFCE может само выбрать нужный размер.
![image](https://user-images.githubusercontent.com/8083855/142750091-9964e7e5-68c1-4d44-b937-bddb13fca4e5.png)

**Comment by vladimiry** [comment]
> We not doing something with the tray icons. Application use electron icon name instead of electron-mail.
It's not our bug.

Does something means exactly this, doing something. I didn't look deep into the commit. 

> Для правильной логики программы могу просто перекрасить значок для трея в цвет #1ba489 и всё будет работать как и задумано.

Yep, the #1ba489 value is [hardcoded](https://github.com/vladimiry/ElectronMail/blob/8ea1bd1cd499fe20a403e87b00d5f1548fa7d709/src/shared/constants.ts#L39) in the app as a base color of the static tray icon. So the app then could use that value as a base color for [recoloring](https://github.com/vladimiry/ElectronMail/blob/2299d9a76acc818112b98e9f9414536773e5e315/src/electron-main/api/endpoints-builders/tray-icon/lib.ts#L113) when the respective settings gets changed in the app as displayed in https://github.com/vladimiry/ElectronMail/issues/464#issuecomment-974619885.

Anyway, the outcome is that `papirus-icon-theme` got the fix so now it doesn't break the app's UX and fills the ticks of its own checklist at the same time which should be good for everyone.
