### ISSUE TITLE
Auto Update App

### ISSUE THREAD

**Issue by trymeouteh** [vladimiry/ElectronMail#465]
Please consider adding an automatic updating system within the app so the app updates itself in the background without having to download the DEB file, checking the hashsums and reinstalling the app.

**Comment by vladimiry** [comment]
The auto-update thing was here before but then got dropped. Both built-in and electron-builder based auto-update features are limited, especially on Linux (only specific package types are supported). Besides in my opinion the auto-update feature should be rock solid but I remember there were severe issues.

The workaround for Linux is using https://flathub.org/apps/details/com.github.vladimiry.ElectronMail or https://snapcraft.io/electron-mail.
