### ISSUE TITLE
Spell-checking - Automatic language switching + option to manually define languages for spell-checking

### ISSUE THREAD

**Issue by itisafrickinhighlander** [vladimiry/ElectronMail#469]
I write emails in multiple languages and I always use spell-checking, but because of a lack of automatic language switching something native to Chromium-based browsers, but I am not sure how and if it integrated in Electron. They even work in this magical way that they can do like multi-lingual spell-checking at once, e.g. I am writing in English, and I include a quote in French. In those browsers it would underline only a typo, regardless of language. 
I have to always switch it manually via RMB > Languages, otherwise everything is underlined and it is little distracting. But then again, Mozilla has a ticket for this open for well over [21 years](https://bugzilla.mozilla.org/show_bug.cgi?id=69687) and still counting. We don't exist for them.

Also, it would be sweet to have a language setting in ElectronMail to be able to define languages to be used. Currently, in my instance of EM, I see four English locales (en_CA, en_LR, en_PH, en_US) and French and German (it looks like it is using languages defined in OS (Windows 10). 

What I personally think would be the perfect solution is something like it is done in Chromium (screenshot took from Brave, however)

![image](https://user-images.githubusercontent.com/54138438/144510551-560e42ee-10cb-4037-9237-57ddf4c8cf58.png)

I am not sure if this is possible, viable or worth the time, but hopefully there will be others finding this useful.

**Comment by vladimiry** [comment]
Switching to Chromium-based spellchecker is going to happen one day (@electron supports it since v8). See #216 for details.

**Comment by vladimiry** [comment]
> Switching to Chromium-based spellchecker is going to happen one day

It's coming in the next release. So things like using multiple languages will be possible.
