### ISSUE TITLE
Can't enter in ProtonVPN

### ISSUE THREAD

**Issue by shdwchn10** [vladimiry/ElectronMail#470]
![Screenshot from 2021-12-05 12-46-57](https://user-images.githubusercontent.com/79763381/144741563-73b57a41-807e-4b92-9cda-57e3a145730f.png)

Alter clicking on 'ProtonVPN' button popover menu closes and nothing happens

**Comment by shdwchn10** [comment]
Proton Subscription: Visionary
ElectronMail version: v4.13.1 (Flatpak)
OS: Fedora Silverblue 35

**Comment by vladimiry** [comment]
It used be an external link. Currently the respective web client is not packed into the app but I think I could try to pack the https://github.com/ProtonMail/WebClients/tree/main/applications/vpn-settings one.

**Comment by vladimiry** [comment]
Resolved in the `wip` branch, so will be a part of the next release.
