### ISSUE TITLE
cannot connect anymore

### ISSUE THREAD

**Issue by abdurrais** [vladimiry/ElectronMail#474]
since updating to the latest I have awful issues and cannot seem to resolve with help online, etc. When I launch the app, it opens "setup master password" which I follow. Upon following next, it asks for login password and which is when I get the messages as attache
![Electronmail issueDec21](https://user-images.githubusercontent.com/69436930/147106324-eb381104-5c8f-4b9a-bb70-ddfc27adb5a4.jpg)
d

**Comment by vladimiry** [comment]
Such error message normally means that you are entering a wrong master password. I think I better make it less verbose (full error is written to the log file anyway).

> since updating to the latest

This implies that you were using the app before, so the master password has been setup before.

> When I launch the app, it opens "setup master password" which I follow

But then you write that you setup it again.

**Comment by abdurrais** [comment]
Thanks, I was assuming something similar and fresh reinstalled and set up master password. Now if I launch, I comes directly to login window with any messages. If I enter password, I get the following as attached
![Electronmail 2issueDec21](https://user-images.githubusercontent.com/69436930/147107959-8a20468a-9ba1-4996-b134-74f338518064.jpg)

**Comment by abdurrais** [comment]
Sorry, I meant in the above that upon launching I get clean login window without the error message. I am using macOS btw

**Comment by abdurrais** [comment]
Yes I have been using Electronmail without any issues for sometime. I updated to the latest recently

**Comment by abdurrais** [comment]
I cannot login using correct password now
![Electronmail 2issueDec21](https://user-images.githubusercontent.com/69436930/147108795-ab57badf-cdf4-41c1-b4b0-1a7c00797c72.jpg)

**Comment by vladimiry** [comment]
There is no indication that the app is broken but that you are doing something wrong.

**Comment by abdurrais** [comment]
OOKAAAY... thought developers try to help
bye
