### ISSUE TITLE
Unhide options tab

### ISSUE THREAD

**Issue by chief-1buk** [vladimiry/ElectronMail#475]
Hello,![ElectronMail-1](https://user-images.githubusercontent.com/97078818/148011042-07931600-ad5b-4412-927e-2e86b25aed38.jpg)
I am using ElectronMail (Protonmail) on macOS and "hid" the options tab at the top and now I am unable to re-enable it. Can someone advise how i can re-enable this Options tab?

Thank you,
chief-buk
ElectronMail v4.13.17170eaa
Unofficial ProtonMail Desktop App
Distributed under GPL-3.0 license.

**Comment by vladimiry** [comment]
You can reach the "general" app's settings tab via the tray menu and there you can toggle the "Hide controls bar" control (also notice F12 hotkey near to this control).

**Comment by chief-1buk** [comment]
Ok, I am unsure where the "tray menu" is located, but I used Control/F12 and the Options tab is shown again.

If possible, can you advise if there is a method to stop/disable showing the email address when hovering the mouse/pointer over a clickable link in an email message? (see attached screen shot)
![Eectron email header-R-2](https://user-images.githubusercontent.com/97078818/148044789-9a48823b-339b-4fb7-a531-0199ef288f83.jpg)

**Comment by vladimiry** [comment]
> If possible, can you advise if there is a method to stop/disable showing the email address when hovering the mouse/pointer over a clickable link in an email message?

There is no option in the app to disable this feature.

**Comment by chief-1buk** [comment]
> 

So, it's not possible by some other method?

**Comment by vladimiry** [comment]
> So, it's not possible by some other method?

It's currently possible only if you are ok to deal with changing a source code and assembling own app package.

**Comment by chief-1buk** [comment]
Ok, lets do it.

**Comment by vladimiry** [comment]
> Ok, lets do it.

This will likely take you hours since the app package assembling process includes building the https://github.com/ProtonMail/WebClients stuff.

1) See how to build the app https://github.com/vladimiry/ElectronMail#how-to-build-your-own-installation-package-from-source-code. So 2 options: via cloning the project and then building via CI system or local build. I don't provide an entry level guidance, so you will likely need some programming/technical skills.
2) If you want to completely remove links highlighting remove the following code https://github.com/vladimiry/ElectronMail/blob/83f63e0645f47baab50a2f1ea952479467b682cb/src/electron-main/web-contents.ts#L245-L270
3) If you only need to disable email links highlighting add the following code
```
            if (url && isEmailHref(url)) {
                IPC_MAIN_API_NOTIFICATION$.next(
                    IPC_MAIN_API_NOTIFICATION_ACTIONS.TargetUrl({url:""}),
                );
                return;
            }
```
after this line https://github.com/vladimiry/ElectronMail/blob/83f63e0645f47baab50a2f1ea952479467b682cb/src/electron-main/web-contents.ts#L245

**Comment by BeiBarBoy** [comment]
Sorry to reopen this, but having the same issue of being unable to show the Options bar again after hiding it under MacOS... I tried pressing F12 and Control-F12 (after enabling the standard function keys), nothing happens. How can I resolve this? It's driving me crazy as I want to change my Proton account and can't.

Thanks.

ElectronMail v5.2.0.8b54e69

**Comment by vladimiry** [comment]
@BeiBarBoy, F12 supposed to work, but I can't test it on macOS at this time.

You can also make the controls bar back by disabling the "Hide controls bar" toggle located in the app "General" settings block. How to access the "Settings" dialog having controls bar hidden - via the respective tray menu item. Finally, you can manually modify `config.json` settings file by setting `hideControls: true` value.
![Settings](https://github.com/vladimiry/ElectronMail/assets/1560781/300bf7a2-bd4a-4a2a-b7f9-82a3f72dbbd7)

**Comment by BeiBarBoy** [comment]
Am going to try again with your directions, but as I have no menu bar or side bar, I don't even see the app General settings block you mention !

Am happy to start again from 0, but I can't seem to uninstall the app completely. Some settings storage remains somewhere as, when I uninstall (using an uninstaller app) and reinstall, I return to the same settings, with the same Proton account and the same window without any menu or side bar.

**Comment by vladimiry** [comment]
> but as I have no menu bar or side bar, I don't even see the app General settings block you mention !

How to access the "Settings" dialog having controls bar hidden - via the respective tray menu item.

**Comment by BeiBarBoy** [comment]
Solved by editing config.json. Thanks for the directions and sorry for the hassle.
