### ISSUE TITLE
Build release packages for Chocolatey

### ISSUE THREAD

**Issue by RAYs3T** [vladimiry/ElectronMail#477]
As currently no (secure) auto update for windows is possible, adding support for https://chocolatey.org/ would be awesome.

### Quick information on what Chocolatey is
It's a package manager for windows. You can compare it to apt on Ubuntu.

You can basically install a package with a powershell command for example: `choco install electronmail`
And if you want to update a package you can just run `choco upgrade pkgname`.

### Benefits
* Upgrading is more secure, as choco is verifying the Hash after download.
* More comfortable (as the user has just to run a command, instead of downloading a new .exe)
* And this might even attract new users who just search in the packages of choco for something like this.

**Comment by vladimiry** [comment]
The [electronmail](https://community.chocolatey.org/packages/electronmail) name is already taken by someone and the package is not being updated. So I've pushed https://community.chocolatey.org/packages/electron-mail package which is currently being validated by the chocolatey platform. They say that validation takes 1-3 days.

**Comment by RAYs3T** [comment]
Awesome!
I'll set me a reminder and test once the package is available.

**Comment by RAYs3T** [comment]
It's still in pending review, but installing it with a specified version works so far.

**Comment by vladimiry** [comment]
> works so far

There is no fancy stuff by the way. Just a run of the "exe" package from https://github.com/vladimiry/ElectronMail/releases with `/S` flag (silent installing mode).

[tools\chocolateyinstall.ps1](https://community.chocolatey.org/packages/electron-mail#files):
```powershell
$ErrorActionPreference = 'Stop'

if ((Get-OSArchitectureWidth 32) -or $env:ChocolateyForceX86) {
  throw ("This application currently only supports 64-bit Windows systems.")
}

$packageArgs = @{
  url64         = 'https://github.com/vladimiry/ElectronMail/releases/download/v4.13.2/electron-mail-4.13.2-windows-x64-nsis-installer.exe'
  checksum64    = '5c6c6bce6967a4e43ac1ffaa5692a5cdb3b85fe5f616654b978d115147399d29'
  checksumType  = 'sha256'
  softwareName  = 'ElectronMail*'
  fileType      = 'exe'
  silentArgs    = "/S"
  validExitCodes= @(0)
  packageName   = $env:ChocolateyPackageName
}

Install-ChocolateyPackage @packageArgs
```

**Comment by vladimiry** [comment]
I just contacted the site admins via https://community.chocolatey.org/packages/electron-mail/4.13.2/ContactAdmins Hope this will speed up the approval process.

**Comment by dhbtfs** [comment]
Fair enough, didnt know it was requested before. Thanks for the update.

**Comment by vladimiry** [comment]
> I just contacted the site admins as an author of the app via https://community.chocolatey.org/packages/electron-mail/4.13.2/ContactAdmins Hope this will speed up the approval process.

Based on the received response from moderators it looks like the package is going to get a "trusted" status not earlier than after a few couples of versions get published. My understanding is that right now, without a "trusted" status, the Choco repo is sort of pointless since approving takes forever and can potentially take longer than a new/next version gets published.

**Comment by RAYs3T** [comment]
Even then I think it should be kept so that in a few version in might acquire this state as it is really useful.

**Comment by vladimiry** [comment]
It's now approved, thanks @TheCakeIsNaOH. So the issue got closed.
