### ISSUE TITLE
Mac OS icon for BigSur/Monterey

### ISSUE THREAD

**Issue by hollow-frenk** [vladimiry/ElectronMail#478]
Hello, as the current app icon has several issues, I allowed myself to create a version of the icon that follows the dictates of the new Apple design while also reworking its logo. If you like it, what would be the other files to edit?
![icon](https://user-images.githubusercontent.com/22840336/148937007-ec0033f0-f0b8-4533-9ab6-ae66cbd40eb7.png)

**Comment by vladimiry** [comment]
I'm not ok with serving different icons for different platforms. The current icon might not be ideal but I think the time to change its design has not come yet.

It's, in general, preferred to open the issue before starting developing things in order to avoid time-wasting.

**Comment by hollow-frenk** [comment]
Ok, I understand your thinking, but the current icon is pixelated...

**Comment by vladimiry** [comment]
The [source](https://github.com/vladimiry/ElectronMail/tree/master/src/assets/icon) is not pixelated but the tray icon on macOS is. This is a known issue, see https://github.com/vladimiry/ElectronMail/issues/199.

**Comment by hollow-frenk** [comment]
The problem is the resolution of the icon... 128x128 i see pixellated on iphone, Mac etc..
