### ISSUE TITLE
Add "old.protonmail.com" as an entry point?

### ISSUE THREAD

**Issue by NintendoManiac64** [vladimiry/ElectronMail#482]
Maybe this is the wrong way to go about doing it, but on horizontally-challenged displays, I find that the older v3.x interface found with "old.protonmail.com" to work better.

I don't suppose it'd be possible for ElectronMail to include it as an option?

**Comment by vladimiry** [comment]
> I don't suppose it'd be possible for ElectronMail to include it as an option?

It's technically possible but my capacity is limited so it won't' be happening.
