### ISSUE TITLE
Fedora: Conflict with Ferdi 5.7.0 when installing/upgrading

### ISSUE THREAD

**Issue by joao-milheirico** [vladimiry/ElectronMail#484]
When trying to upgrade to the latest version of ElectronMail on fedora using the rpm version I get the following error:

> Transaction Summary
> ===============================================================================================================================================================================================================================================
> Upgrade  1 Package
> 
> Total size: 113 M
> Is this ok [y/N]: y
> Downloading Packages:
> Running transaction check
> Transaction check succeeded.
> Running transaction test
> Error: Transaction test error:
>   file /usr/lib/.build-id/0d/8f310d54f5f85a7ebef67f5715336b0b842e97 from install of electron-mail-4.13.2-1.x86_64 conflicts with file from package ferdi-5.7.0-1.x86_64
>   file /usr/lib/.build-id/3b/1fb592235ccb098a49105e320ff94fc591c279 from install of electron-mail-4.13.2-1.x86_64 conflicts with file from package ferdi-5.7.0-1.x86_64
>   file /usr/lib/.build-id/4d/7f2379406b1270acac20b1ae2bb8881e7a54fc from install of electron-mail-4.13.2-1.x86_64 conflicts with file from package ferdi-5.7.0-1.x86_64
>   file /usr/lib/.build-id/81/ccb493db86a1b405e237401fa01d51085ec382 from install of electron-mail-4.13.2-1.x86_64 conflicts with file from package ferdi-5.7.0-1.x86_64
>   file /usr/lib/.build-id/89/60cbe13d23e0621e2f0950598ce5eb0453f90e from install of electron-mail-4.13.2-1.x86_64 conflicts with file from package ferdi-5.7.0-1.x86_64
>   file /usr/lib/.build-id/a0/6ec32b01ec8c89ac837dc2b978e7f63f428f51 from install of electron-mail-4.13.2-1.x86_64 conflicts with file from package ferdi-5.7.0-1.x86_64
>   file /usr/lib/.build-id/a2/af043872ddb7e21e09a175a1a7a4c4a563a7d0 from install of electron-mail-4.13.2-1.x86_64 conflicts with file from package ferdi-5.7.0-1.x86_64
>   file /usr/lib/.build-id/b1/ee1bbbdcc20737848a14af7c98b3f00803186a from install of electron-mail-4.13.2-1.x86_64 conflicts with file from package ferdi-5.7.0-1.x86_64
>   file /usr/lib/.build-id/cc/d2efa56d0c5696fb0d687a0d59aa449216aa24 from install of electron-mail-4.13.2-1.x86_64 conflicts with file from package ferdi-5.7.0-1.x86_64
>   file /usr/lib/.build-id/e1/ba4c855b085181137cb4d087fed3fed65dfb7a from install of electron-mail-4.13.2-1.x86_64 conflicts with file from package ferdi-5.7.0-1.x86_64

Any advice?

**Comment by vladimiry** [comment]
I'm not a Fedora user. Maybe try `--force` option or the Flatpak/Snap version.

**Comment by vladimiry** [comment]
Closing as a stale issue. Fedora users are welcome to assist though.
