### ISSUE TITLE
Add MPR to download list in the README

### ISSUE THREAD

**Issue by hiddeninthesand** [vladimiry/ElectronMail#489]
I maintain [the MPR package for ElectronMail,](https://mpr.makedeb.org/packages/electronmail-bin) and I think it'd be useful for any Ubuntu or Debian users.

**Comment by vladimiry** [comment]
Thanks for the contribution but I'm not yet ready to list this repo in the readme/front-page. It doesn't mean I reject the proposal.

**Comment by hiddeninthesand** [comment]
That's respectable. If you're interested in comaintainership, I can also grant you that.

**Comment by hiddeninthesand** [comment]
If you could tell me your reasoning behind not listing it, I can attempt to resolve those issues posthaste.
