### ISSUE TITLE
Verifying that you are Human

### ISSUE THREAD

**Issue by pwl256** [vladimiry/ElectronMail#492]
Using Kbuntu Linux 20.04  after logging into to ProtonMail asks to confirm I am Human but does not tell me how to do it nor show anything but a screen with 2 lines of text

**Comment by vladimiry** [comment]
Dupe of #490. See workaround in https://github.com/vladimiry/ElectronMail/issues/490#issuecomment-1045233006.

> but a screen with 2 lines of text

Can you attach a screenshot of those 2 lines of text?

**Comment by vladimiry** [comment]
Resolved in #490. New release is on its way.
