### ISSUE TITLE
URL Does Not Open In Browser

### ISSUE THREAD

**Issue by DebSec** [vladimiry/ElectronMail#493]
ElectronMail v4.13.3 on Linux Mint

Links or URL's when clicked on do not prompt to open in browser?

Not sure if this is on my end only.

**Comment by vladimiry** [comment]
What kind of URLs (a screenshot would be helpful)?

Btw, I'd suggest to review #45.

**Comment by DebSec** [comment]
ElectronMail v4.13.4 on Linux Mint.
The issue was not there on ElectronMail v4.13.2 and prior releases.
Any link or url when left clicked on has no action.
If I hover over the URL it is displayed but performs no action now.
It has always opened up the link in my browser.
Right clicking will copy the url address and I can place it in the address bar of my browser.

![Screenshot from 2022-02-21 16-16-33](https://user-images.githubusercontent.com/31349799/155033020-631d353e-4b26-4dba-a791-7309975d179d.png)

![Screenshot from 2022-02-21 16-17-03](https://user-images.githubusercontent.com/31349799/155033030-d0327ece-05e8-402c-a810-3df87a8c401b.png)

**Comment by vladimiry** [comment]
I can confirm the issue. Didn't do any debugging yet but it's clear that @protonmail has changed something in their https://github.com/ProtonMail/WebClients.

Workarounds:
- Copying the link address via context menu.
- Enabling the "Link confirmation" feature in the proton settings ("General" section). The links still get open via the confirmation dialog.

**Comment by vladimiry** [comment]
What about [this build](https://mega.nz/folder/o4gxxKIB#EkP_4lhSiSKH-xLUiqJMTg)?

**Comment by vladimiry** [comment]
The fix has been released in v4.13.5. Thanks for placing the issue with provided detailed explanation.

**Comment by DebSec** [comment]
v4.13.5 is working fine as far as the hyperlinks not working correctly.
Thank you for your time and I really appreciate your efforts.
Stay safe.
