### ISSUE TITLE
How to compose protonmail by using command line in electronmail?

### ISSUE THREAD

**Issue by goldpooh** [vladimiry/ElectronMail#496]
Hi, vladimiry!
I do like your email client so much.
I ask of you how to compose email by using command line in electronmail.
Best regards, thnx.

**Comment by vladimiry** [comment]
This is not currently supported.

**Comment by goldpooh** [comment]
I want you to add this ability as soon as possible.
Can you do it?

**Comment by goldpooh** [comment]
Hello, vladimiry! 

I am very happy to know you on this world.

I thank you for your help, But I need your important help.

Umm... I executed a following command line for ElectronMail by myself.

Command line Ex:  
open -n -a ElectronMail.app --args -compose to='******@protonmail.com',from='******@outlookmail.com',subject='news',
body='<br/>Hello. How is your work going?<br/>I have some news to share with you.<br/>I am pretty sure you will be glad for these.<br/>Please check them out.<br/>Good Luck.<br/>',attachment=' '

When I executed Up CMD line, ElectronMail was executed automatically, but in ElectronMail New Message window was not appeared.
 
This CMD line is for  Mac OS, but this CMD line was not executed for ElectronMail

If you have a good think, I hope you send me your opinion.

Thanks, dear vladimiry

**Comment by vladimiry** [comment]
@goldpooh you get banned for a while. The reason is:
- the answer was short but clear
  > This is not currently supported.
- duplicated posts.
