### ISSUE TITLE
Setting up Account - 

### ISSUE THREAD

**Issue by VicM58** [vladimiry/ElectronMail#500]
Hi I am trying to setup an account it asks for Login and then wants confirmation of being alive. Nothing is coming up to verify that, so I am unable to finish the setup.

**Comment by vladimiry** [comment]
A screenshot would be helpful (of the step where you stuck). If it's a captcha verification, then it's only available on https://mail.protonmail.com/ API entry point (see https://github.com/vladimiry/ElectronMail/issues/419).

Btw, the app is not designed for setting up the proton accounts but using already existing ones. So try the setup step in a browser.

**Comment by VicM58** [comment]
Hello,
Please see attached picture of message. I am using https//mail.protonmail.com ***@***.***) as API entry point.
I have clicked Persistent session.

Does the web browser make any difference?

Thanks Vic

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by VicM58** [comment]
Hi Just to let you know, I have an existing protonmail account. Also how to change to API entry point 419. Thanks Vic

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by vladimiry** [comment]
> Please see attached picture of message. 

There is no image in your message.

Closing the issue as invalid for now.

**Comment by vdbhb59** [comment]
See the images for my error here: https://github.com/vladimiry/ElectronMail/issues/419#issuecomment-1099395684
This is irrespective of the API entry point, and is happening for "adding" an existing account to the app.
