### ISSUE TITLE
[Feature Request] - Being able to activate services individually per account

### ISSUE THREAD

**Issue by Jvlsc** [vladimiry/ElectronMail#502]
Hello:

I was wondering if it would be possible to active services individually for every account (not only email). So, every active service would have a tab in the main toolbar and stay active all time. I think it could improve usability keeping email always active and have the other services in different tabs also ready.

Additionally, a keyboard shortcut to move quickly between tabs would be interesting. It can be achieved in different ways, but I think map tabs in order with Ctrl+1, Ctrl+2... would be great.

I hope these considerations are useful.

Kind regards.

**Comment by vladimiry** [comment]
Proton still allows login via any email identity you have in the list. So the workaround is to add to the app the same account multiple times with a different login name. But still in this case an "entry service option" would be helpful as switching to the needed service every time you start the app, like mail/drive/account/calendar/vpn, would be a headache.

**Comment by vladimiry** [comment]
This is landing in the v5.3.0 (already implemented in the `wip` branch):

- Enable support for selecting entry Proton app (#502). This makes it convenient to use several Proton services of the same account loaded in individual tabs.

  ![selecting entry Proton app](https://github.com/user-attachments/assets/c0c662bd-dc00-4ace-9673-d7bdd5000951)

  It's know that Proton allows sign-in via any email address you have in the account. Even on a free account with a single email address in the account, it's possible to use at least two logins. Which is the email address itself and the part of the email address that is placed before "@".

   So, having possibility to sign-in in the same account using different logins, you can add in the app several account records for the same account, and assign each record own Proton app to load.

  By the way, notice the `"Login Alias"` input field on the screenshot (originally introduced in [v4.0.0](https://github.com/vladimiry/ElectronMail/releases/tag/v4.0.0)). It can be used for naming the account tabs, like for example "Mail" and "Calendar".

**Comment by vladimiry** [comment]
This got released in v5.3.0. Hotkeys is something different from this issue.

**Comment by Jvlsc** [comment]
Thank you so much for your dedication and work on this app.

I've just tested this new feature, and it works great.


Kind regards
