### ISSUE TITLE
Email Body Still Looks Light Mode

### ISSUE THREAD

**Issue by romeoacevedo** [vladimiry/ElectronMail#504]
Is there a way that you guys can add an option for the users to force dark mode on the emails? Dark Reader does that in the web version. I was wondering if you guys can do a color inversion or something simple for the emails? The light mode makes my head hurt. I really like your app, but that is the only issue that is preventing me to use it. Is there a way that you can make emails like the following dark? Thanks

![Screen Shot 2022-04-16 at 7 47 41 PM](https://user-images.githubusercontent.com/103864004/163694582-d4439d35-15de-4af0-81dc-a189890365b5.png)

**Comment by vladimiry** [comment]
The need in my opinion has to be handled in https://github.com/ProtonMail/WebClients by @protonmail, so I'm adding "upstream" label here.

> Dark Reader does that in the web

It might technically be easier to integrate Dark Reader extension support in the app than building a custom CSS. Not saying yet that I'm going to do that.

By the way, the body content in the app's [local store](https://github.com/vladimiry/ElectronMail/wiki/FAQ) mode is dark. But content in this mode always gets converted to raw text, so enabling complete dark mode was easy in this case.

![123](https://user-images.githubusercontent.com/1560781/163702786-1a43e8c5-5adf-4ce5-b9fb-13734df710ab.png)

**Comment by romeoacevedo** [comment]
> It might technically be easier to integrate Dark Reader extension support in the app than building a custom CSS. Not saying yet that I'm going to do that.

Are you consider doing it in the immediate future?

**Comment by vladimiry** [comment]
I just looked into https://github.com/ProtonMail/WebClients/ and located implementation for the "dark mode support for mail content/body". It's currently hidden under the feature flag/code though. So apparently they are currently testing this feature and will be releasing it to the public at some point. I don't have the capacity to build already implemented stuff, so closing the issue with the respective status.
