### ISSUE TITLE
ProtonDrive  Blocked

### ISSUE THREAD

**Issue by xyz-nobody** [vladimiry/ElectronMail#509]
The connection to protondrive is blocked again, but I have a paid plan ^^

![Capture d’écran de 2022-04-24 14-52-26](https://user-images.githubusercontent.com/6586244/164982884-8a8458fa-4895-4f3e-ae72-cf95ecd6ccc9.png)

**Comment by vladimiry** [comment]
Not reproducible at my side. Anyway, @protonmail manages the backend, so this is an upstream issue.

**Comment by vladimiry** [comment]
Closing the issue, as it's an upstream one, so needs to be sorted out by @ProtonMail.

Btw, I tried to ping proton dev team members directly before, here on github, and also contacted one of them via email. Unfortunately, such communication was of no effect when it was related to the Drive service (in other cases they were helpful). So I'm not going to contact them anymore with apparently a very similar to #377.
