### ISSUE TITLE
Crashing when opening ElectronMail from new mail notification

### ISSUE THREAD

**Issue by TheDcoder** [vladimiry/ElectronMail#511]
This started happening recently since yesterday, basically ElectronMail crashes whenever I try to open it via the "new mail" notification. Otherwise it opens just fine when I do it manually via the tray icon.

I ran `electron-mail` from the terminal and here's the output:
```
(node:46545) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `electron-mail --trace-deprecation ...` to show where the warning was created)
[46583:0504/084516.077764:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
(node:46545) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
fish: Job 1, 'electron-mail' terminated by signal SIGSEGV (Address boundary error)
```

The first two lines are not critical, they're printed soon after the app is launched. The final line however indicates that the entire process is being terminated by the OS due to a segment fault, there's a good chance this issue is some kind of bug in ElectronJS itself.

My environment:
OS: Arch Linux
Desktop: Xfce
ElectronMail version: v4.14.0

I have not updated my system nor ElectronMail recently, and as I mentioned it started happening only since yesterday, so it's a very interesting phenomenon.

It crashes 90% of the time whenever I open it via the notification, sometimes it works just fine if I was using ElectronMail recently before the notification, not really sure what's happening.

**Comment by vladimiry** [comment]
I see you highlighted that didn't update the system in any way, but it's hard to guess any other reason why the app suddenly started action crashing.

Consider trying the flarpak/snap package version as a potential workaround.

**Comment by vladimiry** [comment]
Any luck with a flatpak/snap package?

**Comment by vladimiry** [comment]
Closing the issue since no code change is expected to happen here. If you manage to find a way to collect the crash dump, consider opening the issue in @electron's tracker.

**Comment by TheDcoder** [comment]
Sorry for the late response, I was meaning to get back but I couldn't and eventually it slipped my mind until now.

Surprisingly the issue seems to be fixed now, I did not update EM but I did update my system a few times, I do not know when it got fixed because I wasn't using the notifications to open mail until now.

A strange issue nevertheless.
