### ISSUE TITLE
Feature request: Option to show notifications only for certain accounts

### ISSUE THREAD

**Issue by supermomonga** [vladimiry/ElectronMail#513]
## background

I don't want show desktop notifications only for certain accounts, but I also want to run "shell command execution" for those accounts. Or I might not want to see notifications for specific accounts that receive a lot of email.

## suggestion

How about adding new toggle switch option "Show desktop notification" in the "Desktop Notification" section of the settings pane for each account? I mean that this option can only be changed if "Desktop notifications for unread email messages" is enabled in the General section.

**Comment by vladimiry** [comment]
This is already possible. See https://github.com/vladimiry/ElectronMail/releases/tag/v4.14.0 changelog for details:

> If the resolved notification content is empty, then the notification won't be displayed. So this is a way to suppress the notification for a specific account or mail data.

Let me know if this works.
