### ISSUE TITLE
Add dynamic version number of deployment types to main github page

### ISSUE THREAD

**Issue by knakamura8** [vladimiry/ElectronMail#519]
Hello!  I am wondering if perhaps there is a way of adding dynamic version information next to the different build types on the main github page.  For example, Flatpak is currently at version 5.0.0, yet the unofficial snap is currently at version 4.15.0.  You have to click on each of the deployment links on the main github page to determine this, however.

I think it would be convenient to have some organized grid where one could quickly see the highest level version currently offered by each deployment type.

**Comment by vladimiry** [comment]
It's noted on the https://github.com/vladimiry/ElectronMail#download section that available repositories are maintained by different persons. This means that normally Snap/AUR/Makedeb repos get updated 1-2 days later. The flatpak & choco repos maintained by me, so normally get updated faster.

I don't think that a few days delay is a big deal, so closing the issue with won't fix status.

If you want to be among the first users who get a new release, just subscribe to releases notification using the "Watch" button here on GitHub (you would select the "custom => releases" option from the dropdown list attached to this button).

CC @joshirio, @hiddeninthesand.

**Comment by knakamura8** [comment]
Sure, I am aware that they take a few days, it is not a problem for me.  I just thought it might be a nice to have a version grid is all :)  Anyway, thank you for all your hard work (as well as for the rapid response!).

**Comment by vladimiry** [comment]
> Do a pull request

Makedeb repo badge is missing in the list. So we would need a similarly styling generic badge for Makedeb repo, but apparently static for now.

**Comment by knakamura8** [comment]
Yup, I noticed that, and made an Issue there.  There seems to be some way to use badgen to make a custom badge with makedeb's API, and I will look into perhaps in several hours.

**Comment by vladimiry** [comment]
Let's wait for PR then. There is no rush.

**Comment by knakamura8** [comment]
@hiddeninthesand It appears as though makedeb requires an API key.  As far as I understand, this can then be passed into badgen as a request such as https://badgen.net/https/mpr.makedeb.org/api/electronmail-bin/makedeb

**Comment by hiddeninthesand** [comment]
I believe the feature OP is looking for is a [Repology](https://repology.org/) embed in the README. You can see an example of the embed on the site, or a working example on a GitHub repository like [scrcpy's](https://github.com/Genymobile/scrcpy) (even though I think they have an excessive amount of package repositories listed). You can see ElectronMail's Repology page [here.](https://repology.org/project/electronmail/versions)

**Comment by hiddeninthesand** [comment]
> Well, the issue with repology is that it's another thing that has to be clicked on, rather than quickly available as badges

Repology supports badges, which I mentioned previously. No requirement for anything to be clicked on, just another source of badges like https://shields.io

> Nothing about Flathub or Snapcraft.

This does actually seem to be a rather unfortunate obstacle. By their own words: `Repology does not support self-contained blobs like flatpaks, which require versions of all bundled components to be considered.`

Using it strictly for the makedeb badge would seem to fix the current API issue though, glad I could help.

**Comment by knakamura8** [comment]
Submitted a PR with all known package types
