### ISSUE TITLE
Suddenly getting "Failed to decrypt the settings storage"

### ISSUE THREAD

**Issue by badger62** [vladimiry/ElectronMail#521]
I logged out of electronmail  after not having logged out for over a year . Tried to log back in using a pass word that I am 99% sure is correct I am getting "Failed to decrypt the settings storage"  . I am guessing that because it can't be ruled out that I might have made a mistake entering the password into my password manager I may have to completely uninstall and reinstall electronmail . If I do how do I ensure that the old password is not  still in the keychain and make a completely clean reinstall enabling to set a new password etc.

**Comment by vladimiry** [comment]
If you remember the password, you could enter it manually, not using keychain.

If you want to start from scratch, remote the respective record from the keychain (you could look up info on the internet how to remove the keychain record depending on the system you use).

Currently, I have no reason to believe that the "Failed to decrypt the settings storage" error message is triggered by something other than a wrong master password.
