### ISSUE TITLE
Hide inbox count?

### ISSUE THREAD

**Issue by ylluminate** [vladimiry/ElectronMail#523]
Is there a mechanism to hide inbox count? It isn't really helpful and only hides some of the name space for my use case and I'd prefer to eliminate the red box inbox count for each account.

**Comment by vladimiry** [comment]
https://github.com/vladimiry/ElectronMail/issues/175#issuecomment-589953917

**Comment by ylluminate** [comment]
Holy cow. I looked and looked for this again - but didn't see it. Lol. Thanks for refreshing my memory. You know something, though, the actual red (or whatever color you set it to) badge should also disappear with it.

**Comment by vladimiry** [comment]
> should also disappear with it.

The option hides the count value on both badge on account handle button and tray icon.

**Comment by ylluminate** [comment]
Hmm. Notice how I still see these:
![example](https://p153.p0.n0.cdn.getcloudapp.com/items/jkuXnjmW/773eff2b-e803-4502-8e4f-235882243655.jpg?v=39f2d25ef77332453e007c6dfc0d489a)

**Comment by vladimiry** [comment]
Yes. You see the badge as a "new message" visual indicator, but the count value is hidden.

**Comment by ylluminate** [comment]
Oh, hmmm. I see. I guess I was hoping to remove those altogether as well, but I understand your intention now at least insomuch that hitherto it's seemed like an oversight / mistake in leaving it.

**Comment by vladimiry** [comment]
> I guess I was hoping to remove those altogether as well

You [were not](https://github.com/vladimiry/ElectronMail/issues/175#issuecomment-589941625) :smiley:. So that `a "new message" visual indicator` quote I posted above is taken from your message.

Anyway, the request to drop the badge completely would be won't fix. at this time.

**Comment by ylluminate** [comment]
Lol. People change, eh? 🫣 Btw, still having trouble with copy/paste not working on macOS. I think you were waiting for an upstream fix before...
