### ISSUE TITLE
Unhandled Error: TypeError: No protocol

### ISSUE THREAD

**Issue by ystan-** [vladimiry/ElectronMail#525]
This sometimes pops up while replying to an email and requires dismissing several times. Not sure if it's related to the contents of the mail being replied to, but it should fail gracefully since the message can be sent after dismissing the error.

![Error Screenshot](https://i.ibb.co/kBxXZCH/2022-06-08-17-43-12.png)

Windows 11 21H2

**Comment by vladimiry** [comment]
> but it should fail gracefully since the message can be sent after dismissing the error.

If this doesn't affect the functionality, then yes, sure it should fail gracefully. The thing is that by default, no URL's without protocol expected to be there (I would be interested in reproducing this case at my side). Anyway, I'm going to try/catch this place, log the URL's "origin" value, and fail gracefully. Thanks for the report.

**Comment by vladimiry** [comment]
> Anyway, I'm going to try/catch this place, log the URL's "origin" value, and fail gracefully.

Besides, I think I should ban such kind of requests. At least until I figure details.
