### ISSUE TITLE
Captcha shows up at each start in V5.0.0 wheras do not shows in V4.15.0 

### ISSUE THREAD

**Issue by dominix** [vladimiry/ElectronMail#526]
not clearly a bug, but is it annoying. tag it has feature request maybe. 

At (quite) every start, since I have upgraded to V5.0.0 on my home machine, Captcha is showing up, and sometimes it makes me miss some important email. 
while this is not the case (at least not as frequent as) for V4.15.0 still used on my office machine, so I am not willing to upgrade on office machine. 

thanks for the good job anyway.

**Comment by vladimiry** [comment]
Enabling the "Persistent session" toggle on the account form allows the session reuse between app restarts. This is a way to avoid a need to login into the account on every app start.
