### ISSUE TITLE
Allow Visual C++ Redist Silent Install

### ISSUE THREAD

**Issue by CharlesZ54** [vladimiry/ElectronMail#528]
Visual Studio C++ Redistributable isn't able to be installed silently since there's no way to pass a silent install param from the ElectronMail installer, this is blocking deployment of ElectronMail via WinGet.
Could functionality for this be added?
Please see https://github.com/microsoft/winget-pkgs/issues/61743

**Comment by vladimiry** [comment]
The linked commit adds support for the silent mode inheritance. So it should work as needed since the next app release (if I didn't do any mistake tweaking the NSIS script).

**Comment by vladimiry** [comment]
Just noticed that for `vcredist140` executable, it has to be `/quiet` arg vs originally committed `/silent` arg.

**Comment by vladimiry** [comment]
The originally applied `IfSilent` test use approach didn't work for some reason, so I ended up for now always running `vcredist140` setup in a `/quiet` mode. Ideally, the `quiet` mode should only be applied if the app's NSIS setup was executed with `/S` flag.

**Comment by vladimiry** [comment]
The change released in just published 5.0.2.
