### ISSUE TITLE
Incorrect unread emails counters rendered in the Proton UI

### ISSUE THREAD

**Issue by RobertKirchner9** [vladimiry/ElectronMail#529]
This is a not-very-serious-but-still-annoying bug. I'm running ElectronMail 5.0.1 on Linux Mint Mate 20.3. As you can see in the attached screenshot, there is a 2 to the right of "All mail" in the  folder menu on the left, ostensibly indicating 2 unread messages. But this is spurious. There are no unread messages in any of my folders. Even when I click the "unread" filter in "All mail" itself, nothing shows up. These spurious unread message numbers show up next to various folders regularly. I can't clear them, even by logging out and in again. And the ElectronMail tray icon shows spurious unread message numbers as well.
![Screenshot at 2022-06-24 12-02-59](https://user-images.githubusercontent.com/36320249/175618554-00f0e9aa-308e-4cec-8d41-d537f1655f38.png)

**Comment by vladimiry** [comment]
![3](https://user-images.githubusercontent.com/1560781/175636768-2f8e9f74-3bff-4666-8b21-417ca9795386.png)

This unread indication is not part of the ElectronMail project, but https://github.com/ProtonMail/WebClients, so it's irrelevant here.

**Comment by vladimiry** [comment]
Do you have the "local store" option enabled in the app for the mail account?

> Restarting ElectronMail clears it up until you get another new message.

You could also click "Unload" menu item opened by right mouse click on the account handle button. This action triggers the page reload, and so the proton-web-client gets reloaded too.

> I recently signed out of my account and back in (to get Proton Drive access) and ever since doing that I have this issue.

To make the Drive service work, the app forces the "account" auth scope when a new session gets open (so you had to re-sign in into the account), as discussed in https://github.com/vladimiry/ElectronMail/issues/522#issuecomment-1156989727. This could potentially introduce side effects as Proton might differentiate some logic based on the auto scope type. There were no other recent major changes in the app, so it's either this auth scope related issue or the Proton's web client change. It's yet to be investigated.

**Comment by vladimiry** [comment]
Can confirm that if the "local store" disabled, making the 1 unread email read doesn't wipe the "1" tray indicator nor the "all mail (1)" counter. I normally go with a "local store" option enabled, so didn't notice the issue before. If the "local store" enabled, the tray  icon is fine (at least if you make the mails read via the "local store" means) as in this mode tray icon under status update has its own logic, but the "all mail (1)" in the proton's app is still there. Beside if I remove the mail, select the "all mail" folder in the proton-web-client, the summary mails count value displayed at the right page side doesn't get updated with -1 value (so remains static). Everything is fine in the "local store" mode as it handles the mails independently ("all mails" counter is fine, same as the tray update, etc).

> I went back to v5.0.0 and the issue persists, then tried v4.14.0 and it's working fine. So it seems like the issue started happening with v5.0.0.

Same user session was used or you signed-in (you can see the open session list in the account's settings app, then go "security" section ...)?

**Comment by vladimiry** [comment]
> There were no other recent major changes in the app, so it's either this auth scope related issue or the Proton's web client change.

> I went back to v5.0.0 and the issue persists, then tried v4.14.0 and it's working fine. So it seems like the issue started happening with v5.0.0.

So if the issue was still there in 5.0.0 then it's not related to the "account" auth scope forcing and the remaining issue cause is the proton web client change itself. If so, then it's likely related to some caching (I've noticed they started using Redux for some needs not so long time ago).

**Comment by vladimiry** [comment]
> Between switching versions I removed my Proton account from the app then added it back.

Ok, so "account" auth scope forcing is still an optiuon.

**Comment by vladimiry** [comment]
Here is the debugging progress. In the app the `/v4/events/<event-id>` request, the output doesn't include a `*Counts`-like fields (like `MessageFields`). But if I run in-browser version (v5.0.5.4 at the moment), those fields are there. This is likely the invalid counter values rendering issue cause (and also the tray update if the "local store" feature is disabled, as the app simply doesn't see "unread" value update).

**Comment by vladimiry** [comment]
> Ok, so "account" auth scope forcing is still an option.

In both cases, the app and in-browser client, the session title is `Proton Account for web`. So the cause doesn't seem to be the "account" scope forcing related.

The `mail-api` subdomain use and `/api` prefix dropping was introduced since v5.0.0, so going to drop this logic and see what happens, since the in-browser version still uses the [officially deprecated `/api`-prefixed API requests](https://github.com/ProtonMail/WebClients/issues/276).

**Comment by vladimiry** [comment]
Just reverted the [`x-pm-appversion: web-account@...` header forcing for the `/auth/*` API call](https://github.com/vladimiry/ElectronMail/issues/522#issuecomment-1157469718) needed for the Drive access fix and got the `*Count`-like fields filled for the `/v4/events/<event-id>` API call.

So it's a blocker here, as we either get access to the Drive service by forcing the `"Proton Account for web"` session via `x-pm-appversion: web-account@...` header for `/auth/*` API call, or we get `*Count`-like fields filled for the `/v4/events/<event-id>` API call which fixes the unread counters rendering, but without having access to the Drive service. @bartbutler would appreciate some feedback.

**Comment by vladimiry** [comment]
@prestr if there won't be a workaround/solution found like in a few days, I tend to drop the Drive service use via the app and release a new version.

**Comment by superfreeman1989** [comment]
I'm having similar issue. Unread badge persists after deleting new email. Disabling and enabling the account removed the badge.

**Comment by vladimiry** [comment]
> Disabling and enabling the account removed the badge.

> You could also click "Unload" menu item opened by right mouse click on the account handle button. This action triggers the page reload, and so the proton-web-client gets reloaded too.

**Comment by vladimiry** [comment]
> In the mean time, if you want the message or conversation counts or both you just need to include MessageCounts and/or ConversationCounts query parameters (values are not important) and they'll be put in the response.

Thanks. Going to try this later today.

**Comment by vladimiry** [comment]
> In the mean time, if you want the message or conversation counts or both you just need to include MessageCounts and/or ConversationCounts query parameters (values are not important) and they'll be put in the response.

Can confirm that applying [this logic](https://github.com/vladimiry/ElectronMail/commit/743229c1ca44f15c3cf9c219728f23f102d7b731) fixes the issue. Going to publish a new release within a few days.
