### ISSUE TITLE
v5.0.2 macOS arm build damaged

### ISSUE THREAD

**Issue by prestr** [vladimiry/ElectronMail#536]
@vladimiry I just downloaded the new v5.0.2 builds on my M1. 

**electron-mail-5.0.2-mac-x64.dmg** - Working fine
**electron-mail-5.0.2-mac-arm64.dmg** - macOS reports the file is damaged (I have deleted and re-downloaded the file but same error appears). 

![Screen Shot 2022-07-28 at 2 38 15 PM](https://user-images.githubusercontent.com/39970655/181613139-4702bc45-5925-4998-ae7c-494742bc0ab6.png)

**Comment by vladimiry** [comment]
Does the build shared in the https://github.com/vladimiry/ElectronMail/issues/357#issuecomment-1185246559 message work?

**Comment by vladimiry** [comment]
@badwulfy / @ylluminate can you test the released build?

I believe that the only change in comparison with a previously shared working build is updated @electron & `electron-builder` and that can potentially be the issue cause (especially the `electron-builder` as it's how the app gets packaged).

**Comment by vladimiry** [comment]
> xattr -d com.apple.quarantine /Applications/ElectronMail.app

Yes, that was mentioned in https://github.com/vladimiry/ElectronMail/issues/357#issuecomment-1185343048 and I missed to put a note into the release description (doing now).

**Comment by vladimiry** [comment]
Btw, it looks like Apple should make an effort toward improving this error message.

**Comment by ylluminate** [comment]
> @badwulfy / @ylluminate can you test the released build?

Works great! No visible issues at all.
