### ISSUE TITLE
[Request] Adopt Proton's new colour scheme

### ISSUE THREAD

**Issue by Nive9** [vladimiry/ElectronMail#539]
I love all the work that has been put into ElectronMail and I think it would be nice to replace the [logo](https://github.com/vladimiry/ElectronMail/blob/master/src/assets/dist/icons/icon.png) and colours to match [Proton's redesign](https://proton.me/blog/new-visual-universe) that was introduced a few months ago. 

The default green colour looks a little out of place in my opinion and it might be worth considering replacing it with the [Proton Mail icon](https://github.com/ProtonMail/protoncore_android/blob/main/presentation/src/main/ic_logo_mail_adaptive-playstore.png), or even the [Proton icon](https://github.com/ProtonMail/protoncore_android/blob/main/presentation/src/main/ic_logo_proton_adaptive-playstore.png) since Calendar notifications are also supported (even if experimental).

In addition to that, the notification badge could also be adjusted to match the size and position of [Proton VPN's connected badge](https://github.com/ProtonVPN/win-app/blob/master/src/ProtonVPN.App/Resources/Assets/Images/Icons/systray-connected.ico), so that it doesn't hide the logo so much.

The settings colours could be replaced too but since they're mostly invisible, it would be even less of a priority.

It's just a rather minor detail and change but it would be nice to see some adoption of Proton's (subjectively?) more modern look.

**Comment by vladimiry** [comment]
Thanks for the input. There is no goal to math the proton's schemes, but extend its features and make it more convenient for using on desktop. So closing with won't fix status.

**Comment by Nive9** [comment]
Alright, got it. Thanks for the quick reply and all your work though!
