### ISSUE TITLE
[Feature request] - Consider storing custom CSS in separate files

### ISSUE THREAD

**Issue by xDarksome** [vladimiry/ElectronMail#540]
As I understand, custom CSS is currently stored in the encrypted `settings.bin`?

It would be great to have it stored separately and unencrypted.

The usecase I am interested in is to be able to `git add` custom CSS to a personal `dotfiles` repository.

**Comment by vladimiry** [comment]
The account-specific options currently stored in encrypted `settings.bin`. Your proposal breaks a single responsibility principle, which normally leads to increased maintenance burden. So the request gets rejected.

**Comment by xDarksome** [comment]
@vladimiry I do see an increase in required maintenance, since the codebase would get bigger. Addition of almost any feature would lead to this.

However, the single responsibility principle is arguable here. I don't see any reason to encrypt customization files alongside secrets. It's just a limitation of the current storage implementation.

I understand if you consider this feature not worth of reimplementing the storage.
