### ISSUE TITLE
Windows App Completely Broken - Presented with this Upon Startup

### ISSUE THREAD

**Issue by cww032992** [vladimiry/ElectronMail#544]
Unhandled Error
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ReadStream.<anonymous> (C:/Users/Carter/AppData/Local/Programs/ElectronMail/resources/app.asar/app/electron-main/index.cjs:92437:31)
    at ReadStream.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at node:internal/fs/streams:275:14
    at FSReqCallback.wrapper [as oncomplete] (node:fs:660:5)

**Comment by cww032992** [comment]
I'd used a dozen (at least) prior builds, all on Win11 64-bit.  The latest update is what prompted this bug.

**Comment by vladimiry** [comment]
Remove/rename the `database-session.bin` from the [settings folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg). If the issue is still there, do the same with `database.bin` file too.

**Comment by cww032992** [comment]
Hi Vlad - your first suggestion worked perfectly.  Truly appreciate the response time here - sorry if my description was a bit harsh.  Thank you so much! Please consider this resolved.

**Comment by vladimiry** [comment]
There is an atomic write implementation which is supposed to prevent the data corruption on abnormal program exit. But this implementation appears to be flawed. Maybe at some point I will replace the storage with a real portable database, like sqlite.

**Comment by cww032992** [comment]
I’m glad I could put it on your radar.

For what it’s worth everything’s worked flawlessly for me until this one small bug.

**Comment by vladimiry** [comment]
After a brief review, added some tweak to the local store serializer. Hope this improves stability in the next release.
