### ISSUE TITLE
NOT an issue, Help about password forgotten

### ISSUE THREAD

**Issue by nicolas2014** [vladimiry/ElectronMail#547]
hi,
i don't know how to recover my electronMail password, do i have to reinstall electronMail?
Can't find info on web, hope i'll find here,
Thank you

**Comment by vladimiry** [comment]
To start from scratch (wiped app data/configs), remove everything in the [app settings folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg).
