### ISSUE TITLE
When upgrading to v5.1 with ARM Mac M1

### ISSUE THREAD

**Issue by CA2MI** [vladimiry/ElectronMail#549]
Hi,

I just tried to upgrade my Mac M1 running ARM. I tried to just run it afterwards and ran into an issue. Users will still need to run the xattr -d com.apple.quarantine /Applications/ElectronMail.app command to make it work. It was not posted in the download area and had to go back to the previous version and grab that command. Just an FYI

**Comment by vladimiry** [comment]
Thanks for the input. I was not going to highlight in each release a need to run `xattr -d com.apple.quarantine /Applications/ElectronMail.app` command. But it seems to confuse macos users, so updating the latest release description now.

**Comment by CA2MI** [comment]
Thanks for that. I just know some of my clients miss a update and they can be clueless on why it does not work.  I created a video for ~2000 of our users. At times I post things to our youtube channel and I think I posted one about the ARMs issue. it only has 95 views so who knows if it was helpful to folks - https://www.youtube.com/watch?v=ll3I7f_7k1E
