### ISSUE TITLE
Indexing Error: Empty sender address

### ISSUE THREAD

**Issue by ystxn** [vladimiry/ElectronMail#554]
I have no idea how the sender address might be empty. Is this something to be concerned about?

```
Local database entity validation error has occurred: {"entityType":"mails","sentDate":1492506233000,"subject":"Support for Exchanges / Asset Classes","error":"sender: ; address: isNotEmpty: address should not be empty"}
```

![2022-09-22_15-51-18](https://user-images.githubusercontent.com/7151832/191690276-d6769c20-c8a8-4caf-901d-ce5e4dd33f61.png)

**Comment by ystxn** [comment]
Okay I found the message in question. It was an old message that I sent that Proton's import process created when I migrated from outlook.com.

**Comment by vladimiry** [comment]
Good finding. Clearly, the app currently doesn't accept the emails without sender's address. So it's going to work if you remove this email if removing it is acceptable for you. Before removing it, maybe forward it first so the sender address gets filled, and you have it saved in a way

**Comment by vladimiry** [comment]
This validation is not going to be dropped. So closing as no change needed.
