### ISSUE TITLE
Icon exists in tray, but is completely transparent (invisible)

### ISSUE THREAD

**Issue by hoerdter** [vladimiry/ElectronMail#555]
And so I can't see how many new mails I got.

Issue exists since update yesterday.

Xubuntu 20.04.5

**Comment by vladimiry** [comment]
I don't run Xubuntu and so not going to look into this issue in the near future. There are many package options for Linux. So you could try https://flathub.org/apps/details/com.github.vladimiry.ElectronMail/ or https://snapcraft.io/electron-mail and see if it helps.

**Comment by hoerdter** [comment]
Thanks for your fast reply!

I was already using the snap version, I uninstalled and reinstalled but still the same problem.

After that I tried the flathub version, it works fine! Icon visible in tray again just as it used to be!
