### ISSUE TITLE
Problem with loading the proton web client webview/page (timeout)

### ISSUE THREAD

**Issue by vladimiry** [vladimiry/ElectronMail#559]
Grouping issue for this kind of problem.

I made some changes for 5.1.0, but it appears that the issue is still there, #558 in 5.1.1.

**Comment by hopeless-attempt** [comment]
Thanks Vladimiry for the reply.
Tried the 5.1.1 Flatpak. Same problem as with the deb & appimage. Not to worry, 5.1.0 sttill works.

**Comment by vladimiry** [comment]
> Not to worry, 5.1.0 sttill works.

I didn't make any changes in 5.1.1 related to the proton web client webview/page loading. So since 5.1.0 still works well, it appears that the currently implemented webview/page loading scenario is somehow sensitive to the @electron / @chromium / @angular updates (I used to update everything before every release).

**Comment by vladimiry** [comment]
Added short delay before loading that blank.html entry point page. Hope this will increase the stability.

**Comment by vladimiry** [comment]
Those who face the permanent "webview" loading timeout issue and running multiple accounts, consider setting up the login/load delay for the accounts, so you load them in a sequence. See the "Login delay range (seconds)" input field in the "Advanced settings" block located on the account edit form. So you set up no delay value for the first account, like 5-10 range for the second account, then 10-15, and so on.

**Comment by frorayz** [comment]
```Uncaught (in promise): WebviewPingFailedError: Failed to ping the "webview" backend service (timeout: 7000ms).
WebviewPingFailedError: Failed to ping the "webview" backend service (timeout: 7000ms).
at file:///Applications/ElectronMail.app/Contents/Resources/app.asar/app/web/browser-window/index.mjs:8845:83
at Observable.init [as _subscribe] (file:///Applications/ElectronMail.app/Contents/Resources/app.asar/app/web/browser-window/index.mjs:4096:33)
at Observable._trySubscribe (file:///Applications/ElectronMail.app/Contents/Resources/app.asar/app/web/browser-window/index.mjs:2948:23)
at file:///Applications/ElectronMail.app/Contents/Resources/app.asar/app/web/browser-window/index.mjs:2942:119
at errorContext (file:///Applications/ElectronMail.app/Contents/Resources/app.asar/app/web/browser-window/index.mjs:5293:14)
at Observable.subscribe (file:///Applications/ElectronMail.app/Contents/Resources/app.asar/app/web/browser-window/index.mjs:2940:63)
at doInnerSub (file:///Applications/ElectronMail.app/Contents/Resources/app.asar/app/web/browser-window/index.mjs:4425:52)
at outerNext (file:///Applications/ElectronMail.app/Contents/Resources/app.asar/app/web/browser-window/index.mjs:4419:38)
at OperatorSubscriber._this._next (file:///Applications/ElectronMail.app/Contents/Resources/app.asar/app/web/browser-window/index.mjs:4149:13)
at Subscriber.next (file:///Applications/ElectronMail.app/Contents/Resources/app.asar/app/web/browser-window/index.mjs:3219:97)×
Failed to ping the "webview" backend service (timeout: 7006ms).```

Just got this o.o

**Comment by Skaalgard** [comment]
I am still getting this error message on ElectronMail v5.1.6 on Linux Mint 21.1. Every time I come back to my computer to check my email, I have _hundreds_ of these error messages.

**Comment by Skaalgard** [comment]
> I am still getting this error message on ElectronMail v5.1.6 on Linux Mint 21.1. Every time I come back to my computer to check my email, I have _hundreds_ of these error messages.

Situation is the same in v5.1.7

**Comment by vladimiry** [comment]
Asking those who experience the issue to test [this](https://mega.nz/folder/okQTXbAD#OuZhygqF3nzfcQlt9qf21Q) build (assembled from the `wip` branch). If it runs well, the change is going to be included in the next release. I'm starting using it too.

**Comment by frorayz** [comment]
Got this recently
```Failed to ping the "webview" backend service (timeout: 7006ms).×
Uncaught (in promise): WebviewPingFailedError: Failed to ping the "webview" backend service (timeout: 7000ms).
WebviewPingFailedError: Failed to ping the "webview" backend service (timeout: 7000ms).
at file:///Applications/ElectronMail.app/Contents/Resources/app.asar/app/web/browser-window/index.mjs:8855:83
at Observable.init [as _subscribe] (file:///Applications/ElectronMail.app/Contents/Resources/app.asar/app/web/browser-window/index.mjs:4096:33)
at Observable._trySubscribe (file:///Applications/ElectronMail.app/Contents/Resources/app.asar/app/web/browser-window/index.mjs:2948:23)
at file:///Applications/ElectronMail.app/Contents/Resources/app.asar/app/web/browser-window/index.mjs:2942:119
at errorContext (file:///Applications/ElectronMail.app/Contents/Resources/app.asar/app/web/browser-window/index.mjs:5293:14)
at Observable.subscribe (file:///Applications/ElectronMail.app/Contents/Resources/app.asar/app/web/browser-window/index.mjs:2940:63)
at doInnerSub (file:///Applications/ElectronMail.app/Contents/Resources/app.asar/app/web/browser-window/index.mjs:4425:52)
at outerNext (file:///Applications/ElectronMail.app/Contents/Resources/app.asar/app/web/browser-window/index.mjs:4419:38)
at OperatorSubscriber._this._next (file:///Applications/ElectronMail.app/Contents/Resources/app.asar/app/web/browser-window/index.mjs:4149:13)
at Subscriber.next (file:///Applications/ElectronMail.app/Contents/Resources/app.asar/app/web/browser-window/index.mjs:3219:97)```

**Comment by vladimiry** [comment]
I was somehow misleading in the previous message. The shared build comes with `Failed to ping the "webview" backend service` error message suppressing/fix, but the original issue cause `Problem with loading the proton web client webview/page` remains untouched.

**Comment by jarrard** [comment]
This issue happens on Windows11 from time to time.  
Normally deleting the offending account that triggers it (or all) and readding them resolves the problem however not always. 
When this issue happens the accounts affected or all accounts loose their credential logins. 
Sometimes restarting app can resolve those accounts that timeout and re-login isn't needed, sometimes not.

**Comment by Skaalgard** [comment]
These error messages continue to accumulate for me. If I step away from my computer for more than 20 minutes I will have hundreds of these. My accounts stay logged in but I'm still getting these. Still no fix for this, more than a year later? I'm using the .deb downloaded from the releases page on Linux Mint 21.1 Xfce.

**Comment by vladimiry** [comment]
> Still no fix for this, more than a year later? 

Correct. And no upcoming related work planned to happen from my side. Why? Because it's FOSS, so anyone who faces the issue could look into it in a debugger, etc. If I get the issue reproduced at my side, I likely look into it, but it's no the case at the moment, and making improvements based on guesses is not something I'm ready to continue doing for this project at this time.

>  If I step away from my computer for more than 20 minutes I will have hundreds of these.

The recent app release should not throw `Failed to ping the "webview" backend service` errors at all, so it must be something different from the `Failed to ping the "webview" backend service` error.

**Comment by Skaalgard** [comment]
This is the error message I am receiving:

```
Uncaught (in promise): Error: Invocation timeout of calling "resolveLiveProtonClientSession" method on "electron-mail:webview-api:primary" channel with 25000ms timeout
Error: Invocation timeout of calling "resolveLiveProtonClientSession" method on "electron-mail:webview-api:primary" channel with 25000ms timeout
at <anonymous>:965:24
at Observable.init [as _subscribe] (<anonymous>:5192:35)
at Observable._trySubscribe (<anonymous>:3207:25)
at <anonymous>:3201:121
at Object.errorContext (<anonymous>:10325:16)
at Observable.subscribe (<anonymous>:3199:26)
at doInnerSub (<anonymous>:6915:58)
at outerNext (<anonymous>:6909:40)
at OperatorSubscriber._this._next (<anonymous>:5367:15)
at Subscriber.next (<anonymous>:3613:123)
```

**Comment by vladimiry** [comment]
@Skaalgard, this is not the original error. Can't say what causes the issue since I didn't look into it as there is no reproducible case at my side, but clearly in your case something is jamming the process of resolving Proton's client/web-side session for further saving it at the app side which is a part of the "auto-login into the proton account" feature.

**Comment by vladimiry** [comment]
@Skaalgard, consider trying alternative Linux package types with some isolation capabilities, like https://flathub.org/apps/com.github.vladimiry.ElectronMail or/and https://snapcraft.io/electron-mail. There is a small chance that there will be no issue you are facing.

**Comment by Skaalgard** [comment]
I get this error with both the flatpak and .deb, on both of my Linux Mint machines.

**Comment by softwarepagan** [comment]
I'm still getting this error:

`Invocation timeout of calling "resolveLiveProtonClientSession" method on "electron-mail:webview-api:primary" channel with 25000ms timeout`

Every time I open the window after it's been open for about 20 minutes (sometimes less), regardless of if the computer has gone to sleep or not, there are always 50 of these notifications open.

This happens regardless of if I'm using the .deb, the flatpak, or the appimage. I've tried all three.

I'm running ElectronMail v5.2.2, with:
Electron: 27.1.0
Chromium: 118.0.5993.144
Node: 18.17.1

My system is running Linux Mint 21.1 x86_64 with Xfce 4.16
V8: 11.8.172.17-electron.0

**Comment by vladimiry** [comment]
> Invocation timeout of calling "notification" method on "electron-mail:webview-api:primary" channel with 25000ms timeout

Working on updating packaged https://github.com/ProtonMail/WebClients bundle, I faced the case myself. Now it's easy to reproduce and so it's going to be fixed in the next release. It's clearly a regular timing/racing issue, when "notification" call gets triggered before the handler for this call got registered at the "webview" side.
