### ISSUE TITLE
How do I upgrade on OS X Monterey?

### ISSUE THREAD

**Issue by PacoH** [vladimiry/ElectronMail#560]
When I start the app, I get a popup:

	ElectronMail
	App update is available.

![Update](https://user-images.githubusercontent.com/6173647/193299576-cec1a643-56ea-4749-875f-7d43317b6277.jpg)

It has about a two second persistence. If I am lucky, I can click it but nothing happens. If I go to the site Releases, I can download the latest version but it is just a new version of the app. How can I *upgrade* the existing app?

**Comment by vladimiry** [comment]
> I can download the latest version but it is just a new version of the app

This is a way.

**Comment by PacoH** [comment]
Huh? I want to be notified but usually you can upgrade an app from within the app.

**Comment by PacoH** [comment]
Oh, thanks for telling me. Why didn't you say so in the Installation section? `Homebrew` is the preferred way to install and manage `GitHub` tools and apps on a Mac.

`brew install electronmail` did the trick. It installed the latest version into the Applications folder. All data and settings are intact.
