### ISSUE TITLE
I there I forgot my password

### ISSUE THREAD

**Issue by kivoosh** [vladimiry/ElectronMail#561]
I try to remove and reinstall from flathub and nothing any ideas??

**Comment by vladimiry** [comment]
To start from scratch, you will need to remove app settings located in the [respective folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg) (for flatpak it's `~/.var/app/com.github.vladimiry.ElectronMail/config/electron-mail`). Removing this folder means losing all the app settings, so you will have to set up the master password again, add mail accounts, etc.

**Comment by kivoosh** [comment]
Thanks… it helps
