### ISSUE TITLE
Is there a portable version of ElectronMail?

### ISSUE THREAD

**Issue by sakibarifin** [vladimiry/ElectronMail#562]
Hi, a portable version would be very helpful.
Relevant: https://github.com/portapps/portapps/issues/205

**Comment by vladimiry** [comment]
I'm not aware of one.

**Comment by ask2018** [comment]
@vladimiry I know this was closed as wontfix long time ago, but could you actually consider portable version or portable settings in the application? I'm not sure how easy or hard it would be in current application state, but I think it would be pretty useful to be able for example have portable version on ecrypted USB stick or be able to have another fully private and invisible instance on local encrypted drive without any writes to system folders.

**Comment by vladimiry** [comment]
@ask2018 I'm not interested in pursuing a portable app build path, nor do I have any need for one. It would solely rely on software for portability. So it might behave exactly as needed one day when you test it, and then break at some point due to OS updates, Electron changes, or other system-level shifts that were not predicted in the released app. Software-based portability introduces unpredictability. If you need to carry stuff with you, consider carrying a tiny/pocket computer with you, if a laptop is too large option.

**Comment by ask2018** [comment]
@vladimiry Ok I understand. But tiny/pocket computer is really not a solution for this. That is like using sledgehammer to kill the fly. Also it doesn't help with multiple instances on single computer for example. Where some of them might be fully hidden on encrypted drive. I can use virtual machine for that, but that is again the sledgehammer story :) To be honest I think most of the software should be portable by default. It is much better like that. But I respect your decision. Thank your for answer.

**Comment by vladimiry** [comment]
@ask2018 if you really want to go portable way, you can start the app with `ELECTRON_MAIL_USER_DATA_DIR` env var and see if it does the trick. On Linux, start command could look like `ELECTRON_MAIL_USER_DATA_DIR=/home/username/.config/electron-mail2 /opt/ElectronMail/electron-mail`. If it works as expected, you can add custom start scripts, and it's done. The `ELECTRON_MAIL_USER_DATA_DIR` env var is not documented here in the project, so it might stop working in new releases without a notice.

**Comment by ask2018** [comment]
@vladimiry Great thank you. I will try this later. And I'm still running ElectronMail on Win7, so everything might stop working in new release without a notice for me. So not really problem. I get used to that :)

**Comment by ask2018** [comment]
@vladimiry I did just quick test, but it seems to be working. But I'm facing another issue. I'd like to be able to run it even if the normal instance is running in the background. And that is not possible. If the normal instance is running, then the cmd just opens the normal instance window. Is there maybe some cmd to ignore the already running instance?

**Comment by vladimiry** [comment]
> If the normal instance is running, then the cmd just opens the normal instance window. Is there maybe some cmd to ignore the already running instance?

Currently, there is no way. But skipping the below logic if `ELECTRON_MAIL_USER_DATA_DIR` env value is present might make it work:

https://github.com/vladimiry/ElectronMail/blob/ff6630a722ee4a3c19d1294e29ff929533100fe5/src/electron-main/bootstrap/init.ts#L17-L21

https://github.com/vladimiry/ElectronMail/blob/ff6630a722ee4a3c19d1294e29ff929533100fe5/src/electron-main/bootstrap/app-ready.ts#L51

Going to push the change soon.

**Comment by ask2018** [comment]
Awesome. Thank you.

**Comment by vladimiry** [comment]
> skipping the below logic if `ELECTRON_MAIL_USER_DATA_DIR` env value is present

I better introduce new `ALLOW_MULTIPLE_INSTANCES` env var to handle the need, so there is no breaking change as there might be users who use `ELECTRON_MAIL_USER_DATA_DIR` in a single instance scenario with custom data location purpose.

**Comment by ask2018** [comment]
That sounds like even better solution. I really appreciate it :)

**Comment by vladimiry** [comment]
> introduce new `ALLOW_MULTIPLE_INSTANCES` env var

Pushed to the `wip` branch. To test it, you need to make your own build from that branch, locally or via GitHub CI (clone the project and trigger the CI build).

**Comment by vladimiry** [comment]
> clone the project

If you go this way. After cloning, run `git cherry-pick 2a1479681699146839f47d792f4ef2ddd7531a93` and then `git push`. It should pick the change to the master/main branch and then CI build gets triggered by the push.

**Comment by ask2018** [comment]
@vladimiry I'm doing more tests with version 5.3.4 and this portable option. Everything seems to be working fine, but I have found one bug. If you enable the "keep me signed in option" and allow to store the ElectronMail master password on the system, it will mess with the settings if another instance exists. Example scenario: I have main instance where I have it enabled and stored. Then I run second portable this way and don't store it. After restart of main instance it asks for master pasword again. 

This is how I'm running it:

```
@echo off
set ALLOW_MULTIPLE_INSTANCES=true
set ELECTRON_MAIL_USER_DATA_DIR=D:\path\ElectronMail-Portable\conf
start "" "D:\path\ElectronMail-Portable\electron-mail.exe"
```

**Comment by vladimiry** [comment]
@ask2018 this is how it currently works - single `master-password` keychain record per application, not per instance.

Possible app code changes to fix the issue you listed:
- If ELECTRON_MAIL_USER_DATA_DIR presents, the app skips all the "keep me signed in option"-related logic.
- Or, if ELECTRON_MAIL_USER_DATA_DIR presents, the app adds hashed `ELECTRON_MAIL_USER_DATA_DIR` value to `master-password` keychain record name, so it looks like `master-password-<hashed ELECTRON_MAIL_USER_DATA_DIR value>` vs just `master-password` use. Hashing would be used to derive a unique ID from the path, not for security purpose.

**Comment by ask2018** [comment]
@vladimiry I guess the second option would be good for my needs if I understand you correctly. I don't need it for security purpose there. Nobody can access the Electron-Portable path except of me and it is on ecrypted drive. I just don't want to enter the master password again and again on any instance. But the question is if it is good this way for others. I can imagine scenarios where it would not be good. So I guess the best would be if both options are possible, if it is not too much work for you.

**Comment by vladimiry** [comment]
To not harm the existing logic, it's better to introduce new env var - like USER_DATA_DIR_BASED_KEYCHAIN_RECORD. So if passed, the app uses `master-password-<hashed ELECTRON_MAIL_USER_DATA_DIR value>`-like record names.

**Comment by ask2018** [comment]
> To not harm the existing logic, it's better to introduce new env var - like USER_DATA_DIR_BASED_KEYCHAIN_RECORD. So if passed, the app uses `master-password-<hashed ELECTRON_MAIL_USER_DATA_DIR value>`-like record names.

Sounds good to me. Basically all I need is to don't enter the master password again and again manually and keep the portable version fully isolated from the main one.

**Comment by vladimiry** [comment]
@ask2018 discussed change has been pushed into the `wip` branch - [e65ca41](https://github.com/vladimiry/ElectronMail/commit/e65ca41c302df2e22412c8f50f76276447e0bc96).

**Comment by ask2018** [comment]
I did some tests and seems to be working as expected. Thank you very much.
