### ISSUE TITLE
Trojan Detected

### ISSUE THREAD

**Issue by rand342234** [vladimiry/ElectronMail#566]
don't download, trojan in windows app, vladimiry reported.

**Comment by vladimiry** [comment]
Can you be more specific?

No suspects based on the Virustotal report https://www.virustotal.com/gui/url/1c94101e17c52aece2946e1bf43988529a0e4a9479afbce0f0a57dc7dd482949/detection
But even if it detects something, there would be a need to identify the issue cause, since the statement doesn't really mean that the issue is real.

**Comment by rand342234** [comment]
Trojan.PWS.Panda.122 in the windows version. virustotal is totally unreliable.

**Comment by rand342234** [comment]
reported

**Comment by vladimiry** [comment]
I still have no reason to believe that there is a some sort of trojan, although I can comment on my code only which is open, not on the dependencies, build tools or CI environment.

I will need the unpacked NSIS/exe file gets scanned by your tools to narrow down the scope to the exact file. You can look up on the internet how to unpack the NSIS installer without running it. If the unpacked version doesn't trigger the warning, then it's likely NSIS container causes the warning.

**Comment by vladimiry** [comment]
Btw, here is the Virustotal scan triggered by the [Choco](https://community.chocolatey.org/packages/electron-mail) version updating process https://www.virustotal.com/gui/file/26263a166bf9435f716383c20174e1f3484f6d92e14d211e89b4bded518b4e35/detection/f-26263a166bf9435f716383c20174e1f3484f6d92e14d211e89b4bded518b4e35-1666985455. You can see that the released "exe" has the same SHA256 as the scanned version.

**Comment by vladimiry** [comment]
> I will need the unpacked NSIS/exe file gets scanned by your tools to narrow down the scope to the exact file.

No information provided.

I have no reason to believe that the app includes some trojans or other malicious stuff, nor do I have tools to positively detect them in the way the issue author did.
