### ISSUE TITLE
From Mac to Windows

### ISSUE THREAD

**Issue by id21-space-developer** [vladimiry/ElectronMail#567]
How can I transfer my saved emails to the Windows app from Mac ?

**Comment by vladimiry** [comment]
Copy files listed in https://github.com/vladimiry/ElectronMail#dataconfig-files-created-and-used-by-the-app from the [settings folder on Mac system](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg) to the respective folder on the Win system. Files to copy: config.json, settings.bin, database.bin, database-session.bin, session.bin.
