### ISSUE TITLE
Does not work when 2 user accounts on machine run it

### ISSUE THREAD

**Issue by richardARPANET** [vladimiry/ElectronMail#570]
Problem:

Login to user account A on linux machine, run the app
Switch to user account B on same machine, run the app, won't start

Must `sudo pkill electron-mail` to start it.

**Comment by richardARPANET** [comment]
Why? When you could just store all state for the application in the $HOME dir and run multiple instances on 1 machine?

**Comment by vladimiry** [comment]
Easier implementation and very rare need. If for some reason you need to run several app instances with the individual state, you can run for example deb/pacman+flatpak apps (`flaptak` keeps state in `~/.var/.com.github.vladimiry.ElectronMail`).
