### ISSUE TITLE
No more updates

### ISSUE THREAD

**Issue by alfredonodo** [vladimiry/ElectronMail#573]
Hi,
you usually release one or even two updates a month, whereas now the last update is two months old. Is there a problem with the development?
Thank you for your great work.

**Comment by vladimiry** [comment]
> I think I will be ok to publish new release when @electron updates v22 branch (not getting updates since Nov 30 / v22.0.0).

@electron v22.0.1 is out, so the app release is planned for this week.

**Comment by vladimiry** [comment]
v5.1.3 went live.
