### ISSUE TITLE
[Feature Request] Builtin Auto Updater

### ISSUE THREAD

**Issue by SkilledAlpaca** [vladimiry/ElectronMail#575]
Would adding a built in auto-updater be worth while? I am mainly on Windows and use the desktop client quite often. It's not much of a hassle to come here and download the latest release but it would be much more convenient if it could download the update files for platform it's on?

**Comment by vladimiry** [comment]
The auto-updater thing was here for a while, until if I'm not wrong the respective dependency got some issue. So it got dropped, and I didn't care to get it back, and not yet planning to do so.

For Windows system, there is a Choco repo https://community.chocolatey.org/packages/electron-mail.
