### ISSUE TITLE
Tray icon not showing when app is autostarted

### ISSUE THREAD

**Issue by waredrive** [vladimiry/ElectronMail#576]
Environment:
* Manjaro 
* KDE Plasma Version: 5.26.4
* KDE Frameworks Version 5.101.0
* Qt Version: 5.15.7
* Kernel: 6.1.1
* Graphics platform: X11

Issue:
When electron-mail is added to KDE as an autostart application, the tray icon is not shown. If the app is launched manually, the tray icon is visible as expected. This issue was not present in version 5.1.2.

Steps to reproduce:
* Add electron-mail to autostart applications through KDE autostart settings.
* Restart computer.
* Verify that the tray icon is NOT visible.

**Comment by vladimiry** [comment]
See the following point in release notes for [v5.1.3](https://github.com/vladimiry/ElectronMail/releases/edit/v5.1.3):

> - Since this app version, the tray icon on Linux requires support for [StatusNotifierItem](https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/) by the desktop environment (https://github.com/vladimiry/ElectronMail/issues/514#issuecomment-1332700126).

**Comment by vladimiry** [comment]
I presume you are using v5.1.3 app version. So I guess you could look up StatusNotifier+KDE specific issues on the internet.
