### ISSUE TITLE
since 5.1.3 electronmail is missing from tray

### ISSUE THREAD

**Issue by Kyuunex** [vladimiry/ElectronMail#578]
steps to reproduce:
1. update to 5.1.3
2. launch the application

expected result: it appears in tray
actual result: it is missing from tray

notes:
"Close to tray" and "Start minimized to tray" are enabled in settings.

system:
Linux archlinux 6.1.6-zen1-1-zen
i3-wm

**Comment by vladimiry** [comment]
See the following point in release notes for [v5.1.3](https://github.com/vladimiry/ElectronMail/releases/edit/v5.1.3):

> - Since this app version, the tray icon on Linux requires support for [StatusNotifierItem](https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/) by the desktop environment.

**Comment by Kyuunex** [comment]
thanks.

---

note for those in the same situation as me looking through issues: setting up `snixembed` solved the issue on i3-wm and probably will on other window managers.
