### ISSUE TITLE
tray icon had disapear in v5.1.3 (flatpak)

### ISSUE THREAD

**Issue by dominix** [vladimiry/ElectronMail#581]
I'm on Ubuntu Mate 22.04 LTS. 
there is no more application tray icons in the task bar, however I receive notification when email arrives.
if you don't catch the notification, you have to dig in the menu to open the app to access  the main windows.

**Comment by vladimiry** [comment]
I didn't work on XFCE DE until I added https://github.com/flathub/com.github.vladimiry.ElectronMail/blob/876adbe7b4507cca5634d9430573f5ed9ec0096c/com.github.vladimiry.ElectronMail.yaml#L27 workaround.

So, repeating the point from the release notes:

>  Since this app version, the tray icon on Linux requires support for [StatusNotifierItem](https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/) by the desktop environment

Maybe try the workaround listed in https://github.com/vladimiry/ElectronMail/issues/578#issuecomment-1384180183.

Flatpak still has some issue with StatusNotifier-based tray icon support in @electron context, but there is progress.

I don't think I can do anything to fix it here by some app code change.

Btw, https://github.com/flathub/com.github.vladimiry.ElectronMail is a better place for placing flatpak-related issues.

**Comment by dominix** [comment]
OK, I have installed snixembed from https://git.sr.ht/~steef/snixembed
that required some pkg like libdbusmenu-gtk3-dev libdbusmenu-glib-dev valac libvala-0.56-dev 

and may be mate-sntray-plugin
and I finally got my tray icon back.
