### ISSUE TITLE
I have received 6000 email spam my inbox has became practically unusable

### ISSUE THREAD

**Issue by mariodani** [vladimiry/ElectronMail#584]
Dear sir or madam,
one month ago I Visited for curiosity a dating website and I registered, I gave my email address **wiped-email-address**  (I recognize that was stupid) but now they have sent **6100 spam email** and they have completely full my inbox 
The spam emails come from the www.dating.com  I have tried to UNREGISTERED and cancel my profile from the website but it is impossible, there is no way to unsubscribe and they continue sending emails 

help for your attention and help 

Mario Dani

**Comment by vladimiry** [comment]
There is no question or the issue I could handle within this project. So closing it.

**Comment by vladimiry** [comment]
@mariodani let me know if you want this issue to be removed, so the history gets wiped too.
