### ISSUE TITLE
Error: App version outdated

### ISSUE THREAD

**Issue by Nickwasused** [vladimiry/ElectronMail#588]
## Info
Version: Electronmail v5.1.3
OS: Windows 10

I am getting the following error since today:

![ElectronMail_ikEHKAqVab](https://user-images.githubusercontent.com/34883496/221847047-9e52d3cf-af15-4617-9684-52756e7f49dd.png)

## Log
```
[2023-02-28 12:51:12.359] [error] src\electron-main\web-contents.ts {"level":3,"message":"Uncaught (in promise) AppVersionBadError: App version outdated","line":32831,"sourceId":"webclient://mail.proton.me/index.0ea7be75.js"}
[2023-02-28 12:51:12.360] [error] src\web\browser-window\app\_accounts\account-view.component.ts AccountViewComponent webview event {"type":"console-message","level":3,"message":"Uncaught (in promise) AppVersionBadError: App version outdated","line":32831,"sourceId":"webclient://mail.proton.me/index.0ea7be75.js"}
[2023-02-28 12:51:12.362] [error] src\electron-main\web-contents.ts {"level":3,"message":"Uncaught (in promise) AppVersionBadError: App version outdated","line":32831,"sourceId":"webclient://mail.proton.me/index.0ea7be75.js"}
[2023-02-28 12:51:12.362] [error] src\electron-main\web-contents.ts {"level":3,"message":"Uncaught (in promise) AppVersionBadError: App version outdated","line":32831,"sourceId":"webclient://mail.proton.me/index.0ea7be75.js"}
[2023-02-28 12:51:12.363] [error] src\web\browser-window\app\_accounts\account-view.component.ts AccountViewComponent webview event {"type":"console-message","level":3,"message":"Uncaught (in promise) AppVersionBadError: App version outdated","line":32831,"sourceId":"webclient://mail.proton.me/index.0ea7be75.js"}
[2023-02-28 12:51:12.363] [error] src\web\browser-window\app\_accounts\account-view.component.ts AccountViewComponent webview event {"type":"console-message","level":3,"message":"Uncaught (in promise) AppVersionBadError: App version outdated","line":32831,"sourceId":"webclient://mail.proton.me/index.0ea7be75.js"}

```

**Comment by jleonar** [comment]
Same issue for me on ElectronMail v5.1.3

**Comment by distrair** [comment]
Same issue, same version

**Comment by PegHorse** [comment]
Same issue, same version, Windows.

**Comment by mh4ckt3mh4ckt1c4s** [comment]
Same issue, same version, installed on Arch with the AUR package.

**Comment by FalxDraco** [comment]
Same issue. Windows 10, v5.1.3.

**Comment by imjustleaving** [comment]
same issue - Fedora 37

**Comment by Thouareg** [comment]
Same,
Electronmail v5.1.3
Linux Debian Sid, deb version.

**Comment by BobWs** [comment]
same problem! This morning everything was working fine, but now I'm having the same problem as described above

**Comment by a-lameira** [comment]
Same problem,
Electronmail v5.1.2
Linux Debian Sid, Flatpak version.

**Comment by jfalava** [comment]
Got the same error message,
Microsoft Windows 11 Pro, 10.0.22621 N/D Comp 22621
Electronmail 5.1.3

**Comment by BaronvonLederhosen** [comment]
Same here on Ubuntu 22.10

**Comment by serovar** [comment]
Same on macOS 13.2.1

**Comment by k3n51mm** [comment]
I'll report another Windows installation with the same problem. 
Note: it also happened in v5.1.2.

**Comment by gene-fls** [comment]
Same issue for me, Zorin OS 16.2. 
ElectronMail 5.1.2, Flatpak version.

**Comment by YoungIndiana** [comment]
Same issue..
Microsoft Windows 11 Pro build 22623.1325
Electronmail 5.1.3

**Comment by ask2018** [comment]
Same problem here on Windows 7 x64 SP1 with latest ESU
Electronmail 5.1.3

**Comment by t3dium** [comment]
same

**Comment by veprk130** [comment]
Does anyone know what happened?

Regards,
Ruben H. Padilla Jr.
480.217.1007

------- Original Message -------

**Comment by GoldenGlimpse** [comment]
same here. 
5.1.3-linux-amd64.deb on linux mint 20.3

**Comment by trymeouteh** [comment]
same, linux mint 21.1 flatpak

**Comment by gucio321** [comment]
Hi everyone!
Could you not write-to-write? Everyone already knows about the issue so you don't need to confirm it. You can always express your confirmation by reacting on the Description post, since it does not generate an email notification to everyone subscribed.
Thanks!

**Comment by vladimiry** [comment]
Confirmed. Have not yet looked into it, but clearly the packaged into the app web clients stack need to be updated.

**Comment by vladimiry** [comment]
> Does anyone know what happened?

They/proton made breaking changes to their [web client](https://github.com/ProtonMail/WebClients) project. So the packaged into the app web clients stack got outdated, ie got incompatible with Proton's backend. Proton have already made such kind of breaking changes before, but it's very rare case. The fix is releasing new app version with updated web clients stack.

**Comment by vladimiry** [comment]
If the web clients stack updating procedure goes as usual, without surprises, then I should be able to publish a new version in a day or so.

**Comment by ask2018** [comment]
vladimiry. Great and please consider recent electron/chromium updates breaking Win7 and Win8/8.1 support. So please provide binaries also with older electron/chromium on the fixed version.

**Comment by vladimiry** [comment]
> recent electron/chromium updates breaking Win7 and Win8/8.1 support

Can you point me to the related info?.

**Comment by ask2018** [comment]
https://github.com/electron/electron/releases/tag/v23.0.0
Release Notes for v23.0.0
Windows 7, Windows 8, and Windows 8.1 are not supported anymore, as Chromium 110 dropped support. #

**Comment by vladimiry** [comment]
@ask2018, I think I might maintain it on a separate branch and update the latest release with a one more Windows build when it's ready. But supporting outdated @electron versions here will have to end at some point.

**Comment by ask2018** [comment]
@vladimiry Great and thank you. Yeah I know it must end at some point, but hopefully there will be solution to run updated electron soon on those systems and using outdated one will be not needed anymore.

**Comment by OmrShlby** [comment]
Same issue for me on ElectronMail v5.1.3
linux, pop os

**Comment by vladimiry** [comment]
I'm already running updated app locally, so new release coming soon.

**Comment by pongsoft** [comment]
According to comments, it looks like something has changed on Protonmail side. Nothing is wrong with ElectronMail.
An ElectronMail update should fix this issue once released.

**Comment by veprk130** [comment]
Thank you!!

Regards,

Ruben H Padilla Jr

**Comment by vladimiry** [comment]
v5.1.4 got released.

**Comment by benbois** [comment]
Thanks @vladimiry, issue fixed on last Ubuntu!

**Comment by PegHorse** [comment]
Thanks @vladimiry it's working now perfectly, on Windows 10 :)

**Comment by fosko** [comment]
Hi there, thanks @vladimiry for solving the issue that quick. I've installed v5.1.4 but it seems like a new fresh installation: none of my accounts is there. Even v5.1.3 is still here. Is that normal or is it me? I hoped to open electronmail and find my accounts with their email messages: i.e: an update/upgrade not to start afresh.

**Comment by vladimiry** [comment]
@fosko this is certainly not normal, but I can't say anything specific not knowing the context. The app doesn't remove its config files. What is the way you installed the app?

**Comment by PegHorse** [comment]
I know only one reason for this issue, if you didn't install the software as the first time, then the settings will be different.
For example if the first time, you chosen to install in System wide and the 2nd time, you chosen user share accounts, the installation will be different.
But in order to prevent ça, the setup should detect the previous installation and repeating the same process when updating.

**Comment by fosko** [comment]
> 
I downloaded electron-mail-5.1.4-linux-amd64.deb and installed it with Software Install on my Ubuntu 22.04.2 LTS

**Comment by jleonar** [comment]
I can confirm that I have it installed via snap.  The update works just fine for me.

**Comment by PegHorse** [comment]
I don't know what is the SNAP version but yes of course, it makes sense as it's different installation process ^^

**Comment by fosko** [comment]
Imma try installing the .snap

**Comment by fosko** [comment]
oops
![image](https://user-images.githubusercontent.com/85874471/222133993-76d09cfb-b91c-4894-83f8-2304fc028c11.png)

**Comment by PegHorse** [comment]
Well @fosko i guess you won the right to make another issue for your case 🤣

**Comment by fosko** [comment]
Oh plz help me I've got 6 professional email accounts on my Electronmail. First time I have an issue in... IDK 4/5 years?

**Comment by vladimiry** [comment]
> the setup should detect the previous installation and repeating the same process when updating.

I'm not going to spend time on such kind of improvement.

> For example if the first time, you chosen to install in System wide and the 2nd time, you chosen user share accounts, the installation will be different.

You should be able to find an [existing configs files](https://github.com/vladimiry/ElectronMail#dataconfig-files-created-and-used-by-the-app) somewhere in your folders and copy/move them to [the actual config folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg) used by a current app installation.

@fosko, let's not spam a similar message in this issue. First try to locate the previously used config files and then copy/move them where required. I'm repeating that the app doesn't remove the config files. If you keep spamming, you will be banned.

> Could it be I had the SNAP version installed? (sorry if I ask nonsense)

I don't remember where Snap package keeps the config files, but flatpak keeps it in `/home/<user>/.var/app/com.github.vladimiry.ElectronMail/config/electron-mail/` which is different to a regular location `/home/<user>/.config/electron-mail/`.

**Comment by vladimiry** [comment]
> Great and please consider recent electron/chromium updates breaking Win7 and Win8/8.1 support. So please provide binaries also with older electron/chromium on the fixed version.

> I might maintain it on a separate branch and update the latest release with a one more Windows build when it's ready

@ask2018, the `electron-mail-5.1.4-windows78-x64-nsis-installer.exe` installation package has been attached to the v5.1.4 release.

**Comment by fosko** [comment]
Thank you all, especially @vladimiry for being so quick in solving the issue and so kind in helping noobs like me. I assume my Ubuntu fooled me when it said "failed to install snap" as it had already installed the v5.1.4.snap over the old v5.1.3 as usual. I've removed the .deb installation via package manager. Everything works fine unless the pink error message when opening Electronmail (Imma post it in a new issue).

**Comment by ask2018** [comment]
@vladimiry Thank you very much. Everything is now working fine with electron-mail-5.1.4-windows78-x64-nsis-installer.exe on Win7.

**Comment by gene-fls** [comment]
Is there a way to update ElectronMail from within the app? I have it deployed large scale and updating each machine via .exe would be time consuming.

**Comment by PegHorse** [comment]
Yes i use Chocolatey and i programmed a task in my task scheduler so each time i boot my computer, Chocolatey check my packages and update them.
This is a nice way when your software doesn't include self autoupdate.
I'm doing that for most useful app like 7-Zip, WinRAR, Electronmail etc...

**Comment by vladimiry** [comment]
@gene-fls, there are Choco/Winget/Scoop repositories (I maintain Choco repo, but not the Winget/Scoop). The app was able to update itself before, but I cut that feature out after it started demonstrating some issues and I didn't get it back since then, and not planing to. The only thing the app does regarding updating is checking new version and showing related message (opt-out feature, see the respective toggle in the "General" settings section).

**Comment by rauldipeas** [comment]
I'm still getting some errors and no tray icon.
![Screenshot_20230301_142427](https://user-images.githubusercontent.com/12108031/222216456-81587f7b-d2c8-4fdc-8d62-466e9c71b3bd.png)
![Screenshot_20230301_142457](https://user-images.githubusercontent.com/12108031/222216480-c9a0d2e7-fc92-44a1-a97e-5bd181a46f2a.png)

**Comment by vladimiry** [comment]
@rauldipeas this should be placed as a separate issue. Looks like an issue caused with `pureimage` dependency update.

**Comment by perfectpassage** [comment]
I'm getting the same issue on 5.1.6, Debian 11.
Did deleting the config files fix it?

**Comment by PegHorse** [comment]
Same error on Windows since today...
![image](https://user-images.githubusercontent.com/7678316/229761716-b507b509-5d0a-4e21-9019-92b86c2dd3ed.png)

**Comment by git-Hmmm** [comment]
Please reopen, it started happening again...

**Comment by PegHorse** [comment]
On Windows it's fixed since 5.1.7

**Comment by Zan1456** [comment]
![image](https://github.com/vladimiry/ElectronMail/assets/62830223/30f2acc3-4457-4c7e-8c4e-27caf7160ab5)
Again broken

**Comment by vladimiry** [comment]
>  Again broken

See pinned issue ...
