### ISSUE TITLE
Flathub.org V5.1.2 > 5.1.4

### ISSUE THREAD

**Issue by evok3d** [vladimiry/ElectronMail#589]
Great work! Thank you for updating to 5.1.4 and fixing the connection issues. Is it possible to update the flathub.org version? it is currently on 5.1.2

Cheers

**Comment by evok3d** [comment]
> It's already updated, see [flathub/com.github.vladimiry.ElectronMail@8f17c6f](https://github.com/flathub/com.github.vladimiry.ElectronMail/commit/8f17c6f9ef5db2514213cb92420d29961d7de7d7) It should appear on Flathub sometime today, probably in some hours

Thank you!

**Comment by vladimiry** [comment]
>  It should appear on Flathub sometime today, probably in some hours

If the need is urgent, you should be able to install the updated build by the command listed in https://github.com/flathub/com.github.vladimiry.ElectronMail/pull/9#issuecomment-1449610004.

**Comment by evok3d** [comment]
> 

All resolved! was able to update this morning. Thank you again for the great app and update.
