### ISSUE TITLE
Still the pink error message in v5.1.4

### ISSUE THREAD

**Issue by fosko** [vladimiry/ElectronMail#590]
As I said, there's still this error message when starting Electronmail. 
![image](https://user-images.githubusercontent.com/85874471/222157169-a89f9534-b241-4bdf-8d3e-6fb9462a88cf.png)

**Comment by vladimiry** [comment]
I'm grouping this kind of issues in #559. So closing this one as duplicate. The issue remains unresolved at the moment.
