### ISSUE TITLE
I'm getting some errors and no tray icon

### ISSUE THREAD

**Issue by rauldipeas** [vladimiry/ElectronMail#591]
I'm getting some errors and no tray icon.

![Screenshot_20230301_142427](https://user-images.githubusercontent.com/12108031/222216456-81587f7b-d2c8-4fdc-8d62-466e9c71b3bd.png)
![Screenshot_20230301_142457](https://user-images.githubusercontent.com/12108031/222216480-c9a0d2e7-fc92-44a1-a97e-5bd181a46f2a.png)

_Originally posted by @rauldipeas in https://github.com/vladimiry/ElectronMail/issues/588#issuecomment-1450549434_

**Comment by vladimiry** [comment]
Picked from https://github.com/vladimiry/ElectronMail/issues/588#issuecomment-1450585857:

> Looks like an issue caused with `pureimage` [dependency update](https://github.com/joshmarinacci/node-pureimage/commit/c63da8225d6c00a8aaa942f80988e7529a091524) (used for tray icon rendering).

**Comment by vladimiry** [comment]
As a simple, a reliable fix, I'm considering rolling back to the well working `pureimage` version.

**Comment by vladimiry** [comment]
@rauldipeas, I'm triggering WIP v5.1.5 build with included potential fix and will ask you to test it when it's ready. What kind of package you are using (deb, pacman, etc)?

**Comment by rauldipeas** [comment]
I'm using a deb package.

**Comment by vladimiry** [comment]
@rauldipeas / @ask2018 can you test the build uploaded [here](https://mega.nz/folder/t1BUWBpJ#39vVzb6_ZegibT0333Byhg)? If the tray icon is fine there, I'm considering publishing a new release.

**Comment by ask2018** [comment]
@vladimiry I'm the Win7 user, so unfortunately I cannot test, as I don't see there installer for 7/8.

**Comment by vladimiry** [comment]
@ask2018 I tested myself as I was able to reproduce that black background. But the error case has to be tested by @rauldipeas as it was not reproducible at my side.

**Comment by vladimiry** [comment]
Thanks. So new release coming soon.

**Comment by ask2018** [comment]
@vladimiry It is fixed now for me as well on 5.1.5 on Win7. Thank you.
