### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by t3dium** [vladimiry/ElectronMail#592]
hey, wonderful app btw, just had a couple questions:

if i enable local storage, and delete some emails from protonmail's website, is it possible to prevent local store from also deleting the emails? acting as an archive

also, what files contain downloaded emails for local store? database.bin? if i move this file between linux and windows will i be able to access local store across os's?

**Comment by vladimiry** [comment]
> if i enable local storage, and delete some emails from protonmail's website, is it possible to prevent local store from also deleting the emails? acting as an archive

The feature is not designed for this, so the answer is no.

> also, what files contain downloaded emails for local store? database.bin? if i move this file between linux and windows will i be able to access local store across os's?

https://github.com/vladimiry/ElectronMail#dataconfig-files-created-and-used-by-the-app
