### ISSUE TITLE
[Feature Request] Integrate Proton's SimpleLogin service

### ISSUE THREAD

**Issue by TimmyBoi155** [vladimiry/ElectronMail#594]
I use Proton's email aliasing service, SimpleLogin, very regularly. One of the reasons I haven't used ElectronMail more regularly was because there is no way for me to use SL like I do when I use proton mail through my browser, either with the extension or the web UI dashboard

Is it possible to integrate this into ElectronMail? I wonder if there is an easy to do this buy adding the SL extension to Electron

https://www.electronjs.org/docs/latest/tutorial/devtools-extension
https://www.electronjs.org/docs/latest/api/extensions
https://github.com/simple-login/browser-extension

Thanks in advance for your consideration

**Comment by vladimiry** [comment]
It looks like simplelogin's features going to be integrated into the proton itself, see https://simplelogin.io/blog/simplelogin-join-proton/

There are many different services around. Starting integrating one into the app, for many reasons, is a vicious thing to do. Allowing extensions is an option, but I'm not going to enable this capability for the app in the near future.

Closing with won't fix status.

**Comment by TimmyBoi155** [comment]
yeah it's a just a "login with proton" button on their website/extension. that's the integration
