### ISSUE TITLE
CHANGE DIRECTORY FOR EMAILS

### ISSUE THREAD

**Issue by FROVERB** [vladimiry/ElectronMail#597]
HELLO!
I have a large amount of emails, several Go (around 15) , is it possible to chose to store the file on another disk (other than C)?

**Comment by vladimiry** [comment]
You could try `ELECTRON_MAIL_USER_DATA_DIR` environment variable. You will need to copy/move [the currently used app data](https://github.com/vladimiry/ElectronMail#dataconfig-files-created-and-used-by-the-app) from the [settings folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg) to the folder the `ELECTRON_MAIL_USER_DATA_DIR` env var points to. It's undocumented and unsupported, but it might work.
