### ISSUE TITLE
macOS build v5.1.7 - Launch issues with the recent build of the app

### ISSUE THREAD

**Issue by mlanteigne** [vladimiry/ElectronMail#607]
Let me start by saying that I really love this app, and appreciate the effort of this community.

I have issues when trying to launch the new version of the app on macOS.
I never saw these messages when using the previous builds.

I completely removed the old version of the app before installing the new one and here's the error message when opening the apps.

macOS version : Ventura 13.3

ARM build :
<img width="285" alt="mac_arm" src="https://user-images.githubusercontent.com/39577694/229938718-2d400f33-49b6-40a4-b274-03911240d252.png">

x64 : This version work by whitelisting the app provider

**Comment by vladimiry** [comment]
Missed adding this to the release notes:

> The Apple Silicon/M1 ARM64 package requires `xattr -d com.apple.quarantine /Applications/ElectronMail.app` command execution.
