### ISSUE TITLE
Error: App version outdated

### ISSUE THREAD

**Issue by TimmyBoi155** [vladimiry/ElectronMail#608]
Surprised that no one has opened an issue. Since yesterday I suddenly cannot log in to my proton account:

![image](https://user-images.githubusercontent.com/88632743/229957532-43829122-f140-46f3-b686-dd0b0243b4b6.png)

I disabled the "block non-API requests" option but still this happens. Also I noticed that when I have a socks proxy, it just times out, but when I have no proxy, it gives the outdated error. However, initially, even with my proxy configured it was giving the error about being outdated.

**Comment by git-Hmmm** [comment]
I apologize for the confusion, but issue #588 already exists. Therefore, it might be better to reopen that issue instead of creating a new one.

**Comment by vladimiry** [comment]
@TimmyBoi155, v5.1.7 release fixes the issue.
