### ISSUE TITLE
Archlinux, segmentation fault AND install hangs on: -> Stripping unneeded symbols from binaries and libraries...

### ISSUE THREAD

**Issue by Jirido** [vladimiry/ElectronMail#611]
Hi, I run archlinux.  After been informed that electronmail needed to update, I tried but it got stuck at  : -> "Stripping unneeded symbols from binaries and libraries..."       For ever...
When tried to run electron mail after that I got segmentation fault and core dump. Now I have it uninstalled and can't reinstall.

**Comment by vladimiry** [comment]
The installation package is fine. This sounds like something Arch/pacman specific. Consider installing/running it via an alternative source, like https://flathub.org/apps/details/com.github.vladimiry.ElectronMail or Appimage package.

**Comment by vladimiry** [comment]
The pacman package is valid, as I verified it myself by installing on Arch system. So closing for now, but I don't reject some glitch happening case, like for example triggered by imperfection of the way pacman applied a supposed to be transactional actions.
