### ISSUE TITLE
[bug] failed to set cookie with an invalid domain attribute

### ISSUE THREAD

**Issue by t3dium** [vladimiry/ElectronMail#613]
![image](https://user-images.githubusercontent.com/83690012/233584596-7fb56f18-db3c-4102-b356-c163fc4f82a4.png)

**system info:**
**os:** fedora 37, gnome 43.4
**version:** latest flatpak stable branch

this was working fine before, first time getting this issue. i haven't changed anything on the account, app or my system.

**Comment by vladimiry** [comment]
Possible workaround:
- Disable "Persistent session" for the account.
- Restart the app and sign-in into the account.
- Enable the "Persistent session" for the account.

**Comment by vladimiry** [comment]
Another brutal workaround is removing `session.bin` file located in the [app settings folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg) and restarting the app. But you will need to relogin into the accounts then if you were using the [persistent sessions](https://github.com/vladimiry/ElectronMail/issues/227) feature.

**Comment by vladimiry** [comment]
Closing as glitch with possible workaround.
