### ISSUE TITLE
Stepping down as maintainer of the AUR and Snap packages

### ISSUE THREAD

**Issue by joshirio** [vladimiry/ElectronMail#614]
Hi @vladimiry and ElectronMail community,

after more than 4 years of maintaining the ArchLinux [AUR package](https://aur.archlinux.org/packages/electronmail-bin) and the [Snap package](https://snapcraft.io/electron-mail) on Snapcraft I'm stepping down, mostly because since some time already I no longer use Linux as my daily driver, and due to work stuff, I will be traveling for weeks and sometimes on bad or no internet connection, so I ca longer guarantee a timely upload and attention to potential packaging issues.

I still love this software and use it almost daily. Thanks.

I'm looking to transfer package ownership within the next 2-3 weeks.
How should we organize this transfer? Who will be able to step up as maintainer?

I can leave here the basic instructions and commands I use routinely to publish to the Snap store and AUR repo, if necessary.

**Comment by vladimiry** [comment]
Thanks, @joshirio, for stepping into the maintaining those repositories starting from the early project stage and doing it flawlessly for such long time, which I believe significantly contributed into adopting the app by Linux users.

I guess I will have to take maintaining those repos on me, but let's see, maybe someone else appears.

> I can leave here the basic instructions and commands I use routinely to publish to the Snap store and AUR repo, if necessary.

Let's do it later, like in a few weeks, as maybe someone who already knows the process takes over the burden before this.

**Comment by vladimiry** [comment]
@joshirio, no one appeared, so please send the instructions for both repos to the email specified in the project's `package.json` file (the address should already be familiar to you).

**Comment by vladimiry** [comment]
See the new look of repo maintainers list https://github.com/vladimiry/ElectronMail/tree/wip#download.

**Comment by joshirio** [comment]
The transfer of ownership is now completed.
