### ISSUE TITLE
windows78 branch future

### ISSUE THREAD

**Issue by ask2018** [vladimiry/ElectronMail#615]
I'd like to discuss here future of Windows 7/8 branch and post related info about possible future solutions. Electron 22 will receive security updates until October 10, 2023 - https://www.electronjs.org/blog/electron-22-0

`The Electron team will continue to backport any security fixes that are part of this program to Electron 22 until October 10, 2023.`

For now the only reason why Electron 23+ is not compatible with Win 7/8/8.1 systems should be this:
https://github.com/electron/electron/releases/tag/v23.0.0

`Windows 7, Windows 8, and Windows 8.1 are not supported anymore, as Chromium 110 dropped support.`

And as we have here first fork of Chromium for legacy systems, I thought it is good time to start the discussion here about ElectronMail future for legacy systems.
https://github.com/win32ss/supermium

`The aim of Supermium is to provide the latest Chromium features, support for rendering the web and security patches to users of Windows Vista (with extended kernel), Windows 7 and Windows 8.x.`

**Comment by vladimiry** [comment]
At this time, it doesn't look like this project is going to use anything, but standard @electron releases. I don't believe @electron is going to utilize `supermium` or alike projects just to support Chromium security updates on longer supported Win 7/8 systems.

**Comment by ask2018** [comment]
Thank you for reply @vladimiry.
I've opened issue there with the question about this: https://github.com/electron/electron/issues/38262

**Comment by ask2018** [comment]
Just an update on this issue with possible future solution.
https://github.com/win32ss/supermium-electron

**Comment by vladimiry** [comment]
I'm not ready to support unsupported systems, like Win 7. So closing as won't fix.

**Comment by ask2018** [comment]
I understand and thank you for clear statement. That means I'll need to try fix it somehow on my own when the time will come. Keep up the good work on this project.

**Comment by ask2018** [comment]
If anyone needs to use ElectronMail on Win7/8 there are these options now.
Both tested with ElectronMail 5.2.0 and seems to be working just fine.
1.
Download latest Windows ElectronMail release, unpack it and delete everything with exception of "resources" folder. 

2a
Download latest Electron 22 release (supports ends October 10, 2023)
For now it is https://github.com/electron/electron/releases/tag/v22.3.24

or

2b
Download latest supermium-electron release
For now it is https://github.com/win32ss/supermium-electron/releases/tag/v28-testing

3
Copy all files with exception of "resources" folder from Supermium-electron or Electron 22 to the same folder where you have "resources" folder from ElectronMail.

4
Rename electron.exe to ElectronMail.exe and now you can run latest ElectronMail on Win 7/8.

**Comment by ask2018** [comment]
Just an update for anybody who wants to use ElectronMail on Win7.
Today VxKex added support for ElectronMail in version 1.1.0.1291, so you can now use official ElectronMail builds on Win7 system with VxKex extended kernel. 
https://github.com/vxiiduu/VxKex

**Comment by ask2018** [comment]
Another update for people still running ElectronMail on Win7. Current version of VxKex doesn't work anymore with ElectronMail 5.2.3 and there is atm unknown status of Extended Kernel updates. Also supermium-electron is not yet updated to Electron version needed for running current version if ElectronMail. But here is solution for Windows 7 users.
https://github.com/Blaukovitch/GOOGLE_CHROME_Windows_7/releases/tag/ElectronMail_523
