### ISSUE TITLE
Wrong timezone for Tehran/Asia

### ISSUE THREAD

**Issue by elamir-ir** [vladimiry/ElectronMail#617]
Protonmail recently updated the timezone for Tehran/Asia from GMT +4:30 to +3:30 (this is a recent change in Iran) but the change isn't reflected in the app

**Comment by vladimiry** [comment]
It won't be reflected until a new app version gets released, since proton's web clients stack packaged into the app as a static resource.

The `wip` branch contains updated proton's web clients stack.
