### ISSUE TITLE
Notification does not open application after click

### ISSUE THREAD

**Issue by silvacarlosec** [vladimiry/ElectronMail#618]
Hello ElectronMail team,

I am having an bug with the app related to the user experience on Windows 11 (version 22H2). After I have received a notification from a new email, appear a notification banner. If I click on the **notification banner** when this pops up, the app will open normally. But the issue will be there  if I postpone to later the click, clicking the email notification in the **notification center**. The notification will fade out after click but the application won't open.

Bellow are some screenshots to illustrate that.

Thank you!

![Screenshot 2023-05-25 023717](https://github.com/vladimiry/ElectronMail/assets/58672246/904eaa8d-9699-4e59-a26c-9e2745bc519f)

![Screenshot 2023-05-25 023758](https://github.com/vladimiry/ElectronMail/assets/58672246/0c04b17f-3a56-4690-9a78-6a0849075cbc)

![Screenshot 2023-05-25 023957](https://github.com/vladimiry/ElectronMail/assets/58672246/56662693-7621-413d-9a17-c8b99ebaac91)

**Comment by vladimiry** [comment]
This is the responsibility of @electron, so upstream issue. See https://github.com/electron/electron/issues/37892 and https://github.com/electron/electron/issues/32261.
