### ISSUE TITLE
ElectronMail->TauriMail

### ISSUE THREAD

**Issue by alfredonodo** [vladimiry/ElectronMail#623]
Hello,
given the excellent [performance of Tauri](https://tauri.app/v1/references/benchmarks/) in terms of speed and resource utilization (CPU and RAM) compared to [Electron](https://github.com/microsoft/vscode/issues/118308#issuecomment-800078214), and given the support for mobile and desktop platforms, it would be nice to see ElectronMail ported to such a platform as a long-term project, TauriMail.
Thank you

**Comment by vladimiry** [comment]
This would take another 6 years. So not going to happen here.
