### ISSUE TITLE
temporary node file with dynamic filename causing login issues on some accounts

### ISSUE THREAD

**Issue by ask2018** [vladimiry/ElectronMail#624]
In short: I've got login/account unlock issues on some of my ProtonMail accounts, where captcha has been triggered and account not correctly unlocked. Then I noticed temporary file with dynamic filename is created in my C:\Users\USERNAME\AppData\Local\Temp folder. That was causing security software alerts as new process trying to access the network. File included here in ZIP archive.

It is related to issues I've posted here before:
https://github.com/vladimiry/ElectronMail/issues/621#issuecomment-1632475848_
https://github.com/vladimiry/ElectronMail/issues/621#issuecomment-1632721133_
https://github.com/vladimiry/ElectronMail/issues/621#issuecomment-1641710043_

[f0441d2e-b000-449c-8dfb-1f7e8fae6ee7.tmp.zip](https://github.com/vladimiry/ElectronMail/files/12093279/f0441d2e-b000-449c-8dfb-1f7e8fae6ee7.tmp.zip)

**Comment by vladimiry** [comment]
Native dependencies get unpacked from @electron's "asar" archive, for proper execution. I made them to be pre-unpacked into app's "node_modules" directory, so the security scanners don't get triggered. But it appears that I missed something in the recent release.

But, if you were using the same app version, and then it suddenly started action like this, then this sounds like a potential issue at your side, as the app remains static.

**Comment by ask2018** [comment]
Yes it was the same version of the app, but it started only after the captcha issue on some accounts. Before it was not there. Maybe the security alert is somehow related to the additional network connections to the captcha server.

**Comment by vladimiry** [comment]
This sounds like @protonmail doing something tricky in relation to named verification.

**Comment by vladimiry** [comment]
I anciently dropped `msgpackr-extract` library patching in the recent release, and this looks like a cause of the issue. If so, this should be resolved in the next release.

**Comment by kiwiman2023** [comment]
My fathers is on windows 8.1 and latest version wont login.. but webpage directly works
it comes up with captcha with move jigsaw piece to prove human. 
so he hasnt used it for 3 weeks. so you say go to older version to solve it? I didnt try that
or wait for next build?

**Comment by ask2018** [comment]
The issue seems to be fixed for me with 5.2.0. Thank you.
