### ISSUE TITLE
Display Issues

### ISSUE THREAD

**Issue by JTDimino** [vladimiry/ElectronMail#628]
I've been having a recurring problem whereby the ElectronMail window is opening off-screen, and there seems to be no way for me to move it back to where I can interact with it.

**Comment by vladimiry** [comment]
Locate the `config.json` file in the [settings folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg). When the app is closed, set `window.bounds.x/y` values to `0` and start the app.

**Comment by vladimiry** [comment]
Closing as resolved.
