### ISSUE TITLE
[Question] Do you know a way to block the anyoing "self ads" of proton?

### ISSUE THREAD

**Issue by BobWs** [vladimiry/ElectronMail#629]
Hi,
Not a bug or issue report, but a question!
Do you know a way to block the annoying ads of proton about upgrade to  paid account and all those other promotions?
See screenshot for example
 
![Screen_Shot 4](https://github.com/vladimiry/ElectronMail/assets/5485820/c4bd9009-7877-4476-8645-82bb1cd7ff7c)
TIA

**Comment by vladimiry** [comment]
Any stuff can be cut out or modified by patching https://github.com/ProtonMail/WebClients/ sources before it gets build for packaging into the app, see https://github.com/vladimiry/ElectronMail/tree/master/patches/protonmail.

**Comment by vladimiry** [comment]
If @protonmail saves "closed" state of this ad in the browser's local storage, then this state will be lost, since the app by design keep all the browser/web-specific storages in memory only, so the data not persisted between the app restarts.

**Comment by BobWs** [comment]
> keep all the browser/web-specific storages in memory only, so the data not persisted between the app restarts

I guess that's what's happening, because after every new start of the app they all appear again.

**Comment by vladimiry** [comment]
> Do you want to take look at it and see if you can patch it?

If I do this, then as an opt-in feature, so @protonmail upsell messages not suppressed by default. For opt-in feature, simple static patching won't be a solution, so more dev work would be required. There is no ETA, so if I do this, you will see it done.

**Comment by vladimiry** [comment]
It's coming in the next release. See the new "Disable Proton upsell messages" toggle in the "General" app settings.

![upsell-message](https://github.com/vladimiry/ElectronMail/assets/1560781/7c2fa8c1-3c6f-46e4-b39c-a8f074013938)

**Comment by BobWs** [comment]
> It's coming in the next release. See the new "Disable Proton upsell messages" toggle in the "General" app settings. The toggle is disabled by default, so this is an opt-in feature.

That's a great solution, nice! Thank you for implementing it!

**Comment by vladimiry** [comment]
> will it also hide the 'upgrade now' banner?

If it's similar to the image in the first message https://github.com/vladimiry/ElectronMail/issues/629#issue-1845281306, then yes, it will.

**Comment by vladimiry** [comment]
>  will it be hidden as well ?

Nope. Looking into it. The above-displayed "Disable Proton upsell messages" toggle is going to be renamed to "Disable Proton upsell messages & buttons".

**Comment by vladimiry** [comment]
> there also an upgrade button on header next to settings. will it be hidden as well ?

Done now.

> toggle is going to be renamed to "Disable Proton upsell messages & buttons".

The new toggle title name is "Disable Proton upsell ads". So the toggle disables upsell messages and buttons too.

![123](https://github.com/vladimiry/ElectronMail/assets/1560781/3895f872-9c13-41f1-86c6-392faf25fb70)

**Comment by vladimiry** [comment]
> the banner is still visible in spam and trash folders...

Not for me. Screenshot?

**Comment by vladimiry** [comment]
It's different on paid plan, so I didn't look like an ad for me. But on free plan it indeed looks like an ad, so has to be taken care too. Thanks for this finding.

free account:
![free](https://github.com/vladimiry/ElectronMail/assets/1560781/7b81e6a9-5263-40b3-82a8-7807c7ba415d)
paid account:
![paid](https://github.com/vladimiry/ElectronMail/assets/1560781/cc263fe6-9e63-4862-bae3-551cbfac4f6a)

**Comment by BobWs** [comment]
Just installed the latest version, nice work thank you for tackling it so quickly!

**Comment by vladimiry** [comment]
> free account:
![free](https://github.com/vladimiry/ElectronMail/assets/1560781/7b81e6a9-5263-40b3-82a8-7807c7ba415d)
paid account:
![paid](https://github.com/vladimiry/ElectronMail/assets/1560781/cc263fe6-9e63-4862-bae3-551cbfac4f6a)

v5.2.1 comes with dropped spam/trash ad banners. No change made for paid users since it's not an ad there, but a shortcut to an available feature and the banner there comes with "close" icon which closes it permanently.
