### ISSUE TITLE
cookie loading error  profile load error timeout

### ISSUE THREAD

**Issue by Dux-mk1** [vladimiry/ElectronMail#631]
hello 
I am experiencing these issues on macOs 13.4.1 (c) air m2 2023 
I have the latest version of the program installed 
Please tell me how to fix this 
![image](https://github.com/vladimiry/ElectronMail/assets/77417199/70495166-ac18-463f-8ddf-4f28c9f127f1)
![image](https://github.com/vladimiry/ElectronMail/assets/77417199/c6a4f2d3-2707-426b-b2d1-e87dbf200b65)

**Comment by vladimiry** [comment]
The workaround is removing `session.bin` file located in the [app settings folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg) and then restarting the app. This will remove the data related to the "persistent session" feature (auto login into the accounts), so after app restarting explicit sign in into the proton accounts will be required.
