### ISSUE TITLE
electronmail not launching on Macintosh M2 

### ISSUE THREAD

**Issue by dominix** [vladimiry/ElectronMail#632]
I have installed electronMail with `brew install electronmail`

this works well, but when I launch electromail I got a message from system saying "ElectronMail is damaged and can't be opened. you should push it in the trash." (translation approximate).

So at the end it is unusable.
uninstalling and re-installing (with clear cache) won't help either. 

for information:
file /Applications/ElectronMail.app/Contents/MacOS/ElectronMail
/Applications/ElectronMail.app/Contents/MacOS/ElectronMail: Mach-O 64-bit executable arm64

otool -L /Applications/ElectronMail.app/Contents/MacOS/ElectronMail
/Applications/ElectronMail.app/Contents/MacOS/ElectronMail:
	@rpath/Electron Framework.framework/Electron Framework (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.100.3)

**Comment by vladimiry** [comment]
Did you run `xattr -d com.apple.quarantine /Applications/ElectronMail.app` command like written in the release description?

**Comment by dominix** [comment]
Sorry I have missed this point . it works well now.
