### ISSUE TITLE
homebrew update

### ISSUE THREAD

**Issue by superfreeman1989** [vladimiry/ElectronMail#652]
Homebrew update seems to lag quite a bit behind github. I'm unable to access protonmail due to old version on homebrew right now.

**Comment by vladimiry** [comment]
I don't maintain Homebrew repo and now aware of who does.

**Comment by superfreeman1989** [comment]
Oh, said repo is here: https://formulae.brew.sh/cask/electronmail#default
It's been updated now.
Do you intend to run an official repo on homebrew?

**Comment by vladimiry** [comment]
> Do you intend to run an official repo on homebrew?

Nope. Too many repos to maintain are already on me.

**Comment by superfreeman1989** [comment]
Alright, thanks anyway though :)
