### ISSUE TITLE
Is High Sierra (macOS 10.13) no longer supported?

### ISSUE THREAD

**Issue by BobWs** [vladimiry/ElectronMail#653]
Hi,
Is macOS High Sierra (10.13) no longer supported?

When I try to open ElectronMail I'm getting this error and when I try to update to the latest version 5.2.2 I see that my macOS isn't supported anymore!
![Screen_Shot 3](https://github.com/vladimiry/ElectronMail/assets/5485820/f0bdacd1-956b-4c76-8aec-0807bcfa0ed7)
![Screen_Shot 2](https://github.com/vladimiry/ElectronMail/assets/5485820/27513b90-7dff-41bb-b46b-bf7226ec85eb)

How do I fix this to keep using version 5.2.1 which supported macOS 10.13 and being able to see my mail again?

TIA

**Comment by vladimiry** [comment]
See #650 and try recent v5.2.2 release.

**Comment by vladimiry** [comment]
I mean, the message you posted, "App version is outdated", belongs to Proton, and the related issue should be fixed in v5.2.2.

**Comment by BobWs** [comment]
> I mean, the message you posted, "App version is outdated", belongs to Proton, and the related issue should be fixed in v5.2.2.

Yes I get that, but as you can see on the other screenshot I uploaded I'm **not able** to install the latest version 5.2.2 because it require **macOS version 10.15 or later!**

**Comment by vladimiry** [comment]
According to the https://www.electronjs.org/blog/electron-27-0#breaking-changes `macOS 10.13 (High Sierra) and macOS 10.14 (Mojave) are no longer supported by Chromium`. So it's clear now.

I'm not going to downgrade @electron for this project, but one who prefers using old system, could fork the project and assembly the own custom app build with downgraded @electron.

**Comment by vladimiry** [comment]
> macOS 10.13 (High Sierra) and macOS 10.14 (Mojave) are no longer supported

I've just added a related note to the release description.

**Comment by BobWs** [comment]
I'm truly sorry to learn that my current version of macOS is no longer supported, and it's disheartening to hear that there are no plans to address this. I find myself in a challenging financial situation now, making it difficult to afford a new Mac, which is why I continue to use my still functional 2011 MacBook Pro.

The reality is that the trend of increasingly expensive upgrades limits my ability to access certain services, including your wonderful program. It's disheartening to realize that staying connected with my ProtonMail accounts through your application is no longer an option.

Despite this setback, I want to express my sincere gratitude for all the hard work you've put into developing this program. It has been an integral part of my computing experience over the past few years. Unfortunately, as with many things in life, all good things must come to an end. Thank you for the valuable service you've provided, and I appreciate the positive impact your program has had on my digital journey.

**Comment by vladimiry** [comment]
> staying connected with my ProtonMail accounts through your application is no longer an option.

False statement, as it's still possible to use the app on old macOS with downgraded @electron. It's not complex to do (really, just do the fork, downgrade @electtron and GitHub Actions CI will assemble the build for you), but my capacity is limited, and so at this time I'm not ready to extend supporting the systems the big for-profit players dropped support for.

**Comment by BobWs** [comment]
> False statement, as it's still possible to use the app on old macOS with downgraded @electron.

I'm sorry but that is beyond my scope of technical knowledge...

**Comment by vladimiry** [comment]
> I'm sorry but that is beyond my scope of technical knowledge...

I get this. But I believe anyone who has a computer with internet and some English knowledge could do this, so it's a matter of how valuable the program was.

**Comment by BobWs** [comment]
Interesting.. but I don't see any mac version in the list https://github.com/electron/electron/releases/tag/v22.3.24
Also his description is for Windows..I guess it could work for macOS if one knows how to do that..

**Comment by vladimiry** [comment]
https://github.com/vladimiry/ElectronMail/commit/176ef3cb71ea23aff832b82ebf1c87e73b2debde commit is trying to enable assembling @electron-v26-based macOS package. If the GitHub Actions CI job completes with success, the result package file named as `app-package-dmg-*.dmg` should be available at https://github.com/vladimiry/ElectronMail/actions/runs/6904745509 in the "Artifacts" section at the page bottom, when/if it completes.

**Comment by ask2018** [comment]
@BobWs
as @vladimiry already mentioned Electron 27 removed macOS 10.13 / 10.14 support
because macOS 10.13 (High Sierra) and macOS 10.14 (Mojave) are no longer supported by Chromium.

So it means you need to use electron 26 version for now. But expect more issues with other applications compatibility. If Chromium is no more supported on your OS, every other Chromium/Electron based application will stop work for you as for me on Win7. For older Windows there is already the Supermium fork. But no idea if something like that exists for older MacOS.

**Comment by ask2018** [comment]
@BobWs here is some Chromium fork for legacy MacOS 
https://github.com/blueboxd/chromium-legacy
Maybe ask there if they can provide also some Electron fork for those legacy systems or know some. That's what you need for the future. You cannot stay with Electron 26 forever, because there will be no more security updates for that version..
As an example for Windows its
https://github.com/win32ss/supermium and https://github.com/win32ss/supermium-electron

**Comment by vladimiry** [comment]
@BobWs does the `app-package-dmg-macos-11` package located in the "Artifacts" section at the https://github.com/vladimiry/ElectronMail/actions/runs/6904745509 page bottom work well (it's a zip archive of "dmg" package)?

**Comment by BobWs** [comment]
@ask2018 Thanks for the info!
@vladimiry thank you very much for your help with the downgraded version! I do appreciate your help!
I was struggling with the Fork and how to downgrade, but I will keep trying and learning how to solve these problems myself.
But for now I'm able to use ElectronMail again to access my ProtonMail... Again Thank you!

**Comment by vladimiry** [comment]
So if you fork the project by the button click (see GitHub docs if it's unclear, but basically it's button click), to pick up updates from the next app release, you would:
- [Sync the fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork).
- Merge changes from the `master` to `macos-downgraded-electron` branch via pull request by opening https://github.com/BobWs/ElectronMail/compare/macos-downgraded-electron...master. If needed, see GitHub docs abut pull requests.
- You then merge the created pull request by green button click and just wait for the new app package to appear in https://github.com/vladimiry/BobWs/actions.
 
This simple scenarios is going to work until there is no merge conflicts or @electron v26 becomes incompatible with the updated app's code/logic.
