### ISSUE TITLE
Windows78 Installer - and Using Old Version Without Updating (Question)

### ISSUE THREAD

**Issue by RogalDoe** [vladimiry/ElectronMail#654]
Hello There, 

Is this Possible to use  v5.1.8 without updating it and without Error Message > Error Outdated Version 

Because latest version didn't have Windows78 Installer then impossible to use thes new version 

Vladimiry can you make a Standalone Version For Windows 7&8 that one will never expire please ?

**Comment by vladimiry** [comment]
The issue like this was rejected before, so this one goes the same way. Not sure, but @ask2018 might be able to give a hint of how to make it work for a limited period of time.

**Comment by ask2018** [comment]
@RogalDoe here is guide how to run current version of ElectronMail on older Windows systems. I'm running it on Win7 without any issues.
https://github.com/vladimiry/ElectronMail/issues/615#issuecomment-1732611223
supermium-electron should have stable version in near future, but the testing build works fine for now.

**Comment by RogalDoe** [comment]
> The issue like this was rejected before, so this one goes the same way. Not sure, but @ask2018 might be able to give a hint of how to make it work for a limited period of time.

Thanks you Vladimiry for making this very usefull software thanks you so much for this 



> @RogalDoe here is guide how to run current version of ElectronMail on older Windows systems. I'm running it on Win7 without any issues. [#615 (comment)](https://github.com/vladimiry/ElectronMail/issues/615#issuecomment-1732611223) supermium-electron should have stable version in near future, but the testing build works fine for now.

Ask2018, hello Comrade,

Thanks you so much for your trick, is working perfectly a big big thanks for you vladimiry and your team 



`
ask2018 commented Sep 24, 2023

If anyone needs to use ElectronMail on Win7/8 there are these options now.
Both tested with ElectronMail 5.2.0 and seems to be working just fine.
1.
Download latest Windows ElectronMail release, unpack it and delete everything with exception of "resources" folder.

2a
Download latest Electron 22 release (supports ends October 10, 2023)
For now it is https://github.com/electron/electron/releases/tag/v22.3.24

or

2b
Download latest supermium-electron release
For now it is https://github.com/win32ss/supermium-electron/releases/tag/v28-testing

3
Copy all files with exception of "resources" folder from Supermium-electron or Electron 22 to the same folder where you have "resources" folder from ElectronMail.

4
Rename electron.exe to ElectronMail.exe and now you can run latest ElectronMail on Win 7/8.`

For me the helped alot for Noobs people :

in step 2a When clicked in the link find >
electron-v22.3.24-win32-x64.zip 

and extract all exept ressource folder in C:\Users\YOURUSERNAME\AppData\Local\Programs\ElectronMail

And rename Electron > ElectronMail

**Comment by ask2018** [comment]
@RogalDoe look at this :) https://github.com/vladimiry/ElectronMail/issues/615#issuecomment-2001896405

**Comment by RogalDoe** [comment]
> @RogalDoe look at this :) [#615 (comment)](https://github.com/vladimiry/ElectronMail/issues/615#issuecomment-2001896405)

Thanks you Comrade
