### ISSUE TITLE
What does the yellow dot mean ?

### ISSUE THREAD

**Issue by iTrooz** [vladimiry/ElectronMail#655]
Hey ! I'm currently constantly seeing a yellow dot in the ElectronMail tray icon: 
![image](https://github.com/vladimiry/ElectronMail/assets/42669835/e378ba63-6c6c-489f-83ae-31fb917e2939)

I have no idea what it means or how to remove it, and I don't see anything in the ProtonMail UI that requires my attention (no popups, no new messages..)

I've tried to delete `~/.config/electron-mail`, and this removed it for a little while, but just now it reappeared again

What does the yellow dot mean, and how to remove it ?
Thanks !

**Comment by vladimiry** [comment]
The yellow dot hints that there is at least one locked mail account. The one you didn't logged in. The feature can be turned off in the settings.

![111](https://github.com/vladimiry/ElectronMail/assets/1560781/0f6eea1f-59e6-4ba8-9ad2-4c3b2cd5fe5f)

**Comment by iTrooz** [comment]
Oh, thanks !

That said, I only have one account, and I'm logged in. I'll try to investigate

**Comment by iTrooz** [comment]
I tried to compile the project using the instructions in the README, but every time I run `pnpm run app:dist` or `pnpm run electron-builder:dist:linux:pacman`, the command takes ~2mins to execute, making it very hard for me to test changes.

Is there a way to compile the project more quickly to be able to iterate changes more easily ?

**Comment by vladimiry** [comment]
2 mins is not a lot compared to my current hardware. Currently, there is no other way to speed up the process than getting more performant hardware. Web part of the project supported hot reloading before, but I didn't get it back yet.

**Comment by vladimiry** [comment]
Actually, to run it, you don't need to every time pack it using `electron-builder:dist:linux:pacman`. When you're done with building, use `pnpm start:electron` command to start it, which is an alias for `electron ./app/electron-main/index.cjs`.

**Comment by vladimiry** [comment]
Also, the built files in `./app` folder are not minimized nor packed, so for testing small changes, you could directly edit those files.
