### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by alfredonodo** [vladimiry/ElectronMail#658]
Hi,
the latest version is the first in two years that works very fast for me. Many errors are no longer visible. 
However, I still have the following that appeared with the last version.
Thank you
![Electronmail](https://github.com/vladimiry/ElectronMail/assets/41476198/4ed32fc0-4f3e-4e5e-a6ab-71a7cf5b197e)

**Comment by vladimiry** [comment]
This looks like an environment-specific issue, as it's a rare one based on reports, and I couldn't reproduce it so far. Try disabling experimental "Desktop notifications for calendar events" toggle in the "General" app settings.

**Comment by alfredonodo** [comment]
Thank you, the problem has been solved. Sometimes I do not receive the notification for some e-mails. Apart from that, it is now almost perfect.
