### ISSUE TITLE
ERROR: App vesion Outdated

### ISSUE THREAD

**Issue by davidovic999** [vladimiry/ElectronMail#659]
Hi ElectronMail Support Team,

As I have Windows 7 installed, I can't install newer versions of ElectronMail. So I installed the latest version supporting Windows 7, version 5.1.8.

But once installed and trying to configure ProtonMail accounts, I got this error message:
"ERROR: App vesion Outdated".

See screenshot:
https://www.screencast.com/t/PBH3m50h

I don't understand why this blocking message in relation to the version used!

In principle, I can use any version compatible with my system, and it should work.

My Internet connection is fine and when I refresh the page, I still get the same message.

How can I solve this issue?

Best regards,

**Comment by vladimiry** [comment]
Things explained in the https://github.com/vladimiry/ElectronMail/issues/650#issuecomment-1814666412. It's not the app sets the version restriction, but Proton.

How to get working app version for old Windows systems listed in https://github.com/vladimiry/ElectronMail/issues/654#issuecomment-1816925040. CC @ask2018 / @RogalDoe.
