### ISSUE TITLE
Does ElectronMail work on M3?

### ISSUE THREAD

**Issue by javaduke** [vladimiry/ElectronMail#660]
I just tried to run ElectronMail on my new M3 MacBookPro, and got the message "“ElectronMail” is damaged and can’t be opened. You should move it to the Trash.". The archive I used is electron-mail-5.2.2-mac-arm64.dmg.

**Comment by vladimiry** [comment]
See the following note in the release description:

> The Apple Silicon/M1 ARM64 package requires xattr -d com.apple.quarantine /Applications/ElectronMail.app command execution.
