### ISSUE TITLE
Prontomail account cannot log in to ElectronMail

### ISSUE THREAD

**Issue by davidovic999** [vladimiry/ElectronMail#663]
Hi Vladimir,
The Prontomail account cannot log in to ElectronMail.
Look at this screenshot of the message I received:
[https://www.screencast.com/t/kYJ5ptMh]
Even when I refresh the page, it's the same message.

Thanks,

**Comment by davidovic999** [comment]
I'd just like to add that my internet connection is good.

**Comment by vladimiry** [comment]
The Proton's "App version outdated" restriction has been handled in the recent/v5.2.2 app release. See #650 for details.

**Comment by davidovic999** [comment]
Thank you Vladimir for your reply,



How do I update the application? Because there is no "Update" button.
And in the FAQ, there is no precision.
Should I completely uninstall and reinstall the application? Then re-enter all email accounts?






De : Vladimir Yakovlev ***@***.***>
À : vladimiry/ElectronMail ***@***.***>
Sujet : Re: [vladimiry/ElectronMail] Prontomail account cannot log in to ElectronMail (Issue #663)
Date : 26/11/2023 17:04:56 Europe/Paris
Copie à : davidovic999 ***@***.***>;
   Author ***@***.***>


The Proton's "App version outdated" restriction has been handled in the recent/v5.2.2 app release. See #650 for details.

**Comment by vladimiry** [comment]
> Should I completely uninstall and reinstall the application?

Simply installing a new version normally works.

> Then re-enter all email accounts?

Normally this is not required.

So you would simply install a new version from https://github.com/vladimiry/ElectronMail/releases/tag/v5.2.2.
