### ISSUE TITLE
Messages are no longer displayed

### ISSUE THREAD

**Issue by davidovic999** [vladimiry/ElectronMail#669]
Hi Vladimir,

When starting the application, messages are no longer displayed in some mailboxes.
On all email accounts, I have configured "Local Store".
You can see on the screenshot for more details.

![emails](https://github.com/vladimiry/ElectronMail/assets/59475468/e493ff21-07ea-4427-b11b-6f0309922267)

**Comment by davidovic999** [comment]
I've been able to access the messages and find one of your answers.
I right-clicked on the mailbox, and clicked on "Unload".

Thank you,
Have a nice day,

**Comment by vladimiry** [comment]
No code change actions planned in this regard. So, closing the issue.
