### ISSUE TITLE
Maybe this is outside of the scope, but ability to access new web app of Proton Pass?

### ISSUE THREAD

**Issue by NintendoManiac64** [vladimiry/ElectronMail#673]
As of today, they've launched a web app for Proton Pass to allow access to its functionality without a browser extension:

- https://pass.proton.me/

Perhaps it's outside of the scope of this project, but I'm wondering if it'd be possible to access that in some way within ElectronMail?

**Comment by vladimiry** [comment]
Duplicae of #645.
