### ISSUE TITLE
Can't open web links from e-mails in default browser

### ISSUE THREAD

**Issue by XxTriviumxX** [vladimiry/ElectronMail#674]
Hi! I used to be able to open links in my default browser. I re-installed arch linux and electronmail and it wont open links in my default browser anymore. version 5.2.2. Is there a setting i could not see? Like a button to click somewhere..?

Copying the link and paste it in my browser works for now...

**Comment by vladimiry** [comment]
If the same app version worked and then stopped working, it's on your side. It's handled by XDG/open on Linux, so this is where you would start the research. Make sure first that `xdg-open your-link-here` console command opens the link in a default browser.

**Comment by XxTriviumxX** [comment]
the "xdg-open github.com" command opens github.com on my browser as it should

**Comment by vladimiry** [comment]
Links opening being handled by @electron's `shell.openExternal` call, you could use it when looking up things on the internet.

**Comment by XxTriviumxX** [comment]
My issue is with the flatpak version.  I tried opening links with webcord, which is another electron app i installed as a flatpak. It didn't work there either. What do you think i should do about it?

**Comment by vladimiry** [comment]
I had this issue with flatpak apps like 4-5 month ago, and it got self-fixed something like few months ago. So in my case it got fixed with updates of the system and flatpak's system stuff.

**Comment by XxTriviumxX** [comment]
my OS has been freshly re-installed last week. 

Anyways, i could simply wait like you said. I'll report back if it works again.

**Comment by XxTriviumxX** [comment]
It started working again.

**Comment by XxTriviumxX** [comment]
It started working again.

**Comment by vladimiry** [comment]
Thanks for the update. So the issue got self fixed, same as happened to me some time ago.
