### ISSUE TITLE
Windows 7 CRACK for v. 5.2.2 

### ISSUE THREAD

**Issue by Blaukovitch** [vladimiry/ElectronMail#676]
official [**Windows 7 crack**](https://github.com/Blaukovitch/GOOGLE_CHROME_Windows_7_CRACK/releases/tag/ElectronMail)

![image](https://github.com/Blaukovitch/GOOGLE_CHROME_Windows_7_CRACK/assets/116763547/1b36b5bb-cee7-494e-a6a5-627d1a6318c4)

**Comment by vladimiry** [comment]
Is this some sort of vulnerability report? If so, https://github.com/advisories/GHSA-r4pf-3v7r-hh55 related or something else?

Closing for now as `won't fix` and `duplicate`, as supporting Windows 7 was discussed before, see https://github.com/search?q=repo%3Avladimiry%2FElectronMail+supermium&type=issues if interested.

**Comment by ask2018** [comment]
@vladimiry this is just another way how to run ElectronMail on Windows 7 and I can confirm it also works :)

**Comment by vladimiry** [comment]
@ask2018 thanks for shedding some light on this.

**Comment by ask2018** [comment]
@vladimiry No problem. It was basically my request. You can read more tech info about this here:
https://github.com/Blaukovitch/GOOGLE_CHROME_Windows_7_CRACK/issues/2
