### ISSUE TITLE
I am confused on how to do the code for recovering my proton mail password

### ISSUE THREAD

**Issue by odditysurpasser** [vladimiry/ElectronMail#680]
I copied and pasted the code from your instructions on this form:https://github.com/vladimiry/ElectronMail/issues/318 then I got an error message can you instruct me as well?

**Comment by vladimiry** [comment]
Not enough details provided. Like error message.

**Comment by odditysurpasser** [comment]
![image](https://github.com/vladimiry/ElectronMail/assets/125298903/d20a1ce7-e6e5-41be-8a18-b126889c7a13)

**Comment by vladimiry** [comment]
Like described in https://github.com/vladimiry/ElectronMail/issues/318#issuecomment-678121062, you create the `package.json` and `index.js` files with that code content. That code is not for running in the console.

The commands you run in the console are (being located in the folder with those `package.json` and `index.js` files):
- npm install
- node index.js [app-settings-folder-path](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg)/settings.bin 'your-master-password'

**Comment by odditysurpasser** [comment]
where do I access them?

**Comment by vladimiry** [comment]
Access what? It's all in your computer. The `open settings folder` is an app's tray menu item.

**Comment by odditysurpasser** [comment]
I cant find it

**Comment by odditysurpasser** [comment]
![image](https://github.com/vladimiry/ElectronMail/assets/125298903/f19eea10-fb62-4d71-ba7e-fbdfcd84d990)  is this it? if so what do I do from hear?

**Comment by vladimiry** [comment]
Yes, this looks like a right folder, now:
- Open console in this folder
- Create the `package.json` and `index.js` files like described in https://github.com/vladimiry/ElectronMail/issues/318#issuecomment-678121062.
- Make sure you have Node.js installed, see https://nodejs.org/en/download.
- `Execute the console command:` npm install
- `execute the console command:` node index.js settings.bin 'your-master-password'

**Comment by odditysurpasser** [comment]
how do I open the console in the folder?

**Comment by vladimiry** [comment]
> how do I open the console in the folder?

I don't know, it's your system, but I believe you could look up this on the internet. For example, you can open console in any folder/drive and then navigate to the needed path, see https://www.digitalcitizen.life/command-prompt-how-use-basic-commands/.

**Comment by odditysurpasser** [comment]
![image](https://github.com/vladimiry/ElectronMail/assets/125298903/92a34273-d8f8-4a3f-96ca-6fe29517c5ff)

**Comment by odditysurpasser** [comment]
now what do I put there

**Comment by vladimiry** [comment]
Right, now follow the rest of the above-listed steps.

**Comment by odditysurpasser** [comment]
I am still lost can you show me?

**Comment by odditysurpasser** [comment]
![image](https://github.com/vladimiry/ElectronMail/assets/125298903/1dd46b1b-10be-46c3-8e18-580b3a3240b4)
it mest up at the index part what am I missing?

**Comment by odditysurpasser** [comment]
hello?

**Comment by vladimiry** [comment]
It looks like you didn't complete the second step from https://github.com/vladimiry/ElectronMail/issues/680#issuecomment-2027239320. You need to create the `package.json` and `index.js` with the code posted in https://github.com/vladimiry/ElectronMail/issues/318#issuecomment-678121062. Run `notepad package.json` console command, put the code content in the file and save it. Then run `notepad index.js`, put the content and save it. Then follow the next steps from https://github.com/vladimiry/ElectronMail/issues/680#issuecomment-2027239320. I won't be able to provide additional support on this matter until you complete the listed steps.

**Comment by odditysurpasser** [comment]
when I create the index.js  it messes up

**Comment by vladimiry** [comment]
Closing as I have nothing to add here at the moment.
