### ISSUE TITLE
Proton Mail has received official Windows client

### ISSUE THREAD

**Issue by Zan1456** [vladimiry/ElectronMail#682]
[Direct link](https://proton.me/download/mail/windows/ProtonMail-desktop.exe)
[Download site](https://proton.me/mail/download)

**Comment by vladimiry** [comment]
#664 might be related.

**Comment by Zan1456** [comment]
![image](https://github.com/vladimiry/ElectronMail/assets/62830223/6ee76784-6ff5-4b50-aeb6-9cfb91a8f3a0)
Free trial?

**Comment by vladimiry** [comment]
No idea. I didn't try it and not going to in the near future, but I might when it gets mature and will have some desktop-specific features implemented.
