### ISSUE TITLE
Preview of PDF

### ISSUE THREAD

**Issue by Mireiarm** [vladimiry/ElectronMail#691]
The preview of PDF's in appllicattion proton Mail doesn't work in my computer. I need everytime to download and open the PDF's with another application. But the preview works for some images and text documents. I don't know how to solve the problem because it's annoying to download the pdf's everytime. Thank you very much!

**Comment by vladimiry** [comment]
Known unresolved issue, see #371.

**Comment by Mireiarm** [comment]
ok, thank you!
