### ISSUE TITLE
HOW DO I RESET THE MASTER PASSWORD?

### ISSUE THREAD

**Issue by hackhubafrica** [vladimiry/ElectronMail#692]
I recently lost my master password to this desktop application and there was no option to reset the password.I uninstalled the app and reinstalled the app several times but it returns to same login screen. PLEASE HELP ME ON THIS AND I THINK THIS FEATURE SHOULD BE INTRODUCED TO THE APPLICATION.

**Comment by vladimiry** [comment]
It's possible to change the master password, but knowing the current password is required:

![pass](https://github.com/user-attachments/assets/4473fb4c-0aee-4c4c-a39e-167dd1ab8703)

But there is no option to just "reset" it, as it would be an insecure thing.

When you enter the master password, the encryption key gets derived from the password on the fly, and then this key is used to decrypt the data. So, technically, you can't "reset" something that is not stored anywhere.
