### ISSUE TITLE
[bug] dragging and dropping into folders causes page to scroll

### ISSUE THREAD

**Issue by TimmyBoi155** [vladimiry/ElectronMail#694]
looking at my mail inbox, when i drag and drop an email into a folder, as long as the email is not the first email in the list, the page scrolls a bit downward after dropping the email into a folder. I'm using flatpak release.

Not sure what else to say. maybe try it out on your end

**Comment by TimmyBoi155** [comment]
Any update on this? im going insane

**Comment by vladimiry** [comment]
It's reproducible in the app, but there will be a need to test it on the proton.me too, since it's likely to be a proton's issue as it occurs in their web client.

**Comment by TimmyBoi155** [comment]
Any update on this? What needs to be done? Does the code need to be updated from proton's side?

I tested on proton.me and it does not have this bug

**Comment by vladimiry** [comment]
> I tested on proton.me and it does not have this bug

proton.me comes with recent https://github.com/ProtonMail/WebClients, so it doesn't mean that there was no original issue at the time of v5.2.3 app releasing.

> What needs to be done?

Packaging the recent https://github.com/ProtonMail/WebClients into the app and testing it then. This normally requires updating https://github.com/vladimiry/ElectronMail/tree/master/patches/protonmail, which might potentially be a complex task.

**Comment by TimmyBoi155** [comment]
bro this isn't minor :'(
but okay i guess. let me know and I'll be happy to help test

**Comment by vladimiry** [comment]
> bro this isn't minor :'(

I understand that for you, it's not minor. But given the nature of this project, the major issue would be something close to a blocker, which would prevent performing essentials actions.

**Comment by TimmyBoi155** [comment]
I disagree but it's your project, will let you decide. :+1:

**Comment by vladimiry** [comment]
@TimmyBoi155 [here is the build](https://mega.nz/folder/91wkXRiR#1mMuRf8HS0iFAg2Cj8c01w) to test. It comes with updated [WebClients](https://github.com/ProtonMail/WebClients) stack (except the "account" app, for now). Assembled from the `wip` branch at https://github.com/vladimiry/ElectronMail/actions/runs/11242777829.

**Comment by TimmyBoi155** [comment]
Yep, I tried the AppImage. Seems to work great, I tried many types and positions of dragging dropping

**Comment by vladimiry** [comment]
Let's close then.

**Comment by TimmyBoi155** [comment]
Sounds good, thank you for being patient with my persistence, and for updating this :)

**Comment by vladimiry** [comment]
Apparently, that was not only you who suffered, as Proton noticed and fixed this issue in their web client.

**Comment by TimmyBoi155** [comment]
I'm glad, because I am dragging and dropping all day :'(

**Comment by TimmyBoi155** [comment]
Any word on when flatpak will be updated?

**Comment by vladimiry** [comment]
The flatpak gets updated in along with new app release, same as the repositories. New app release is planned for the next few days.
