### ISSUE TITLE
ElectronMail not starting GUI on Qubes OS

### ISSUE THREAD

**Issue by TwinkleToes777** [vladimiry/ElectronMail#699]
OS: Whonix VM (Based on debian 12) on Qubes OS.

Output: 
```
flatpak run com.github.vladimiry.ElectronMail
[44:1013/173653.890532:ERROR:viz_main_impl.cc(166)] Exiting GPU process due to errors during initialization
[2:1013/173653.976972:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.login1.Manager.Inhibit: object_path= /org/freedesktop/login1: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
[92:1013/173654.028507:ERROR:viz_main_impl.cc(166)] Exiting GPU process due to errors during initialization
(node:2) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `electron-mail --trace-deprecation ...` to show where the warning was created)
```

It used to work 6 months ago.

**Comment by vladimiry** [comment]
Using Flatpak build?

**Comment by vladimiry** [comment]
Can you run `flatpak override --system-talk-name=org.freedesktop.login1 com.github.vladimiry.ElectronMail` and testing the app then?

**Comment by TwinkleToes777** [comment]
same problem different output:
```
flatpak run com.github.vladimiry.ElectronMail
[44:1014/194636.052583:ERROR:viz_main_impl.cc(166)] Exiting GPU process due to errors during initialization
[87:1014/194636.193699:ERROR:viz_main_impl.cc(166)] Exiting GPU process due to errors during initialization
(node:2) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `electron-mail --trace-deprecation ...` to show where the warning was created)
```

**Comment by vladimiry** [comment]
This has nothing to do with ElectronMail code, but apparently with some @electron / @chromium / system update, so you might have to look up for the workaround for your system in your own.

Consider trying this workaround https://github.com/electron/electron/issues/41066#issuecomment-1913509942.

**Comment by TwinkleToes777** [comment]
sorry for false report, it works, only confusing because I had to click on systray electronmail icon to open it, it does not open by itself which was confusing, before it was opening by itself 6 months ago

**Comment by TwinkleToes777** [comment]
I see "start minimized to tray" was checked... not sure if I did that or update did it

**Comment by vladimiry** [comment]
> or update did it

The recent update doesn't touch this config option (none of them).
