### ISSUE TITLE
Bug and crashes: GBM-DRV error and Buffer deprecation warning

### ISSUE THREAD

**Issue by mathe00** [vladimiry/ElectronMail#701]
Hello,

I'm encountering an issue with Electron Mail. While I haven't done much research due to lack of time and expertise, I wanted to report the error in case it helps improve the app. I don't fully understand the cause of the issue, but here’s the error I get in the terminal when launching the application:

```zsh
src/gbm_drv_common.c:131: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000
(node:426054) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
resolveProtonAppTypeFromUrlHref: failed to resolve the value by {"requestBasePath":"/assets/static"}
...
[426054:1020/215402.218516:ERROR:atom_cache.cc(230)] Add chromium/from-privileged to kAtomsToCache
```

It seems related to a graphics or GBM issue, and I also see deprecation warnings about `Buffer()` in Node.js, as well as errors resolving static file paths.

### System Context

Here are my system specs for more context:

- **OS**: Arch Linux KDE Plasma (Wayland) with ZSH (not Bash)
- **KDE Plasma Version**: 6.2.1
- **KDE Frameworks Version**: 6.7.0
- **Qt Version**: 6.8.0
- **Kernel Version**: 6.11.4-arch1-1 (64-bit)
- **CPU**: Intel® Core™ i7-9700 CPU @ 3.00GHz (8 cores)
- **RAM**: 31.3 GiB
- **GPU**: NVIDIA GeForce RTX 3070 with proprietary NVIDIA drivers
- **Manufacturer**: Micro-Star International Co., Ltd. (MS-7B51)
- **Wayland**: Yes, I’m running Wayland

I'm also using **nvm** to manage Node.js versions, in case that helps.

### Note

I haven’t looked into the issue further (due to time constraints and limited knowledge) but wanted to report it in case it helps with diagnosing and fixing the issue in the app.

Thanks for your work!

**Comment by vladimiry** [comment]
Thanks for the detailed report.

> (node:426054) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

> resolveProtonAppTypeFromUrlHref: failed to resolve the value by {"requestBasePath":"/assets/static"}

These two are known ones, have seen them many times. There is no actual functional issue here, yet.

> src/gbm_drv_common.c:131: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000

> [426054:1020/215402.218516:ERROR:atom_cache.cc(230)] Add chromium/from-privileged to kAtomsToCache

These two seeing first time. The answer here will be the same as recently posted in #700:

> Clearly something system-specific I won't be able to look into, as I don't run `<reported environment>`. So this is something you will have to sort out in your own.

> There is no direct interaction with `<reported thing>` in this project, but might happen in @electron / @chromium which used here as a runtime. So I guess this is where you could start the research.

**Comment by vladimiry** [comment]
By the way, is there a functional issue in the app or printing that stuff into the console output is the only concern?

**Comment by vladimiry** [comment]
> By the way, is there a functional issue in the app (it doesn't start, crashes, has some broken functionality, etc) or printing that stuff into the console output is the only concern?

Striking this question out, as I missed properly reading title: Bug and **crashes**...

**Comment by mathe00** [comment]
> By the way, is there a functional issue in the app (it doesn't start, crashes, has some broken functionality, etc) or printing that stuff into the console output is the only concern?

Hi,

Yesterday, after a few seconds of using the app, I was getting a weird gray window followed by a crash. However, today after rebooting, everything seems to be working fine.

I'll let you know if the crashes happen again, but it's probably resolved. It might have been the reboot or some updates that fixed the issue (as is often the case 😄).

Thanks for your help!

**Comment by vladimiry** [comment]
Ok, closing for now.
