### ISSUE TITLE
memory consumption

### ISSUE THREAD

**Issue by babebort** [vladimiry/ElectronMail#710]
`       943.95 Mb /app/ElectronMail/electron
      2291.72 Mb /app/ElectronMail/electron
       979.35 Mb /app/ElectronMail/electron
      2452.44 Mb /app/ElectronMail/electron
       156.55 Mb /app/ElectronMail/electron
        59.33 Mb /app/ElectronMail/electron
         7.73 Mb /app/ElectronMail/electron
         7.68 Mb /app/ElectronMail/electron
`
more than 5 gb.......

Why is it so much and can I limit it via cmd?

**Comment by vladimiry** [comment]
This might be the case if you got many email messages and enabled "local sore" feature, as all the locally stored data gets decrypted into the memory when the app starts. See more details in #708.
