### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by PegHorse** [vladimiry/ElectronMail#711]
![image](https://github.com/user-attachments/assets/afd53f09-c29e-4509-a7dd-ed9fd765c2a4)

Hi,
I read paid features for ProtonMail and after rejecting the offer of "Dark Web Monitoring" this error message keeps displaying in loop until i close the application.
Thanks

![image](https://github.com/user-attachments/assets/6589ddd7-cc73-46e9-8cf3-5f21dd768175)

**Comment by vladimiry** [comment]
Thanks for the detailed report. This is a known issue, so closing this one as duplicated of #696.
