### ISSUE TITLE
Invocation timeout of calling "dbIndexerOn" method on "electron-mail:ipcMain-api" channel with 15000ms timeout

### ISSUE THREAD

**Issue by babebort** [vladimiry/ElectronMail#715]
Invocation timeout of calling "dbIndexerOn" method on "electron-mail:ipcMain-api" channel with 15000ms timeout

I don't know how to trigger it,  just opened from tray and noticed this notify

**Comment by vladimiry** [comment]
This has the same root as the #708, except the fact that this specific timeout is currently hard-coded. I will be increasing it, but as was put in #708 there is no other proper solution for handling big data other than implementing #571, so closing the issue.
