### ISSUE TITLE
[Enhancement] Return to default view (inbox?) when closing program window (but not quitting program)

### ISSUE THREAD

**Issue by NintendoManiac64** [vladimiry/ElectronMail#717]
(I'm using the v5.2.3 flatpak)

Just a minor improvement I was thinking of is to not retain whatever is open when closing the program window but aren't quitting the program.

(alternatively this could be an additional toggle-able setting in ElectronMail)

As someone that never uses "automatically save session" functionality in my programs (web browsers, email clients, image viewers, text editors, etc etc), I do get tripped up when things are "saved" or retained, such as looking at an old email or the like, even though I closed the program window. This particularly throws me off when I've scrolled down in the inbox and new emails aren't "showing up" because I need to scroll up first to see them, but needing to scroll up when opening the previously-closed ElectronMail program window goes against every fiber of my muscle-memory (see also: you don't need to scroll up when you navigate to a new web page)

The one major caveat is that the current behavior makes a lot of sense if you're the type to prefer "minimize to tray" behavior rather than "close to tray". For me, I much prefer "minimize to task bar/panel" and "close to tray" (which I have enabled on my copy of ElectronMail), with the former behaving as traditional minimizing of an open application would while "close to tray" behaving much more akin to closing all open files/documents/pages/etc but leaving the program running.

...I do suppose that's one key thing - currently, closing and minimizing the program window behaves the exact same way within ElectonMail itself and the only difference is OS-side (minimizing leaves an active "window button" on your taskbar/panel while closing doesn't).

**Comment by vladimiry** [comment]
Sorry, but my brain processor could not parse the actual need from the original message. I guess #703 might be somehow similar, who knows.

- If the "Close to tray" option is enabled in the app (by default), the "window closing action" just makes the app window invisible, so it's "closing to tray" action.
- If the "Close to tray" option is disabled in the app, the "window closing action" closes the app entirely.
- The behavior of the "window minimizing action" is a standard one. So the window always gets minimized to the taskbar.

This is the way it works in most of the apps I've seen, and so such behavior is familiar to me and other users.

Naming "close to tray" as "minimizing to tray" would introduce the confusion, as it's the "window close" button triggers the action.

**Comment by NintendoManiac64** [comment]
OK yeah, you're definitely confused as to what I'm getting at.

So let's use the example of a web browser. I know many modern web browsers by default close the entire program when you close the last tab, but this didn't use to be the case (and, even in my current non-mainstream choice of primary browser, it at least has an option to not close the program when closing the last tab).

In the example of a browser, I'm asking for the equivalent of closing all tabs but leaving the program running when "closing to tray".

My main issue is that, when using "close to tray" like I do, the minimize and close functions behave the same within ElectronMail itself - despite the option being called "close to tray", ElectronMail doesn't actually close anything and is instead more akin to making the close button behave as "minimize to tray".

**Comment by vladimiry** [comment]
> In the example of a browser, I'm asking for the equivalent of closing all tabs but leaving the program running when "closing to tray".

How the restore/resume work flow would look then?

Each account in the app can be "disabled" (see the "active" toggle near each account in the settings). And then, if some account disabled, its handle button doesn't get displayed on the panel. So technically, we could "disable" each account when the window gets closed to tray. But the account's "active" state is kept in the encrypted `settings.bin` file. So updating any account-related settings is a very slow action.

Another, more feasible option, is to "unload" each account in along with closing to tray. The "Unload" action simply resets the account to the initial state. As opposes to the account "disable" action, "unload" actions runs fast, and the account handle buttons remain on the panel.

For example, the  "Unload" action is convenient to use with "Persistent session" and ("Login delay range (seconds)" or/and "Login on account selection") options enabled. Like, you enable the "Login on account selection" for the account. Then the account doesn't get loaded until its handle gets clicked by a user. You click it and do needed stuff. And when you're finished working with this account, you simply "Unload" it until the next activation by a click. This is a use case for a rarely/occasionally used accounts.

So if you are ok to "unload" each account in along with closing to tray, this might be the way to fulfill your need. I'm not saying yet that I will have the described behavior implemented here in the project, as this looks like a very rare user need, but technically you can do the fork.

**Comment by vladimiry** [comment]
> the "Unload" action

I missed to mention, the "Unload" action is available by the right mouse click on the account handle button, so via the account "context menu".

**Comment by NintendoManiac64** [comment]
Maybe the example of a web browser wasn't the best either...

All I mean is that, let's say you start with the following view:

![before](https://github.com/user-attachments/assets/e7adc061-6ce5-44a9-b055-034d400ff4fb)

Then if you close just the window itself (while "close to tray" is enabled), then re-opening ElectronMail via the tray would ideally return you to:

![after](https://github.com/user-attachments/assets/e09b3407-1575-43aa-afae-92ab93dcdb08)

**Comment by vladimiry** [comment]
It doesn't make sense to hardcode the "reset to initial/inbox state" action into the app, as at some point you as a user might change the opinion on what the initial state is. So this "reset" action should be dynamic, especially given the fact how custom/rare the need like this is. Dynamic action means custom JavaScript code for execution on some events. Currently, a discussed event is "closing to tray" or "restoring from tray" depending on the preference. That custom JavaScript code gets defined by a user, and in your case it would programmatically click the "Inbox" link.

For this project, this get "won't fix" status, as the need looks very custom/rare. But it's technically possible to implement/maintain in the fork with some effort.

**Comment by NintendoManiac64** [comment]
> you as a user might change the opinion on what the initial state is

Could you elaborate on this? I'm probably missing something, but I thought ElectronMail always dumped you into the inbox as the so-called "default view" after logging you in?

**Comment by vladimiry** [comment]
> I find it interesting that you feel this is custom/rare. Maybe I'm getting the wrong impression, but this feels like the difference between the types of people that never turn off their PC and the types of people that always turns off their PC? (and I don't mean standby nor hibernate) I myself am very much the latter "always shut down" category.

No one expressed this need before during 8 years of project existing, and I can understand that. I've never seen any app that would reset its view state to the initial state when it gets restored from the tray.

> I thought ElectronMail always dumped you into the inbox as the so-called "default view" after logging you in?

Nope. ElectronMail simply loads the static web client app assembled from the https://github.com/ProtonMail/WebClients app, like mail/calendar/drive/etc. So the initial state gets defined by Proton in https://github.com/ProtonMail/WebClients, not in ElectronMail. I don't want to maintain the default state of Proton's web clients in the code here. This is a different story if it gets maintained by a user.

By the way, there is a request #451 for controlling initial state of the Proron's Mail web client. Loading defined folder, like "All mail", vs default "Inbox". Simply mentioning it for the issues cross-referencing purposes.

**Comment by NintendoManiac64** [comment]
> I've never seen any app that would reset its view state to the initial state when it gets restored from the tray.

This might originate from how I used to use a browser-based notifier extension, like over a decade ago (back when protonmail wasn't even a thing) and before that used Google Talk to double as a gmail notifier.

The issue for me is that, from what I can tell, there's no way to have ElectronMail's tray icon only behave as a notifier without having the program open and running all of the time.

...heck, now that I think of it, wouldn't the official Proton mobile app behave this way? Providing mail notifications but, upon opening, taking you to the default inbox view?
