### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by cyber-sec0** [vladimiry/ElectronMail#719]
I'm unable to easily find the current version number anywhere, so I'm not sure if my version is up to date or not.

I couldn't find an auto-update feature anywhere, so this should probably be added.

I've saved my master password, so now the password is no longer required to log me in, I do regret doing that for security reasons, so I wanted to undo that, but there's no undo option anywhere.

I also don't see the point of multiple "Entry Proton App" options, like Mail/Calendar/Drive, they're all the exact same thing.
I've tried adding my calendar after I added my email, and I'm unable to do that since they have the same email, so the last 2 options should be removed.

**Comment by cyber-sec0** [comment]
Ok.

It doesn't annoy me, I just don't understand the point/reason for it to exist in the first place.

-------- Original Message --------

**Comment by vladimiry** [comment]
> It doesn't annoy me, I just don't understand the point/reason for it to exist in the first place.

Ok, now you do, I hope, as I explained.

**Comment by cyber-sec0** [comment]
Not really, I already understood the concept the I can have two accounts logged in, which I do now.

But using calendar to add an account doesn't work, as I'm already logged in with that account, by I used email when setting it up.

-------- Original Message --------

**Comment by vladimiry** [comment]
> But using calendar to add an account doesn't work, as I'm already logged in with that account, by I used email when setting it up.

I believe everyone can use Calendar on any account, free/paid, not just Mail. So it should be possible to load 2 tabs with Mail+Calendar for the same account. Each will have it's login session, as you do independent sign-in using different logins (full email address and the part of the address before "@"). But I didn't actually test this 2 tabs scenario in my own on a free account.

**Comment by cyber-sec0** [comment]
That's what I thought the purpose of it was, but in my free account I'm just unable to add 2 tabs, 1 tab for email and 1 tab for calendar.

Currently I only have 2 tabs for 2 diff free PM emails.

I can still use and see the calendar page, but not a the top of your application, I've yo go through the left side square menu and select calendar between all options that proton shows by default on any browser.

-------- Original Message --------

**Comment by vladimiry** [comment]
>  but in my free account I'm just unable to add 2 tabs, 1 tab for email and 1 tab for calendar.

Why not? Did you try to add in the app 2 account records with the logins like "my-email-address@protonmail.com" and just "my-email-address" (without @protonmail.com)? In the first record, you set "Mail" as "Entry Proton App" and "Calendar" for the second account record.

> I've yo go through the left side square menu and select calendar between all options that proton shows by default on any browser.

Right, but this is not convenient for non-Mail users, so the selection of initially loaded Proton App got added in the app. Some details available in #502.

**Comment by vladimiry** [comment]
> But I didn't actually test this 2 tabs scenario in my own on a free account.

Just did and it works. The scenario from my previous message.
