### ISSUE TITLE
The program does not open from the tray with the left mouse button

### ISSUE THREAD

**Issue by Faust30000** [vladimiry/ElectronMail#94]
I use the program in Linux Mint 19.1 Cinnamon, if the program is closed in tray, then it can be reopened only by clicking the left mouse button and selecting Toggle Window. Can you fix it and make the program unfold when you click the left mouse button on the tray icon?

**Comment by vladimiry** [comment]
This is [a known issue](https://github.com/electron/electron/issues/14941#issuecomment-435616681). Electron platform did break the tray icon event handlers processing since v3. We have to wait for Electron resolves the issue since rolling back to electron@v2 is not an option.

**Comment by vladimiry** [comment]
I'm closing this issue as no changes expected to happen at the app side but I keep tracking the [upstream](https://github.com/electron/electron/issues/14941) issue.

**Comment by arch-btw** [comment]
Could you re-open until upstream fixes it?


https://github.com/electron/electron/issues/16462

**Comment by arch-btw** [comment]
@vladimiry thank you for your hard work.

Maybe we can move away from libappindactor?

**Comment by vladimiry** [comment]
I've been tracking the issue even though it's closed here, see:
https://github.com/electron/electron/issues/14941
https://github.com/electron/electron/issues/21445
https://github.com/electron/electron/issues/21499
https://github.com/electron/electron/issues/10427

Looks like the primary/left click is going to work again with upgrading to Electron version 8, but right now the tray menu on Linux is broken (see https://github.com/electron/electron/issues/21499) so I can't upgrade yet.

**Comment by vladimiry** [comment]
With @electron version 8, the primary/left click seems to be working well even though the libappindicator-gtk3/libappindicator3-1 is installed. Yes, removing libappindicator-gtk3 is a hacky workaround, on some systems it helps, but if you force-remove it using Gnome 3 Shell DE (Ubuntu 19.10 has the package named as `libappindicator3-1`) there will be no icon shown at all if @electron version below 7 is used but works without the library with newer versions, ie 8+. Also, see https://github.com/electron/electron/issues/10427.

**Comment by vladimiry** [comment]
See related issue #254. Closing this one as next v4.2.3+ release will be based on @electron version 8 which makes the left mouse click work as expected.
